import type { ServiceText } from "../types";

const REF = "General reference values; they do not represent company capacity. The value that applies to your part is stated in the quote.";

export const part2: Record<string, ServiceText> = {
  "silikon-kaliplama": {
    categoryLabel: "Pre-Production",
    title: "Silicone Moulding",
    metaTitle: "Silicone Moulding | Vacuum Casting | Short Runs | Mas Technic",
    metaDescription: "Short-run production by vacuum silicone moulding. PU, silicone, epoxy. Pore-free replicas from a master model; the suitable quantity is stated in the quote.",
    description: "Short-run production by vacuum silicone moulding. Pore-free replicas from a master model; the suitable quantity is stated in the quote according to the part and the material.",
    content: [
      "Casting under vacuum prevents air being trapped in the mould cavity and gives a pore-free surface. We produce in PU, silicone, polyester and epoxy and offer colour options with pigments.",
      "Material options PU 60A (60 Shore A, flexible and tear-resistant), PU 80A (80 Shore A, medium hardness), PU 90A (90 Shore A, high strength) and Silicone 40A (40 Shore A, high-temperature resistant) cover a wide range of applications.",
      "With overmoulding we can combine materials of different hardness. We offer silicone moulding solutions for medical, automotive and industrial applications. The lead time is given with the quote according to the readiness of the master model, the casting quantity and the finishing scope.",
    ],
    features: [
      "Vacuum Casting — pore-free surface without trapped air",
      "Various Materials — PU, silicone, polyester, epoxy",
      "Colour Options — Any colour with pigments",
      "Overmoulding — Materials of different hardness combined",
    ],
    technicalSpecs: [
      { label: "Shore Hardness", value: "40A-90A" },
      { label: "Tolerance", value: "Stated in the quote" },
      { label: "Material", value: "PU, LSR, HTV, EPDM" },
      { label: "Temperature Resistance", value: "To the selected material" },
      { label: "Batch Size", value: "Short run" },
    ],
    processSteps: ["Master Model Preparation", "Silicone Mould Casting", "Vacuum Casting", "Curing", "Demoulding", "Quality Inspection"],
    advantages: [
      "Quick replication from the mould once the master model is approved",
      "Short-run production",
      "4 hardness options",
      "Overmoulding capability",
    ],
    comparisonTables: [
      {
        title: "Silicone Moulding Material Comparison",
        description: "Typical material values; the technical data sheet of the selected product is the basis. Not a company capacity.",
        headers: ["Material", "Shore Hardness", "Elongation (%)", "Temperature Range", "Tear Strength", "Application"],
        rows: [
          ["PU 60A", "60 Shore A", "450%", "-30°C / +80°C", "25 kN/m", "Flexible seal, bumper"],
          ["PU 80A", "80 Shore A", "350%", "-30°C / +90°C", "35 kN/m", "Handle, cover"],
          ["PU 90A", "90 Shore A", "250%", "-20°C / +100°C", "45 kN/m", "Structural, load-bearing"],
          ["Silicone 40A", "40 Shore A", "600%", "-60°C / +300°C", "20 kN/m", "High temperature, medical"],
          ["Silicone 70A", "70 Shore A", "400%", "-55°C / +250°C", "30 kN/m", "O-ring, seal, keypad"],
          ["Epoxy Resin", "80 Shore D", "5%", "-40°C / +120°C", "Rigid", "Prototype, model"],
        ],
      },
      {
        title: "Production Method Comparison (Short Run)",
        description: REF,
        headers: ["Method", "Min. Quantity", "Part Cost", "Mould Cost", "Surface Quality"],
        rows: [
          ["Vacuum Casting", "1", "$$", "$", "Good (depends on master)"],
          ["3D Printing (SLA)", "1", "$$$", "None", "Very good"],
          ["CNC Machining", "1", "$$$$", "None", "Excellent"],
          ["Silicone Injection", "500+", "$", "$$$", "Excellent"],
          ["Compression Moulding", "100+", "$$", "$$", "Good"],
        ],
      },
    ],
  },
  "fikstur-aparat-tasarimi": {
    categoryLabel: "Pre-Production",
    title: "Fixture & Jig Design",
    metaTitle: "Fixture & Jig Design | Custom CNC Fixtures | Mas Technic",
    metaDescription: "Custom fixture and jig design for CNC machining, assembly, welding and inspection. 3D modelling, clamping-force and tolerance-chain assessment, validation in the production environment.",
    description: "Custom-designed fixtures and jigs for CNC machining, assembly, welding and inspection operations. Repeatability and operator independence.",
    content: [
      "We design custom fixtures and jigs that speed up your production and improve precision. Our range includes turning fixtures (custom work-holding that locates and holds the part about its axis of rotation), milling fixtures (vice, vacuum and hydraulic), assembly fixtures (preventing operator error), inspection fixtures (measurement repeatability) and welding fixtures (alignment and holding).",
      "Our design service runs through 3D modelling, clamping-force and tolerance-chain assessment, prototype production by 3D printing or rapid manufacturing, and validation testing and approval in the production environment.",
      "We build fixtures in steel, aluminium and composite materials; the fixture's repeatability target is set by the part's tolerance chain and measured during validation. The design and manufacturing lead time is given with the quote after the fixture complexity, material supply and validation scope have been reviewed.",
    ],
    features: [
      "Turning Fixture — Locating and holding the part about its axis of rotation",
      "Milling Fixture — Vice, vacuum and hydraulic",
      "Assembly Fixture — Preventing operator error",
      "Inspection Fixture — Measurement repeatability",
      "Welding Fixture — Alignment and holding",
    ],
    technicalSpecs: [
      { label: "Repeatability", value: "To the tolerance chain" },
      { label: "Material", value: "Steel, Al, Composite" },
      { label: "Lead Time", value: "With the quote" },
      { label: "Validation", value: "Test in the production environment" },
    ],
    processSteps: ["Needs Analysis", "3D Modelling", "Clamping Force & Tolerance Assessment", "Prototype (3D Printing / Rapid Manufacturing)", "CNC Machining & Assembly", "Test & Approval"],
    advantages: [
      "Solid model and manufacturing drawing in one flow",
      "Clamping-force and tolerance-chain assessment",
      "Rapid prototyping by 3D printing",
      "Validation test in the production environment",
    ],
    comparisonTables: [
      {
        title: "Fixture Type Selection Guide",
        description: REF,
        headers: ["Fixture Type", "Clamping Force", "Change-over Time", "Cost", "Application"],
        rows: [
          ["Mechanical Vice", "10-50 kN", "1-2 min", "$", "General milling"],
          ["Hydraulic Clamping", "20-100 kN", "10-20 s", "$$$", "Series production, automated"],
          ["Pneumatic Clamping", "5-30 kN", "5-10 s", "$$", "Light parts, fast"],
          ["Vacuum Clamping", "1-10 kN", "5 s", "$$", "Thin plate, delicate"],
          ["Magnetic Table", "5-20 kN", "3 s", "$$", "Ferromagnetic, grinding"],
          ["Modular Fixture", "Variable", "15-30 min", "$$$$", "Multi-purpose, flexible"],
        ],
      },
    ],
  },
  "mekanik-yuzey-islemleri": {
    categoryLabel: "Surface Treatments",
    title: "Mechanical Surface Treatments",
    metaTitle: "Mechanical Surface Treatments | Blasting & Polishing | Mas Technic",
    metaDescription: "Blasting, vibratory finishing, polishing and brushing. Options from mirror to satin finish; the achievable surface quality is stated in the quote according to the material.",
    description: "Improving surface quality and preparing parts for assembly by blasting, vibratory finishing, polishing and brushing. Passivation is a chemical process and is described on the Chemical Treatments page.",
    content: [
      "Mechanical surface treatments bring the surface quality of your parts to the required level. Shot blasting cleans and roughens the surface, vibratory finishing (tumbling) breaks sharp edges, centreless polishing improves the surface of round parts, polishing gives a mirror finish and brushing gives a satin effect.",
      "We work with different abrasives — glass bead for fine cleaning, aluminium oxide for surface preparation, steel grit for heavy cleaning and soda for gentle cleaning; the media and grit size are chosen to suit the part material and the target surface.",
      "The achievable surface quality and the process parameters are set by the material and geometry. The working range is stated in the quote after the part geometry and the process plan have been reviewed.",
    ],
    features: [
      "Shot Blasting — Cleaning and surface roughening",
      "Vibratory Finishing (Tumbling) — Edge breaking",
      "Centreless Polishing — For round parts",
      "Polishing — Mirror finish",
      "Brushing — Satin surface effect",
    ],
    technicalSpecs: [
      { label: "Polish Level", value: "Mirror finish" },
      { label: "Working range", value: "Stated in the quote" },
    ],
    processSteps: ["Surface Analysis", "Process Selection", "Abrasive / Media Selection", "Surface Treatment", "Quality Inspection"],
    advantages: [
      "4 abrasive options",
      "Polishing up to a mirror finish",
      "Surfaces delivered ready for assembly",
      "Media chosen to suit the part material",
    ],
    comparisonTables: [
      {
        title: "Mechanical Surface Treatment Methods Compared",
        description: REF,
        headers: ["Method", "Surface Finish (Ra)", "Process Time", "Cost", "Application"],
        rows: [
          ["Blasting (Glass Bead)", "Ra 1.6-3.2µm", "5-15 min", "$", "Cleaning, roughening"],
          ["Blasting (Al₂O₃)", "Ra 2.0-4.0µm", "5-15 min", "$", "Pre-paint preparation"],
          ["Vibratory Finishing", "Ra 0.4-1.6µm", "30-120 min", "$", "Deburring, edge breaking"],
          ["Centreless Polishing", "Ra 0.1-0.4µm", "10-30 min", "$$", "Shaft, pin polishing"],
          ["Mechanical Polishing", "Ra 0.05-0.2µm", "15-60 min", "$$$", "Mirror finish"],
          ["Brushing", "Ra 0.4-1.2µm", "5-10 min", "$", "Satin effect, decorative"],
        ],
      },
      {
        title: "Abrasive Media Selection Table",
        description: REF,
        headers: ["Media Type", "Grit Size", "Hardness", "Suitable Material", "Effect"],
        rows: [
          ["Glass Bead", "0.1-0.5mm", "Medium", "All metals", "Fine cleaning, matt surface"],
          ["Aluminium Oxide", "0.2-1.0mm", "High", "Steel, cast iron", "Aggressive cleaning, roughening"],
          ["Steel Grit", "0.2-2.0mm", "Very high", "Steel, castings", "Heavy rust/sand removal"],
          ["Ceramic Media", "3-15mm", "High", "All metals", "Deburring, surface smoothing"],
          ["Plastic Media", "2-10mm", "Low", "Aluminium, plastics", "Gentle deburring"],
          ["Walnut Shell", "0.5-2.0mm", "Low", "Soft metals", "Cleaning (no dimensional change)"],
        ],
      },
    ],
  },
  anodizasyon: {
    categoryLabel: "Surface Treatments",
    title: "Anodising",
    metaTitle: "Anodising Service | Type I-II-III Hard Anodising | MIL-A-8625 | Mas Technic",
    metaDescription: "Type I, II and III (hard) anodising, colouring with organic and inorganic dyes. Layer thickness, hardness and corrosion-test requirements are set by the specification and the alloy.",
    description: "Corrosion resistance, wear resistance, electrical insulation and decorative finishes with Type I chromic acid, Type II sulphuric acid and Type III hard anodising.",
    content: [
      "Anodising is an aluminium oxide (Al₂O₃) layer formed electrochemically on an aluminium surface. The layer considerably improves the part's corrosion resistance, wear resistance and appearance. At Mas Technic we offer Type I, Type II and Type III anodising for aerospace and medical applications.",
      "Under MIL-A-8625, Type I (chromic acid) forms a thin oxide layer and is preferred as a base for paint adhesion. Type II (sulphuric acid) is the most widely used type, for corrosion protection, coloured finishes and general engineering applications. Type III (hard anodising) forms a thicker, harder layer for surfaces that need wear resistance and electrical insulation. Layer thickness and hardness are set by the alloy and the specification; coating hardness is expressed in Vickers (HV) — HRC is for the hardness of the base material.",
      "In colouring we use organic and inorganic dyes for black, red, blue, green, gold, bronze, purple, orange, yellow, smoke and natural (clear) finishes; custom RAL and Pantone matching is also possible. The colour tolerance is defined by the specification. Sealing closes the pores of the oxide layer and improves protection.",
      "The method and acceptance criteria for coating thickness, hardness and colour inspection are defined in the inspection plan; a corrosion test (e.g. ASTM B117) is applied if the specification requires it. A measurement record is kept for every batch.",
      "Whether a part can be processed, given its size and weight, is decided at the quotation stage. The working range is stated in the quote after the part geometry and the process plan have been reviewed.",
    ],
    features: [
      "Type I (Chromic Acid) — Thin oxide layer, paint base",
      "Type II (Sulphuric Acid) — Corrosion protection, coloured finish",
      "Type III (Hard Anodising) — Thick, hard layer, wear resistance",
      "Colouring — Organic and inorganic dyes",
      "Type I / II / III — MIL-A-8625 coating classes",
      "ASTM B117 Salt Spray — If the specification requires it",
    ],
    technicalSpecs: [
      { label: "Layer thickness", value: "Per specification" },
      { label: "Layer hardness", value: "HV; to alloy and process" },
      { label: "Salt Spray", value: "ASTM B117; per specification" },
      { label: "Coating Class", value: "MIL-A-8625 Type I / II / III" },
      { label: "Working range", value: "Stated in the quote" },
      { label: "Colour Tolerance", value: "Per specification" },
    ],
    processSteps: ["Surface Cleaning & Degreasing", "Etching", "Anodising Bath", "Colouring (Optional)", "Sealing", "Quality Inspection & Reporting"],
    advantages: [
      "4 anodising types (Type I, II, III and decorative)",
      "Type I, Type II and Type III coating classes",
      "ASTM B117 salt spray test if the specification requires it",
      "Decorative and functional finishes with organic and inorganic dyes",
      "Lead time is given with the quote according to batch size and coating class",
      "Quality inspection by coating thickness and hardness measurement",
      "Experience in the aerospace, automotive, medical and defence sectors",
    ],
    materials: [
      { name: "Aluminium 6061-T6", grade: "Al-Mg-Si alloy", properties: "Most common, excellent anodising response, even colour" },
      { name: "Aluminium 7075-T6", grade: "Al-Zn-Mg alloy", properties: "High strength, anodised colour tone may vary" },
      { name: "Aluminium 5083", grade: "Al-Mg alloy", properties: "Marine grade, good corrosion resistance" },
      { name: "Aluminium 2024-T3", grade: "Al-Cu alloy", properties: "Aerospace, copper content may affect colour uniformity" },
      { name: "Titanium Grade 2", grade: "Commercially pure titanium", properties: "Medical and aerospace, special anodising parameters" },
      { name: "Cast Aluminium (A356)", grade: "Al-Si-Mg casting", properties: "Cast parts, porosity affects anodising quality" },
    ],
    faq: [
      { question: "Which metals can be anodised?", answer: "Mainly aluminium and its alloys. Titanium and magnesium can also be anodised. The most common applications are the Al 6061 and 7075 series alloys." },
      { question: "What is the difference between hard anodising (Type III) and normal (Type II)?", answer: "Type III hard anodising forms a thicker, harder layer than Type II and is preferred where wear resistance and electrical insulation are needed. Type II suits general corrosion protection and decorative finishes. Thickness and hardness values are set by the specification and the alloy." },
      { question: "Does anodising change the dimensions?", answer: "Yes. In sulphuric anodising roughly half of the oxide layer penetrates the material and half grows outward from the surface; in hard anodising the ratio differs. So each face grows by part of the layer thickness, and a diameter by twice that. The exact allowance is set before processing together with the masking and tolerance plan." },
      { question: "Which anodising colours can you do?", answer: "We work in black, red, blue, green, gold, bronze, purple, orange, yellow, smoke and natural (clear). Custom RAL and Pantone matching is also possible; the colour tolerance is defined by the specification." },
      { question: "How durable is the coating?", answer: "Durability depends on the anodising type, the layer thickness and the sealing. The corrosion test (e.g. ASTM B117) and its acceptance criteria are set by the specification; hard anodising is preferred for surfaces that need wear resistance." },
      { question: "What is your anodising lead time?", answer: "The lead time depends on batch size, coating class and whether a colouring step is included. It is given with the quote after material supply, the number of operations and the capacity plan have been reviewed." },
    ],
    comparisonTables: [
      {
        title: "Anodising Types Compared",
        description: "The types follow MIL-A-8625; layer thickness, hardness (HV) and corrosion-test requirements are set by the alloy and the specification.",
        headers: ["Feature", "Type I (Chromic Acid)", "Type II (Sulphuric Acid)", "Type III (Hard Anodising)"],
        rows: [
          ["Colouring", "Limited", "Full colour range", "Limited (black, dark tones)"],
          ["Electrical Insulation", "Medium", "Good", "High"],
          ["Wear Resistance", "Low", "Medium", "High"],
          ["Suitable Application", "Aerospace structural, paint base", "General engineering, decorative", "Cylinder, piston, shaft surfaces"],
          ["Standard", "MIL-A-8625 Type I", "MIL-A-8625 Type II", "MIL-A-8625 Type III"],
          ["Cost", "$", "$$", "$$$"],
        ],
      },
      {
        title: "Anodising Compatibility of Aluminium Alloys",
        description: "How the choice of alloy affects anodising quality",
        headers: ["Alloy", "Colour Uniformity", "Coating Quality", "Recommended Type", "Notes"],
        rows: [
          ["6061-T6", "Excellent", "Even, smooth", "Type I, II, III", "Most common, ideal for anodising"],
          ["7075-T6", "Good", "Slight tone variation possible", "Type II, III", "Zn content may affect the colour tone"],
          ["5083", "Good", "Even", "Type II", "Marine, good corrosion resistance"],
          ["2024-T3", "Medium", "Copper streaks may show", "Type I, II", "Cu content may spoil colour uniformity"],
          ["A356 (Casting)", "Low", "Porous, uneven", "Type II", "Casting quality is critical, pre-treatment needed"],
          ["MIC-6 (Casting)", "Medium", "Acceptable", "Type II", "Suitable for precision cast plate"],
        ],
      },
    ],
  },
  "kimyasal-islemler": {
    categoryLabel: "Surface Treatments",
    title: "Chemical Treatments",
    metaTitle: "Chemical Surface Treatments | Passivation & Phosphating | Mas Technic",
    metaDescription: "Industrial degreasing, passivation, phosphating and electropolishing. Verification by ASTM B117 salt spray and ASTM A967 passivation test methods.",
    description: "Surface cleaning and preparation for subsequent processes by degreasing, passivation, phosphating and electropolishing.",
    content: [
      "Chemical surface treatments improve the corrosion resistance of your parts. We carry out industrial washing and ultrasonic degreasing, passivation for corrosion protection of stainless steel, phosphating as surface preparation for paint adhesion, electropolishing for brightening stainless steel and deburring to soften sharp edges.",
      "The verification method — for example ASTM B117 salt spray or ASTM A967 passivation tests — and the acceptance criteria are set by the specification. Layer thickness depends on the process: passivation leaves no measurable coating; for phosphating the thickness is set by the specification.",
    ],
    features: [
      "Degreasing — Industrial washing, ultrasonic",
      "Passivation — Corrosion protection of stainless steel",
      "Phosphating — Surface preparation for paint adhesion",
      "Electropolishing — Brightening stainless steel",
      "Deburring — Softening sharp edges",
    ],
    technicalSpecs: [
      { label: "Salt Spray", value: "ASTM B117; per specification" },
      { label: "Layer thickness", value: "To process and specification" },
      { label: "Test Method", value: "ASTM B117 salt spray" },
      { label: "Passivation", value: "ASTM A967" },
    ],
    processSteps: ["Surface Analysis", "Pre-cleaning", "Chemical Treatment", "Rinsing", "Drying & Inspection"],
    advantages: [
      "Corrosion-test requirement defined by the specification",
      "Verification by salt spray and passivation test methods",
      "Ultrasonic cleaning capability",
      "Surfaces ready for subsequent processes",
    ],
    comparisonTables: [
      {
        title: "Chemical Surface Treatment Methods",
        description: "Standards and process types; layer thickness and corrosion-test requirements are set by the specification.",
        headers: ["Process", "Applied To", "Coating/Effect", "Standard", "Application"],
        rows: [
          ["Passivation (Nitric)", "Stainless steel", "Passive oxide (no coating left)", "ASTM A967", "Medical, food"],
          ["Passivation (Citric)", "Stainless steel", "Passive oxide (no coating left)", "ASTM A967", "Greener alternative"],
          ["Phosphating (Zinc)", "Steel", "Zinc phosphate conversion layer", "MIL-DTL-16232", "Paint base preparation"],
          ["Phosphating (Manganese)", "Steel", "Manganese phosphate conversion layer", "MIL-DTL-16232", "Wear resistance, oil retention"],
          ["Electropolishing", "Stainless steel", "Surface levelling", "ASTM B912", "Medical, food, optics"],
          ["Alodine (Chromate)", "Aluminium", "Chromate conversion layer", "MIL-DTL-5541", "Paint base, conductivity"],
        ],
      },
    ],
  },
  "boya-koruyucu-kaplamalar": {
    categoryLabel: "Surface Treatments",
    title: "Paint & Protective Coatings",
    metaTitle: "Powder Coating & Protective Coatings | RAL Colours | Mas Technic",
    metaDescription: "Powder coating, wet paint, ceramic and PTFE coatings; standard and custom RAL colours. Corrosion-test and temperature-resistance requirements are set by the coating system and the specification.",
    description: "Powder coating, wet paint, ceramic coating and special protective coatings, from industrial applications to decorative surfaces.",
    content: [
      "We offer four paint types: powder coating (environmentally friendly and durable), wet paint (smooth surface), ceramic coating (high-temperature resistance) and E-coat (electrical insulation). Coating thickness is set by the specification and the part.",
      "We offer a wide colour range including RAL 9005 (Black), 9010 (White), 9006 (Grey), 3000 (Red), 5015 (Blue), 6018 (Green), 1003 (Yellow), 2004 (Orange) and custom RAL colours. Corrosion and temperature resistance depend on the coating system; test requirements such as salt-spray duration are confirmed at the quotation stage according to the specification.",
    ],
    features: [
      "Powder Coating — Environmentally friendly and durable",
      "Wet Paint — Smooth surface",
      "Ceramic Coating — High temperature",
      "E-Coat — Electrical insulation",
    ],
    technicalSpecs: [
      { label: "Coating thickness", value: "Per specification" },
      { label: "Salt Spray", value: "ASTM B117; per specification" },
    ],
    processSteps: ["Surface Preparation", "Primer Application", "Paint / Coating", "Baking / Curing", "Quality Inspection"],
    advantages: [
      "4 paint/coating types",
      "Standard and custom RAL colours",
      "Corrosion-test requirement defined by the specification",
      "Non-stick, low-friction surfaces with PTFE coating",
    ],
    comparisonTables: [
      {
        title: "Paint & Coating Types Compared",
        description: REF,
        headers: ["Coating Type", "Thickness", "Temperature Resistance", "Friction Coeff.", "Application"],
        rows: [
          ["Powder Coat (Polyester)", "60-120µm", "180°C", "0.30-0.40", "Outdoor, decorative"],
          ["Powder Coat (Epoxy)", "60-100µm", "120°C", "0.35-0.45", "Indoor, chemical resistance"],
          ["Wet Paint (2K PU)", "25-50µm", "130°C", "0.30-0.40", "Smooth surface, thin coat"],
          ["Ceramic Coating", "50-100µm", "1000°C", "0.15-0.25", "Exhaust, engine, high temperature"],
          ["PTFE (Teflon)", "15-40µm", "260°C", "0.05-0.10", "Non-stick, low friction"],
          ["E-Coat (Electrocoat)", "20-40µm", "150°C", "0.35-0.45", "Automotive, electrical insulation"],
          ["DLC (Diamond-Like)", "1-5µm", "350°C", "0.05-0.15", "Wear, medical, space"],
        ],
      },
    ],
  },
};
