import type { ServiceText } from "../types";

export const part4: Record<string, ServiceText> = {
  "kitting-paketleme": {
    categoryLabel: "Assembly & Joining",
    title: "Kitting & Packaging",
    description: "Customer-specific kitting, labelling and protective packaging. Improve the efficiency of your supply chain.",
    content: [
      "We deliver your products safely with vacuum (moisture and dust protection), ESD/antistatic (electronic parts), foam (fragile parts) and wooden crate (heavy and valuable parts) packaging options.",
      "We offer comprehensive labelling with barcode labels, RFID tags, customer-specific label design and multi-language support. Our packaging service includes MIL-PRF-81705 class ESD protective packaging, VCI and desiccant protection, and DDP/FCA delivery options.",
    ],
    features: [
      "Vacuum Packaging — Moisture and dust protection",
      "ESD (Antistatic) — For electronic parts",
      "Foam Protection — For fragile parts",
      "Wooden Crate — For heavy and valuable parts",
    ],
    technicalSpecs: [
      { label: "ESD Protection", value: "MIL-PRF-81705" },
      { label: "Labelling", value: "Barcode + QR + RFID" },
      { label: "Protection", value: "VCI, Desiccant" },
      { label: "Delivery", value: "DDP / FCA" },
    ],
    processSteps: ["Kit List Preparation", "Component Picking & Counting", "Protective Packaging", "Labelling", "Shipment"],
    advantages: [
      "MIL-PRF-81705 ESD protection standard",
      "Multiple labelling options including RFID",
      "VCI and desiccant protection",
      "Flexible DDP/FCA delivery options",
    ],
    comparisonTables: [
      {
        title: "Packaging Types and Protection Levels",
        headers: ["Packaging Type", "Protection Level", "Moisture Protection", "Impact Protection", "Cost", "Suitable Parts"],
        rows: [
          ["PE Bag", "Basic", "Low", "None", "$", "General, small parts"],
          ["Vacuum Bag", "High", "Excellent", "Low", "$$", "Corrosion-sensitive metal"],
          ["ESD Bag", "High", "Good", "Low", "$$", "Electronics, PCB"],
          ["Foam Insert", "Very high", "Medium", "Excellent", "$$$", "Delicate, fragile parts"],
          ["VCI Paper/Film", "High", "Excellent", "Low", "$$", "Long-term metal storage"],
          ["Wooden Crate", "Maximum", "Good", "Very high", "$$$$", "Heavy, large, valuable"],
        ],
      },
    ],
  },
  "kaynakli-imalat": {
    categoryLabel: "Assembly & Joining",
    title: "Welded Fabrication",
    description: "Joining metal parts by TIG, MIG/MAG and resistance welding. Quality control through a written welding procedure and non-destructive testing.",
    content: [
      "We join metal parts by TIG welding (Al, steel, Ti; precision applications), MIG/MAG welding (steel, Al; fast production) and resistance welding (steel; spot welding). The weldable thickness depends on the material and the joint design.",
      "Welding is carried out to a written welding procedure specification (WPS); the parameters and consumables used are recorded for each job. If the specification requires it, welds are inspected by RT, UT, PT or MT non-destructive testing and the results are added to the delivery file.",
    ],
    features: [
      "TIG Welding — Al, steel, Ti; precision applications",
      "MIG/MAG Welding — Steel, Al; fast production",
      "Resistance Welding — Steel; spot welding",
      "Written Welding Procedure — Welding to a WPS",
    ],
    technicalSpecs: [
      { label: "Procedure", value: "Welding to a WPS" },
      { label: "Thickness", value: "To the joint design" },
      { label: "NDT", value: "RT, UT, PT, MT (per specification)" },
      { label: "Materials", value: "Al, SS, Ti, Ni" },
    ],
    processSteps: ["Welding Procedure (WPS)", "Material & Equipment Preparation", "Welding", "NDT Inspection", "Quality Report"],
    advantages: [
      "Production to a written welding procedure (WPS)",
      "NDT inspection per specification",
      "Inspection and measurement records for welds",
      "TIG, MIG/MAG and resistance welding capability",
    ],
    comparisonTables: [
      {
        title: "Welding Methods Compared",
        description: "A general comparison of welding methods; not a company equipment list or capacity.",
        headers: ["Method", "Material Thickness", "Speed", "Heat Input", "Distortion", "Application"],
        rows: [
          ["TIG (GTAW)", "0.5-10mm", "Low", "Low-medium", "Low", "Precision, thin work, Al/Ti"],
          ["MIG/MAG (GMAW)", "1-20mm", "High", "Medium-high", "Medium", "Series production, steel/Al"],
          ["Resistance (Spot)", "0.2-3mm", "Very high", "Low (local)", "Very low", "Sheet metal, automotive"],
          ["Laser Welding", "0.1-8mm", "Very high", "Very low", "Minimal", "Precision, medical, electronics"],
          ["Electron Beam", "0.5-100mm", "Medium", "Very low", "Minimal", "Aerospace, nuclear"],
          ["Friction Stir", "1-50mm", "Medium", "Low", "Low", "Al alloys, space"],
        ],
      },
      {
        title: "NDT (Non-Destructive Testing) Methods",
        headers: ["Method", "Abbreviation", "Detects", "Sensitivity", "Speed", "Standard"],
        rows: [
          ["Radiographic Testing", "RT", "Internal defects, porosity", "High", "Slow", "EN ISO 17636"],
          ["Ultrasonic Testing", "UT", "Internal cracks, delamination", "Very high", "Medium", "EN ISO 17640"],
          ["Penetrant Testing", "PT", "Surface cracks", "High", "Medium", "EN ISO 3452"],
          ["Magnetic Particle", "MT", "Surface/near-surface cracks", "High", "Fast", "EN ISO 17638"],
          ["Visual Inspection", "VT", "Surface defects", "Medium", "Very fast", "EN ISO 17637"],
        ],
      },
    ],
  },
  "makine-parkuru": {
    categoryLabel: "Production Infrastructure",
    title: "Machine Park",
    metaTitle: "Production Capabilities | CNC Milling, Turning, EDM | Mas Technic",
    metaDescription: "5-axis CNC milling, C/Y-axis turning, Swiss turning, deep hole machining and wire EDM. Process selection to suit the part geometry.",
    description: "Which machine a part is made on is decided by its geometry and its tolerance chain. Our process families are planned together so that this decision can follow the part's requirements.",
    content: [
      "Production planning starts with the part, not with a machine list. The number of set-ups, the faces that must be reached, the dimensional chain and the behaviour of the material decide which process family is used and in what order.",
      "5-axis simultaneous milling is used for geometries that need access to several faces in one clamping. Fewer set-ups do not just save time: every new set-up adds a new error source to the dimensional chain, so reducing them works directly in favour of the tolerance.",
      "C- and Y-axis turning combines turning and milling operations on rotational parts in one set-up. Sliding-headstock (Swiss-type) turning limits deflection on small-diameter, long parts by keeping the unsupported length short.",
      "Deep hole machining, wire EDM and sinker EDM are used for geometries milling cannot reach: channels with a high length-to-diameter ratio, sharp internal corners in hard materials, thin-walled sections.",
      "Machine accuracy is an input to production, not its result. Accuracy is therefore monitored by periodic checks, confirmed with a test part before critical jobs, and when a deviation appears the process is corrected, not the part.",
    ],
    features: [
      "5-Axis Simultaneous Milling — multi-face geometries in one clamping",
      "3- and 4-Axis Milling — flat faces, pockets and peripheral machining",
      "C/Y-Axis CNC Turning — turning and milling of rotational parts in one set-up",
      "Sliding-Headstock (Swiss) Turning — small-diameter, long parts",
      "Deep Hole Machining — holes with a high length-to-diameter ratio",
      "Wire and Sinker EDM — sharp internal corners in hard materials",
    ],
    technicalSpecs: [
      { label: "Milling Configuration", value: "3-, 4- and 5-axis" },
      { label: "Turning Configuration", value: "C and Y axis, sliding headstock" },
      { label: "Standard Tolerance", value: "±0.01 mm" },
      { label: "Process Selection", value: "To geometry and dimensional chain" },
      { label: "Accuracy Monitoring", value: "Periodic check + test part" },
      { label: "Inspection", value: "Measurement to the inspection plan" },
    ],
    processSteps: ["Technical Review", "Process Selection", "Capacity Planning", "CAM Programming", "Set-up & Clamping", "CNC Machining", "In-process Inspection", "Final Inspection"],
    advantages: [
      "The process is chosen to suit the part's geometry; the part is not forced to fit the process",
      "The number of set-ups is minimised with the dimensional chain in mind",
      "Machine accuracy is monitored by periodic checks and test parts",
      "The inspection plan for critical dimensions is prepared before production",
      "Milling, turning and EDM can be planned together for the same job",
      "When a deviation appears the process is corrected, not the part",
    ],
    faq: [
      { question: "Which process will my part be made with?", answer: "The geometry decides: the faces that must be reached, the dimensional chain, the length-to-diameter ratio and the material. After the technical review we share, with the quote, which process will be used and in how many set-ups." },
      { question: "Is 3-axis or 5-axis needed?", answer: "Flat faces and simple pockets are more economical on 3 axes. If undercuts, inclined faces or several faces in one clamping are needed, 5-axis is preferred; fewer set-ups work in favour of the tolerance." },
      { question: "Can sharp internal corners be made in hard materials?", answer: "In milling, the internal corner radius is limited by the tool diameter. For corners below that limit, wire or sinker EDM is used." },
      { question: "How do you confirm machine accuracy?", answer: "Accuracy is monitored by periodic checks and confirmed by measuring a test part before critical jobs. The measurement results are recorded." },
      { question: "What do you do with long, slender parts?", answer: "Sliding-headstock turning limits deflection by keeping the unsupported length short. If needed, the operation sequence and support arrangement are re-planned for the part." },
    ],
    comparisonTables: [
      {
        title: "Applications by Process Family",
        description: "Which process family is preferred for which part geometry",
        headers: ["Process Family", "Typical Geometry", "Why It Is Chosen", "Limitation"],
        rows: [
          ["5-Axis Milling", "Multi-face parts with inclined planes", "Reduces set-ups and shortens the dimensional chain", "Long set-up and programming time"],
          ["3/4-Axis Milling", "Flat faces, pockets, peripheral slots", "Economical and quick to set up", "Inadequate for undercuts and inclined faces"],
          ["C/Y-Axis Turning", "Rotational bodies, shafts with cross holes", "Combines turning and milling in one set-up", "Not suited to non-rotational geometry"],
          ["Sliding-Headstock Turning", "Small-diameter, long parts", "Shortens the unsupported length, limits deflection", "Narrow diameter range"],
          ["Deep Hole Machining", "Holes with a high length-to-diameter ratio", "Preserves straightness and chip evacuation", "The hole axis is constrained"],
          ["Wire / Sinker EDM", "Sharp internal corners in hard materials", "No cutting force, copies the form", "Low material removal rate"],
        ],
      },
      {
        title: "Accuracy Monitoring",
        description: "How machine accuracy is monitored",
        headers: ["When", "What Is Done", "What It Leaves"],
        rows: [
          ["Start of shift", "Operator check", "Operation record"],
          ["Before a critical job", "Test part measurement", "Measurement record"],
          ["Periodically", "Geometry and accuracy check", "Maintenance record"],
          ["When a deviation appears", "Process correction and re-validation", "Corrective action record"],
        ],
      },
    ],
  },
  "malzeme-kutuphanesi": {
    categoryLabel: "Production Infrastructure",
    title: "Material Library",
    metaTitle: "Material Library | Traceable Supply | Mas Technic",
    metaDescription: "A wide range of materials from aluminium to titanium and from PEEK to Inconel. Traceable supply through batch and heat records; material certificates on request.",
    description: "A wide range of materials, from aluminium to titanium and from plastics to composites, to suit your project. Material certificates and batch records are provided on request.",
    content: [
      "The Mas Technic material library covers metals, plastics, composites and special alloys, from aerospace-grade aluminium to medical-grade titanium and from high-performance plastics to superalloys.",
      "Our metals include aluminium (6061, 7075, 5083 — 95-150 HB), stainless steel (304, 316, 17-4PH — 150-350 HB), carbon steel (1045, 4140, 4340 — 200-350 HB), titanium (Gr2, Gr5 Ti6Al4V — 250-350 HB) and brass/bronze (C360, C932 — 60-150 HB).",
      "Our plastics and composites include acetal (POM — low friction), nylon (PA6, PA66 — wear resistance), PTFE (chemical resistance), PEEK (high temperature — aerospace/medical) and polycarbonate (PC — transparency). Among special alloys we can supply Inconel 718 (high temperature — turbines), Hastelloy (corrosion — chemical industry), Kovar (thermal expansion — electronics) and tungsten (high density — radiation shielding).",
      "At goods-in the certificate and material identity are checked, a dimensional check is made and the material is recorded with its batch and heat number. The supply approach and lead time depend on the material class and are stated in the quote.",
    ],
    features: [
      "Wide Material Range — metals, plastics, composites and special alloys",
      "Material Certificate — Provided on request",
      "Goods-in Inspection — Certificate, identity and dimensional check",
      "Batch Traceability — Full tracking from raw material to finished part",
      "Stock Tracking — Material and batch records",
      "Aerospace & Medical Grade — material selection per specification",
    ],
    technicalSpecs: [
      { label: "Material Groups", value: "Metal, plastic, composite, special alloy" },
      { label: "Certificate", value: "On request" },
      { label: "Supply", value: "To material class" },
      { label: "Supply lead time", value: "Stated in the quote" },
    ],
    processSteps: ["Stock Check", "Certificate Verification", "Identity Check", "Dimensional Check", "Storage", "Batch Tracking"],
    advantages: [
      "Engineering support to choose the right material for each project",
      "Supply lead time planned by material class",
      "Goods-in inspection with certificate and identity checks",
      "Stock and supply tracking through material and batch records",
      "Supply assurance through multiple suppliers",
      "Material selection per specification for aerospace and medical applications",
    ],
    materials: [
      { name: "Aluminium", grade: "6061, 7075, 5083", properties: "Typically 95-150 HB, aerospace/electronics" },
      { name: "Stainless Steel", grade: "304, 316, 17-4PH", properties: "Typically 150-350 HB, medical/food" },
      { name: "Carbon Steel", grade: "1045, 4140, 4340", properties: "Typically 200-350 HB, mechanical parts" },
      { name: "Titanium", grade: "Gr2, Gr5 (Ti6Al4V)", properties: "Typically 250-350 HB, medical/aerospace" },
      { name: "Brass / Bronze", grade: "C360, C932", properties: "Typically 60-150 HB, gear and bearing applications" },
      { name: "Inconel 718", grade: "Superalloy", properties: "High temperature, turbine parts, made to order" },
      { name: "PEEK", grade: "450G", properties: "High temperature, chemical resistance, aerospace/medical" },
      { name: "POM (Delrin)", grade: "Delrin 150/500", properties: "Low friction, gears and bearings" },
    ],
    faq: [
      { question: "Which material certificates do you provide?", answer: "A material certificate and chemical analysis report are provided on request. Every delivery is recorded with its batch and heat number." },
      { question: "How long does material supply take?", answer: "The supply time depends on the material class; special materials such as titanium and Inconel are supplied to order. The time is stated in the quote." },
      { question: "Can you supply special alloys?", answer: "Yes. Special alloys such as Inconel 718, Hastelloy, Kovar and tungsten are supplied to order. The lead time is given with the quote after material supply, the number of operations and the capacity plan have been reviewed." },
      { question: "How is material quality checked?", answer: "At goods-in the certificate and material identity are verified and a dimensional check is made; the material is tracked by its batch and heat number." },
    ],
    comparisonTables: [
      {
        title: "Material Comparison Matrix",
        description: "Typical mechanical values of the main material groups; the material certificate is the basis for design.",
        headers: ["Material", "Hardness (HB)", "Tensile Strength", "Cost"],
        rows: [
          ["Al 6061-T6", "95", "310 MPa", "$"],
          ["Al 7075-T6", "150", "572 MPa", "$$"],
          ["SS 304", "187", "515 MPa", "$$"],
          ["SS 316L", "217", "485 MPa", "$$$"],
          ["Ti6Al4V (Gr5)", "334", "950 MPa", "$$$$"],
          ["Inconel 718", "363", "1034 MPa", "$$$$$"],
          ["PEEK 450G", "100 (Shore D)", "100 MPa", "$$$$"],
          ["POM (Delrin)", "85 (Shore D)", "70 MPa", "$"],
        ],
      },
      {
        title: "Supply Approach and Certificate Matrix",
        headers: ["Material Group", "Supply", "Certificate"],
        rows: [
          ["Aluminium (6061, 7075)", "To material class", "On request"],
          ["Stainless Steel (304, 316)", "To material class", "On request"],
          ["Carbon Steel (1045, 4140)", "To order", "On request"],
          ["Titanium (Gr2, Gr5)", "To order", "On request"],
          ["Inconel / Hastelloy", "To order", "On request"],
          ["PEEK / High-Perf. Plastics", "To order", "On request"],
        ],
      },
    ],
  },
  "kalite-kontrol": {
    categoryLabel: "Quality & Standards",
    title: "Quality Control",
    metaTitle: "Quality Control | Inspection Plan and Measurement Record | Mas Technic",
    metaDescription: "An inspection plan for every job, in-process inspection and final inspection to the plan. Accredited third-party CMM measurement on request. ISO 9001:2015.",
    description: "Quality control is not an inspection done after production but a plan written before it. Which dimension is checked, how and at what stage is decided before the part is clamped.",
    content: [
      "An inspection plan is created for every job. The plan defines which dimensions on the drawing are critical, by which method and at which stage each is checked, and what record each check leaves. It is the output of the technical review at the quotation stage.",
      "In-process inspections take place during production. The aim is not to catch errors at final inspection but never to pass a faulty part to the next operation. First-part approval, the steps after operations that shift dimensions such as heat treatment, and set-up changes are the natural stops for in-process inspection.",
      "Final inspection is made against the dimensions defined in the inspection plan and the results are recorded. Where coordinate measurement (CMM) is required, it is carried out by an accredited third party on request; this keeps the measurement independent of production.",
      "Material traceability runs through batch and heat records; a material certificate is added to the delivery file on request. The list of measuring and inspection equipment we use is published as a separate document and can be downloaded from the resources section.",
      "When a nonconformity appears, the question is not whether the part can be saved but why the process produced that result. Production does not continue with the same set-up until the root cause is found.",
    ],
    features: [
      "Inspection Plan — critical dimensions set before production",
      "First-Part Inspection — no series before the set-up is approved",
      "In-process Inspection — errors are not carried to the next operation",
      "Final Inspection — to the inspection plan, recorded",
      "Accredited 3rd-Party CMM — on request, independent of production",
      "Material Traceability — batch and heat records",
    ],
    technicalSpecs: [
      { label: "Management System", value: "ISO 9001:2015" },
      { label: "Standard Tolerance", value: "±0.01 mm" },
      { label: "Inspection Plan", value: "For every job" },
      { label: "CMM Measurement", value: "Accredited 3rd party, on request" },
      { label: "Measurement Record", value: "In the delivery file" },
      { label: "Traceability", value: "Batch and heat records" },
    ],
    processSteps: ["Technical Review", "Inspection Plan", "Goods-in Record", "First-Part Inspection", "In-process Inspections", "Final Inspection", "Measurement Record"],
    advantages: [
      "The inspection plan is written before production, not made up afterwards",
      "In-process inspections keep errors from reaching the next operation",
      "Coordinate measurement is done by an accredited third party, independent of production",
      "Measurement records are delivered with the delivery file",
      "Material is traced through batch and heat records",
      "In a nonconformity the process is corrected, not the part",
    ],
    faq: [
      { question: "Which quality certificates do you hold?", answer: "We hold ISO 9001:2015 and ISO 14001:2015 management system certificates. If a standard outside their scope is required, we assess it together in the technical review." },
      { question: "Do you provide a measurement report?", answer: "Yes. The dimensions defined in the inspection plan are measured and the results recorded; the measurement record is added to the delivery file." },
      { question: "Is CMM measurement performed?", answer: "Coordinate measurement is carried out by an accredited third party on request. This keeps the measurement independent of production; just state your need at the quotation stage." },
      { question: "How does the quality control process work?", answer: "The technical review produces the inspection plan; goods-in is recorded, the first part is approved, in-process inspections are made during production and final inspection is completed to the plan and recorded." },
      { question: "Can I get a material certificate?", answer: "Material is traced through batch and heat records. If you request a material certificate, it is added to the delivery file." },
    ],
    comparisonTables: [
      {
        title: "Inspection Stages and the Record Each Leaves",
        description: "Every inspection step is a decision point and leaves a record behind",
        headers: ["Stage", "Check Point", "Method", "Record Left", "Frequency"],
        rows: [
          ["1. Goods-in", "Material identity", "Batch / heat tracking", "Traceability record", "Every batch"],
          ["2. Set-up", "Tool and clamping verification", "Visual + measurement", "Set-up approval", "Every set-up"],
          ["3. First Part", "Critical dimensions", "Measurement to the inspection plan", "First-part record", "Every set-up"],
          ["4. In-process", "Dimensions prone to drift", "In-process inspection", "Operation record", "Per plan"],
          ["5. Final Inspection", "All dimensions in the inspection plan", "Measurement; accredited CMM if needed", "Measurement record", "Per plan"],
        ],
      },
      {
        title: "Choosing the Inspection Method",
        description: "The method is set by the feature to be measured and how tight the tolerance is",
        headers: ["Feature", "Typical Method", "When Accredited CMM Is Needed"],
        rows: [
          ["Diameter and length", "Measurement to the inspection plan", "When the tolerance chain is tight"],
          ["Form (flatness, cylindricity)", "Measurement to the inspection plan", "If a geometric tolerance is specified"],
          ["Position and concentricity", "Check from the datum", "When the datum structure is complex"],
          ["Surface condition", "Comparative check", "If a numerical Ra is specified"],
          ["Material identity", "Batch / heat tracking", "Not applicable — handled by documents"],
        ],
      },
    ],
  },
  "tolerans-hassasiyet": {
    categoryLabel: "Quality & Standards",
    title: "Tolerance & Precision",
    metaTitle: "Tolerance & Precision | ±0.01 mm | ISO 2768 | GD&T | Mas Technic",
    metaDescription: "±0.01 mm standard tolerance range, reading ISO 2768 and ASME Y14.5 (GD&T). The tolerance is set in the technical review according to geometry, material and the dimensional chain.",
    description: "A tolerance is not an advertising figure but a decision: how tightly each dimension is held depends on what must work in the assembly. Our standard working range is ±0.01 mm.",
    content: [
      "Our standard working range is ±0.01 mm. Whether a part can be held tighter than that is not a question for the machine alone but for the geometry, the material, the part size and the dimensional chain; it is therefore decided separately for each part in the technical review.",
      "What most often decides the tolerance is the number of set-ups. Every new set-up adds a new error source to the dimensional chain; a part finished in one clamping holds a tighter tolerance than the same part machined in two set-ups on the same machine.",
      "Geometric tolerances (GD&T) are read in the language of ASME Y14.5. Position, perpendicularity, concentricity, flatness and roundness tolerances only make sense together with the datum structure: which face is taken as the reference matters as much as the tolerance itself.",
      "For dimensions without a tolerance on the drawing, the ISO 2768 general tolerance classes apply. Which class applies is confirmed at the quotation stage; a general tolerance left undefined is the most common cause of disputes after production.",
      "A tolerance tighter than needed raises cost and lengthens delivery. In the technical review we suggest relaxing dimensions that do not affect function; deciding together which dimension is really critical makes the part both cheaper and more reliable.",
    ],
    features: [
      "±0.01 mm Standard Tolerance — confirmed per part in the technical review",
      "GD&T Reading — position, form and orientation tolerances in ASME Y14.5",
      "Datum Structure — which face is the reference is decided together",
      "ISO 2768 General Tolerances — agreed class for unspecified dimensions",
      "Dimensional Chain Analysis — assessing the number of set-ups and stack-up",
      "Tolerance Relaxation Proposal — for dimensions that do not affect function",
    ],
    technicalSpecs: [
      { label: "Standard Tolerance", value: "±0.01 mm" },
      { label: "General Tolerance", value: "ISO 2768 (agreed class)" },
      { label: "Geometric Tolerance", value: "ASME Y14.5 (GD&T)" },
      { label: "Determined by", value: "Geometry, material, dimensional chain" },
      { label: "Confirmation", value: "Technical review" },
      { label: "Inspection", value: "Measurement to the inspection plan" },
    ],
    advantages: [
      "Tolerances are agreed dimension by dimension according to the part's function",
      "The number of set-ups is minimised with the dimensional chain in mind",
      "GD&T and the datum structure are read together in the technical review",
      "The general tolerance class for unspecified dimensions is confirmed in the quote",
      "Relaxing unnecessarily tight tolerances is suggested to lower cost",
      "Critical dimensions are written into the inspection plan and leave a measurement record",
    ],
    faq: [
      { question: "What is your standard tolerance range?", answer: "±0.01 mm. Whether a part can be held tighter depends on geometry, material, part size and the dimensional chain, and is decided in the technical review." },
      { question: "Do you support geometric tolerancing (GD&T)?", answer: "Yes. We read position, perpendicularity, concentricity, flatness and roundness tolerances in ASME Y14.5 together with the datum structure and write them into the inspection plan." },
      { question: "My drawing has no tolerances — what happens?", answer: "For unspecified dimensions the ISO 2768 general tolerance classes apply. We confirm which class applies at the quotation stage." },
      { question: "What changes if I ask for a tighter tolerance?", answer: "The operation sequence, clamping arrangement and inspection method change; time and cost increase. We may suggest relaxing dimensions that do not affect function." },
      { question: "How do you show that the tolerance is held?", answer: "Critical dimensions are written into the inspection plan, measured and the results recorded. Where coordinate measurement is needed, accredited third-party measurement is provided on request." },
    ],
    comparisonTables: [
      {
        title: "ISO 2768 Tolerance Classes",
        description: "General tolerances by size range for dimensions not specified on the drawing (mm)",
        headers: ["Tolerance Class (ISO 2768)", "0.5 – 3 mm", "3 – 6 mm", "6 – 30 mm", "30 – 120 mm", "120 – 400 mm"],
        rows: [
          ["f (Fine)", "±0.05", "±0.05", "±0.1", "±0.15", "±0.2"],
          ["m (Medium)", "±0.1", "±0.1", "±0.2", "±0.3", "±0.5"],
          ["c (Coarse)", "±0.2", "±0.3", "±0.5", "±0.8", "±1.2"],
          ["v (Very Coarse)", "—", "±0.5", "±1.0", "±1.5", "±2.5"],
        ],
      },
      {
        title: "GD&T — What Each Tolerance Controls",
        description: "ASME Y14.5 symbols and the assembly question each one answers",
        headers: ["Tolerance Type", "Symbol", "What It Controls", "Typical Application", "Datum Needed"],
        rows: [
          ["Position", "⌖", "Location of a feature relative to the reference", "Hole and pin positioning", "Yes"],
          ["Perpendicularity", "⊥", "Orientation of a face relative to the datum", "Face–shaft square reference", "Yes"],
          ["Concentricity", "◎", "Coincidence of two axes", "Bearing seat, shaft", "Yes"],
          ["Flatness", "▱", "Deviation of a surface within itself", "Sealing face", "No"],
          ["Roundness", "○", "Deviation of a section from a circle", "Piston, cylinder", "No"],
          ["Runout", "↻", "Surface runout while rotating", "Shaft, spindle", "Yes"],
        ],
      },
      {
        title: "Before Tightening a Tolerance",
        description: "A tight tolerance is not always the right answer; these three questions come first",
        headers: ["Question", "Why It Is Asked", "Typical Outcome"],
        rows: [
          ["What does this dimension decide in the assembly?", "A dimension with no function creates unnecessary cost", "The dimension is relaxed"],
          ["Which datum is the dimension taken from?", "Changing the reference redistributes the tolerance", "The chain gets shorter"],
          ["In how many set-ups will it be made?", "Every set-up is a new error source", "The operation sequence changes"],
        ],
      },
    ],
  },
};
