import type { ServiceText } from "../types";

export const part1: Record<string, ServiceText> = {
  "cnc-frezeleme": {
    categoryLabel: "Machining",
    title: "CNC Milling",
    metaTitle: "CNC Milling Services | 5-Axis Precision Machining | Mas Technic",
    metaDescription: "3-, 4- and 5-axis CNC milling within a ±0.01 mm standard tolerance range. Aluminium, titanium and steel machining, with a manufacturability review alongside the quote.",
    description: "Our 5-axis CNC milling centres machine complex geometries with high precision, across a wide range of materials from aluminium to titanium and from plastics to composites.",
    content: [
      "On our 5-axis CNC milling centres we complete complex geometries in a single set-up. Fewer set-ups do not just save time: every new set-up adds a new error source to the dimensional chain, so reducing them works directly in favour of the tolerance.",
      "3-axis milling gives economical solutions for flat faces, pocketing and standard geometries. With 4-axis milling, the rotary table lets us cut slots, drill holes and machine profiles on cylindrical parts. 5-axis simultaneous milling machines the most complex part geometries in one clamping to meet the demands of the aerospace, medical and automotive sectors.",
      "High-speed machining (HSM) strategies lower the cutting force on thin-walled parts and improve the surface finish. In critical sectors such as aerospace, automotive, medical and defence our standard working range is ±0.01 mm; the achievable tolerance is set for each part in the technical review.",
      "Our team works with engineering materials such as aluminium (6061, 7075), stainless steel (304, 316), carbon steel, titanium, PEEK and POM/Delrin. We apply a DFM analysis on every project to optimise cost; the uploader in the quote flow accepts the STEP, STP, STL, OBJ, IGES, IGS and 3MF extensions, and native CAD files or drawings not on that list are received by e-mail.",
    ],
    features: [
      "3-Axis Milling — Economical solution for flat faces and standard geometries",
      "4-Axis Milling — Peripheral and profile machining with a rotary table",
      "5-Axis Simultaneous — Complex geometries in a single clamping",
      "High-Speed Machining (HSM) — Lower cutting force on thin-walled parts",
      "±0.01 mm Standard Tolerance — confirmed by the inspection plan",
      "Automatic Tool Change — uninterrupted machining over long cycles",
    ],
    technicalSpecs: [
      { label: "Working range", value: "Stated in the quote" },
      { label: "Standard Tolerance", value: "±0.01mm" },
    ],
    processSteps: ["DFM Analysis", "CAM Programming", "Fixture Preparation", "CNC Machining", "CMM Measurement", "Quality Report"],
    advantages: [
      "Any geometry with 3-, 4- and 5-axis configurations",
      "Low cutting force and good surface finish on thin-walled parts with HSM",
      "Automatic tool change",
      "Flexible from prototype to series production (min. 1 piece)",
      "Lead time is given with the quote after the capacity plan has been reviewed",
    ],
    materials: [
      { name: "Aluminium", grade: "6061-T6 / 7075-T6", properties: "Light, corrosion-resistant, good machinability" },
      { name: "Stainless Steel", grade: "304 / 316L", properties: "High corrosion resistance, hygienic" },
      { name: "Carbon Steel", grade: "1045 / 4140", properties: "High strength, suitable for heat treatment" },
      { name: "Titanium", grade: "Ti6Al4V (Grade 5)", properties: "Light, biocompatible, high strength" },
      { name: "POM (Delrin)", grade: "Delrin 150 / 500", properties: "Low friction, dimensional stability" },
      { name: "PEEK", grade: "PEEK 450G", properties: "High temperature resistance, chemical resistance" },
    ],
    faq: [
      { question: "Should I use 3-axis or 5-axis?", answer: "For flat faces and simple pockets 3-axis is sufficient and more economical. If undercuts, inclined faces or machining several faces in one clamping are needed, 5-axis is preferred." },
      { question: "What are your CNC milling tolerances?", answer: "Our standard working range is ±0.01mm. The achievable tolerance depends on geometry, material, part size and the dimensional chain, and is set for each part in the technical review." },
      { question: "Which file formats do you accept?", answer: "The uploader in the quote flow accepts these extensions: .step, .stp, .stl, .obj, .iges, .igs, .3mf — an extension not on the list does not pass the upload step. If you send your native CAD files or a PDF/DWG drawing to sales@mastechnic.com, we review them for a quote." },
      { question: "Is there a minimum order quantity?", answer: "No, we produce any quantity from a single part to series production. Prototype orders are also accepted." },
      { question: "What is your lead time?", answer: "The lead time is given with the quote after material supply, the number of operations and the capacity plan have been reviewed." },
    ],
    comparisonTables: [
      {
        title: "CNC Milling Axis Comparison",
        description: "Choose the axis configuration that suits your part geometry",
        headers: ["Feature", "3-Axis", "4-Axis (3+1)", "5-Axis Simultaneous"],
        rows: [
          ["Geometry", "Flat faces, pockets", "Cylindrical profiles", "Complex free forms"],
          ["Number of Set-ups", "2-4 set-ups", "1-2 set-ups", "Single set-up"],
          ["Set-up Time", "Short", "Medium", "Long (first part)"],
          ["Unit Cost", "$", "$$", "$$$"],
          ["Typical Application", "Plate, bracket", "Flange, slot", "Turbine, complex housing"],
        ],
      },
      {
        title: "Machining Strategies and Surface Finish",
        description: "General reference values; they do not represent company capacity. The value that applies to your part is stated in the quote.",
        headers: ["Strategy", "Feed Rate", "Surface Finish (Ra)", "Tool Life", "Application"],
        rows: [
          ["Roughing (HPC)", "5000-8000 mm/min", "Ra 3.2-6.3µm", "Standard", "Maximising chip volume"],
          ["Semi-finishing", "2000-4000 mm/min", "Ra 1.6-3.2µm", "Good", "Approaching final shape"],
          ["Finishing", "1000-2000 mm/min", "Ra 0.8-1.6µm", "Long", "Final surface quality"],
          ["HSM (High Speed)", "8000-15000 mm/min", "Ra 0.4-0.8µm", "Short", "Thin walls, hard materials"],
          ["Super-finishing", "500-1000 mm/min", "Ra 0.1-0.4µm", "Very long", "Optical surfaces, moulds"],
        ],
      },
    ],
  },
  "cnc-tornalama": {
    categoryLabel: "Machining",
    title: "CNC Turning",
    metaTitle: "CNC Turning Services | Twin-Spindle & Swiss Turning | Mas Technic",
    metaDescription: "Precision CNC turning: live-tool, Y-axis and sliding-headstock (Swiss-type) lathes. ±0.01 mm standard tolerance; the working range is stated in the quote.",
    description: "Multi-axis turning centres that can complete shafts, nuts, housings and complex rotational parts in a single set-up.",
    content: [
      "CNC turning is the most efficient production method for cylindrical and rotationally symmetric parts. Our C-axis and Y-axis CNC lathes integrate milling operations, so off-centre holes and slots are machined in the same clamping.",
      "2-axis turning produces shafts, bushings and simple cylindrical parts, while live-tool turning performs milling, drilling and tapping on the lathe through the Y axis. With turn-mill capability we both turn and mill in a single clamping, gaining precision and efficiency on complex parts.",
      "Sliding-headstock (Swiss-type) turning produces small-diameter, long parts such as screws, pins and connector pins: keeping the unsupported length short limits deflection. On twin-spindle turning centres, front and back face operations are completed in one set-up.",
      "On bar-fed lathes the bar stock advances automatically, so long batches can run continuously. The working range is stated in the quote after the part geometry and the process plan have been reviewed.",
    ],
    features: [
      "2-Axis Turning — Shafts, bushings and cylindrical parts",
      "Live-Tool Turning — Milling, drilling and tapping on the Y axis",
      "Turn-Mill — Complete machining in a single clamping",
      "Swiss Turning — Sliding headstock for small-diameter, long parts",
      "Automatic Bar Feeder — Continuous production in long batches",
      "Twin-Spindle Turning — Front and back faces in one set-up",
    ],
    technicalSpecs: [
      { label: "Working range (diameter / length)", value: "Stated in the quote" },
      { label: "Standard Tolerance", value: "±0.01mm" },
      { label: "Lathe types", value: "2-axis, C/Y, turn-mill, Swiss" },
      { label: "Bar Feeder", value: "Automatic" },
    ],
    processSteps: ["Drawing Review", "Material Preparation", "CNC Turning", "Measurement & Inspection", "Packaging"],
    advantages: [
      "Complete machining in a single clamping",
      "With the second spindle, the back face of the part is finished without a separate set-up",
      "Small-diameter, long parts with Swiss-type turning",
      "Unattended machining of long batches with the bar feeder",
      "Turn-mill covers the milling need in one operation",
    ],
    materials: [
      { name: "Aluminium", grade: "6061 / 2024 / 7075", properties: "Free-machining grade, light" },
      { name: "Brass", grade: "CuZn39Pb3 (CW614N)", properties: "Excellent machinability, decorative" },
      { name: "Stainless Steel", grade: "303 / 304 / 316", properties: "Corrosion resistance, hygienic" },
      { name: "Free-Machining Steel", grade: "1215 / 11SMnPb30", properties: "Optimised for high-speed turning" },
      { name: "Titanium", grade: "Grade 2 / Grade 5", properties: "Biocompatible, high strength-to-weight" },
      { name: "Delrin (POM)", grade: "Delrin 150 / PTFE", properties: "Low friction, wear resistance" },
    ],
    faq: [
      { question: "Should I choose turning or milling?", answer: "If your part is cylindrical or rotationally symmetric, turning is more economical. For prismatic parts, milling is preferred." },
      { question: "Are complex parts made on one machine?", answer: "On our turn-mill machines both turning and milling can be done in a single clamping. This improves precision and lowers cost." },
      { question: "When is Swiss turning needed?", answer: "For small-diameter parts with a high length-to-diameter ratio (e.g. screws, pins), a Swiss lathe keeps the cutting point close to the guide bush and so limits deflection. Whether a part suits Swiss turning is decided in the drawing review." },
      { question: "Is it suitable for series production?", answer: "Yes. On bar-fed lathes the bar stock advances automatically, so long batches can be machined without operator intervention; batch size and lead time are confirmed in the quote together with the capacity plan." },
      { question: "What diameter range can you turn?", answer: "The working range is stated in the quote after the part geometry and the process plan have been reviewed." },
    ],
    comparisonTables: [
      {
        title: "CNC Lathe Configuration Comparison",
        headers: ["Feature", "2-Axis Lathe", "Live Tool (C/Y)", "Turn-Mill", "Swiss Lathe"],
        rows: [
          ["Machining Type", "Turning only", "Turning + drilling/milling", "Complete turning + milling", "Long/slender parts"],
          ["Set-up Time", "Short", "Medium", "Long", "Medium"],
          ["Unit Cost", "$", "$$", "$$$", "$$"],
          ["Typical Part", "Shaft, bushing", "Flange, valve body", "Complex housing", "Pin, screw, connector"],
        ],
      },
      {
        title: "Turning Machinability Matrix",
        description: "General reference values; they do not represent company capacity. The value that applies to your part is stated in the quote.",
        headers: ["Material", "Cutting Speed (m/min)", "Feed (mm/rev)", "Tool Type"],
        rows: [
          ["Free-Machining Steel (11SMnPb30)", "180-250", "0.15-0.35", "Coated carbide"],
          ["Aluminium 6061", "300-600", "0.10-0.30", "PCD / Diamond"],
          ["Brass CuZn39Pb3", "200-400", "0.10-0.25", "Uncoated carbide"],
          ["Stainless 304", "120-180", "0.08-0.20", "CVD coated"],
          ["Titanium Grade 5", "40-80", "0.05-0.15", "PVD coated"],
          ["Inconel 718", "20-40", "0.05-0.10", "Ceramic / CBN"],
        ],
      },
    ],
  },
  "hassas-mikro-isleme": {
    categoryLabel: "Machining",
    title: "Precision Micro Machining",
    metaTitle: "Precision Micro Machining | Small-Diameter Tooling | Medical & Electronics | Mas Technic",
    metaDescription: "Micro milling, micro turning and micro drilling. Small-scale precision machining for electronic connectors, optics and medical components; the working range is stated in the quote.",
    description: "Micro machining for parts with features too small for standard tooling. Medical, electronic and optical components are typical applications.",
    content: [
      "Micro machining produces features that standard tools cannot reach — narrow slots, small holes, thin walls — with small-diameter tools and high spindle speeds. Optical, electronic and medical components are typical applications.",
      "Micro milling, Swiss-type micro turning and micro drilling produce small parts such as pins, screws, connector pins, nozzles and flow-control parts. The working range is stated in the quote after the part geometry and the process plan have been reviewed.",
      "For micro parts the inspection method is also chosen to suit the scale: contact measurement can deform the part, so optical methods are preferred. The inspection plan defines in advance which dimension is measured by which method, and the results are recorded.",
      "Typical applications: surgical instrument and device components in the medical sector; fuel injectors, sensor housings and micro valves in aerospace; connector pins, fibre-optic components and semiconductor test fixtures in electronics; movement parts, lens holders and camera components in watchmaking and optics.",
    ],
    features: [
      "Micro Milling — 5-axis machining with small-diameter tools",
      "Micro Turning — Swiss-type for small-diameter, long parts",
      "Micro Drilling — Small-diameter precision holes",
      "Micro Measurement — Inspection by optical measurement",
    ],
    technicalSpecs: [
      { label: "Working range", value: "Stated in the quote" },
      { label: "Standard Tolerance", value: "±0.01mm" },
    ],
    processSteps: ["Micro CAM Programming", "Special Tool Selection", "Micro Machining", "Optical Measurement", "Cleaning & Packaging"],
    advantages: [
      "Controlled machining of small-scale geometries",
      "Machining with small-diameter tools and a high-speed spindle",
      "Part cleaning and packaging to the inspection plan",
      "Inspection under optical magnification",
      "Experience in the medical, aerospace and electronics sectors",
      "Micro series production on bar-fed Swiss lathes",
    ],
    materials: [
      { name: "Titanium", grade: "Grade 5 (Ti6Al4V)", properties: "Biocompatible, light, high strength" },
      { name: "Stainless (Medical)", grade: "316L", properties: "Biocompatible, corrosion-resistant" },
      { name: "Aluminium", grade: "7075-T6", properties: "Light, high strength, good machinability" },
      { name: "Copper", grade: "C101 (OFE)", properties: "High conductivity, precision machining" },
      { name: "PEEK", grade: "PEEK 450G", properties: "High temperature, chemical resistance" },
      { name: "Tungsten Carbide", grade: "WC-Co", properties: "Extreme hardness, wear resistance" },
    ],
    faq: [
      { question: "When should micro machining be chosen?", answer: "If the features are too small for standard tools to reach — narrow slots, small holes, thin walls — micro machining is needed. Whether a part requires it is decided in the drawing review." },
      { question: "Is it more expensive than standard CNC?", answer: "Yes, special tooling, slow feed rates and precise measurement requirements make it more expensive. It is used for results that standard methods cannot achieve." },
      { question: "Can you do series production?", answer: "Yes. Series production of micro parts is possible on bar-fed Swiss lathes; the batch size is planned at the quotation stage." },
      { question: "Do you provide a measurement report?", answer: "The dimensions defined in the inspection plan are measured and the measurement record is added to the delivery file. Where coordinate measurement is needed, accredited third-party measurement is provided on request." },
    ],
    comparisonTables: [
      {
        title: "Micro Machining Technology Comparison",
        description: "General reference values; they do not represent company capacity. The value that applies to your part is stated in the quote.",
        headers: ["Parameter", "Micro Milling", "Micro Turning", "Micro Drilling", "Micro EDM"],
        rows: [
          ["Machining Speed", "Medium", "High", "Low", "Very low"],
          ["Material Constraint", "All", "Cylindrical", "All", "Conductive"],
          ["Cost", "$$$", "$$", "$$", "$$$$"],
          ["Typical Application", "Optics, medical component", "Pin, screw", "Nozzle, injector", "Micro mould"],
        ],
      },
      {
        title: "Sector Requirements for Micro Machining",
        description: "The project requirement is defined by the specification; the table is not a company capacity.",
        headers: ["Sector", "Typical Part", "Tolerance Expectation", "Documentation Expectation"],
        rows: [
          ["Medical", "Surgical instrument, medical component", "Per specification", "Biocompatible material record"],
          ["Aerospace", "Fuel injector, sensor", "Per specification", "Traceable material record"],
          ["Electronics", "Connector pin, PCB", "Per specification", "Visual acceptance criteria"],
          ["Watch & Optics", "Movement, lens holder", "Per specification", "Measurement record"],
          ["Automotive", "Injector nozzle, sensor", "Per specification", "Batch traceability"],
        ],
      },
    ],
  },
  "derin-delik-raybalama": {
    categoryLabel: "Machining",
    title: "Deep Hole Drilling & Reaming",
    metaTitle: "Deep Hole Drilling & Reaming | Gun Drill & BTA | Mas Technic",
    metaDescription: "Gun drilling, BTA drilling, reaming and honing for holes with a high length-to-diameter ratio. The working range and tolerance class are stated in the quote to the drawing.",
    description: "Precise, straight machining of holes with a high length-to-diameter ratio. Specialist solutions for hydraulic cylinders, mould cooling channels and machine parts.",
    content: [
      "Deep hole drilling is a special machining process for holes with a high length-to-diameter (L/D) ratio; at such ratios it is hard to get a straight, accurate hole with standard drills.",
      "Gun drilling uses a single-lip drill and carries the chips out with high-pressure coolant, producing small-diameter, long holes; oil galleries and cooling holes are typical applications. BTA drilling evacuates the chips through the inside of the tool and is preferred for larger-diameter deep holes.",
      "Reaming and honing bring the diameter, form and surface of the drilled hole to final size. The hole tolerance class and its lower and upper limits are set by the nominal size and the drawing.",
      "Hydraulic cylinder bodies, valve blocks, manifold bores and mould cooling channels are typical applications of these methods. The working range is stated in the quote after the part geometry and the process plan have been reviewed.",
    ],
    features: [
      "Gun Drilling — Small-diameter, long holes and oil galleries",
      "BTA Drilling — Internal chip evacuation in large-diameter deep holes",
      "Precision Reaming — Diameter and form brought to final size",
      "Honing — Bore surface improvement",
    ],
    technicalSpecs: [
      { label: "Methods", value: "Gun drill, BTA, reaming, honing" },
      { label: "Working range (diameter / depth)", value: "Stated in the quote" },
      { label: "Hole tolerance", value: "To nominal size and drawing" },
    ],
    processSteps: ["Technical Analysis", "Drilling Method Selection", "Deep Hole Machining", "Reaming / Honing", "Measurement & Report"],
    advantages: [
      "Gun drill and BTA methods",
      "Final size and surface by reaming and honing",
      "Run-out limited by guide bushes and high-pressure coolant",
    ],
    materials: [
      { name: "Steel", grade: "1045 / 4140 / 42CrMo4", properties: "High strength, suitable for heat treatment" },
      { name: "Stainless Steel", grade: "304 / 316L", properties: "Corrosion resistance, hydraulic applications" },
      { name: "Aluminium", grade: "6061 / 7075", properties: "Light, ideal for cooling channels" },
      { name: "Cast Iron", grade: "GGG-40 / GGG-50", properties: "Vibration damping, heavy load" },
      { name: "Inconel", grade: "625 / 718", properties: "High temperature resistance, aerospace" },
      { name: "Bronze", grade: "CuSn8 / CuAl10", properties: "Wear resistance, friction reduction" },
    ],
    faq: [
      { question: "What is a deep hole?", answer: "Holes with a high length-to-diameter ratio are called 'deep holes'; at such ratios it is hard to get a straight, accurate hole with standard drills." },
      { question: "What is the difference between gun drilling and BTA?", answer: "Gun drilling is used for small diameters and high length-to-diameter ratios; the chips are carried out by the coolant. BTA is preferred for larger diameters; the chips are evacuated through the inside of the tool. Which method is used is decided in the part and drawing review." },
      { question: "How is straightness achieved?", answer: "Special guide-bush systems, high-pressure coolant and optimised cutting parameters keep run-out to a minimum." },
      { question: "Can the bore surface be improved?", answer: "Yes, reaming and honing bring the bore surface and diameter to final size. The hole tolerance class and its lower and upper limits are set by the nominal size and the drawing." },
    ],
    comparisonTables: [
      {
        title: "Deep Hole Drilling Methods Compared",
        headers: ["Parameter", "Gun Drilling", "BTA Drilling", "Conventional Drill"],
        rows: [
          ["Chip Control", "External evacuation with coolant", "Internal chip evacuation", "Drill flutes"],
          ["Typical Diameter", "Small diameter", "Large diameter", "General"],
          ["Typical Application", "Oil gallery, cooling hole", "Cylinder body", "Standard hole"],
        ],
      },
    ],
  },
  "enjeksiyon-kalibi": {
    categoryLabel: "Pre-Production",
    title: "Injection Moulds",
    metaTitle: "Injection Mould Manufacturing | Mas Technic",
    metaDescription: "Aluminium and steel injection mould manufacturing. Material selection from prototype to production moulds; mould life is stated in the quote according to the mould steel and production quantity.",
    description: "Aluminium and steel mould making, from rapid prototype moulds to high-volume production moulds.",
    content: [
      "We design and manufacture high-precision plastic injection moulds. Filling behaviour is assessed in the mould design; for complex parts the scope of the flow analysis is stated in the quote. Draft angle, shrinkage compensation and gate/vent positioning are covered in the DFM analysis.",
      "The mould material is chosen to suit the expected production quantity: Al 7075 (150 HB) for prototypes and low volume, P20 (280-320 HB) for medium volume, H13 (45-52 HRC) for high volume and S136 (48-52 HRC) for applications that need corrosion resistance. Hot-runner support saves material and improves cycle time.",
      "Aluminium moulds are ready sooner for low and medium volumes, while steel moulds last longer in high-volume production. The expected quantity and the part geometry decide the mould material and the number of cavities together.",
    ],
    features: [
      "Aluminium Mould — quick preparation for low and medium volume",
      "Steel Mould — long life in high-volume production",
      "Multi-Cavity Design — Higher productivity",
      "Hot-Runner System — Material saving and cycle improvement",
    ],
    technicalSpecs: [
      { label: "Number of Cavities", value: "Set in the quote" },
      { label: "Mould life", value: "To mould steel and quantity" },
      { label: "Tolerance", value: "±0.01mm" },
    ],
    processSteps: ["Product Analysis", "Mould Design", "Filling & Flow Assessment", "CNC Machining", "Trial Moulding", "Delivery"],
    advantages: [
      "Filling behaviour assessed in the mould design",
      "DFM analysis; draft angle and shrinkage compensation assessed separately",
      "Hot-runner system support",
      "4 mould material options (Al 7075, P20, H13, S136)",
    ],
    materials: [
      { name: "Al 7075", grade: "150 HB", properties: "Prototype and low-volume mould" },
      { name: "P20 (1.2311)", grade: "280-320 HB", properties: "Medium volume, general purpose" },
      { name: "H13 (1.2344)", grade: "45-52 HRC", properties: "High volume, hot-work steel" },
      { name: "S136 (1.2083)", grade: "48-52 HRC", properties: "Corrosion resistance, optical moulds" },
    ],
    faq: [
      { question: "How long does a mould take?", answer: "Mould lead time depends on the material grade, the number of cavities and the surface requirement; an aluminium mould is machined faster than a steel one. The lead time is given with the quote after material supply, the number of operations and the capacity plan have been reviewed." },
      { question: "Is a flow analysis necessary?", answer: "Not for every part; it is recommended especially for complex parts, to see filling problems, sink marks and warpage risk in advance. Its scope is set at the quotation stage." },
      { question: "Should I choose an aluminium or a steel mould?", answer: "Aluminium moulds are usually more economical at low quantities and steel moulds at high quantities; the threshold is set at the quotation stage according to the part geometry, the plastic and the expected production quantity." },
    ],
    comparisonTables: [
      {
        title: "Injection Mould Material Selection Matrix",
        description: "Typical hardness values of mould steels; mould life is stated in the quote according to the steel, the plastic and the production quantity.",
        headers: ["Mould Material", "Hardness", "Cost", "Application"],
        rows: [
          ["Al 7075", "150 HB", "$", "Prototype, low volume"],
          ["P20 (1.2311)", "280-320 HB", "$$", "Medium volume, general purpose"],
          ["H13 (1.2344)", "45-52 HRC", "$$$", "High volume, hot work"],
          ["S136 (1.2083)", "48-52 HRC", "$$$$", "Optical, medical, corrosion"],
          ["NAK80", "38-42 HRC", "$$$", "High gloss, pre-hardened"],
        ],
      },
      {
        title: "Number of Cavities and Production Efficiency",
        description: "As the number of cavities rises the unit cost falls and the mould investment rises; the right number is set in the quote for the part and quantity.",
        headers: ["Cavities", "Unit Cost", "Mould Cost"],
        rows: [
          ["Single cavity", "$$$", "$"],
          ["2 cavities", "$$", "$$"],
          ["4 cavities", "$$", "$$$"],
          ["8 cavities", "$", "$$$$"],
          ["16+ cavities", "$", "$$$$$"],
        ],
      },
    ],
  },
  "basincli-dokum": {
    categoryLabel: "Pre-Production",
    title: "Die Casting",
    metaTitle: "Die-Casting Mould Manufacturing | Aluminium & Zamak | Mas Technic",
    metaDescription: "Design and manufacture of aluminium and zinc die-casting moulds. Wall thickness and the raw-part tolerance class are stated in the quote according to alloy and geometry.",
    description: "Complex geometries cast as a single part in aluminium and zinc alloys, with high production rates and a low unit cost.",
    content: [
      "We design and manufacture die-casting moulds to suit the part geometry, the alloy and the expected production quantity. Minimum wall thickness, the tolerance class of the raw casting (the ISO 8062 CT class varies with the nominal size) and the as-cast surface depend on the alloy, the part size and the mould design; the values are stated in the quote. Machined faces are then machined to the tolerance on the drawing.",
      "ADC12 and A380 (Al-Si) are casting alloys used for general-purpose and structural parts, ZA-8 and ZA-27 (Zn-Al) for thin-walled and heavy-load applications; the alloy is chosen to suit the part's function.",
      "In aluminium, zamak and magnesium die-casting moulds, filling and solidification behaviour is assessed in the mould design; the scope of the flow analysis is stated in the quote.",
    ],
    features: [
      "Mould Design — To part size and alloy",
      "Thin-Walled Parts — Wall thickness to alloy and geometry",
      "Raw-Part Tolerance — ISO 8062 CT class, to nominal size",
      "As-Cast Surface — Depends on the mould surface and the alloy",
    ],
    technicalSpecs: [
      { label: "Working range", value: "Stated in the quote" },
      { label: "Materials", value: "ADC12, A380, ZA-8, ZA-27" },
      { label: "Mould Life", value: "Stated in the quote" },
      { label: "Tolerance", value: "CT class to nominal size" },
    ],
    processSteps: ["Part Analysis", "Mould Design", "Filling & Flow Assessment", "Mould Manufacture", "Trial Casting", "Series Production"],
    advantages: [
      "Wide choice of alloys (Al, Zn, Mg)",
      "Mould design that accounts for filling behaviour",
      "Thin-walled part capability",
      "High production rate and low unit cost",
    ],
    comparisonTables: [
      {
        title: "Die-Casting Alloy Comparison",
        description: "Typical literature values; the material certificate is the basis for design. Not a company capacity.",
        headers: ["Alloy", "Tensile Strength", "Density", "Casting Temperature", "Application"],
        rows: [
          ["ADC12 (Al-Si)", "280 MPa", "2.74 g/cm³", "640-680°C", "General purpose, engine housing"],
          ["A380 (Al-Si-Cu)", "320 MPa", "2.71 g/cm³", "650-700°C", "High strength, structural"],
          ["ZA-8 (Zn-Al)", "350 MPa", "6.3 g/cm³", "420-440°C", "Thin wall, nut"],
          ["ZA-27 (Zn-Al)", "420 MPa", "5.0 g/cm³", "440-480°C", "Heavy load, bearing"],
          ["AZ91D (Mg)", "230 MPa", "1.81 g/cm³", "620-650°C", "Light, electronic enclosure"],
        ],
      },
    ],
  },
};
