import type { ServiceText } from "../types";

export const part6: Record<string, ServiceText> = {
  "operasyonel-verimlilik": {
    categoryLabel: "Process & Operations",
    title: "Operational Efficiency",
    metaTitle: "Operational Efficiency | Lean Manufacturing, Kaizen, SMED | Mas Technic",
    metaDescription: "Lean manufacturing, 5S, Kaizen, Kanban, TPM and SMED in practice. Defined methods for shortening setup time, cutting downtime and improving repeatability.",
    description: "Efficiency is not a target sheet but a way of working: shorter setups, less downtime and the same part coming out the same every time are results of the same discipline.",
    content: [
      "A job's duration is not just cutting time. For most jobs the decisive factors are setup, waiting, handling and re-measuring; that is why our improvement work looks at setup and flow before cutting parameters.",
      "The SMED approach splits setup work into two groups: tasks that must be done while the machine is stopped and tasks that can be prepared while it runs. Moving the second group out of the setup directly shortens the time the machine is not making parts.",
      "5S and Kanban reduce the time it takes to find things and the amount of work-in-progress stock. Standard setup procedures stop an operator doing the same job a second time from having to remake the first time's decisions — repeatability starts here.",
      "Under TPM, maintenance is a planned work step, not an intervention after a breakdown. Because machine accuracy is an input to production, a maintenance delay comes straight back as lost tolerance.",
      "The question asked in Kaizen workshops is not 'who made the mistake' but 'why is this step prone to error'. A correction made without reaching the root cause produces the same error again in the next batch.",
    ],
    features: [
      "SMED — moving setup work off the machine",
      "5S — cutting search and preparation time",
      "Kanban — material flow and work-in-progress control",
      "TPM — maintenance run as a planned work step",
      "Standard Setup Procedure — decisions are not remade",
      "Kaizen — corrective action that reaches the root cause",
    ],
    technicalSpecs: [
      { label: "Approach", value: "Lean manufacturing" },
      { label: "Setup", value: "Separated with SMED" },
      { label: "Material Flow", value: "Kanban" },
      { label: "Maintenance", value: "Planned (TPM)" },
      { label: "Improvement", value: "Kaizen workshops" },
      { label: "Record", value: "Corrective action record" },
    ],
    advantages: [
      "Setup time is addressed before cutting time",
      "Work that can be prepared while the machine runs is moved out of the setup",
      "A standard setup procedure improves repeatability",
      "Maintenance is planned; delay comes back as lost tolerance",
      "A correction is not closed until the root cause is found",
      "Improvements are recorded and followed up",
    ],
    faq: [
      {
        question: "How does efficiency work affect my part?",
        answer: "Directly in two places: as setups get shorter, small batches become economical, and a standard setup procedure makes it easier for the same part to come out the same between batches.",
      },
      {
        question: "What is SMED and why does it matter?",
        answer: "It splits setup work into tasks that must be done while the machine is stopped and tasks that can be prepared while it runs. Moving the latter out of the setup shortens the time the machine is not making parts.",
      },
      {
        question: "How do you manage maintenance?",
        answer: "Maintenance is a planned work step (TPM). Because machine accuracy is an input to production, a maintenance delay directly creates a risk of lost tolerance.",
      },
      {
        question: "What happens if a nonconformity occurs?",
        answer: "The Kaizen and corrective action process is run: production does not continue on the same setup until the root cause is found, and the correction made is recorded.",
      },
    ],
    comparisonTables: [
      {
        title: "Type of Loss and the Matching Method",
        description: "In lean manufacturing each type of loss has its own tool",
        headers: ["Type of Loss", "Where It Shows", "Method Applied", "Record Left"],
        rows: [
          ["Setup time", "Preparation while the machine is stopped", "SMED + standard setup", "Setup approval"],
          ["Searching and preparation", "Looking for tools, fixtures, gauges", "5S", "Layout standard"],
          ["Work-in-progress stock", "Parts waiting between operations", "Kanban", "Flow record"],
          ["Unplanned downtime", "Waiting after a breakdown", "TPM — planned maintenance", "Maintenance record"],
          ["Recurring error", "The same nonconformity coming back", "Kaizen — root cause analysis", "Corrective action record"],
        ],
      },
      {
        title: "Separating Setup Work (SMED)",
        description: "Which side you do a task on decides how long the machine stands idle",
        headers: ["Task", "Must the Machine Be Stopped", "How It Is Shortened"],
        rows: [
          ["Tool preparation and presetting", "No", "Prepared while the previous job runs"],
          ["Fixture mounting", "Yes", "Quick clamping and fixed datum"],
          ["Program loading and verification", "No", "Simulation is completed beforehand"],
          ["Zeroing and picking up datums", "Yes", "A standard datum surface is used"],
          ["First-part inspection", "Yes", "The control plan is ready in advance"],
        ],
      },
    ],
  },
  "havacilik-uzay": {
    categoryLabel: "High Technology",
    title: "Aerospace",
    metaTitle: "Aerospace Part Manufacturing | Ti & Inconel Machining | Mas Technic",
    metaDescription: "Machining of titanium Ti6Al4V, Inconel 718 and aerospace aluminium for aerospace. Control plan, first-part inspection and batch traceability.",
    description: "We produce engine components, structural parts and avionics housings for the aerospace industry. Traceable production tied to a control plan in hard-to-machine alloys.",
    content: [
      "We produce engine components, structural parts (brackets, fittings, ribs) and avionics housings for the aerospace industry. Titanium Ti6Al4V, Inconel 718 and aerospace aluminium alloys (7075-T6, 2024-T3) are materials that carry heat into the cutter, shorten tool life and are sensitive to clamping force.",
      "Special process needs — chemical processes (anodising, passivation, chromating), non-destructive testing, heat treatment (precipitation hardening, stress relieving) and surface coating — are planned to the project specification and run together with the supply chain. Parameters are frozen; a change requires revalidation.",
      "Our quality approach: first-part inspection, dimensional and visual inspection of the characteristics defined in the control plan, GD&T measurement, verification of the material specification (AMS, ASTM) against the batch record, and batch-level traceability. The documentation format is set by the customer specification.",
      "On our 5-axis machining centres we machine complex aerospace geometries in a single setup; our standard working range is ±0.01 mm. Toolpaths are verified by simulation, and series production does not start before first-part inspection is approved.",
    ],
    features: [
      "Hard-to-Machine Alloy Experience — Ti6Al4V, Inconel 718",
      "Special Process Planning — chemical process, NDT, heat treatment",
      "Titanium & Inconel Machining — 5-axis, HSM, special tooling",
      "First-Part Inspection — series does not start without approval",
      "Traceability — batch and heat record",
      "Frozen Process — Approved process parameters are fixed",
    ],
    technicalSpecs: [
      { label: "Management System", value: "ISO 9001:2015" },
      { label: "NDT", value: "Planned per specification" },
      { label: "Traceability", value: "Batch and heat record" },
      { label: "Materials", value: "Ti6Al4V, Inconel 718, Al 7075" },
      { label: "Standard Tolerance", value: "±0.01mm" },
      { label: "First Part", value: "Per control plan" },
    ],
    processSteps: ["Contract Review & PO", "Material Supply (per specification)", "CAM Programming & Simulation", "5-Axis CNC Machining", "NDT Inspection", "CMM & FAI Report", "Surface Treatment", "Final Inspection & Packaging"],
    advantages: [
      "Tooling and parameter discipline in hard-to-machine alloys",
      "Traceability based on batch and heat records",
      "Ti6Al4V and Inconel 718 machining expertise",
      "Complex aerospace geometries in a single 5-axis setup",
      "First-part inspection record and delivery of the measurement file",
      "Approved parameters fixed through a frozen process",
    ],
    materials: [
      { name: "Titanium", grade: "Ti6Al4V (Grade 5)", properties: "Light, biocompatible, 950 MPa tensile" },
      { name: "Inconel", grade: "718", properties: "High temperature, 1034 MPa, turbine parts" },
      { name: "Aluminium", grade: "7075-T6", properties: "High strength, aerospace structural" },
      { name: "Aluminium", grade: "2024-T3", properties: "Aerospace clad sheet, fatigue resistance" },
    ],
    faq: [
      {
        question: "Which quality certificates do you hold?",
        answer: "We hold ISO 9001:2015 and ISO 14001:2015 management system certificates. If your project requires a different standard, we assess it together in the technical review.",
      },
      {
        question: "Can you machine titanium?",
        answer: "Yes, we specialise in machining Ti6Al4V (Grade 5) and Grade 2 titanium. We get optimal results with special tooling, a low-speed/high-feed strategy and coolant management.",
      },
      {
        question: "Do you carry out first-part inspection?",
        answer: "Yes. First-part inspection is carried out and recorded for every new part and every revision; we agree the documentation format with you according to your specification.",
      },
      {
        question: "How are special processes handled?",
        answer: "Special processes such as chemical processing, non-destructive testing and heat treatment are planned to the project specification and run together with the supply chain. Parameters are frozen; a change requires revalidation.",
      },
    ],
    comparisonTables: [
      {
        title: "Aerospace Material Performance Comparison",
        description: "Typical literature values; the material certificate governs design. Not company capacity.",
        headers: ["Material", "Tensile Strength", "Density", "Max. Temperature", "Corrosion Resistance", "Cost", "Typical Application"],
        rows: [
          ["Al 7075-T6", "572 MPa", "2.81 g/cm³", "150°C", "Good (with anodising)", "$$", "Structural bracket, rib, fitting"],
          ["Ti6Al4V (Gr5)", "950 MPa", "4.43 g/cm³", "400°C", "Excellent", "$$$$", "Engine, landing gear, fastening"],
          ["Inconel 718", "1034 MPa", "8.19 g/cm³", "700°C", "Excellent", "$$$$$", "Turbine, combustion chamber, exhaust"],
          ["SS 15-5PH", "1000 MPa", "7.78 g/cm³", "316°C", "Very good", "$$$", "Actuator, valve, structural"],
        ],
      },
    ],
  },
  "savunma-sanayi": {
    categoryLabel: "High Technology",
    title: "Defence Industry",
    metaTitle: "Defence Part Manufacturing | Ballistic Steel and Special Alloys | Mas Technic",
    metaDescription: "Machining of ballistic steel, titanium and special alloys for the defence industry. Batch and heat traceability, inspection tied to the control plan.",
    description: "Precision part manufacturing for the defence industry. Production tied to a control plan in hard-to-machine materials, with batch-level traceability.",
    content: [
      "We produce critical components for land, naval and air platforms: weapon system components, optronic housings, armour parts and communication system components. We read the specification and standard requirements your project is subject to together in the technical review.",
      "In defence projects, how technical data will be shared and under what conditions it will be handled is agreed in writing at the start of the project. We assess the conditions your specification requires together at the quote stage.",
      "With our ability to machine ballistic steel (Armox 500T, Hardox 600), aerospace titanium (Ti6Al4V), high-strength steels (4340, 300M) and special alloys (Inconel, Stellite), we meet the most demanding material requirements of the defence industry.",
      "The scope of non-destructive testing (RT, UT, PT, MT) is defined in the control plan to the specification and the results are recorded. Batch-level traceability runs together with configuration and revision tracking.",
    ],
    features: [
      "Specification Reading — the project standard is assessed together in the technical review",
      "Configuration Tracking — version and revision record",
      "Data Sharing — conditions are set in writing at the start of the project",
      "Non-Destructive Testing — RT, UT, PT, MT; scope written into the plan",
      "Ballistic Material Machining — Armox 500T, Hardox 600",
      "Configuration Management — Version and change tracking",
    ],
    technicalSpecs: [
      { label: "Management System", value: "ISO 9001:2015" },
      { label: "Specification", value: "Read project by project" },
      { label: "NDT", value: "RT, UT, PT, MT (per specification)" },
      { label: "Materials", value: "Armox, Ti, 4340, 300M" },
      { label: "Conditions", value: "In writing at project start" },
      { label: "Traceability", value: "Batch and heat record" },
    ],
    processSteps: ["Setting Project Conditions", "Technical Review & Quote", "Material Supply (per specification)", "Production", "Non-Destructive Testing", "Configuration Verification", "Secure Packaging & Delivery"],
    advantages: [
      "The project specification is read line by line in the technical review",
      "Technical data conditions are set in writing at the start of the project",
      "Expertise in machining ballistic steel and special alloys",
      "The scope of non-destructive testing is defined in the control plan",
      "Traceability based on batch and heat records",
      "Configuration management and change control",
    ],
    faq: [
      {
        question: "How is my technical data handled?",
        answer: "How technical data will be shared and under what conditions it will be handled is agreed in writing at the start of the project. We assess the conditions your specification requires together at the quote stage.",
      },
      {
        question: "Can you meet my project specification?",
        answer: "We read your specification line by line in the technical review and state clearly which requirements we can meet with our current capability and which need the supply chain.",
      },
      {
        question: "Can you machine ballistic materials?",
        answer: "Yes, we can CNC machine high-hardness ballistic steels such as Armox 500T, Hardox 600 and 300M.",
      },
    ],
  },
  robotik: {
    categoryLabel: "High Technology",
    title: "Robotics & Automation",
    metaTitle: "Robotics & Automation Part Manufacturing | ±0.01 mm | Mas Technic",
    metaDescription: "Precision mechanical components for industrial robots, cobots and automation systems. Actuator bodies, joint parts, grippers. Al 7075, SS 316L, ±0.01 mm.",
    description: "Precision mechanical components for industrial robots, cobots and automation systems. Actuator bodies, joint parts and gripper components.",
    content: [
      "We produce precision mechanical components for industrial robots, collaborative robots (cobots) and custom automation systems: actuator bodies, joint parts, gearbox housings, gripper components and sensor mounting brackets.",
      "What matters in robot components is not a single dimension but the position of the axes relative to each other: concentricity and perpendicularity directly affect the arm's repeatability. That is why datum surfaces are machined in a single setup and measured from the same datum.",
      "We plan flexibly from prototype to series production. Every robotics project starts with a DFM analysis, is validated with a functional prototype and moves to series production after sample approval.",
    ],
    features: [
      "Actuator Body — Al 7075, SS 316L, ±0.01 mm",
      "Joint Parts — High precision, low weight",
      "Gripper Components — Custom geometry, functional surface",
      "Gearbox Housing — Concentric precision, thermal stability",
      "Sensor Mounting Bracket — Micro precision, vibration resistance",
      "From Prototype to Series — DFM → Prototype → Sample Approval → Series",
    ],
    technicalSpecs: [
      { label: "Standard Tolerance", value: "±0.01mm" },
      { label: "Material", value: "Al 7075, SS 316L, POM" },
      { label: "Concentricity", value: "Measured from the datum" },
      { label: "Weight Opt.", value: "Topology optimisation" },
      { label: "GD&T", value: "In the control plan" },
    ],
    advantages: [
      "Complex robot geometries in a single 5-axis setup",
      "Light, high-strength components in Al 7075",
      "Datum surfaces machined in one setup and measured from the same datum",
      "Weight and cost optimisation through DFM analysis",
      "Smooth transition from prototype to series production",
      "Concentricity and perpendicularity are defined in the control plan",
    ],
    faq: [
      {
        question: "What tolerances can you hold on robot components?",
        answer: "Our standard working range is ±0.01mm. Geometric tolerances such as concentricity and perpendicularity are assessed together with the datum structure and written into the control plan.",
      },
      {
        question: "Do you have lightweight material solutions?",
        answer: "Yes, we offer a high strength-to-weight ratio with Al 7075-T6, weight reduction through topology optimisation and high-performance plastics such as PEEK.",
      },
      {
        question: "Can you do series production?",
        answer: "Yes. In automated CNC series production, uninterrupted machining is achieved with a bar feeder and pallet system; batch size and delivery schedule are set together at the quote stage.",
      },
    ],
  },
  otomotiv: {
    categoryLabel: "Series Production",
    title: "Automotive",
    metaTitle: "Automotive Part Manufacturing | Repeatable Series Production | Mas Technic",
    metaDescription: "Engine, transmission, brake and suspension components for automotive. Repeatable series manufacturing tied to a control plan, with batch traceability.",
    description: "Repeatable series part production for the automotive supply chain: standard setup, measurement tied to the control plan and batch-level traceability.",
    content: [
      "For the automotive sector we produce engine components (cylinder heads, crankshafts, camshafts), transmission parts (gears, shafts, housings), brake system components (callipers, discs, pistons) and suspension components (control arms, ball joints, wheel studs).",
      "The move from concept to series production goes through approval points: risk analysis, control plan, pilot production and sample approval. We set the documentation scope your specification requires together at the quote stage.",
      "In automotive work what matters is not the tolerance of a single part but consistency between batches. Dimensions sensitive to tool wear are monitored by in-process checks, measurement results are recorded, and when a drift trend appears the process is corrected, not the part.",
      "We keep the automotive quality culture alive with the 8D problem-solving methodology, Poka-Yoke error-proofing systems and the Kaizen continuous improvement approach.",
    ],
    features: [
      "Standard Setup — consistency between batches",
      "Sample Approval — series does not start before the first part is approved",
      "APQP — Advanced product quality planning",
      "In-Process Check — dimensions sensitive to tool wear are monitored",
      "Automatic Tool Changing — uninterrupted machining on long batches",
      "Batch Traceability — heat and batch record",
    ],
    technicalSpecs: [
      { label: "Management System", value: "ISO 9001:2015" },
      { label: "Approval", value: "Sample approval" },
      { label: "In-Process Check", value: "Dimensions prone to drift" },
      { label: "Setup", value: "Standard procedure" },
      { label: "Inspection", value: "Per control plan" },
      { label: "Traceability", value: "Batch and heat record" },
    ],
    processSteps: ["APQP Planning", "FMEA Analysis", "Control Plan", "Pilot Production & MSA", "Sample Approval", "Series Production", "SPC Monitoring", "Continuous Improvement"],
    advantages: [
      "Series production does not start before the sample is approved",
      "The documentation scope is set by the specification",
      "Dimensions sensitive to tool wear are monitored by in-process checks",
      "Consistency between batches through a standard setup procedure",
      "8D problem solving and Poka-Yoke error-proofing",
      "Control plan, measurement and batch records in the delivery file",
    ],
    faq: [
      {
        question: "Which quality certificates do you hold?",
        answer: "We hold ISO 9001:2015 and ISO 14001:2015 management system certificates. If your customer's specification requires a sector-specific standard, we assess this openly at the quote stage.",
      },
      {
        question: "What documentation do you deliver?",
        answer: "A control plan, measurement records, the material batch/heat record and sample parts are prepared as standard. We agree any additional documents your specification requires at the quote stage.",
      },
      {
        question: "How do you maintain consistency between batches?",
        answer: "Through a standard setup procedure, first-part approval and in-process checks tied to the control plan. Dimensions sensitive to tool wear are monitored in a separate step and the results are recorded.",
      },
      {
        question: "What is your quantity range?",
        answer: "We work from prototype to series production. Batch size and delivery schedule are settled with the quote once capacity planning has been done.",
      },
    ],
  },
  medikal: {
    categoryLabel: "Series Production",
    title: "Medical & Biomedical",
    metaTitle: "Medical Part Manufacturing | Ti Gr5, SS 316L, PEEK Machining | Mas Technic",
    metaDescription: "Precision machining of medical device components, surgical instruments and implant parts. Ti Grade 5, SS 316L, CoCrMo, PEEK; batch traceability and measurement records.",
    description: "Precision machining of medical device components, surgical instruments and implant parts. Parts with difficult materials, tight tolerances and mandatory traceability.",
    content: [
      "We produce medical device components, surgical hand instruments and implant parts: implant geometries such as bone screws, plates and rods, hand instruments such as forceps and scissors, orthopaedic components and laboratory equipment parts.",
      "The materials in this sector are not easy to machine. Ti Grade 5 (Ti6Al4V) carries heat into the cutter and shortens tool life; SS 316L produces sticky chips; CoCrMo is abrasive; and PEEK and UHMWPE have high thermal expansion, so the change in size with temperature at the moment of measurement has to be taken into account.",
      "In most medical parts the surface condition is the function itself. Electropolishing and passivation not only lower surface roughness but also remove free iron, changing corrosion behaviour; which treatment is applied is set by material and specification.",
      "Traceability runs through the batch and heat record. The material certificate and measurement record are added to the delivery file on request; we agree any additional documentation your specification requires at the quote stage.",
      "Small-diameter medical screws, pins and connectors can be produced by micro machining; for long, slender geometries Swiss-type turning is preferred because it limits deflection. The working range is stated in the quote after the part geometry and process plan have been reviewed.",
    ],
    features: [
      "Biocompatible Material Machining — Ti Gr5, SS 316L, CoCrMo, PEEK, UHMWPE",
      "Micro Machining — Small-diameter screws and pins",
      "Swiss-Type Turning — deflection control on long, slender parts",
      "Electropolishing and Passivation — surface and corrosion behaviour",
      "Batch Traceability — heat and batch record",
      "Measurement Record — per control plan, in the delivery file",
    ],
    technicalSpecs: [
      { label: "Management System", value: "ISO 9001:2015" },
      { label: "Material", value: "Ti Gr5, SS 316L, CoCrMo, PEEK" },
      { label: "Standard Tolerance", value: "±0.01mm" },
      { label: "Surface", value: "Electropolishing / passivation" },
      { label: "Traceability", value: "Batch and heat record" },
      { label: "Documentation", value: "Set by the specification" },
    ],
    processSteps: ["Design Review", "Material Supply and Batch Record", "CNC / Micro Machining", "Surface Treatment (Electropolishing / Passivation)", "Measurement per Control Plan", "Cleaning and Packaging", "Delivery of Measurement Record"],
    advantages: [
      "Tooling and parameter discipline in hard-to-machine biocompatible materials",
      "Small-diameter medical part production",
      "Deflection control on long, slender parts through Swiss-type turning",
      "Surface treatment chosen by material and specification",
      "Traceability through batch and heat records",
      "Additional documentation needs are settled at the quote stage",
    ],
    faq: [
      {
        question: "Which quality certificates do you hold?",
        answer: "We hold ISO 9001:2015 and ISO 14001:2015 management system certificates. If your project requires a sector-specific standard, we assess this openly at the quote stage.",
      },
      {
        question: "Which biocompatible materials do you work with?",
        answer: "We machine Ti Grade 5 (Ti6Al4V), SS 316L, CoCrMo, PEEK and UHMWPE. The material certificate comes from the supplier and is added to the delivery file if you request it.",
      },
      {
        question: "Do you carry out surface treatment?",
        answer: "Electropolishing and passivation can be applied. Which treatment is suitable is set by the material and your specification.",
      },
      {
        question: "How do you ensure traceability?",
        answer: "Material is traced through its batch and heat record; the characteristics defined in the control plan are measured and the measurement record is added to the delivery file.",
      },
      {
        question: "Can you produce very small parts?",
        answer: "Yes. Small-diameter screws, pins and connectors can be produced; Swiss-type turning is preferred for long, slender geometries. The working range is stated in the quote after the drawing review.",
      },
    ],
  },
};
