import type { ServiceText } from "../types";

export const part7: Record<string, ServiceText> = {
  "yelken-yat-sistemleri": {
    categoryLabel: "Series Production",
    title: "Sailing & Yacht Systems",
    metaTitle: "Sailing & Yacht Part Manufacturing | Corrosion-Resistant Alloys | Mas Technic",
    metaDescription: "Corrosion-resistant part manufacturing for marine use. Machining of SS 316L, bronze and duplex steel, electropolishing and material selection with galvanic compatibility in mind.",
    description: "Corrosion-resistant precision engineering parts for sailing, yachts and marine use, suited to the seawater environment.",
    content: [
      "For sailing and yacht systems we produce corrosion-resistant parts in SS 316L, Duplex 2205, bronze (C95400) and special marine alloys. We specialise in blocks, winches, forestay fittings, steering system components and propeller shafts.",
      "In seawater what finishes a part is usually corrosion, not load. Materials are selected with galvanic compatibility in mind — dissimilar metals in contact can quickly consume even an alloy that is the right choice on its own. Electropolishing and passivation improve corrosion behaviour by removing free iron from the surface.",
      "In applications where weight is critical, titanium fasteners and special-alloy propeller shafts are assessed together against the specification and galvanic compatibility.",
    ],
    features: [
      "Galvanic Compatibility — materials in contact are assessed together",
      "Corrosion Resistance — Test requirement per specification (ASTM B117)",
      "SS 316L & Duplex — Seawater-compatible materials",
      "Electropolishing — Improving surface roughness and corrosion behaviour",
      "Bronze Machining — C95400, C95500 marine bronze",
      "Propeller Shaft — Titanium and Monel alloys",
    ],
    technicalSpecs: [
      { label: "Material", value: "SS 316L, Duplex, Bronze" },
      { label: "Salt Test", value: "ASTM B117; per specification" },
      { label: "Material Selection", value: "By galvanic compatibility" },
      { label: "Tolerance", value: "±0.01mm" },
    ],
    advantages: [
      "Materials are selected with galvanic compatibility in mind",
      "The salt spray requirement (ASTM B117) is planned per specification",
      "Expertise in machining SS 316L, duplex and bronze",
      "Electropolishing and passivation applied per specification",
      "Low roughness and improved corrosion behaviour through electropolishing",
      "Material advice compatible with cathodic protection",
    ],
    faq: [
      {
        question: "Which seawater-compatible materials do you machine?",
        answer: "We work with seawater-compatible materials such as SS 316L, Duplex 2205, bronze (C95400, C95500), Monel 400 and titanium Grade 2.",
      },
      {
        question: "Do you provide a salt test report?",
        answer: "If the specification calls for a salt spray test (ASTM B117), the test duration and acceptance criterion are set by the part specification; the scope of the report is settled at the quote stage.",
      },
    ],
  },
  "hidrolik-pnomatik": {
    categoryLabel: "Industrial Systems",
    title: "Hydraulics & Pneumatics",
    metaTitle: "Hydraulic & Pneumatic Part Manufacturing | Sealing Surfaces | Mas Technic",
    metaDescription: "Hydraulic and pneumatic system components: valve bodies, cylinders, manifold blocks. 42CrMo4, C45 steel; working pressure and sealing surface requirements per specification.",
    description: "Hydraulic and pneumatic system components: valve bodies, cylinder parts, manifold blocks and custom fluid power components.",
    content: [
      "We produce high-pressure components for hydraulic and pneumatic systems. We specialise in valve bodies (directional, pressure and flow control), cylinder parts (piston, barrel, end cap), manifold blocks (multi-port, integrated circuit) and pump components.",
      "O-ring and sealing surfaces are machined to the system's working pressure and the seal manufacturer's surface requirement. We produce in 42CrMo4, C45, SS 316 and special alloys. Internal channels in manifold blocks are machined by deep-hole drilling.",
      "Pressure and leak tests are applied to the scope defined in the control plan for each job and the results are recorded. Valve mounting faces are machined to the ISO 4401 hole pattern; connection geometries are produced to work with common hydraulic component interfaces.",
    ],
    features: [
      "Valve Body — Directional, pressure and flow control valves",
      "Cylinder Part — Piston, barrel, end cap, rod",
      "Manifold Block — Multi-port, with deep-hole channels",
      "Working Pressure — production to the pressure in the specification",
      "Sealing Surface — O-ring grooves to the seal requirement",
      "Pressure Test — Leak check per control plan",
    ],
    technicalSpecs: [
      { label: "Working pressure", value: "Project requirement (spec.)" },
      { label: "Material", value: "42CrMo4, C45, SS 316" },
      { label: "Pressure Test", value: "Defined in the control plan" },
      { label: "Hole Pattern", value: "ISO 4401" },
    ],
    processSteps: ["Drawing Review", "Material Preparation", "CNC Machining & Deep Hole", "Sealing Surface Machining", "Pressure Test", "Dimensional Inspection & CMM", "Protective Packaging"],
    advantages: [
      "Production to the working pressure in the specification",
      "Sealing surfaces machined to the seal requirement",
      "Manifold channel machining with deep-hole capability",
      "Pressure and leak testing per control plan",
      "Valve mounting faces to the ISO 4401 hole pattern",
      "42CrMo4 and SS 316 material expertise",
    ],
    faq: [
      {
        question: "Up to what pressure can you produce parts?",
        answer: "Working pressure is a design requirement of the system; the part is produced to the pressure in the customer's specification. The scope of the pressure test and the test pressure are defined in the control plan for each job.",
      },
      {
        question: "Can you machine internal channels in manifold blocks?",
        answer: "Yes, manifold channels are machined by deep-hole drilling; the achievable length/diameter ratio is stated in the quote according to channel diameter and material.",
      },
      {
        question: "How is sealing verified?",
        answer: "O-ring grooves and sealing surfaces are machined to the Ra target in the seal requirement. The scope of the pressure and leak test is defined in the control plan for each job and the results are added to the delivery file.",
      },
    ],
  },
  "boru-baglanti-parcalari": {
    categoryLabel: "Industrial Systems",
    title: "Pipes & Fittings",
    metaTitle: "Industrial Pipes & Fittings | ANSI, DIN, JIS | PN6-PN40 | Mas Technic",
    metaDescription: "Pipe fittings to ANSI, DIN and JIS standards. Flanges, adaptors, nipples, elbows. DN15-DN600, PN6-PN40. SS, CS and duplex steel.",
    description: "Industrial pipe fittings to ANSI, DIN and JIS standards. Flanges, adaptors, nipples, elbows and custom transition pieces.",
    content: [
      "For industrial piping systems we produce flanges (weld neck, slip-on, blind), adaptors (pipe diameter and standard transitions), nipples, elbows, tees and reducers. Flange bolt pattern, gasket face and diameters are machined to the ANSI B16.5, DIN EN 1092 and JIS B2220 dimension tables.",
      "We produce in the DN15-DN600 diameter range and the PN6-PN40 pressure classes. We work with carbon steel (A105, A350 LF2), stainless steel (F304, F316, F321), duplex (F51, F53) and special alloys (Inconel, Monel, Hastelloy).",
      "The scope of pressure testing, dimensional inspection and surface examination is defined in the control plan for each job; the results are recorded. Sealing faces are machined to the ASME B16.5 FF/RF geometry. Heat treatment records, NDT inspection reports and material certificates are provided on request.",
    ],
    features: [
      "Multiple Standards — ANSI B16.5, DIN EN 1092, JIS B2220",
      "Wide Diameter Range — From DN15 to DN600",
      "PN6-PN40 Pressure — Production in different pressure classes",
      "Special Alloys — Inconel, Monel, Hastelloy",
      "Sealing Face — FF/RF ASME B16.5 geometry",
      "Material Certificate — Provided on request",
    ],
    technicalSpecs: [
      { label: "Standards", value: "ANSI, DIN, JIS" },
      { label: "Pressure Class", value: "Project requirement (spec.)" },
      { label: "Diameter Range", value: "DN15-DN600" },
      { label: "Material", value: "CS, SS, Duplex, Inconel" },
      { label: "Sealing", value: "FF/RF (ASME B16.5)" },
      { label: "Certificate", value: "On request" },
    ],
    advantages: [
      "Compliance with three standards: ANSI, DIN and JIS",
      "Production across a wide DN15-DN600 diameter range",
      "Duplex and superalloy machining capability",
      "Material certificate and lot record on request",
      "Sealing faces to the ASME B16.5 geometry",
      "Heat treatment and NDT records on request",
    ],
    faq: [
      {
        question: "Which dimension tables are flange sizes machined to?",
        answer: "Flange bolt pattern, gasket face and diameters are machined to the ANSI B16.5, DIN EN 1092 and JIS B2220 dimension tables or to the technical drawing provided by the customer.",
      },
      {
        question: "Can you produce duplex steel flanges?",
        answer: "Yes, we produce flanges and fittings in Duplex 2205 (F51), Super Duplex 2507 (F53) and other corrosion-resistant alloys.",
      },
    ],
  },
  "iklim-teknolojileri": {
    categoryLabel: "Industrial Systems",
    title: "Climate Technologies",
    metaTitle: "HVAC & Refrigeration Part Manufacturing | Mas Technic",
    metaDescription: "HVAC, refrigeration and ventilation system components: compressor parts, valves, heat exchangers. Working temperature, pressure and sealing requirements per specification.",
    description: "Precision mechanical components for HVAC, refrigeration and ventilation systems.",
    content: [
      "For HVAC, refrigeration and ventilation systems we produce compressor parts (piston, valve plate, cylinder), expansion valve components, heat exchanger parts (tube sheet, baffle, connection) and fan-blower components.",
      "Working temperature and pressure are project requirements; materials are selected for these conditions. The leak test (e.g. helium leak test) and its acceptance criterion are defined in the control plan to the customer specification.",
      "We produce in Al 6061 (heat exchangers), copper (Cu-DHP, conductivity), SS 304/316 (corrosion resistance) and special alloys. Refrigerant compatibility (R-134a, R-410A, R-744) and food-contact requirements are assessed in material selection according to your specification.",
    ],
    features: [
      "Compressor Part — Piston, valve plate, cylinder",
      "Heat Exchanger — Tube sheet, baffle, connection",
      "Expansion Valve — Precise flow control",
      "Material Selection — By working temperature",
      "Sealing — Test method and acceptance criterion per specification",
      "Refrigerant Compatible — R-134a, R-410A, R-744",
    ],
    technicalSpecs: [
      { label: "Working conditions", value: "Project requirement (spec.)" },
      { label: "Sealing", value: "Per specification" },
      { label: "Material", value: "Al, Cu, SS 304/316" },
      { label: "Refrigerant", value: "R-134a, R-410A, R-744" },
      { label: "Refrigerant Class", value: "HFC / HFO / natural" },
    ],
    advantages: [
      "Material selection by working conditions",
      "The leak test method is defined per specification",
      "Material selection compatible with the refrigerant",
    ],
    faq: [
      {
        question: "How is the leak test defined?",
        answer: "The leak test method (e.g. helium leak test) and the acceptable leak rate are defined in the control plan to the customer specification; the test scope is settled at the quote stage.",
      },
      {
        question: "Which refrigerants are your parts compatible with?",
        answer: "We produce with materials and surface treatments compatible with R-134a, R-410A, R-744 (CO₂) and R-290 refrigerants.",
      },
    ],
  },
  "prototip-uretim": {
    categoryLabel: "Production Solutions",
    title: "Prototype Production",
    metaTitle: "Rapid Prototyping | CNC, 3D Printing, Silicone Moulding | Mas Technic",
    metaDescription: "Functional prototypes by CNC, 3D printing (FDM/SLA/SLS/DMLS) and silicone moulding. Production-equivalent tolerance in the real material, from a single piece.",
    description: "Functional prototype production by CNC machining, 3D printing and silicone moulding. Production-equivalent quality in the real material, single-piece orders.",
    content: [
      "We turn your design concepts into physical products. We offer prototypes in the real material (Al, SS, Ti, PEEK) at production-equivalent tolerance by CNC machining, fast concept validation by 3D printing and multiple prototypes of 10-50 pieces by silicone moulding.",
      "With a functional prototype you can test your part under real operating conditions. Design improvement through DFM analysis and control plan preparation for the move to series production are part of the process. We accept single-piece orders.",
      "Additive manufacturing options: FDM (ABS, PLA, nylon) for form and fit trials, SLA (resin) for fine detail and surface, SLS (PA12) for functional parts that need no support, and DMLS for functional metal prototypes.",
    ],
    features: [
      "Single-Piece Orders — no minimum quantity for prototypes",
      "Real Material — Production in Al, SS, Ti, PEEK",
      "3D Printing — FDM, SLA, SLS, DMLS technologies",
      "Silicone Moulding — Multiple prototypes",
      "DFM Analysis — Design optimisation included",
      "Revision Cycle — number of iterations stated in the quote",
    ],
    technicalSpecs: [
      { label: "Lead Time", value: "Given with the quote" },
      { label: "Min. Quantity", value: "1 piece" },
      { label: "Tolerance", value: "Production-equivalent" },
      { label: "Material", value: "Real material" },
      { label: "3D Printing", value: "FDM, SLA, SLS, DMLS" },
      { label: "Iterations", value: "Stated in the quote" },
    ],
    advantages: [
      "Lead time is given with the quote once method and material are chosen",
      "Functional testing in the real material",
      "4 different 3D printing technologies (including metal)",
      "Design optimisation through DFM analysis",
      "Lower design risk through a revision cycle",
      "Support for a smooth move to series production",
    ],
    faq: [
      {
        question: "How quickly can the fastest prototype be ready?",
        answer: "The choice of method directly affects lead time: 3D printing is the fastest option for concept validation, while CNC is preferred when the real material and production-equivalent tolerance are needed. Lead time is given with the quote, after material supply, the number of operations and the capacity plan have been reviewed.",
      },
      {
        question: "Can you make prototypes in the real material?",
        answer: "Yes, by CNC we produce prototypes at production-equivalent tolerance in real materials such as Al 6061, SS 304, Ti6Al4V and PEEK.",
      },
    ],
  },
  "kucuk-seri": {
    categoryLabel: "Production Solutions",
    title: "Small-Batch Production",
    metaTitle: "Small-Batch Production | CNC & Rapid Tooling | Mas Technic",
    metaDescription: "Small-batch production: CNC machining, aluminium tooling and silicone moulding; unit cost that falls as volume rises, and batch traceability.",
    description: "Small-batch production: the move from prototype to small batch, unit cost that falls with volume, and batch-level traceability.",
    content: [
      "We meet your small-batch needs with CNC machining, rapid aluminium tooling and silicone moulding; the method is chosen by quantity and precision and stated in the quote.",
      "In small batches the real driver of unit cost is setup: because setup cost is divided over the quantity, the unit price falls as volume rises. A control plan and batch-level traceability are provided as standard; tiered pricing is given with the quote.",
      "An ideal solution for market testing, pilot production and pre-production stages. Planning for the move to series production is included — we provide tooling investment analysis, automation feasibility and a cost projection report.",
    ],
    features: [
      "Flexible Batch Size — Method chosen by quantity",
      "Volume Discount — Unit cost falls as quantity rises",
      "Lead Time — given in the quote together with the capacity plan",
      "Control Plan — prepared as standard even for small batches",
      "Market Testing — Pre-production and pilot production support",
      "Series Transition Plan — Scaling advice",
    ],
    technicalSpecs: [
      { label: "Quantity Range", value: "Stated in the quote" },
      { label: "Delivery", value: "Given with the quote" },
      { label: "Quality", value: "Control plan + measurement record" },
      { label: "Volume Discount", value: "Tiered pricing in the quote" },
      { label: "Methods", value: "CNC, Al tooling, silicone" },
    ],
    advantages: [
      "Cost optimisation through volume discounts",
      "Lead time is given after setup and the capacity plan are reviewed",
      "Control plan and measurement record are standard even for small batches",
      "Smooth move from prototype to small batch",
      "Series transition plan and cost projection",
      "Lot-based traceability and quality reporting",
    ],
    faq: [
      {
        question: "Is the unit cost high in small batches?",
        answer: "The real driver of unit cost is setup, and it is divided over the quantity; the unit price falls as volume rises. We give tiered pricing and a projection for the move to series production with the quote.",
      },
      {
        question: "How does the move from small batch to series production work?",
        answer: "We plan the scaling with a tooling investment analysis, automation feasibility and a cost projection report.",
      },
    ],
  },
};
