import type { ServiceText } from "../types";

export const part5: Record<string, ServiceText> = {
  "tasarim-rehberi-dfm": {
    categoryLabel: "Engineering Support",
    title: "Design Guide (DFM)",
    metaTitle: "DFM Analysis | Design Guide | Cost Optimisation | Mas Technic",
    metaDescription: "Optimise your designs with Design for Manufacturing (DFM/DFA) analysis. CNC and injection DFM rules, manufacturability review and part-by-part cost levers.",
    description: "We optimise your designs for manufacturability through DFM/DFA analysis. Engineering support that lowers production cost, raises quality and shortens lead time.",
    content: [
      "Our Design for Manufacturing (DFM) analysis has 4 stages: initial review and draft DFM report, detailed analysis and optimisation proposals, customer meeting and revised CAD model, final DFM report and approval. The schedule depends on the complexity of the part and the completeness of the files received; it is given with the quote.",
      "Our CNC machining DFM rules: internal corner radius R > 0.5mm (avoid sharp corners), wall thickness > 0.8mm (avoid very thin walls), depth/diameter ratio < 4:1 (avoid very deep holes) and use of standard sizes (avoid special dimensions). Injection mould DFM looks at wall thickness, corner radii and gate location (gate at the thick section). Draft angle and shrinkage compensation are assessed separately; the values are set by process and material.",
      "The analysis is carried out on the solid model uploaded through the quote flow; sending a dimensioned technical drawing with the model shortens the analysis. Toolpaths are verified by simulation and checked for collisions before production.",
      "The levers we typically look at in a DFM analysis: reducing an assembly to a single part, cutting the number of setups, easing tool access, relaxing unnecessarily tight tolerances and reselecting the material for its function. Which of these has how much effect depends on the part geometry and the current production plan; the expected effect is given part by part in the analysis report.",
    ],
    features: [
      "DFM Analysis — 4-stage review, analysis, meeting and reporting",
      "CNC Machining DFM Rules — Corner, wall and depth optimisation",
      "Injection Mould DFM — Wall thickness, draft angle, shrinkage compensation, gate location",
      "CAD/CAM Integration — solid model, toolpath and revision in one flow",
      "Simulation — toolpath verification and collision checking",
      "Cost Optimisation — Part count, setup and tolerance levers",
    ],
    technicalSpecs: [
      { label: "Analysis Time", value: "Given with the quote" },
      { label: "Report Format", value: "PDF + revised CAD" },
      { label: "Supported CAD", value: "STEP, STP, STL, OBJ, IGES, IGS and 3MF" },
      { label: "Revision", value: "Scope stated in the quote" },
      { label: "Cost Levers", value: "Part count, setups, tolerance" },
      { label: "Simulation", value: "Toolpath verification" },
    ],
    processSteps: ["CAD Model Upload", "Initial Review", "Detailed Analysis", "Customer Meeting", "CAD Revision", "Final DFM Report"],
    advantages: [
      "Four-stage DFM process: review, analysis, meeting, report",
      "Work on the customer's model: the solid model received is revised and returned",
      "Toolpath simulation and collision checking before production",
      "Opportunities to cut part count, setups and operations are identified",
      "DFM rules specific to injection moulding and CNC machining",
    ],
    faq: [
      {
        question: "Is there a charge for DFM analysis?",
        answer: "We have no published fixed DFM fee. A manufacturability review of the files received is a step in preparing the quote; a separately requested detailed DFM report and CAD revisions are priced in the quote together with their scope.",
      },
      {
        question: "How long does a DFM analysis take?",
        answer: "The process has four stages: initial review, detailed analysis, customer meeting and final report. The schedule varies with the complexity of the part and the completeness of the files sent. Lead time is given with the quote, after material supply, the number of operations and the capacity plan have been reviewed.",
      },
      {
        question: "Which CAD formats do you accept?",
        answer: "The uploader in the quote flow validates these extensions: .step, .stp, .stl, .obj, .iges, .igs, .3mf — an extension not on the list does not pass the upload step. If you send your native CAD file or a dimensioned technical drawing to sales@mastechnic.com, we will review it for a quote.",
      },
      {
        question: "How much does a DFM analysis save?",
        answer: "The size of the saving depends on the part geometry and the current production plan. A DFM analysis assesses part count, number of setups, tool access and the tolerance chain; the expected effect is given part by part in the analysis report.",
      },
    ],
    comparisonTables: [
      {
        title: "CNC Machining DFM Checklist",
        description: "Assess your design against these criteria before production",
        headers: ["Criterion", "Recommended Value", "Min. / Max.", "Rule", "Effect"],
        rows: [
          ["Internal Corner Radius", "R ≥ 1mm", "R > 0.5mm", "Avoid sharp corners", "Lower risk of tool breakage"],
          ["Wall Thickness", "≥ 1.5mm (metal)", "≥ 0.8mm", "Avoid thin walls", "Prevents vibration and distortion"],
          ["Depth/Diameter Ratio", "< 3:1", "< 4:1", "Avoid deep holes", "Minimises tool deflection"],
          ["Thread Depth", "≤ 3×diameter", "≤ 5×diameter", "Avoid very deep threads", "Lower risk of breakage"],
          ["Tolerance", "ISO 2768-m", "±0.01mm (critical dimensions)", "Avoid unnecessarily tight tolerances", "Lower cost and shorter lead time"],
          ["Surface Finish", "Ra 1.6µm", "By function", "Choose Ra to suit the function", "Shorter machining time"],
        ],
      },
    ],
  },
  "yuzey-islemleri-muhendislik": {
    categoryLabel: "Engineering Support",
    title: "Surface Treatment Guide",
    metaTitle: "Surface Treatment Guide | Anodising, Nitriding, Powder Coating | Mas Technic",
    metaDescription: "A guide to choosing surface treatments, from corrosion protection to decorative coating: anodising, powder coating, nickel plating, electropolishing, an Ra roughness guide and the effect of coating on dimensions.",
    description: "From corrosion protection to electrical insulation, from decorative appearance to tribological properties, we help you choose the surface treatment best suited to your application.",
    content: [
      "Our surface treatment selection matrix: anodising for corrosion protection (aluminium — protective layer), nitriding for higher hardness (steel — surface hardness), powder coating for decorative finishes (metal — coloured coating) and e-coat for electrical insulation (aluminium — insulation). We offer a solution for each need.",
      "General guide to surface roughness (Ra): Ra 0.1-0.2µm mirror finish (optics, bearing applications), Ra 0.4-0.8µm bright surface (shafts, pistons), Ra 1.6-3.2µm matt surface (general mechanical) and Ra 6.3-12.5µm rough surface (structural parts). These ranges are industry guidance; the value achievable for your part depends on material, geometry and machining method and is stated in the quote.",
      "Coating thickness and its tolerance are set by the specification — for example the MIL-A-8625 type for anodising, the relevant plating standard for nickel. Machining tolerances are set with the dimensional change after coating taken into account.",
      "The effect of surface treatments on dimensions is considered in machining planning: part of an anodic layer grows outward from the surface (about half in sulphuric anodising), powder coating adds its own thickness, while blasting and electropolishing remove material from the surface. Allowances are set together with the specification and process parameters.",
    ],
    features: [
      "Surface Treatment Selection Matrix — Choosing the method for the need",
      "Ra Roughness Guide — From mirror finish to rough surface",
      "Coating Thickness Control — Anodising, powder coating, nickel plating",
      "Tolerance Effect Analysis — Calculating dimensional change after treatment",
      "Corrosion Requirement — A salt spray requirement is considered in coating selection",
      "Colour and Appearance — RAL/Pantone colour matching",
    ],
    technicalSpecs: [{ label: "Coating thickness", value: "Per specification" }],
    faq: [
      {
        question: "Which surface treatment suits my part?",
        answer: "It depends on the application: we recommend anodising or nickel plating for corrosion protection, nitriding for higher hardness, powder coating or anodising for appearance, and e-coat for electrical insulation. Our engineering team can carry out a detailed analysis.",
      },
      {
        question: "Does surface treatment change dimensions?",
        answer: "Yes. Anodising increases dimensions because part of the layer grows outward from the surface; blasting and electropolishing reduce them by removing material. Allowances are set from the specification and process parameters and taken into account in machining tolerances.",
      },
      {
        question: "Can you reach very low Ra values?",
        answer: "Achievable surface roughness depends on material, geometry and machining method. Surfaces that need a mirror finish are assessed in the drawing review and the target value is stated in the quote.",
      },
    ],
    comparisonTables: [
      {
        title: "Surface Treatment Selection Matrix",
        description: "Choose the surface treatment best suited to your application",
        headers: ["Surface Treatment", "Compatible Materials", "Main Function", "Typical Ra (µm)", "Cost"],
        rows: [
          ["Anodising Type II", "Aluminium, Titanium", "Corrosion resistance, colour", "0.8 – 1.6", "$$"],
          ["Hard Anodising (Type III)", "Aluminium", "Hardness, wear resistance", "0.8 – 1.6", "$$$"],
          ["Bead Blasting", "Metals, Plastics", "Matt surface, deburring", "1.6 – 3.2", "$"],
          ["Nickel Plating", "Steel, Copper", "Wear resistance, conductivity", "0.4 – 0.8", "$$$"],
          ["Powder Coating", "All Metals", "Decorative, outdoor", "N/A", "$$"],
          ["Electropolishing", "Stainless Steel", "Bright surface, hygiene", "0.1 – 0.4", "$$$"],
          ["Nitriding", "Steel", "Surface hardness", "Unchanged", "$$$$"],
        ],
      },
      {
        title: "Surface Roughness (Ra) Guide",
        description: "Typical Ra ranges by application (industry guidance); the value achievable for your part is stated in the quote.",
        headers: ["Ra Range (µm)", "Surface Appearance", "Application", "Machining Method"],
        rows: [
          ["0.1 – 0.2", "Mirror finish", "Optics, bearing surfaces", "Lapping, polishing"],
          ["0.4 – 0.8", "Bright surface", "Shafts, pistons, sealing", "Fine milling, grinding"],
          ["1.6 – 3.2", "Matt surface", "General mechanical parts", "Standard CNC machining"],
          ["6.3 – 12.5", "Rough surface", "Structural, before welding", "Roughing, blasting"],
        ],
      },
      {
        title: "Dimensional Change After Treatment",
        description: "The effect of surface treatment on dimensions; allowances are set together with the specification and process parameters.",
        headers: ["Surface Treatment", "Dimensional Change", "Planning Note"],
        rows: [
          ["Anodising Type II", "Increases (half grows outward)", "Half of the thickness penetrates the material"],
          ["Anodising Type III", "Increases; allowance per specification", "Leave a coating allowance in the machined size"],
          ["Powder Coating", "Increases (by its thickness)", "Mask critical surfaces"],
          ["Blasting", "Decreases (removes material)", "Mask precision surfaces"],
          ["Electropolishing", "Decreases (removes material)", "Material is removed, size reduces"],
        ],
      },
    ],
  },
  "dusuk-hacimli-uretim": {
    categoryLabel: "From Prototype to Series Production",
    title: "Low-Volume Production",
    metaTitle: "Low-Volume Production | 3D Printing, Silicone Moulding, CNC | Mas Technic",
    metaDescription: "Rapid prototypes by 3D printing, short runs by silicone moulding, larger batches with rapid aluminium tooling. FDM, SLA, SLS and DMLS technologies.",
    description: "We offer flexible solutions for low-volume needs with 3D printing, silicone moulding, rapid aluminium tooling and CNC machining; the method is chosen by quantity and precision.",
    content: [
      "In low-volume production the method is chosen by quantity, time and precision requirement: 3D printing suits concept validation, silicone moulding small plastic batches, aluminium tooling larger batches and CNC machining tight-tolerance parts (CNC standard tolerance ±0.01mm). The tolerance of the other methods and the lead time of each are given with the quote.",
      "Additive manufacturing options differ by the part's function: FDM (ABS, PLA, nylon) for form and fit trials, SLA (resin) for fine detail and surface, SLS (PA12, TPU) for functional parts that need no support structure, and DMLS for functional metal prototypes.",
      "Our silicone moulding process has 4 stages: 1) Master model — produced by 3D printing or CNC, 2) Silicone mould — vacuum moulding, 3) Casting — PU/silicone/EP casting, 4) Finishing — surface treatment and quality control. What drives total lead time is the preparation of the master model and the casting quantity; lead time is given with the quote.",
      "Aluminium tooling is preferred for low- and medium-volume work because it machines faster than steel tooling. In pilot runs for die casting and injection moulding it lets the design be validated before investing in production tooling.",
    ],
    features: [
      "3D Printing (FDM/SLA/SLS/DMLS) — concept validation and rapid prototyping",
      "Silicone Moulding — Short-run PU/silicone/EP casting",
      "Aluminium Tooling — for pilot production and design validation",
      "CNC Machining — ±0.01mm standard tolerance",
      "Metal 3D Printing (DMLS) — aluminium, stainless steel and titanium",
      "Functional Prototype — Testing in the production material",
    ],
    technicalSpecs: [
      { label: "Min. Quantity", value: "1 piece" },
      { label: "Methods", value: "3D printing, silicone, Al tooling, CNC" },
      { label: "Lead Time", value: "Given with the quote" },
    ],
    processSteps: ["Method Selection", "CAD/Model Preparation", "Master Model Production", "Moulding/Printing", "Finishing & Surface", "Quality Control", "Packaging & Delivery"],
    advantages: [
      "4 different methods to suit each need",
      "The method is chosen by balancing quantity, tolerance and lead time",
      "Metal and plastic 3D printing capability",
      "Low tooling cost with silicone moulds",
      "Pilot validation before series production",
      "Testing under real conditions with a functional prototype",
    ],
    faq: [
      {
        question: "Which method is best for a prototype?",
        answer: "We recommend 3D printing for fast concept validation, CNC for parts that need ±0.01mm precision and silicone moulding for small plastic batches. Lead time is given with the quote, after material supply, the number of operations and the capacity plan have been reviewed.",
      },
      {
        question: "Can you do metal 3D printing?",
        answer: "Yes. We produce metal 3D printed parts in aluminium, stainless steel and titanium by DMLS (direct metal laser sintering); part size and achievable tolerance are assessed in the technical review.",
      },
      {
        question: "How many parts does a silicone mould give?",
        answer: "The number of parts from one silicone mould varies with the casting material and geometry; the expected mould life is stated in the quote.",
      },
      {
        question: "How does the move from low volume to series production work?",
        answer: "After prototype and pilot production, steel tooling investment or automated CNC series production is planned for the approved design. The transition is coordinated by our project manager.",
      },
    ],
    comparisonTables: [
      {
        title: "Production Method Comparison (Cost vs. Quantity)",
        description: "Quantity ranges are general guidance; the standard tolerance in CNC machining is ±0.01mm, the tolerance of other methods is stated in the quote.",
        headers: ["Method", "Quantity Range", "Unit Cost", "Tooling Investment"],
        rows: [
          ["3D Printing (FDM/SLA)", "1 – 10", "$$$", "None"],
          ["3D Printing (SLS/DMLS)", "1 – 50", "$$$$", "None"],
          ["CNC Machining", "1 – 100", "$$$", "None"],
          ["Silicone Moulding", "10 – 100", "$$", "Low ($)"],
          ["Rapid Al Tooling", "100 – 1,000", "$", "Medium ($$)"],
          ["Steel Tooling (Injection)", "1,000+", "$", "High ($$$$$)"],
        ],
      },
    ],
  },
  "seri-imalat": {
    categoryLabel: "From Prototype to Series Production",
    title: "Series Manufacturing",
    metaTitle: "Series Manufacturing | Repeatable Setup and Control Plan | Mas Technic",
    metaDescription: "In series manufacturing the point is not making one part but making the hundredth part the same as the first: standard setup, control plan and batch traceability.",
    description: "With steel tooling, die casting, automated CNC and assembly lines, we aim for consistency and efficiency in high-volume series production.",
    content: [
      "In series production the method is chosen by part geometry and tolerance target. The standard tolerance in CNC series machining is ±0.01mm. For cast or moulded parts three requirements are handled separately: the machining tolerance of the tool itself, the tolerance class of the raw (as-cast or as-moulded) part and the drawing tolerance of surfaces machined afterwards. The tolerance class of the raw part is stated in the quote by process and material.",
      "In series work the setup is not done once and forgotten: a standard setup procedure, fixed datum surfaces and automatic tool changing limit variation between batches. Series production does not start before the first part is approved.",
      "Production tracking, stock and capacity planning run from a single record; which batch is where and which check it has passed is recorded at all times. Supply needs are planned from this record, and order status can be seen in the customer portal.",
      "Consistency within a batch is maintained by tying in-process checks to the plan. Dimensions prone to drift — diameters sensitive to tool wear, dimensions after heat treatment — are monitored with a separate check step and the results are recorded.",
    ],
    features: [
      "CNC Series Machining — ±0.01mm tolerance, fixed datum surfaces",
      "Die Casting — Raw part and machined surface tolerance assessed separately",
      "Injection Moulding — Tool, moulded part and machined surface assessed separately",
      "Automatic Tool Changing — uninterrupted machining on long batches",
      "Automatic Pallet Changing — setup separated from production",
      "Production Tracking — batch status kept on record",
    ],
    technicalSpecs: [
      { label: "CNC Series Machining", value: "±0.01mm tolerance" },
      { label: "Die Casting", value: "Stated in the quote" },
      { label: "Injection Moulding", value: "Stated in the quote" },
      { label: "Setup", value: "Standard procedure" },
      { label: "Inspection", value: "Per control plan" },
      { label: "Delivery", value: "Per schedule" },
    ],
    processSteps: ["Batch Record", "Pilot Production", "Series Production Approval", "Automation Setup", "Start of Series Production", "SPC & Quality Tracking", "Scheduled Delivery"],
    advantages: [
      "Consistency between batches through a standard setup procedure",
      "Batch status is kept on record throughout production",
      "Batch size and delivery frequency are tied to a schedule",
      "Dimensions prone to drift are monitored by in-process checks",
      "Full lot-based traceability",
      "Series production does not start before the first part is approved",
    ],
    faq: [
      {
        question: "What is the minimum series quantity?",
        answer: "There is no single threshold; it depends on the method. For methods that need tooling (die casting, injection moulding) the threshold is set by spreading the tooling cost over the parts; in CNC series machining setup time is decisive. We settle it at the quote stage together with part geometry and tolerance target.",
      },
      {
        question: "Can the delivery schedule be arranged?",
        answer: "Yes. Batch size and delivery frequency are agreed together with capacity planning; periodic delivery schedules can be arranged.",
      },
      {
        question: "How do you maintain consistency in series production?",
        answer: "Through first-part approval, a standard setup procedure and in-process checks tied to the control plan. Dimensions prone to drift are monitored in a separate step and measurement results are recorded.",
      },
      {
        question: "How is the machine fed on long batches?",
        answer: "Automatic tool changing and bar feeding allow uninterrupted machining on long batches. Which method is used is planned according to part geometry and batch size.",
      },
    ],
    comparisonTables: [
      {
        title: "Choosing a Series Production Method",
        description: "Method, setup and inspection approach by part geometry and tolerance",
        headers: ["Production Method", "Typical Use", "Tolerance", "Setup", "Inspection Approach"],
        rows: [
          ["CNC Series Machining", "Tight-tolerance metal parts", "±0.01mm", "Standard procedure + fixed datum", "First part + in-process check"],
          ["Die Casting", "Complex high-volume forms", "In the quote; machined surfaces per drawing", "Tool and casting parameters", "Visual + dimensional check"],
          ["Injection Moulding", "High-volume plastics", "In the quote; machined surfaces per drawing", "Tool and process window", "First part + periodic check"],
        ],
      },
    ],
  },
  "proje-yonetimi": {
    categoryLabel: "Process & Operations",
    title: "Project Management",
    metaTitle: "Project Management | Agile & Phase-Gate | Real-Time Reporting | Mas Technic",
    metaDescription: "A five-stage process from quote to delivery, moving through approval points. Each stage produces an output, and the next stage does not start until that output is approved.",
    description: "With a dedicated project manager, real-time reporting and proactive communication, we are with you at every stage of your project. Controlled, transparent process management from quote to delivery.",
    content: [
      "The methodology is chosen by project structure: a staged (waterfall) approach suits traditional mechanical projects, a phase-gate approach the move to series production, and an iterative approach projects that need frequent revisions.",
      "Our five-stage project process: 1) Assessment — quote and approval, 2) DFM analysis — report and design revision if needed, 3) Prototype — sample part, measurement record and sample approval, 4) Production file — control plan and traceability documents, 5) Series production — batch report and periodic review.",
      "Our communication and reporting channels: project meetings, status tracking through the customer portal, photo and video documentation of critical stages, delivery of the production file and an engineering change (ECO) management procedure.",
      "A single point of contact is assigned to each project; stage outputs, approvals and delivery records all go through this contact.",
    ],
    features: [
      "Dedicated Project Manager — One contact from start to finish",
      "5-Stage Process — Controlled move from assessment to series production",
      "Agile/Scrum & Phase-Gate — Methodology suited to the project structure",
      "Status Updates — Stage and approval records",
      "Production File — control plan and traceability records",
      "ECO Management — Engineering change procedure",
    ],
    technicalSpecs: [
      { label: "Assessment", value: "1-3 business days" },
      { label: "DFM Analysis", value: "Given with the quote" },
      { label: "Prototype", value: "Given with the quote" },
      { label: "Production File", value: "After sample approval" },
      { label: "Reporting", value: "By stage" },
    ],
    processSteps: ["Quote & Assessment", "DFM Analysis", "Prototype Production", "Testing & Validation", "Sample Approval", "Series Production Launch", "Continuous Improvement"],
    advantages: [
      "A single contact through an experienced project manager",
      "Progress updates by stage",
      "Photo/video documentation of critical stages",
      "Controlled change management through the ECO procedure",
      "Project tracking through a single contact",
      "Delivery of control plan and traceability records",
    ],
    faq: [
      {
        question: "Is a dedicated project manager assigned to every project?",
        answer: "Yes, a dedicated project manager is assigned to every project and acts as the single contact from quote to delivery.",
      },
      {
        question: "How can I follow project progress?",
        answer: "You can follow every stage through project meetings, status tracking in the customer portal, photo and video records of critical stages and the production file.",
      },
      {
        question: "What happens when a design change is needed?",
        answer: "Changes are managed in a controlled way through our ECO (Engineering Change Order) procedure. The revision is applied with your approval after its cost and time effects have been analysed.",
      },
    ],
    comparisonTables: [
      {
        title: "Project Management Methodologies Compared",
        description: "Choosing the best methodology for the project structure",
        headers: ["Methodology", "Suitable Project Type", "Process Flexibility", "Reporting", "Delivery Approach"],
        rows: [
          ["Agile / Scrum", "Projects with frequent revisions", "★★★★★", "By sprint", "Iterative — short cycles"],
          ["Waterfall", "Traditional mechanical projects", "★★☆☆☆", "By stage", "Sequential — Phase-Gate approved"],
          ["Phase-Gate", "Series production projects", "★★★☆☆", "Gate Review", "Controlled transition — with approval points"],
          ["Hybrid", "Complex engineering projects", "★★★★☆", "Weekly + Sprint", "Flexible — to project needs"],
        ],
      },
      {
        title: "Project Stages and Durations",
        headers: ["Stage", "Duration", "Output", "Customer Approval", "Communication Channel"],
        rows: [
          ["1. Assessment & Quote", "1-3 business days", "Detailed quote + schedule", "Quote approval", "Email + Video conference"],
          ["2. DFM Analysis", "Given with the quote", "DFM report + CAD revision", "DFM approval", "Portal + Meeting"],
          ["3. Prototype Production", "Given with the quote", "Sample part + measurement report", "Sample approval", "Photo/video + report"],
          ["4. Production File", "After sample approval", "Control plan + traceability records", "File approval", "Portal + PDF delivery"],
          ["5. Series Production", "Ongoing", "Batch report", "Periodic review", "Portal + periodic report"],
        ],
      },
    ],
  },
  "tedarik-zinciri": {
    categoryLabel: "Process & Operations",
    title: "Supply Chain",
    metaTitle: "Supply Chain Management | Dual Sourcing, Stock Strategy | Mas Technic",
    metaDescription: "Dual sourcing for critical materials, lead times by material class and batch traceability. Material supply risk is assessed before production is planned.",
    description: "A job's lead time is often set not at the machine but by when the material arrives. That is why supply risk is assessed at the quote stage, before production is planned.",
    content: [
      "Material supply is the biggest uncertainty in lead time. Standard aluminium and stainless steel can be sourced quickly, while titanium and nickel-based alloys arrive to order and their lead time can exceed production time. That is why material status is settled with the quote.",
      "For critical materials we make a point of not depending on a single source. An approved second source keeps work from stopping when supply is interrupted; alternative materials are assessed together in the technical review if they comply with the specification.",
      "Stock strategy varies by material class: safety stock is held for frequently used standard profiles and sheet, while special alloys are sourced to order. The aim is a deliberate balance between stock cost and supply risk.",
      "Every incoming material is recorded with its batch and heat record. When a nonconformity appears later in production, this record is the only reliable way to tell which batch is affected; a material certificate is added to the delivery file on request.",
    ],
    features: [
      "Dual Sourcing — an approved second supplier for critical materials",
      "Lead Time by Class — planning by material group",
      "Safety Stock — for frequently used standard materials",
      "Alternative Material — in the technical review if it complies with the specification",
      "Batch and Heat Record — for every incoming material",
      "Material Certificate — on request, in the delivery file",
    ],
    technicalSpecs: [
      { label: "Critical Material", value: "Dual source" },
      { label: "Standard Al / SS", value: "Short lead time" },
      { label: "Titanium", value: "To order" },
      { label: "Nickel-Based Alloy", value: "To order" },
      { label: "Record", value: "Batch and heat" },
      { label: "Certificate", value: "On request" },
    ],
    processSteps: ["Reading the Material Specification", "Lead Time Assessment", "Source Selection", "Order and Follow-Up", "Goods-In Record (Batch / Heat)", "Release to Production"],
    advantages: [
      "Supply risk is assessed before production is planned",
      "No dependence on a single source for critical materials",
      "Lead time is given together with the material's real supply time",
      "Alternative material is proposed only if it complies with the specification",
      "Incoming material is traced by its batch and heat record",
      "In a nonconformity the affected batch can be identified from the record",
    ],
    faq: [
      {
        question: "What is your material lead time?",
        answer: "It varies by material class: standard aluminium and stainless steel can be sourced quickly; titanium and nickel-based alloys arrive to order. We give your project's real supply time with the quote.",
      },
      {
        question: "How is the risk of supply interruption managed?",
        answer: "An approved second source is kept for critical materials, safety stock is held for frequently used standard materials and alternative materials that comply with the specification are assessed in advance.",
      },
      {
        question: "Can I get a material certificate?",
        answer: "Material is traced through its batch and heat record. If you request a material certificate, it is added to the delivery file.",
      },
      {
        question: "Can I supply the material myself?",
        answer: "Yes. In that case we take the material's specification compliance and batch record from you and plan the goods-in inspection accordingly.",
      },
    ],
    comparisonTables: [
      {
        title: "Supply Approach by Material Class",
        description: "Supply time bears directly on lead time; the strategy varies by class",
        headers: ["Material Group", "Typical Availability", "Stock Strategy", "Effect on Lead Time"],
        rows: [
          ["Standard aluminium", "Short", "Safety stock", "Low"],
          ["Stainless steel", "Short – medium", "Safety stock", "Low – medium"],
          ["Alloy steel", "Medium", "To order", "Medium"],
          ["Titanium", "Long", "To order", "High — stated in the quote"],
          ["Nickel-based alloy", "Long", "To order", "High — stated in the quote"],
          ["Engineering plastic", "Short – medium", "To order", "Low – medium"],
        ],
      },
      {
        title: "Decisions That Reduce Supply Risk",
        headers: ["Decision", "When It Is Taken", "What It Changes"],
        rows: [
          ["Approved second source", "When the material is critical", "Work does not stop on interruption"],
          ["Alternative material", "When the specification allows", "Supply time shortens"],
          ["Safety stock", "When the material is used often", "Lead-time uncertainty falls"],
          ["Early order", "When supply time is long", "The production window is protected"],
        ],
      },
    ],
  },
};
