import type { ServiceText } from "@/content/en/types";

export const part7: Record<string, ServiceText> = {
  "yelken-yat-sistemleri": {
    categoryLabel: "Serienfertigung",
    title: "Segel- und Yachtsysteme",
    metaTitle: "Teilefertigung für Segel- und Yachtsysteme | Korrosionsbeständige Legierungen | Mas Technic",
    metaDescription: "Korrosionsbeständige Teilefertigung für den maritimen Einsatz. Zerspanung von SS 316L, Bronze und Duplexstahl, Elektropolieren und Werkstoffauswahl unter Berücksichtigung der galvanischen Verträglichkeit.",
    description: "Korrosionsbeständige Präzisionsteile für Segel-, Yacht- und Marineanwendungen, ausgelegt für den Einsatz in Meerwasser.",
    content: [
      "Für Segel- und Yachtsysteme fertigen wir korrosionsbeständige Teile aus SS 316L, Duplex 2205, Bronze (C95400) und speziellen Marinelegierungen. Unsere Schwerpunkte sind Blöcke, Winschen, Vorstagbeschläge, Komponenten für Steuersysteme und Propellerwellen.",
      "In Meerwasser scheitert ein Teil meist an Korrosion, nicht an der Belastung. Die Werkstoffauswahl berücksichtigt die galvanische Verträglichkeit — unterschiedliche Metalle im Kontakt können selbst eine für sich genommen richtig gewählte Legierung schnell angreifen. Elektropolieren und Passivieren verbessern das Korrosionsverhalten, indem freies Eisen von der Oberfläche entfernt wird.",
      "Bei gewichtskritischen Anwendungen werden Verbindungselemente aus Titan und Propellerwellen aus Speziallegierungen gemeinsam anhand der Spezifikation und der galvanischen Verträglichkeit bewertet.",
    ],
    features: [
      "Galvanische Verträglichkeit — Werkstoffe im Kontakt werden gemeinsam bewertet",
      "Korrosionsbeständigkeit — Prüfanforderung gemäß Spezifikation (ASTM B117)",
      "SS 316L & Duplex — Meerwasserbeständige Werkstoffe",
      "Elektropolieren — Verbesserung von Oberflächenrauheit und Korrosionsverhalten",
      "Bronzebearbeitung — Marinebronze C95400, C95500",
      "Propellerwelle — Titan- und Monel-Legierungen",
    ],
    technicalSpecs: [
      { label: "Werkstoff", value: "SS 316L, Duplexstahl, Bronze" },
      { label: "Salzsprühtest", value: "ASTM B117; gemäß Spezifikation" },
      { label: "Werkstoffauswahl", value: "Nach galvanischer Verträglichkeit" },
      { label: "Toleranz", value: "±0,01mm" },
    ],
    advantages: [
      "Werkstoffauswahl unter Berücksichtigung der galvanischen Verträglichkeit",
      "Die Salzsprühanforderung (ASTM B117) wird gemäß Spezifikation eingeplant",
      "Erfahrung in der Zerspanung von SS 316L, Duplex und Bronze",
      "Elektropolieren und Passivieren gemäß Spezifikation",
      "Geringe Rauheit und verbessertes Korrosionsverhalten durch Elektropolieren",
      "Werkstoffberatung abgestimmt auf kathodischen Korrosionsschutz",
    ],
    faq: [
      {
        question: "Welche meerwasserbeständigen Werkstoffe bearbeiten Sie?",
        answer: "Wir verarbeiten meerwasserbeständige Werkstoffe wie SS 316L, Duplex 2205, Bronze (C95400, C95500), Monel 400 und Titan Grade 2.",
      },
      {
        question: "Stellen Sie einen Prüfbericht zum Salzsprühtest bereit?",
        answer: "Sieht die Spezifikation einen Salzsprühtest (ASTM B117) vor, werden Prüfdauer und Annahmekriterium durch die Teilespezifikation festgelegt; der Umfang des Berichts wird in der Angebotsphase vereinbart.",
      },
    ],
  },
  "hidrolik-pnomatik": {
    categoryLabel: "Industriesysteme",
    title: "Hydraulik & Pneumatik",
    metaTitle: "Fertigung von Hydraulik- und Pneumatikteilen | Dichtflächen | Mas Technic",
    metaDescription: "Komponenten für Hydraulik- und Pneumatiksysteme: Ventilgehäuse, Zylinder, Steuerblöcke. Stahl 42CrMo4, C45; Betriebsdruck und Anforderungen an Dichtflächen gemäß Spezifikation.",
    description: "Komponenten für Hydraulik- und Pneumatiksysteme: Ventilgehäuse, Zylinderteile, Steuerblöcke und kundenspezifische Fluidtechnik-Komponenten.",
    content: [
      "Wir fertigen Hochdruckkomponenten für Hydraulik- und Pneumatiksysteme. Unsere Schwerpunkte sind Ventilgehäuse (Wege-, Druck- und Stromventile), Zylinderteile (Kolben, Zylinderrohr, Zylinderdeckel), Steuerblöcke (mit mehreren Anschlüssen, integrierte Schaltungen) und Pumpenkomponenten.",
      "O-Ring- und Dichtflächen werden entsprechend dem Betriebsdruck des Systems und der Oberflächenanforderung des Dichtungsherstellers bearbeitet. Wir fertigen aus 42CrMo4, C45, SS 316 und Speziallegierungen. Innenkanäle in Steuerblöcken werden durch Tieflochbohren hergestellt.",
      "Druck- und Dichtheitsprüfungen erfolgen in dem im Prüfplan des jeweiligen Auftrags festgelegten Umfang; die Ergebnisse werden dokumentiert. Ventilanschlussflächen werden nach dem Lochbild ISO 4401 bearbeitet; Anschlussgeometrien werden passend zu gängigen Schnittstellen von Hydraulikkomponenten gefertigt.",
    ],
    features: [
      "Ventilgehäuse — Wege-, Druck- und Stromventile",
      "Zylinderteil — Kolben, Zylinderrohr, Zylinderdeckel, Kolbenstange",
      "Steuerblock — Mehrere Anschlüsse, Kanäle durch Tieflochbohren",
      "Betriebsdruck — Fertigung für den spezifizierten Druck",
      "Dichtfläche — O-Ring-Nuten gemäß Dichtungsanforderung",
      "Druckprüfung — Dichtheitsprüfung gemäß Prüfplan",
    ],
    technicalSpecs: [
      { label: "Betriebsdruck", value: "Projektanforderung (Spez.)" },
      { label: "Werkstoff", value: "42CrMo4, C45, SS 316" },
      { label: "Druckprüfung", value: "Im Prüfplan festgelegt" },
      { label: "Lochbild", value: "ISO 4401" },
    ],
    processSteps: ["Zeichnungsprüfung", "Werkstoffvorbereitung", "CNC-Bearbeitung & Tieflochbohren", "Bearbeitung der Dichtflächen", "Druckprüfung", "Maßprüfung & KMG", "Schutzverpackung"],
    advantages: [
      "Fertigung für den in der Spezifikation festgelegten Betriebsdruck",
      "Dichtflächen gemäß Dichtungsanforderung bearbeitet",
      "Bearbeitung von Steuerblockkanälen durch Tieflochbohren",
      "Druck- und Dichtheitsprüfung gemäß Prüfplan",
      "Ventilanschlussflächen nach Lochbild ISO 4401",
      "Werkstofferfahrung mit 42CrMo4 und SS 316",
    ],
    faq: [
      {
        question: "Bis zu welchem Druck können Sie Teile fertigen?",
        answer: "Der Betriebsdruck ist eine Konstruktionsanforderung des Systems; das Teil wird für den Druck in der Kundenspezifikation gefertigt. Umfang der Druckprüfung und Prüfdruck werden im Prüfplan des jeweiligen Auftrags festgelegt.",
      },
      {
        question: "Können Sie Innenkanäle in Steuerblöcken bearbeiten?",
        answer: "Ja, Kanäle in Steuerblöcken werden durch Tieflochbohren hergestellt; das erreichbare Längen-Durchmesser-Verhältnis wird im Angebot abhängig von Kanaldurchmesser und Werkstoff angegeben.",
      },
      {
        question: "Wie wird die Dichtheit nachgewiesen?",
        answer: "O-Ring-Nuten und Dichtflächen werden auf den Ra-Zielwert der Dichtungsanforderung bearbeitet. Der Umfang der Druck- und Dichtheitsprüfung wird im Prüfplan des jeweiligen Auftrags festgelegt, die Ergebnisse werden der Lieferdokumentation beigefügt.",
      },
    ],
  },
  "boru-baglanti-parcalari": {
    categoryLabel: "Industriesysteme",
    title: "Rohre & Rohrverbindungsteile",
    metaTitle: "Industrielle Rohrverbindungsteile | ANSI, DIN, JIS | PN6-PN40 | Mas Technic",
    metaDescription: "Rohrverbindungsteile nach ANSI-, DIN- und JIS-Normen. Flansche, Adapter, Nippel, Bögen. DN15-DN600, PN6-PN40. Edelstahl, Kohlenstoffstahl und Duplexstahl.",
    description: "Industrielle Rohrverbindungsteile nach ANSI-, DIN- und JIS-Normen. Flansche, Adapter, Nippel, Bögen und kundenspezifische Übergangsstücke.",
    content: [
      "Für industrielle Rohrleitungssysteme fertigen wir Flansche (Vorschweiß-, Überschieb- und Blindflansche), Adapter (Übergänge zwischen Rohrdurchmessern und Normen), Nippel, Bögen, T-Stücke und Reduzierungen. Lochkreis, Dichtfläche und Durchmesser der Flansche werden nach den Maßtabellen von ANSI B16.5, DIN EN 1092 und JIS B2220 bearbeitet.",
      "Wir fertigen im Durchmesserbereich DN15-DN600 und in den Druckstufen PN6-PN40. Wir verarbeiten Kohlenstoffstahl (A105, A350 LF2), Edelstahl (F304, F316, F321), Duplex (F51, F53) und Speziallegierungen (Inconel, Monel, Hastelloy).",
      "Der Umfang von Druckprüfung, Maßprüfung und Oberflächenprüfung wird im Prüfplan des jeweiligen Auftrags festgelegt; die Ergebnisse werden dokumentiert. Dichtflächen werden nach der Geometrie FF/RF gemäß ASME B16.5 bearbeitet. Wärmebehandlungsnachweise, ZfP-Prüfberichte und Werkstoffzeugnisse werden auf Anfrage bereitgestellt.",
    ],
    features: [
      "Mehrere Normen — ANSI B16.5, DIN EN 1092, JIS B2220",
      "Großer Durchmesserbereich — Von DN15 bis DN600",
      "Druckstufen PN6-PN40 — Fertigung in verschiedenen Druckstufen",
      "Speziallegierungen — Inconel, Monel, Hastelloy",
      "Dichtfläche — Geometrie FF/RF nach ASME B16.5",
      "Werkstoffzeugnis — Auf Anfrage",
    ],
    technicalSpecs: [
      { label: "Normen", value: "ANSI, DIN, JIS" },
      { label: "Druckstufe", value: "Projektanforderung (Spez.)" },
      { label: "Durchmesserbereich", value: "DN15-DN600" },
      { label: "Werkstoff", value: "C-Stahl, Edelstahl, Duplex, Inconel" },
      { label: "Dichtfläche", value: "FF/RF (ASME B16.5)" },
      { label: "Zeugnis", value: "Auf Anfrage" },
    ],
    advantages: [
      "Konformität mit drei Normen: ANSI, DIN und JIS",
      "Fertigung im großen Durchmesserbereich DN15-DN600",
      "Kompetenz in der Zerspanung von Duplex und Superlegierungen",
      "Werkstoffzeugnis und Chargennachweis auf Anfrage",
      "Dichtflächen nach der Geometrie gemäß ASME B16.5",
      "Wärmebehandlungs- und ZfP-Nachweise auf Anfrage",
    ],
    faq: [
      {
        question: "Nach welchen Maßtabellen werden Flanschabmessungen bearbeitet?",
        answer: "Lochkreis, Dichtfläche und Durchmesser der Flansche werden nach den Maßtabellen von ANSI B16.5, DIN EN 1092 und JIS B2220 oder nach der vom Kunden bereitgestellten technischen Zeichnung bearbeitet.",
      },
      {
        question: "Können Sie Flansche aus Duplexstahl fertigen?",
        answer: "Ja, wir fertigen Flansche und Rohrverbindungsteile aus Duplex 2205 (F51), Super Duplex 2507 (F53) und anderen korrosionsbeständigen Legierungen.",
      },
    ],
  },
  "iklim-teknolojileri": {
    categoryLabel: "Industriesysteme",
    title: "Klimatechnik",
    metaTitle: "Teilefertigung für HLK- und Kältetechnik | Mas Technic",
    metaDescription: "Komponenten für HLK-, Kälte- und Lüftungssysteme: Verdichterteile, Ventile, Wärmetauscher. Betriebstemperatur, Druck und Dichtheitsanforderungen gemäß Spezifikation.",
    description: "Mechanische Präzisionskomponenten für HLK-, Kälte- und Lüftungssysteme.",
    content: [
      "Für HLK-, Kälte- und Lüftungssysteme fertigen wir Verdichterteile (Kolben, Ventilplatte, Zylinder), Komponenten für Expansionsventile, Wärmetauscherteile (Rohrboden, Umlenkblech, Anschluss) sowie Komponenten für Ventilatoren und Gebläse.",
      "Betriebstemperatur und -druck sind Projektanforderungen; die Werkstoffe werden für diese Bedingungen ausgewählt. Die Dichtheitsprüfung (z. B. Helium-Lecktest) und ihr Annahmekriterium werden im Prüfplan gemäß Kundenspezifikation festgelegt.",
      "Wir fertigen aus Al 6061 (Wärmetauscher), Kupfer (Cu-DHP, Leitfähigkeit), SS 304/316 (Korrosionsbeständigkeit) und Speziallegierungen. Kältemittelverträglichkeit (R-134a, R-410A, R-744) und Anforderungen an den Lebensmittelkontakt werden bei der Werkstoffauswahl gemäß Ihrer Spezifikation bewertet.",
    ],
    features: [
      "Verdichterteil — Kolben, Ventilplatte, Zylinder",
      "Wärmetauscher — Rohrboden, Umlenkblech, Anschluss",
      "Expansionsventil — Präzise Durchflussregelung",
      "Werkstoffauswahl — Nach Betriebstemperatur",
      "Dichtheit — Prüfverfahren und Annahmekriterium gemäß Spezifikation",
      "Kältemittelverträglich — R-134a, R-410A, R-744",
    ],
    technicalSpecs: [
      { label: "Betriebsbedingungen", value: "Projektanforderung (Spez.)" },
      { label: "Dichtheit", value: "Gemäß Spezifikation" },
      { label: "Werkstoff", value: "Al, Cu, SS 304/316" },
      { label: "Kältemittel", value: "R-134a, R-410A, R-744" },
      { label: "Kältemittelklasse", value: "HFKW / HFO / natürlich" },
    ],
    advantages: [
      "Werkstoffauswahl nach Betriebsbedingungen",
      "Das Verfahren der Dichtheitsprüfung wird gemäß Spezifikation festgelegt",
      "Kältemittelverträgliche Werkstoffauswahl",
    ],
    faq: [
      {
        question: "Wie wird die Dichtheitsprüfung festgelegt?",
        answer: "Das Verfahren der Dichtheitsprüfung (z. B. Helium-Lecktest) und die zulässige Leckrate werden im Prüfplan gemäß Kundenspezifikation festgelegt; der Prüfumfang wird in der Angebotsphase vereinbart.",
      },
      {
        question: "Mit welchen Kältemitteln sind Ihre Teile verträglich?",
        answer: "Wir fertigen mit Werkstoffen und Oberflächenbehandlungen, die mit den Kältemitteln R-134a, R-410A, R-744 (CO₂) und R-290 verträglich sind.",
      },
    ],
  },
  "prototip-uretim": {
    categoryLabel: "Fertigungslösungen",
    title: "Prototypenfertigung",
    metaTitle: "Rapid Prototyping | CNC, 3D-Druck, Silikonabformung | Mas Technic",
    metaDescription: "Funktionsprototypen durch CNC, 3D-Druck (FDM/SLA/SLS/DMLS) und Silikonabformung. Seriennahe Toleranz im Originalwerkstoff, ab einem Stück.",
    description: "Fertigung von Funktionsprototypen durch CNC-Zerspanung, 3D-Druck und Silikonabformung. Serienqualität im Originalwerkstoff, auch Einzelstücke.",
    content: [
      "Wir setzen Ihre Konstruktionskonzepte in physische Produkte um. Wir bieten Prototypen im Originalwerkstoff (Al, SS, Ti, PEEK) mit seriennaher Toleranz durch CNC-Zerspanung, schnelle Konzeptvalidierung durch 3D-Druck und mehrere Prototypen von 10-50 Stück durch Silikonabformung.",
      "Mit einem Funktionsprototyp können Sie Ihr Teil unter realen Einsatzbedingungen testen. Konstruktionsverbesserung durch DFM-Analyse und die Erstellung des Prüfplans für den Übergang zur Serienfertigung sind Teil des Prozesses. Wir nehmen auch Einzelstückaufträge an.",
      "Optionen der additiven Fertigung: FDM (ABS, PLA, Nylon) für Form- und Passungsversuche, SLA (Harz) für feine Details und Oberflächen, SLS (PA12) für Funktionsteile ohne Stützstrukturen und DMLS für metallische Funktionsprototypen.",
    ],
    features: [
      "Einzelstückaufträge — keine Mindestmenge bei Prototypen",
      "Originalwerkstoff — Fertigung in Al, SS, Ti, PEEK",
      "3D-Druck — FDM-, SLA-, SLS-, DMLS-Technologien",
      "Silikonabformung — Mehrere Prototypen",
      "DFM-Analyse — Konstruktionsoptimierung inklusive",
      "Revisionszyklus — Anzahl der Iterationen im Angebot angegeben",
    ],
    technicalSpecs: [
      { label: "Lieferzeit", value: "Mit dem Angebot" },
      { label: "Mindestmenge", value: "1 Stück" },
      { label: "Toleranz", value: "Seriennah" },
      { label: "Werkstoff", value: "Originalwerkstoff" },
      { label: "3D-Druck", value: "FDM, SLA, SLS, DMLS" },
      { label: "Iterationen", value: "Im Angebot angegeben" },
    ],
    advantages: [
      "Die Lieferzeit wird nach Wahl von Verfahren und Werkstoff mit dem Angebot genannt",
      "Funktionsprüfung im Originalwerkstoff",
      "4 verschiedene 3D-Druck-Technologien (einschließlich Metall)",
      "Konstruktionsoptimierung durch DFM-Analyse",
      "Geringeres Konstruktionsrisiko durch Revisionszyklen",
      "Unterstützung für einen reibungslosen Übergang zur Serienfertigung",
    ],
    faq: [
      {
        question: "Wie schnell kann ein Prototyp frühestens fertig sein?",
        answer: "Die Wahl des Verfahrens bestimmt die Lieferzeit unmittelbar: 3D-Druck ist die schnellste Option zur Konzeptvalidierung, CNC wird gewählt, wenn Originalwerkstoff und seriennahe Toleranz benötigt werden. Die Lieferzeit wird mit dem Angebot genannt, nachdem Werkstoffbeschaffung, Anzahl der Arbeitsgänge und Kapazitätsplanung geprüft wurden.",
      },
      {
        question: "Können Sie Prototypen im Originalwerkstoff fertigen?",
        answer: "Ja, per CNC fertigen wir Prototypen mit seriennaher Toleranz aus Originalwerkstoffen wie Al 6061, SS 304, Ti6Al4V und PEEK.",
      },
    ],
  },
  "kucuk-seri": {
    categoryLabel: "Fertigungslösungen",
    title: "Kleinserienfertigung",
    metaTitle: "Kleinserienfertigung | CNC & Rapid Tooling | Mas Technic",
    metaDescription: "Kleinserienfertigung: CNC-Zerspanung, Aluminiumwerkzeuge und Silikonabformung; mit steigender Menge sinkende Stückkosten und chargenbezogene Rückverfolgbarkeit.",
    description: "Kleinserienfertigung: Übergang vom Prototyp zur Kleinserie, mit der Menge sinkende Stückkosten und Rückverfolgbarkeit auf Chargenebene.",
    content: [
      "Ihren Kleinserienbedarf decken wir mit CNC-Zerspanung, schnellen Aluminiumwerkzeugen und Silikonabformung; das Verfahren wird nach Menge und Genauigkeit gewählt und im Angebot angegeben.",
      "In Kleinserien bestimmt vor allem das Rüsten die Stückkosten: Da sich die Rüstkosten auf die Menge verteilen, sinkt der Stückpreis mit steigender Menge. Ein Prüfplan und Rückverfolgbarkeit auf Chargenebene sind Standard; eine Staffelpreisliste erhalten Sie mit dem Angebot.",
      "Eine ideale Lösung für Markttests, Pilotfertigung und Vorserien. Die Planung des Übergangs zur Serienfertigung ist inbegriffen — wir liefern eine Analyse der Werkzeuginvestition, eine Machbarkeitsbewertung zur Automatisierung und einen Bericht zur Kostenprognose.",
    ],
    features: [
      "Flexible Losgröße — Verfahren nach Menge gewählt",
      "Mengenrabatt — Stückkosten sinken mit steigender Menge",
      "Lieferzeit — im Angebot zusammen mit der Kapazitätsplanung",
      "Prüfplan — auch bei Kleinserien standardmäßig erstellt",
      "Markttest — Unterstützung bei Vorserie und Pilotfertigung",
      "Plan für den Serienübergang — Beratung zur Skalierung",
    ],
    technicalSpecs: [
      { label: "Mengenbereich", value: "Im Angebot angegeben" },
      { label: "Lieferung", value: "Mit dem Angebot" },
      { label: "Qualität", value: "Prüfplan + Messprotokoll" },
      { label: "Mengenrabatt", value: "Staffelpreise im Angebot" },
      { label: "Verfahren", value: "CNC, Al-Werkzeuge, Silikon" },
    ],
    advantages: [
      "Kostenoptimierung durch Mengenrabatte",
      "Die Lieferzeit wird nach Prüfung von Rüstaufwand und Kapazitätsplanung genannt",
      "Prüfplan und Messprotokoll auch bei Kleinserien Standard",
      "Reibungsloser Übergang vom Prototyp zur Kleinserie",
      "Plan für den Serienübergang und Kostenprognose",
      "Chargenbezogene Rückverfolgbarkeit und Qualitätsberichte",
    ],
    faq: [
      {
        question: "Sind die Stückkosten bei Kleinserien hoch?",
        answer: "Die Stückkosten werden vor allem durch das Rüsten bestimmt, dessen Kosten sich auf die Menge verteilen; der Stückpreis sinkt mit steigender Menge. Staffelpreise und eine Prognose für den Übergang zur Serienfertigung erhalten Sie mit dem Angebot.",
      },
      {
        question: "Wie erfolgt der Übergang von der Kleinserie zur Serienfertigung?",
        answer: "Wir planen die Skalierung mit einer Analyse der Werkzeuginvestition, einer Machbarkeitsbewertung zur Automatisierung und einem Bericht zur Kostenprognose.",
      },
    ],
  },
};
