import type { ServiceText } from "@/content/en/types";

const REF = "Allgemeine Referenzwerte; sie stellen nicht die Kapazität des Unternehmens dar. Der für Ihr Teil geltende Wert wird im Angebot angegeben.";

export const part2: Record<string, ServiceText> = {
  "silikon-kaliplama": {
    categoryLabel: "Vorserie",
    title: "Silikonabformung",
    metaTitle: "Silikonabformung | Vakuumguss | Kleinserien | Mas Technic",
    metaDescription: "Kleinserienfertigung durch Vakuumguss in Silikonformen. PU, Silikon, Epoxid. Porenfreie Abgüsse vom Urmodell; die geeignete Stückzahl wird im Angebot angegeben.",
    description: "Kleinserienfertigung durch Vakuumguss in Silikonformen. Porenfreie Abgüsse vom Urmodell; die geeignete Stückzahl wird im Angebot je nach Teil und Werkstoff angegeben.",
    content: [
      "Das Gießen unter Vakuum verhindert Lufteinschlüsse im Formhohlraum und ergibt eine porenfreie Oberfläche. Wir fertigen in PU, Silikon, Polyester und Epoxid und bieten Farboptionen mit Pigmenten an.",
      "Die Werkstoffoptionen PU 60A (60 Shore A, flexibel und weiterreißfest), PU 80A (80 Shore A, mittlere Härte), PU 90A (90 Shore A, hohe Festigkeit) und Silikon 40A (40 Shore A, hochtemperaturbeständig) decken ein breites Anwendungsspektrum ab.",
      "Durch Umspritzen (Overmoulding) können wir Werkstoffe unterschiedlicher Härte kombinieren. Wir bieten Lösungen in Silikonabformung für Medizintechnik, Automobil und industrielle Anwendungen. Die Lieferzeit wird mit dem Angebot angegeben – abhängig vom Stand des Urmodells, der Abgussmenge und dem Nachbearbeitungsumfang.",
    ],
    features: [
      "Vakuumguss — porenfreie Oberfläche ohne Lufteinschlüsse",
      "Verschiedene Werkstoffe — PU, Silikon, Polyester, Epoxid",
      "Farboptionen — Beliebige Farbe mit Pigmenten",
      "Umspritzen — Kombination von Werkstoffen unterschiedlicher Härte",
    ],
    technicalSpecs: [
      { label: "Shore-Härte", value: "40A-90A" },
      { label: "Toleranz", value: "Im Angebot angegeben" },
      { label: "Werkstoff", value: "PU, LSR, HTV, EPDM" },
      { label: "Temperaturbeständigkeit", value: "Je nach gewähltem Werkstoff" },
      { label: "Losgröße", value: "Kleinserie" },
    ],
    processSteps: ["Vorbereitung des Urmodells", "Gießen der Silikonform", "Vakuumguss", "Aushärten", "Entformen", "Qualitätskontrolle"],
    advantages: [
      "Schnelle Abformung nach Freigabe des Urmodells",
      "Kleinserienfertigung",
      "4 Härteoptionen",
      "Umspritzen möglich",
    ],
    comparisonTables: [
      {
        title: "Werkstoffvergleich Silikonabformung",
        description: "Typische Werkstoffwerte; maßgeblich ist das technische Datenblatt des gewählten Produkts. Keine Angabe zur Unternehmenskapazität.",
        headers: ["Werkstoff", "Shore-Härte", "Bruchdehnung (%)", "Temperaturbereich", "Weiterreißfestigkeit", "Anwendung"],
        rows: [
          ["PU 60A", "60 Shore A", "450%", "-30°C / +80°C", "25 kN/m", "Flexible Dichtung, Puffer"],
          ["PU 80A", "80 Shore A", "350%", "-30°C / +90°C", "35 kN/m", "Griff, Abdeckung"],
          ["PU 90A", "90 Shore A", "250%", "-20°C / +100°C", "45 kN/m", "Strukturell, tragend"],
          ["Silikon 40A", "40 Shore A", "600%", "-60°C / +300°C", "20 kN/m", "Hochtemperatur, Medizintechnik"],
          ["Silikon 70A", "70 Shore A", "400%", "-55°C / +250°C", "30 kN/m", "O-Ring, Dichtung, Tastenfeld"],
          ["Epoxidharz", "80 Shore D", "5%", "-40°C / +120°C", "Starr", "Prototyp, Modell"],
        ],
      },
      {
        title: "Vergleich der Fertigungsverfahren (Kleinserie)",
        description: REF,
        headers: ["Verfahren", "Mindestmenge", "Teilekosten", "Werkzeugkosten", "Oberflächenqualität"],
        rows: [
          ["Vakuumguss", "1", "$$", "$", "Gut (abhängig vom Urmodell)"],
          ["3D-Druck (SLA)", "1", "$$$", "Keine", "Sehr gut"],
          ["CNC-Zerspanung", "1", "$$$$", "Keine", "Ausgezeichnet"],
          ["Silikon-Spritzguss", "500+", "$", "$$$", "Ausgezeichnet"],
          ["Formpressen", "100+", "$$", "$$", "Gut"],
        ],
      },
    ],
  },
  "fikstur-aparat-tasarimi": {
    categoryLabel: "Vorserie",
    title: "Vorrichtungskonstruktion",
    metaTitle: "Vorrichtungskonstruktion | CNC-Vorrichtungen nach Maß | Mas Technic",
    metaDescription: "Kundenspezifische Vorrichtungen für CNC-Zerspanung, Montage, Schweißen und Prüfung. 3D-Modellierung, Bewertung von Spannkraft und Maßkette, Validierung in der Produktionsumgebung.",
    description: "Kundenspezifisch konstruierte Vorrichtungen für CNC-Zerspanung, Montage, Schweißen und Prüfung. Wiederholgenauigkeit und Unabhängigkeit vom Bediener.",
    content: [
      "Wir konstruieren kundenspezifische Vorrichtungen, die Ihre Fertigung beschleunigen und die Präzision erhöhen. Unser Spektrum umfasst Drehvorrichtungen (kundenspezifische Spannmittel, die das Teil um seine Drehachse positionieren und halten), Fräsvorrichtungen (Schraubstock-, Vakuum- und Hydraulikspannung), Montagevorrichtungen (Vermeidung von Bedienfehlern), Prüfvorrichtungen (Messwiederholbarkeit) und Schweißvorrichtungen (Ausrichten und Halten).",
      "Unsere Konstruktionsleistung umfasst 3D-Modellierung, die Bewertung von Spannkraft und Maßkette, die Prototypenfertigung per 3D-Druck oder Rapid Manufacturing sowie Validierungstests und Freigabe in der Produktionsumgebung.",
      "Wir fertigen Vorrichtungen aus Stahl, Aluminium und Verbundwerkstoffen; der Zielwert für die Wiederholgenauigkeit der Vorrichtung ergibt sich aus der Maßkette des Teils und wird bei der Validierung gemessen. Die Lieferzeit für Konstruktion und Fertigung wird mit dem Angebot angegeben, nachdem Komplexität der Vorrichtung, Werkstoffbeschaffung und Validierungsumfang geprüft wurden.",
    ],
    features: [
      "Drehvorrichtung — Positionieren und Halten des Teils um seine Drehachse",
      "Fräsvorrichtung — Schraubstock, Vakuum und Hydraulik",
      "Montagevorrichtung — Vermeidung von Bedienfehlern",
      "Prüfvorrichtung — Messwiederholbarkeit",
      "Schweißvorrichtung — Ausrichten und Halten",
    ],
    technicalSpecs: [
      { label: "Wiederholgenauigkeit", value: "Gemäß Maßkette" },
      { label: "Werkstoff", value: "Stahl, Al, Verbundwerkstoff" },
      { label: "Lieferzeit", value: "Mit dem Angebot" },
      { label: "Validierung", value: "Test in der Produktionsumgebung" },
    ],
    processSteps: ["Bedarfsanalyse", "3D-Modellierung", "Bewertung von Spannkraft & Toleranz", "Prototyp (3D-Druck / Rapid Manufacturing)", "CNC-Zerspanung & Montage", "Test & Freigabe"],
    advantages: [
      "Volumenmodell und Fertigungszeichnung in einem Ablauf",
      "Bewertung von Spannkraft und Maßkette",
      "Schneller Prototypenbau per 3D-Druck",
      "Validierungstest in der Produktionsumgebung",
    ],
    comparisonTables: [
      {
        title: "Auswahlhilfe Vorrichtungstypen",
        description: REF,
        headers: ["Vorrichtungstyp", "Spannkraft", "Rüstzeit", "Kosten", "Anwendung"],
        rows: [
          ["Mechanischer Schraubstock", "10-50 kN", "1-2 min", "$", "Allgemeines Fräsen"],
          ["Hydraulische Spannung", "20-100 kN", "10-20 s", "$$$", "Serienfertigung, automatisiert"],
          ["Pneumatische Spannung", "5-30 kN", "5-10 s", "$$", "Leichte Teile, schnell"],
          ["Vakuumspannung", "1-10 kN", "5 s", "$$", "Dünne Platten, empfindlich"],
          ["Magnetspannplatte", "5-20 kN", "3 s", "$$", "Ferromagnetisch, Schleifen"],
          ["Modulare Vorrichtung", "Variabel", "15-30 min", "$$$$", "Vielseitig, flexibel"],
        ],
      },
    ],
  },
  "mekanik-yuzey-islemleri": {
    categoryLabel: "Oberflächenbehandlungen",
    title: "Mechanische Oberflächenbearbeitung",
    metaTitle: "Mechanische Oberflächenbearbeitung | Strahlen & Polieren | Mas Technic",
    metaDescription: "Strahlen, Gleitschleifen, Polieren und Bürsten. Optionen von Hochglanz bis Satinoberfläche; die erreichbare Oberflächengüte wird im Angebot je nach Werkstoff angegeben.",
    description: "Verbesserung der Oberflächengüte und montagefertige Vorbereitung von Teilen durch Strahlen, Gleitschleifen, Polieren und Bürsten. Passivieren ist ein chemisches Verfahren und wird auf der Seite Chemische Behandlungen beschrieben.",
    content: [
      "Mechanische Oberflächenbearbeitung bringt die Oberflächengüte Ihrer Teile auf das geforderte Niveau. Kugelstrahlen reinigt und raut die Oberfläche auf, Gleitschleifen (Trowalisieren) bricht scharfe Kanten, spitzenloses Polieren verbessert die Oberfläche runder Teile, Polieren erzeugt Hochglanz und Bürsten einen Satineffekt.",
      "Wir arbeiten mit verschiedenen Strahlmitteln — Glasperlen für die Feinreinigung, Aluminiumoxid für die Oberflächenvorbereitung, Stahlkies für die Grobreinigung und Soda für die schonende Reinigung; Strahlmittel und Korngröße werden passend zum Werkstoff des Teils und zur Zieloberfläche gewählt.",
      "Die erreichbare Oberflächengüte und die Prozessparameter ergeben sich aus Werkstoff und Geometrie. Der Arbeitsbereich wird im Angebot angegeben, nachdem Teilegeometrie und Prozessplan geprüft wurden.",
    ],
    features: [
      "Kugelstrahlen — Reinigen und Aufrauen der Oberfläche",
      "Gleitschleifen (Trowalisieren) — Kantenbrechen",
      "Spitzenloses Polieren — Für runde Teile",
      "Polieren — Hochglanz",
      "Bürsten — Satinierte Oberfläche",
    ],
    technicalSpecs: [
      { label: "Polierstufe", value: "Hochglanz" },
      { label: "Arbeitsbereich", value: "Im Angebot angegeben" },
    ],
    processSteps: ["Oberflächenanalyse", "Verfahrensauswahl", "Auswahl von Strahl-/Schleifmittel", "Oberflächenbearbeitung", "Qualitätskontrolle"],
    advantages: [
      "4 Strahlmitteloptionen",
      "Polieren bis Hochglanz",
      "Montagefertig gelieferte Oberflächen",
      "Strahlmittel passend zum Werkstoff des Teils",
    ],
    comparisonTables: [
      {
        title: "Mechanische Oberflächenbearbeitungsverfahren im Vergleich",
        description: REF,
        headers: ["Verfahren", "Oberflächenrauheit (Ra)", "Prozesszeit", "Kosten", "Anwendung"],
        rows: [
          ["Strahlen (Glasperlen)", "Ra 1,6-3,2µm", "5-15 min", "$", "Reinigen, Aufrauen"],
          ["Strahlen (Al₂O₃)", "Ra 2,0-4,0µm", "5-15 min", "$", "Vorbereitung vor dem Lackieren"],
          ["Gleitschleifen", "Ra 0,4-1,6µm", "30-120 min", "$", "Entgraten, Kantenbrechen"],
          ["Spitzenloses Polieren", "Ra 0,1-0,4µm", "10-30 min", "$$", "Polieren von Wellen und Stiften"],
          ["Mechanisches Polieren", "Ra 0,05-0,2µm", "15-60 min", "$$$", "Hochglanz"],
          ["Bürsten", "Ra 0,4-1,2µm", "5-10 min", "$", "Satineffekt, dekorativ"],
        ],
      },
      {
        title: "Auswahltabelle Strahl- und Schleifmittel",
        description: REF,
        headers: ["Mitteltyp", "Korngröße", "Härte", "Geeigneter Werkstoff", "Wirkung"],
        rows: [
          ["Glasperlen", "0,1-0,5mm", "Mittel", "Alle Metalle", "Feinreinigung, matte Oberfläche"],
          ["Aluminiumoxid", "0,2-1,0mm", "Hoch", "Stahl, Gusseisen", "Intensive Reinigung, Aufrauen"],
          ["Stahlkies", "0,2-2,0mm", "Sehr hoch", "Stahl, Gussteile", "Entfernen starker Rost-/Sandreste"],
          ["Keramische Schleifkörper", "3-15mm", "Hoch", "Alle Metalle", "Entgraten, Glätten der Oberfläche"],
          ["Kunststoff-Schleifkörper", "2-10mm", "Niedrig", "Aluminium, Kunststoffe", "Schonendes Entgraten"],
          ["Walnussschalen", "0,5-2,0mm", "Niedrig", "Weiche Metalle", "Reinigen (ohne Maßänderung)"],
        ],
      },
    ],
  },
  anodizasyon: {
    categoryLabel: "Oberflächenbehandlungen",
    title: "Eloxieren",
    metaTitle: "Eloxieren | Typ I-II-III & Harteloxal | MIL-A-8625 | Mas Technic",
    metaDescription: "Eloxieren nach Typ I, II und III (Harteloxal), Einfärben mit organischen und anorganischen Farbstoffen. Schichtdicke, Härte und Korrosionsprüfung richten sich nach Spezifikation und Legierung.",
    description: "Korrosionsbeständigkeit, Verschleißfestigkeit, elektrische Isolation und dekorative Oberflächen durch Chromsäure-Eloxal (Typ I), Schwefelsäure-Eloxal (Typ II) und Harteloxal (Typ III).",
    content: [
      "Beim Eloxieren wird auf einer Aluminiumoberfläche elektrochemisch eine Aluminiumoxidschicht (Al₂O₃) erzeugt. Diese Schicht verbessert Korrosionsbeständigkeit, Verschleißfestigkeit und Optik des Teils deutlich. Bei Mas Technic bieten wir Eloxieren nach Typ I, Typ II und Typ III für Anwendungen in Luft- und Raumfahrt und Medizintechnik an.",
      "Nach MIL-A-8625 bildet Typ I (Chromsäure) eine dünne Oxidschicht und wird bevorzugt als Haftgrund für Lackierungen eingesetzt. Typ II (Schwefelsäure) ist der am weitesten verbreitete Typ – für Korrosionsschutz, farbige Oberflächen und allgemeine technische Anwendungen. Typ III (Harteloxal) bildet eine dickere, härtere Schicht für Oberflächen, die Verschleißfestigkeit und elektrische Isolation erfordern. Schichtdicke und Härte richten sich nach Legierung und Spezifikation; die Schichthärte wird in Vickers (HV) angegeben – HRC bezieht sich auf die Härte des Grundwerkstoffs.",
      "Zum Einfärben verwenden wir organische und anorganische Farbstoffe für Schwarz, Rot, Blau, Grün, Gold, Bronze, Violett, Orange, Gelb, Rauchgrau und Natur (farblos); auch eine kundenspezifische Abstimmung nach RAL und Pantone ist möglich. Die Farbtoleranz wird durch die Spezifikation festgelegt. Das Verdichten schließt die Poren der Oxidschicht und verbessert den Schutz.",
      "Methode und Annahmekriterien für die Prüfung von Schichtdicke, Härte und Farbe sind im Prüfplan festgelegt; eine Korrosionsprüfung (z. B. ASTM B117) erfolgt, wenn die Spezifikation sie fordert. Für jede Charge wird ein Messprotokoll geführt.",
      "Ob ein Teil aufgrund von Größe und Gewicht bearbeitet werden kann, wird in der Angebotsphase entschieden. Der Arbeitsbereich wird im Angebot angegeben, nachdem Teilegeometrie und Prozessplan geprüft wurden.",
    ],
    features: [
      "Typ I (Chromsäure) — Dünne Oxidschicht, Haftgrund für Lack",
      "Typ II (Schwefelsäure) — Korrosionsschutz, farbige Oberfläche",
      "Typ III (Harteloxal) — Dicke, harte Schicht, Verschleißfestigkeit",
      "Einfärben — Organische und anorganische Farbstoffe",
      "Typ I / II / III — Schichtklassen nach MIL-A-8625",
      "ASTM B117 Salzsprühnebel — Wenn die Spezifikation es fordert",
    ],
    technicalSpecs: [
      { label: "Schichtdicke", value: "Gemäß Spezifikation" },
      { label: "Schichthärte", value: "HV; je nach Legierung und Verfahren" },
      { label: "Salzsprühnebel", value: "ASTM B117; gemäß Spezifikation" },
      { label: "Schichtklasse", value: "MIL-A-8625 Typ I / II / III" },
      { label: "Arbeitsbereich", value: "Im Angebot angegeben" },
      { label: "Farbtoleranz", value: "Gemäß Spezifikation" },
    ],
    processSteps: ["Oberflächenreinigung & Entfetten", "Beizen", "Eloxalbad", "Einfärben (optional)", "Verdichten", "Qualitätskontrolle & Dokumentation"],
    advantages: [
      "4 Eloxalarten (Typ I, II, III und dekorativ)",
      "Schichtklassen Typ I, Typ II und Typ III",
      "Salzsprühnebeltest nach ASTM B117, wenn die Spezifikation es fordert",
      "Dekorative und funktionale Oberflächen mit organischen und anorganischen Farbstoffen",
      "Lieferzeit wird mit dem Angebot je nach Losgröße und Schichtklasse angegeben",
      "Qualitätskontrolle durch Messung von Schichtdicke und Härte",
      "Erfahrung in Luft- und Raumfahrt, Automobil, Medizintechnik und Verteidigung",
    ],
    materials: [
      { name: "Aluminium 6061-T6", grade: "Al-Mg-Si-Legierung", properties: "Am weitesten verbreitet, sehr gutes Eloxierverhalten, gleichmäßige Farbe" },
      { name: "Aluminium 7075-T6", grade: "Al-Zn-Mg-Legierung", properties: "Hohe Festigkeit, Farbton nach dem Eloxieren kann variieren" },
      { name: "Aluminium 5083", grade: "Al-Mg-Legierung", properties: "Seewasserbeständige Qualität, gute Korrosionsbeständigkeit" },
      { name: "Aluminium 2024-T3", grade: "Al-Cu-Legierung", properties: "Luft- und Raumfahrt, Kupfergehalt kann die Farbgleichmäßigkeit beeinträchtigen" },
      { name: "Titan Grade 2", grade: "Reintitan", properties: "Medizintechnik und Luft- und Raumfahrt, spezielle Eloxierparameter" },
      { name: "Aluminiumguss (A356)", grade: "Al-Si-Mg-Gusslegierung", properties: "Gussteile, Porosität beeinflusst die Eloxalqualität" },
    ],
    faq: [
      { question: "Welche Metalle lassen sich eloxieren?", answer: "Vor allem Aluminium und seine Legierungen. Auch Titan und Magnesium können eloxiert werden. Am häufigsten werden Legierungen der Serien Al 6061 und 7075 eloxiert." },
      { question: "Worin unterscheidet sich Harteloxal (Typ III) vom normalen Eloxal (Typ II)?", answer: "Harteloxal nach Typ III bildet eine dickere, härtere Schicht als Typ II und wird bevorzugt, wo Verschleißfestigkeit und elektrische Isolation erforderlich sind. Typ II eignet sich für allgemeinen Korrosionsschutz und dekorative Oberflächen. Schichtdicke und Härte richten sich nach Spezifikation und Legierung." },
      { question: "Verändert das Eloxieren die Maße?", answer: "Ja. Beim Schwefelsäure-Eloxieren wächst etwa die Hälfte der Oxidschicht in den Werkstoff hinein und die Hälfte nach außen auf; beim Harteloxieren ist das Verhältnis anders. Jede Fläche wächst daher um einen Teil der Schichtdicke, ein Durchmesser um das Doppelte davon. Das genaue Aufmaß wird vor der Bearbeitung gemeinsam mit dem Abdeck- und Toleranzplan festgelegt." },
      { question: "Welche Eloxalfarben sind möglich?", answer: "Wir arbeiten in Schwarz, Rot, Blau, Grün, Gold, Bronze, Violett, Orange, Gelb, Rauchgrau und Natur (farblos). Auch eine kundenspezifische Abstimmung nach RAL und Pantone ist möglich; die Farbtoleranz wird durch die Spezifikation festgelegt." },
      { question: "Wie beständig ist die Beschichtung?", answer: "Die Beständigkeit hängt von Eloxalart, Schichtdicke und Verdichtung ab. Korrosionsprüfung (z. B. ASTM B117) und Annahmekriterien werden durch die Spezifikation festgelegt; für Oberflächen, die Verschleißfestigkeit erfordern, wird Harteloxal bevorzugt." },
      { question: "Wie lang ist Ihre Lieferzeit für das Eloxieren?", answer: "Die Lieferzeit hängt von Losgröße, Schichtklasse und einem eventuellen Einfärbeschritt ab. Sie wird mit dem Angebot angegeben, nachdem Werkstoffbeschaffung, Anzahl der Arbeitsgänge und Kapazitätsplanung geprüft wurden." },
    ],
    comparisonTables: [
      {
        title: "Eloxalarten im Vergleich",
        description: "Die Typen folgen MIL-A-8625; Schichtdicke, Härte (HV) und Anforderungen an die Korrosionsprüfung richten sich nach Legierung und Spezifikation.",
        headers: ["Merkmal", "Typ I (Chromsäure)", "Typ II (Schwefelsäure)", "Typ III (Harteloxal)"],
        rows: [
          ["Einfärbung", "Eingeschränkt", "Volles Farbspektrum", "Eingeschränkt (Schwarz, dunkle Töne)"],
          ["Elektrische Isolation", "Mittel", "Gut", "Hoch"],
          ["Verschleißfestigkeit", "Niedrig", "Mittel", "Hoch"],
          ["Geeignete Anwendung", "Luftfahrtstrukturen, Haftgrund für Lack", "Allgemeiner Maschinenbau, dekorativ", "Zylinder-, Kolben-, Wellenoberflächen"],
          ["Norm", "MIL-A-8625 Typ I", "MIL-A-8625 Typ II", "MIL-A-8625 Typ III"],
          ["Kosten", "$", "$$", "$$$"],
        ],
      },
      {
        title: "Eloxierbarkeit von Aluminiumlegierungen",
        description: "Wie die Legierungswahl die Eloxalqualität beeinflusst",
        headers: ["Legierung", "Farbgleichmäßigkeit", "Schichtqualität", "Empfohlener Typ", "Hinweise"],
        rows: [
          ["6061-T6", "Ausgezeichnet", "Gleichmäßig, glatt", "Typ I, II, III", "Am weitesten verbreitet, ideal zum Eloxieren"],
          ["7075-T6", "Gut", "Leichte Farbtonabweichung möglich", "Typ II, III", "Zn-Gehalt kann den Farbton beeinflussen"],
          ["5083", "Gut", "Gleichmäßig", "Typ II", "Schiffbau, gute Korrosionsbeständigkeit"],
          ["2024-T3", "Mittel", "Kupferschlieren möglich", "Typ I, II", "Cu-Gehalt kann die Farbgleichmäßigkeit beeinträchtigen"],
          ["A356 (Guss)", "Niedrig", "Porös, ungleichmäßig", "Typ II", "Gussqualität ist kritisch, Vorbehandlung erforderlich"],
          ["MIC-6 (Guss)", "Mittel", "Akzeptabel", "Typ II", "Geeignet für Präzisionsgussplatten"],
        ],
      },
    ],
  },
  "kimyasal-islemler": {
    categoryLabel: "Oberflächenbehandlungen",
    title: "Chemische Behandlungen",
    metaTitle: "Chemische Oberflächenbehandlung | Passivieren & Phosphatieren | Mas Technic",
    metaDescription: "Industrielles Entfetten, Passivieren, Phosphatieren und Elektropolieren. Nachweis über Salzsprühnebeltest nach ASTM B117 und Passivierungsprüfung nach ASTM A967.",
    description: "Reinigung und Vorbereitung von Oberflächen für nachfolgende Prozesse durch Entfetten, Passivieren, Phosphatieren und Elektropolieren.",
    content: [
      "Chemische Oberflächenbehandlungen verbessern die Korrosionsbeständigkeit Ihrer Teile. Wir führen industrielles Waschen und Ultraschallentfetten durch, Passivieren für den Korrosionsschutz von Edelstahl, Phosphatieren als Oberflächenvorbereitung für die Lackhaftung, Elektropolieren zum Glänzen von Edelstahl sowie Entgraten zum Brechen scharfer Kanten.",
      "Das Nachweisverfahren — zum Beispiel Salzsprühnebeltest nach ASTM B117 oder Passivierungsprüfung nach ASTM A967 — und die Annahmekriterien werden durch die Spezifikation festgelegt. Die Schichtdicke hängt vom Verfahren ab: Passivieren hinterlässt keine messbare Beschichtung; beim Phosphatieren wird die Dicke durch die Spezifikation festgelegt.",
    ],
    features: [
      "Entfetten — Industrielles Waschen, Ultraschall",
      "Passivieren — Korrosionsschutz für Edelstahl",
      "Phosphatieren — Oberflächenvorbereitung für die Lackhaftung",
      "Elektropolieren — Glänzen von Edelstahl",
      "Entgraten — Brechen scharfer Kanten",
    ],
    technicalSpecs: [
      { label: "Salzsprühnebel", value: "ASTM B117; gemäß Spezifikation" },
      { label: "Schichtdicke", value: "Je nach Verfahren und Spezifikation" },
      { label: "Prüfverfahren", value: "ASTM B117 Salzsprühnebel" },
      { label: "Passivieren", value: "ASTM A967" },
    ],
    processSteps: ["Oberflächenanalyse", "Vorreinigung", "Chemische Behandlung", "Spülen", "Trocknen & Prüfen"],
    advantages: [
      "Anforderung an die Korrosionsprüfung durch die Spezifikation festgelegt",
      "Nachweis durch Salzsprühnebel- und Passivierungsprüfverfahren",
      "Ultraschallreinigung möglich",
      "Oberflächen bereit für nachfolgende Prozesse",
    ],
    comparisonTables: [
      {
        title: "Chemische Oberflächenbehandlungsverfahren",
        description: "Normen und Verfahrensarten; Schichtdicke und Anforderungen an die Korrosionsprüfung werden durch die Spezifikation festgelegt.",
        headers: ["Verfahren", "Anwendbar auf", "Schicht/Wirkung", "Norm", "Anwendung"],
        rows: [
          ["Passivieren (Salpetersäure)", "Edelstahl", "Passivoxid (keine Schicht verbleibend)", "ASTM A967", "Medizintechnik, Lebensmittel"],
          ["Passivieren (Zitronensäure)", "Edelstahl", "Passivoxid (keine Schicht verbleibend)", "ASTM A967", "Umweltfreundlichere Alternative"],
          ["Phosphatieren (Zink)", "Stahl", "Zinkphosphat-Konversionsschicht", "MIL-DTL-16232", "Vorbereitung als Lackhaftgrund"],
          ["Phosphatieren (Mangan)", "Stahl", "Manganphosphat-Konversionsschicht", "MIL-DTL-16232", "Verschleißfestigkeit, Ölrückhaltung"],
          ["Elektropolieren", "Edelstahl", "Einebnung der Oberfläche", "ASTM B912", "Medizintechnik, Lebensmittel, Optik"],
          ["Alodine (Chromatieren)", "Aluminium", "Chromat-Konversionsschicht", "MIL-DTL-5541", "Lackhaftgrund, Leitfähigkeit"],
        ],
      },
    ],
  },
  "boya-koruyucu-kaplamalar": {
    categoryLabel: "Oberflächenbehandlungen",
    title: "Lackierung & Schutzbeschichtungen",
    metaTitle: "Pulverbeschichtung & Schutzbeschichtungen | RAL-Farben | Mas Technic",
    metaDescription: "Pulverbeschichtung, Nasslack, Keramik- und PTFE-Beschichtungen; Standard- und Sonder-RAL-Farben. Korrosionsprüfung und Temperaturbeständigkeit richten sich nach Beschichtungssystem und Spezifikation.",
    description: "Pulverbeschichtung, Nasslackierung, Keramikbeschichtung und spezielle Schutzbeschichtungen – von industriellen Anwendungen bis zu dekorativen Oberflächen.",
    content: [
      "Wir bieten vier Lackarten an: Pulverbeschichtung (umweltfreundlich und beständig), Nasslack (glatte Oberfläche), Keramikbeschichtung (hohe Temperaturbeständigkeit) und KTL/E-Coat (elektrische Isolation). Die Schichtdicke richtet sich nach Spezifikation und Teil.",
      "Wir bieten eine breite Farbpalette, darunter RAL 9005 (Schwarz), 9010 (Weiß), 9006 (Grau), 3000 (Rot), 5015 (Blau), 6018 (Grün), 1003 (Gelb), 2004 (Orange) sowie Sonder-RAL-Farben. Korrosions- und Temperaturbeständigkeit hängen vom Beschichtungssystem ab; Prüfanforderungen wie die Dauer des Salzsprühnebeltests werden in der Angebotsphase gemäß Spezifikation bestätigt.",
    ],
    features: [
      "Pulverbeschichtung — Umweltfreundlich und beständig",
      "Nasslack — Glatte Oberfläche",
      "Keramikbeschichtung — Hohe Temperaturen",
      "KTL/E-Coat — Elektrische Isolation",
    ],
    technicalSpecs: [
      { label: "Schichtdicke", value: "Gemäß Spezifikation" },
      { label: "Salzsprühnebel", value: "ASTM B117; gemäß Spezifikation" },
    ],
    processSteps: ["Oberflächenvorbereitung", "Grundierung", "Lackierung / Beschichtung", "Einbrennen / Aushärten", "Qualitätskontrolle"],
    advantages: [
      "4 Lack-/Beschichtungsarten",
      "Standard- und Sonder-RAL-Farben",
      "Anforderung an die Korrosionsprüfung durch die Spezifikation festgelegt",
      "Antihaftende, reibungsarme Oberflächen mit PTFE-Beschichtung",
    ],
    comparisonTables: [
      {
        title: "Lack- und Beschichtungsarten im Vergleich",
        description: REF,
        headers: ["Beschichtungsart", "Schichtdicke", "Temperaturbeständigkeit", "Reibungskoeff.", "Anwendung"],
        rows: [
          ["Pulverlack (Polyester)", "60-120µm", "180°C", "0,30-0,40", "Außenbereich, dekorativ"],
          ["Pulverlack (Epoxid)", "60-100µm", "120°C", "0,35-0,45", "Innenbereich, Chemikalienbeständigkeit"],
          ["Nasslack (2K-PU)", "25-50µm", "130°C", "0,30-0,40", "Glatte Oberfläche, dünne Schicht"],
          ["Keramikbeschichtung", "50-100µm", "1000°C", "0,15-0,25", "Abgasanlage, Motor, Hochtemperatur"],
          ["PTFE (Teflon)", "15-40µm", "260°C", "0,05-0,10", "Antihaft, reibungsarm"],
          ["KTL (Elektrotauchlack)", "20-40µm", "150°C", "0,35-0,45", "Automobil, elektrische Isolation"],
          ["DLC (diamantähnlich)", "1-5µm", "350°C", "0,05-0,15", "Verschleiß, Medizintechnik, Raumfahrt"],
        ],
      },
    ],
  },
};
