import type { ServiceText } from "@/content/en/types";

export const part1: Record<string, ServiceText> = {
  "cnc-frezeleme": {
    categoryLabel: "Zerspanung",
    title: "CNC-Fräsen",
    metaTitle: "CNC-Fräsen | 5-Achs-Präzisionszerspanung | Mas Technic",
    metaDescription: "CNC-Fräsen in 3, 4 und 5 Achsen mit einem Standard-Toleranzbereich von ±0,01 mm. Zerspanung von Aluminium, Titan und Stahl, mit Prüfung der Fertigbarkeit zusammen mit dem Angebot.",
    description: "Unsere 5-Achs-CNC-Fräszentren bearbeiten komplexe Geometrien hochpräzise – in einem breiten Werkstoffspektrum von Aluminium bis Titan und von Kunststoffen bis zu Verbundwerkstoffen.",
    content: [
      "Auf unseren 5-Achs-CNC-Fräszentren fertigen wir komplexe Geometrien in einer einzigen Aufspannung. Weniger Aufspannungen sparen nicht nur Zeit: Jede neue Aufspannung bringt eine zusätzliche Fehlerquelle in die Maßkette, ihre Reduzierung kommt daher unmittelbar der Toleranz zugute.",
      "Das 3-Achs-Fräsen bietet wirtschaftliche Lösungen für ebene Flächen, Taschen und Standardgeometrien. Beim 4-Achs-Fräsen ermöglicht der Rundtisch das Einbringen von Nuten, Bohrungen und Profilen an zylindrischen Teilen. Das simultane 5-Achs-Fräsen bearbeitet komplexeste Teilegeometrien in einer Aufspannung und erfüllt so die Anforderungen der Luft- und Raumfahrt, der Medizintechnik und der Automobilindustrie.",
      "Strategien der Hochgeschwindigkeitsbearbeitung (HSC) senken die Schnittkräfte an dünnwandigen Teilen und verbessern die Oberflächengüte. In kritischen Branchen wie Luft- und Raumfahrt, Automobil, Medizintechnik und Verteidigung liegt unser Standard-Arbeitsbereich bei ±0,01 mm; die erreichbare Toleranz wird für jedes Teil in der technischen Prüfung festgelegt.",
      "Unser Team bearbeitet technische Werkstoffe wie Aluminium (6061, 7075), Edelstahl (304, 316), unlegierten Stahl, Titan, PEEK und POM/Delrin. Zur Kostenoptimierung führen wir bei jedem Projekt eine DFM-Analyse durch; der Upload im Angebotsprozess akzeptiert die Dateiendungen STEP, STP, STL, OBJ, IGES, IGS und 3MF, native CAD-Dateien oder Zeichnungen, die nicht in dieser Liste stehen, nehmen wir per E-Mail entgegen.",
    ],
    features: [
      "3-Achs-Fräsen — Wirtschaftliche Lösung für ebene Flächen und Standardgeometrien",
      "4-Achs-Fräsen — Umfangs- und Profilbearbeitung mit Rundtisch",
      "5-Achs-Simultanbearbeitung — Komplexe Geometrien in einer Aufspannung",
      "Hochgeschwindigkeitsbearbeitung (HSC) — Geringere Schnittkräfte an dünnwandigen Teilen",
      "±0,01 mm Standardtoleranz — durch den Prüfplan bestätigt",
      "Automatischer Werkzeugwechsel — unterbrechungsfreie Bearbeitung bei langen Zyklen",
    ],
    technicalSpecs: [
      { label: "Arbeitsbereich", value: "Im Angebot angegeben" },
      { label: "Standardtoleranz", value: "±0,01mm" },
    ],
    processSteps: ["DFM-Analyse", "CAM-Programmierung", "Vorrichtungsbau", "CNC-Bearbeitung", "KMG-Messung", "Qualitätsbericht"],
    advantages: [
      "Jede Geometrie mit 3-, 4- und 5-Achs-Konfigurationen",
      "Geringe Schnittkräfte und gute Oberflächengüte an dünnwandigen Teilen durch HSC",
      "Automatischer Werkzeugwechsel",
      "Flexibel vom Prototyp bis zur Serienfertigung (ab 1 Stück)",
      "Die Lieferzeit wird nach Prüfung der Kapazitätsplanung mit dem Angebot genannt",
    ],
    materials: [
      { name: "Aluminium", grade: "6061-T6 / 7075-T6", properties: "Leicht, korrosionsbeständig, gut zerspanbar" },
      { name: "Edelstahl", grade: "304 / 316L", properties: "Hohe Korrosionsbeständigkeit, hygienisch" },
      { name: "Unlegierter Stahl", grade: "1045 / 4140", properties: "Hohe Festigkeit, für Wärmebehandlung geeignet" },
      { name: "Titan", grade: "Ti6Al4V (Grade 5)", properties: "Leicht, biokompatibel, hohe Festigkeit" },
      { name: "POM (Delrin)", grade: "Delrin 150 / 500", properties: "Geringe Reibung, Maßhaltigkeit" },
      { name: "PEEK", grade: "PEEK 450G", properties: "Hohe Temperaturbeständigkeit, Chemikalienbeständigkeit" },
    ],
    faq: [
      { question: "3-Achs- oder 5-Achs-Bearbeitung?", answer: "Für ebene Flächen und einfache Taschen reicht die 3-Achs-Bearbeitung aus und ist wirtschaftlicher. Sind Hinterschnitte, schräge Flächen oder die Bearbeitung mehrerer Seiten in einer Aufspannung erforderlich, wird die 5-Achs-Bearbeitung bevorzugt." },
      { question: "Welche Toleranzen erreichen Sie beim CNC-Fräsen?", answer: "Unser Standard-Arbeitsbereich liegt bei ±0,01mm. Die erreichbare Toleranz hängt von Geometrie, Werkstoff, Teilegröße und Maßkette ab und wird für jedes Teil in der technischen Prüfung festgelegt." },
      { question: "Welche Dateiformate akzeptieren Sie?", answer: "Der Upload im Angebotsprozess akzeptiert folgende Dateiendungen: .step, .stp, .stl, .obj, .iges, .igs, .3mf — eine nicht aufgeführte Endung kann nicht hochgeladen werden. Wenn Sie Ihre nativen CAD-Dateien oder eine technische Zeichnung als PDF/DWG an sales@mastechnic.com senden, prüfen wir diese für ein Angebot." },
      { question: "Gibt es eine Mindestbestellmenge?", answer: "Nein, wir fertigen jede Menge – vom Einzelteil bis zur Serienfertigung. Auch Prototypenaufträge werden angenommen." },
      { question: "Wie lang ist Ihre Lieferzeit?", answer: "Die Lieferzeit wird nach Prüfung von Materialbeschaffung, Anzahl der Arbeitsgänge und Kapazitätsplanung mit dem Angebot genannt." },
    ],
    comparisonTables: [
      {
        title: "Vergleich der Achskonfigurationen beim CNC-Fräsen",
        description: "Wählen Sie die passende Achskonfiguration für Ihre Teilegeometrie",
        headers: ["Merkmal", "3-Achs", "4-Achs (3+1)", "5-Achs-Simultan"],
        rows: [
          ["Geometrie", "Ebene Flächen, Taschen", "Zylindrische Profile", "Komplexe Freiformen"],
          ["Anzahl Aufspannungen", "2-4 Aufspannungen", "1-2 Aufspannungen", "Eine Aufspannung"],
          ["Rüstzeit", "Kurz", "Mittel", "Lang (erstes Teil)"],
          ["Stückkosten", "$", "$$", "$$$"],
          ["Typische Anwendung", "Platte, Halter", "Flansch, Nut", "Turbine, komplexes Gehäuse"],
        ],
      },
      {
        title: "Bearbeitungsstrategien und Oberflächengüte",
        description: "Allgemeine Richtwerte; sie geben nicht die Kapazität des Unternehmens wieder. Der für Ihr Teil geltende Wert wird im Angebot angegeben.",
        headers: ["Strategie", "Vorschub", "Oberflächenrauheit (Ra)", "Standzeit", "Anwendung"],
        rows: [
          ["Schruppen (HPC)", "5000-8000 mm/min", "Ra 3,2-6,3µm", "Standard", "Maximales Zerspanvolumen"],
          ["Vorschlichten", "2000-4000 mm/min", "Ra 1,6-3,2µm", "Gut", "Annäherung an die Endkontur"],
          ["Schlichten", "1000-2000 mm/min", "Ra 0,8-1,6µm", "Lang", "Endgültige Oberflächenqualität"],
          ["HSC (Hochgeschwindigkeit)", "8000-15000 mm/min", "Ra 0,4-0,8µm", "Kurz", "Dünne Wände, harte Werkstoffe"],
          ["Feinstschlichten", "500-1000 mm/min", "Ra 0,1-0,4µm", "Sehr lang", "Optische Flächen, Werkzeuge"],
        ],
      },
    ],
  },
  "cnc-tornalama": {
    categoryLabel: "Zerspanung",
    title: "CNC-Drehen",
    metaTitle: "CNC-Drehen | Doppelspindel- & Langdrehen | Mas Technic",
    metaDescription: "Präzises CNC-Drehen: Drehmaschinen mit angetriebenen Werkzeugen, Y-Achse und Langdrehautomaten (Swiss-Type). ±0,01 mm Standardtoleranz; der Arbeitsbereich wird im Angebot angegeben.",
    description: "Mehrachsige Drehzentren, die Wellen, Muttern, Gehäuse und komplexe Rotationsteile in einer einzigen Aufspannung komplett bearbeiten.",
    content: [
      "CNC-Drehen ist das effizienteste Fertigungsverfahren für zylindrische und rotationssymmetrische Teile. Unsere CNC-Drehmaschinen mit C- und Y-Achse integrieren Fräsoperationen, sodass außermittige Bohrungen und Nuten in derselben Aufspannung bearbeitet werden.",
      "Das 2-Achs-Drehen fertigt Wellen, Buchsen und einfache zylindrische Teile, während beim Drehen mit angetriebenen Werkzeugen über die Y-Achse gefräst, gebohrt und Gewinde geschnitten wird. Mit Dreh-Fräs-Bearbeitung drehen und fräsen wir in einer Aufspannung und gewinnen so Präzision und Effizienz bei komplexen Teilen.",
      "Das Langdrehen (Swiss-Type) fertigt Teile mit kleinem Durchmesser und großer Länge wie Schrauben, Stifte und Steckerpins: Die kurz gehaltene freie Länge begrenzt die Durchbiegung. Auf Doppelspindel-Drehzentren werden Vorder- und Rückseitenbearbeitung in einer Aufspannung abgeschlossen.",
      "Auf Drehmaschinen mit Stangenlader wird das Stangenmaterial automatisch nachgeschoben, sodass lange Lose kontinuierlich laufen können. Der Arbeitsbereich wird nach Prüfung von Teilegeometrie und Prozessplan im Angebot angegeben.",
    ],
    features: [
      "2-Achs-Drehen — Wellen, Buchsen und zylindrische Teile",
      "Drehen mit angetriebenen Werkzeugen — Fräsen, Bohren und Gewindeschneiden über die Y-Achse",
      "Dreh-Fräs-Bearbeitung — Komplettbearbeitung in einer Aufspannung",
      "Langdrehen — Langdrehautomat für Teile mit kleinem Durchmesser und großer Länge",
      "Automatischer Stangenlader — Kontinuierliche Fertigung in langen Losen",
      "Doppelspindel-Drehen — Vorder- und Rückseite in einer Aufspannung",
    ],
    technicalSpecs: [
      { label: "Arbeitsbereich (Durchmesser / Länge)", value: "Im Angebot angegeben" },
      { label: "Standardtoleranz", value: "±0,01mm" },
      { label: "Maschinentypen", value: "2-Achs, C/Y, Dreh-Fräs, Langdrehen" },
      { label: "Stangenlader", value: "Automatisch" },
    ],
    processSteps: ["Zeichnungsprüfung", "Materialvorbereitung", "CNC-Drehen", "Messung & Prüfung", "Verpackung"],
    advantages: [
      "Komplettbearbeitung in einer Aufspannung",
      "Mit der Gegenspindel wird die Rückseite des Teils ohne separate Aufspannung fertiggestellt",
      "Teile mit kleinem Durchmesser und großer Länge durch Langdrehen",
      "Mannlose Bearbeitung langer Lose mit dem Stangenlader",
      "Dreh-Fräs-Bearbeitung deckt den Fräsbedarf in einem Arbeitsgang ab",
    ],
    materials: [
      { name: "Aluminium", grade: "6061 / 2024 / 7075", properties: "Automatenqualität, leicht" },
      { name: "Messing", grade: "CuZn39Pb3 (CW614N)", properties: "Hervorragend zerspanbar, dekorativ" },
      { name: "Edelstahl", grade: "303 / 304 / 316", properties: "Korrosionsbeständig, hygienisch" },
      { name: "Automatenstahl", grade: "1215 / 11SMnPb30", properties: "Für Hochgeschwindigkeitsdrehen optimiert" },
      { name: "Titan", grade: "Grade 2 / Grade 5", properties: "Biokompatibel, hohe spezifische Festigkeit" },
      { name: "Delrin (POM)", grade: "Delrin 150 / PTFE", properties: "Geringe Reibung, verschleißfest" },
    ],
    faq: [
      { question: "Drehen oder Fräsen – was ist zu wählen?", answer: "Ist Ihr Teil zylindrisch oder rotationssymmetrisch, ist Drehen wirtschaftlicher. Für prismatische Teile wird Fräsen bevorzugt." },
      { question: "Werden komplexe Teile auf einer Maschine gefertigt?", answer: "Auf unseren Dreh-Fräs-Maschinen kann in einer Aufspannung sowohl gedreht als auch gefräst werden. Das erhöht die Präzision und senkt die Kosten." },
      { question: "Wann ist Langdrehen erforderlich?", answer: "Bei Teilen mit kleinem Durchmesser und hohem Längen-Durchmesser-Verhältnis (z. B. Schrauben, Stifte) hält ein Langdrehautomat die Schneide nah an der Führungsbuchse und begrenzt so die Durchbiegung. Ob ein Teil für das Langdrehen geeignet ist, wird in der Zeichnungsprüfung entschieden." },
      { question: "Ist das Verfahren für die Serienfertigung geeignet?", answer: "Ja. Auf Drehmaschinen mit Stangenlader wird das Stangenmaterial automatisch nachgeschoben, sodass lange Lose ohne Bedienereingriff bearbeitet werden können; Losgröße und Lieferzeit werden zusammen mit der Kapazitätsplanung im Angebot bestätigt." },
      { question: "Welchen Durchmesserbereich können Sie drehen?", answer: "Der Arbeitsbereich wird nach Prüfung von Teilegeometrie und Prozessplan im Angebot angegeben." },
    ],
    comparisonTables: [
      {
        title: "Vergleich der CNC-Drehmaschinenkonfigurationen",
        headers: ["Merkmal", "2-Achs-Drehmaschine", "Angetriebene Werkzeuge (C/Y)", "Dreh-Fräs", "Langdrehautomat"],
        rows: [
          ["Bearbeitungsart", "Nur Drehen", "Drehen + Bohren/Fräsen", "Komplett Drehen + Fräsen", "Lange/schlanke Teile"],
          ["Rüstzeit", "Kurz", "Mittel", "Lang", "Mittel"],
          ["Stückkosten", "$", "$$", "$$$", "$$"],
          ["Typisches Teil", "Welle, Buchse", "Flansch, Ventilkörper", "Komplexes Gehäuse", "Stift, Schraube, Steckverbinder"],
        ],
      },
      {
        title: "Zerspanbarkeitsmatrix Drehen",
        description: "Allgemeine Richtwerte; sie geben nicht die Kapazität des Unternehmens wieder. Der für Ihr Teil geltende Wert wird im Angebot angegeben.",
        headers: ["Werkstoff", "Schnittgeschwindigkeit (m/min)", "Vorschub (mm/U)", "Werkzeugtyp"],
        rows: [
          ["Automatenstahl (11SMnPb30)", "180-250", "0,15-0,35", "Beschichtetes Hartmetall"],
          ["Aluminium 6061", "300-600", "0,10-0,30", "PKD / Diamant"],
          ["Messing CuZn39Pb3", "200-400", "0,10-0,25", "Unbeschichtetes Hartmetall"],
          ["Edelstahl 304", "120-180", "0,08-0,20", "CVD-beschichtet"],
          ["Titan Grade 5", "40-80", "0,05-0,15", "PVD-beschichtet"],
          ["Inconel 718", "20-40", "0,05-0,10", "Keramik / CBN"],
        ],
      },
    ],
  },
  "hassas-mikro-isleme": {
    categoryLabel: "Zerspanung",
    title: "Mikrozerspanung",
    metaTitle: "Mikrozerspanung | Kleinstwerkzeuge | Medizintechnik & Elektronik | Mas Technic",
    metaDescription: "Mikrofräsen, Mikrodrehen und Mikrobohren. Präzisionszerspanung im Kleinstmaßstab für Steckverbinder, Optik und Medizintechnik-Komponenten; der Arbeitsbereich wird im Angebot angegeben.",
    description: "Mikrozerspanung für Teile mit Merkmalen, die für Standardwerkzeuge zu klein sind. Typische Anwendungen sind Komponenten für Medizintechnik, Elektronik und Optik.",
    content: [
      "Die Mikrozerspanung erzeugt Merkmale, die Standardwerkzeuge nicht erreichen – schmale Nuten, kleine Bohrungen, dünne Wände – mit Werkzeugen kleinen Durchmessers und hohen Spindeldrehzahlen. Typische Anwendungen sind optische, elektronische und medizintechnische Komponenten.",
      "Mikrofräsen, Mikro-Langdrehen und Mikrobohren fertigen Kleinteile wie Stifte, Schrauben, Steckerpins, Düsen und Teile zur Durchflussregelung. Der Arbeitsbereich wird nach Prüfung von Teilegeometrie und Prozessplan im Angebot angegeben.",
      "Bei Mikroteilen wird auch das Prüfverfahren passend zum Maßstab gewählt: Taktile Messung kann das Teil verformen, daher werden optische Verfahren bevorzugt. Der Prüfplan legt vorab fest, welches Maß mit welchem Verfahren gemessen wird, und die Ergebnisse werden dokumentiert.",
      "Typische Anwendungen: Komponenten für chirurgische Instrumente und Geräte in der Medizintechnik; Einspritzdüsen, Sensorgehäuse und Mikroventile in der Luft- und Raumfahrt; Steckerpins, faseroptische Komponenten und Prüfvorrichtungen für Halbleiter in der Elektronik; Uhrwerksteile, Linsenhalter und Kamerakomponenten in Uhrenindustrie und Optik.",
    ],
    features: [
      "Mikrofräsen — 5-Achs-Bearbeitung mit Werkzeugen kleinen Durchmessers",
      "Mikrodrehen — Langdrehen für Teile mit kleinem Durchmesser und großer Länge",
      "Mikrobohren — Präzisionsbohrungen mit kleinem Durchmesser",
      "Mikromessung — Prüfung durch optische Messung",
    ],
    technicalSpecs: [
      { label: "Arbeitsbereich", value: "Im Angebot angegeben" },
      { label: "Standardtoleranz", value: "±0,01mm" },
    ],
    processSteps: ["Mikro-CAM-Programmierung", "Auswahl der Sonderwerkzeuge", "Mikrozerspanung", "Optische Messung", "Reinigung & Verpackung"],
    advantages: [
      "Kontrollierte Bearbeitung von Geometrien im Kleinstmaßstab",
      "Bearbeitung mit Werkzeugen kleinen Durchmessers und Hochgeschwindigkeitsspindel",
      "Reinigung und Verpackung der Teile nach Prüfplan",
      "Prüfung unter optischer Vergrößerung",
      "Erfahrung in Medizintechnik, Luft- und Raumfahrt sowie Elektronik",
      "Mikro-Serienfertigung auf Langdrehautomaten mit Stangenlader",
    ],
    materials: [
      { name: "Titan", grade: "Grade 5 (Ti6Al4V)", properties: "Biokompatibel, leicht, hohe Festigkeit" },
      { name: "Edelstahl (Medizintechnik)", grade: "316L", properties: "Biokompatibel, korrosionsbeständig" },
      { name: "Aluminium", grade: "7075-T6", properties: "Leicht, hohe Festigkeit, gut zerspanbar" },
      { name: "Kupfer", grade: "C101 (OFE)", properties: "Hohe Leitfähigkeit, Präzisionszerspanung" },
      { name: "PEEK", grade: "PEEK 450G", properties: "Hohe Temperatur- und Chemikalienbeständigkeit" },
      { name: "Wolframkarbid", grade: "WC-Co", properties: "Extreme Härte, verschleißfest" },
    ],
    faq: [
      { question: "Wann sollte Mikrozerspanung gewählt werden?", answer: "Sind die Merkmale zu klein für Standardwerkzeuge – schmale Nuten, kleine Bohrungen, dünne Wände –, ist Mikrozerspanung erforderlich. Ob ein Teil sie benötigt, wird in der Zeichnungsprüfung entschieden." },
      { question: "Ist sie teurer als Standard-CNC-Bearbeitung?", answer: "Ja, Sonderwerkzeuge, geringe Vorschübe und anspruchsvolle Messanforderungen machen sie teurer. Sie wird für Ergebnisse eingesetzt, die mit Standardverfahren nicht erreichbar sind." },
      { question: "Ist Serienfertigung möglich?", answer: "Ja. Die Serienfertigung von Mikroteilen ist auf Langdrehautomaten mit Stangenlader möglich; die Losgröße wird in der Angebotsphase geplant." },
      { question: "Erhalte ich ein Messprotokoll?", answer: "Die im Prüfplan festgelegten Maße werden gemessen, und das Messprotokoll wird der Lieferdokumentation beigefügt. Ist eine Koordinatenmessung erforderlich, wird auf Wunsch eine akkreditierte Messung durch Dritte veranlasst." },
    ],
    comparisonTables: [
      {
        title: "Vergleich der Mikrozerspanungstechnologien",
        description: "Allgemeine Richtwerte; sie geben nicht die Kapazität des Unternehmens wieder. Der für Ihr Teil geltende Wert wird im Angebot angegeben.",
        headers: ["Parameter", "Mikrofräsen", "Mikrodrehen", "Mikrobohren", "Mikroerodieren (EDM)"],
        rows: [
          ["Bearbeitungsgeschwindigkeit", "Mittel", "Hoch", "Niedrig", "Sehr niedrig"],
          ["Werkstoffeinschränkung", "Alle", "Zylindrisch", "Alle", "Leitfähig"],
          ["Kosten", "$$$", "$$", "$$", "$$$$"],
          ["Typische Anwendung", "Optik, Medizintechnik-Komponente", "Stift, Schraube", "Düse, Einspritzdüse", "Mikrowerkzeug"],
        ],
      },
      {
        title: "Branchenanforderungen an die Mikrozerspanung",
        description: "Die Projektanforderung wird durch die Spezifikation festgelegt; die Tabelle stellt keine Kapazität des Unternehmens dar.",
        headers: ["Branche", "Typisches Teil", "Toleranzerwartung", "Dokumentationserwartung"],
        rows: [
          ["Medizintechnik", "Chirurgisches Instrument, Medizintechnik-Komponente", "Gemäß Spezifikation", "Nachweis biokompatibler Werkstoffe"],
          ["Luft- und Raumfahrt", "Einspritzdüse, Sensor", "Gemäß Spezifikation", "Rückverfolgbarer Werkstoffnachweis"],
          ["Elektronik", "Steckerpin, Leiterplatte", "Gemäß Spezifikation", "Visuelle Abnahmekriterien"],
          ["Uhren & Optik", "Uhrwerk, Linsenhalter", "Gemäß Spezifikation", "Messprotokoll"],
          ["Automobil", "Einspritzdüse, Sensor", "Gemäß Spezifikation", "Chargenrückverfolgbarkeit"],
        ],
      },
    ],
  },
  "derin-delik-raybalama": {
    categoryLabel: "Zerspanung",
    title: "Tieflochbohren & Reiben",
    metaTitle: "Tieflochbohren & Reiben | Einlippen- & BTA-Bohren | Mas Technic",
    metaDescription: "Einlippenbohren, BTA-Bohren, Reiben und Honen für Bohrungen mit hohem Längen-Durchmesser-Verhältnis. Arbeitsbereich und Toleranzklasse werden im Angebot gemäß Zeichnung angegeben.",
    description: "Präzise, gerade Bearbeitung von Bohrungen mit hohem Längen-Durchmesser-Verhältnis. Spezialisierte Lösungen für Hydraulikzylinder, Werkzeug-Kühlkanäle und Maschinenteile.",
    content: [
      "Tieflochbohren ist ein spezielles Zerspanungsverfahren für Bohrungen mit hohem Längen-Durchmesser-Verhältnis (L/D); bei solchen Verhältnissen lässt sich mit Standardbohrern nur schwer eine gerade, genaue Bohrung erzielen.",
      "Beim Einlippenbohren wird ein einschneidiger Bohrer eingesetzt, und die Späne werden mit Hochdruck-Kühlschmierstoff ausgetragen; so entstehen lange Bohrungen mit kleinem Durchmesser – typische Anwendungen sind Ölkanäle und Kühlbohrungen. Beim BTA-Bohren erfolgt die Spanabfuhr durch das Werkzeuginnere; es wird für tiefe Bohrungen mit größerem Durchmesser bevorzugt.",
      "Reiben und Honen bringen Durchmesser, Form und Oberfläche der gebohrten Bohrung auf Fertigmaß. Toleranzklasse sowie unteres und oberes Grenzmaß der Bohrung ergeben sich aus Nennmaß und Zeichnung.",
      "Hydraulikzylinderkörper, Ventilblöcke, Verteilerbohrungen und Werkzeug-Kühlkanäle sind typische Anwendungen dieser Verfahren. Der Arbeitsbereich wird nach Prüfung von Teilegeometrie und Prozessplan im Angebot angegeben.",
    ],
    features: [
      "Einlippenbohren — Lange Bohrungen mit kleinem Durchmesser und Ölkanäle",
      "BTA-Bohren — Innere Spanabfuhr bei tiefen Bohrungen mit großem Durchmesser",
      "Präzisionsreiben — Durchmesser und Form auf Fertigmaß",
      "Honen — Verbesserung der Bohrungsoberfläche",
    ],
    technicalSpecs: [
      { label: "Verfahren", value: "Einlippenbohren, BTA, Reiben, Honen" },
      { label: "Arbeitsbereich (Durchmesser / Tiefe)", value: "Im Angebot angegeben" },
      { label: "Bohrungstoleranz", value: "Gemäß Nennmaß und Zeichnung" },
    ],
    processSteps: ["Technische Analyse", "Auswahl des Bohrverfahrens", "Tieflochbearbeitung", "Reiben / Honen", "Messung & Protokoll"],
    advantages: [
      "Einlippen- und BTA-Verfahren",
      "Fertigmaß und Oberfläche durch Reiben und Honen",
      "Begrenzter Mittenverlauf durch Führungsbuchsen und Hochdruck-Kühlschmierstoff",
    ],
    materials: [
      { name: "Stahl", grade: "1045 / 4140 / 42CrMo4", properties: "Hohe Festigkeit, für Wärmebehandlung geeignet" },
      { name: "Edelstahl", grade: "304 / 316L", properties: "Korrosionsbeständig, Hydraulikanwendungen" },
      { name: "Aluminium", grade: "6061 / 7075", properties: "Leicht, ideal für Kühlkanäle" },
      { name: "Gusseisen", grade: "GGG-40 / GGG-50", properties: "Schwingungsdämpfend, hohe Belastung" },
      { name: "Inconel", grade: "625 / 718", properties: "Hohe Temperaturbeständigkeit, Luft- und Raumfahrt" },
      { name: "Bronze", grade: "CuSn8 / CuAl10", properties: "Verschleißfest, reibungsmindernd" },
    ],
    faq: [
      { question: "Was ist eine Tiefbohrung?", answer: "Bohrungen mit hohem Längen-Durchmesser-Verhältnis werden als „Tiefbohrungen“ bezeichnet; bei solchen Verhältnissen lässt sich mit Standardbohrern nur schwer eine gerade, genaue Bohrung erzielen." },
      { question: "Worin unterscheiden sich Einlippenbohren und BTA?", answer: "Einlippenbohren wird für kleine Durchmesser und hohe Längen-Durchmesser-Verhältnisse eingesetzt; die Späne werden vom Kühlschmierstoff ausgetragen. BTA wird für größere Durchmesser bevorzugt; die Spanabfuhr erfolgt durch das Werkzeuginnere. Welches Verfahren zum Einsatz kommt, wird bei der Prüfung von Teil und Zeichnung entschieden." },
      { question: "Wie wird die Geradheit erreicht?", answer: "Spezielle Führungsbuchsensysteme, Hochdruck-Kühlschmierstoff und optimierte Schnittparameter halten den Mittenverlauf so gering wie möglich." },
      { question: "Lässt sich die Bohrungsoberfläche verbessern?", answer: "Ja, Reiben und Honen bringen Oberfläche und Durchmesser der Bohrung auf Fertigmaß. Toleranzklasse sowie unteres und oberes Grenzmaß der Bohrung ergeben sich aus Nennmaß und Zeichnung." },
    ],
    comparisonTables: [
      {
        title: "Tieflochbohrverfahren im Vergleich",
        headers: ["Parameter", "Einlippenbohren", "BTA-Bohren", "Konventioneller Bohrer"],
        rows: [
          ["Spankontrolle", "Äußere Abfuhr mit Kühlschmierstoff", "Innere Spanabfuhr", "Spannuten des Bohrers"],
          ["Typischer Durchmesser", "Kleiner Durchmesser", "Großer Durchmesser", "Allgemein"],
          ["Typische Anwendung", "Ölkanal, Kühlbohrung", "Zylinderkörper", "Standardbohrung"],
        ],
      },
    ],
  },
  "enjeksiyon-kalibi": {
    categoryLabel: "Vorserie",
    title: "Spritzgießwerkzeuge",
    metaTitle: "Spritzgießwerkzeugbau | Mas Technic",
    metaDescription: "Bau von Spritzgießwerkzeugen aus Aluminium und Stahl. Werkstoffauswahl vom Prototypen- bis zum Serienwerkzeug; die Werkzeugstandzeit wird im Angebot je nach Werkzeugstahl und Stückzahl angegeben.",
    description: "Werkzeugbau in Aluminium und Stahl – von schnellen Prototypenwerkzeugen bis zu Serienwerkzeugen für hohe Stückzahlen.",
    content: [
      "Wir konstruieren und fertigen hochpräzise Kunststoff-Spritzgießwerkzeuge. Das Füllverhalten wird in der Werkzeugkonstruktion bewertet; bei komplexen Teilen wird der Umfang der Füllsimulation im Angebot angegeben. Entformungsschrägen, Schwindungsausgleich sowie Anguss- und Entlüftungspositionen werden in der DFM-Analyse behandelt.",
      "Der Werkzeugwerkstoff wird passend zur erwarteten Stückzahl gewählt: Al 7075 (150 HB) für Prototypen und kleine Stückzahlen, P20 (280-320 HB) für mittlere Stückzahlen, H13 (45-52 HRC) für hohe Stückzahlen und S136 (48-52 HRC) für Anwendungen, die Korrosionsbeständigkeit erfordern. Heißkanaltechnik spart Material und verbessert die Zykluszeit.",
      "Aluminiumwerkzeuge sind bei kleinen und mittleren Stückzahlen schneller einsatzbereit, Stahlwerkzeuge erreichen in der Großserie höhere Standzeiten. Erwartete Stückzahl und Teilegeometrie bestimmen gemeinsam Werkzeugwerkstoff und Kavitätenzahl.",
    ],
    features: [
      "Aluminiumwerkzeug — schnell verfügbar für kleine und mittlere Stückzahlen",
      "Stahlwerkzeug — hohe Standzeit in der Großserie",
      "Mehrfachwerkzeug — Höhere Produktivität",
      "Heißkanalsystem — Materialeinsparung und kürzere Zyklen",
    ],
    technicalSpecs: [
      { label: "Kavitätenzahl", value: "Im Angebot festgelegt" },
      { label: "Werkzeugstandzeit", value: "Je nach Werkzeugstahl und Stückzahl" },
      { label: "Toleranz", value: "±0,01mm" },
    ],
    processSteps: ["Produktanalyse", "Werkzeugkonstruktion", "Füll- & Fließbewertung", "CNC-Bearbeitung", "Bemusterung", "Lieferung"],
    advantages: [
      "Füllverhalten in der Werkzeugkonstruktion bewertet",
      "DFM-Analyse; Entformungsschrägen und Schwindungsausgleich separat bewertet",
      "Unterstützung von Heißkanalsystemen",
      "4 Werkzeugwerkstoffe zur Wahl (Al 7075, P20, H13, S136)",
    ],
    materials: [
      { name: "Al 7075", grade: "150 HB", properties: "Prototypen- und Kleinserienwerkzeug" },
      { name: "P20 (1.2311)", grade: "280-320 HB", properties: "Mittlere Stückzahlen, universell einsetzbar" },
      { name: "H13 (1.2344)", grade: "45-52 HRC", properties: "Hohe Stückzahlen, Warmarbeitsstahl" },
      { name: "S136 (1.2083)", grade: "48-52 HRC", properties: "Korrosionsbeständig, Werkzeuge für Optikteile" },
    ],
    faq: [
      { question: "Wie lange dauert der Bau eines Werkzeugs?", answer: "Die Werkzeugbauzeit hängt von Werkstoffgüte, Kavitätenzahl und Oberflächenanforderung ab; ein Aluminiumwerkzeug ist schneller bearbeitet als ein Stahlwerkzeug. Die Lieferzeit wird nach Prüfung von Materialbeschaffung, Anzahl der Arbeitsgänge und Kapazitätsplanung mit dem Angebot genannt." },
      { question: "Ist eine Füllsimulation erforderlich?", answer: "Nicht für jedes Teil; sie wird vor allem bei komplexen Teilen empfohlen, um Füllprobleme, Einfallstellen und Verzugsrisiken frühzeitig zu erkennen. Ihr Umfang wird in der Angebotsphase festgelegt." },
      { question: "Aluminium- oder Stahlwerkzeug?", answer: "Aluminiumwerkzeuge sind bei kleinen Stückzahlen meist wirtschaftlicher, Stahlwerkzeuge bei hohen Stückzahlen; die Grenze wird in der Angebotsphase anhand von Teilegeometrie, Kunststoff und erwarteter Stückzahl festgelegt." },
    ],
    comparisonTables: [
      {
        title: "Auswahlmatrix Werkstoffe für Spritzgießwerkzeuge",
        description: "Typische Härtewerte von Werkzeugstählen; die Werkzeugstandzeit wird im Angebot je nach Stahl, Kunststoff und Stückzahl angegeben.",
        headers: ["Werkzeugwerkstoff", "Härte", "Kosten", "Anwendung"],
        rows: [
          ["Al 7075", "150 HB", "$", "Prototyp, kleine Stückzahlen"],
          ["P20 (1.2311)", "280-320 HB", "$$", "Mittlere Stückzahlen, universell"],
          ["H13 (1.2344)", "45-52 HRC", "$$$", "Hohe Stückzahlen, Warmarbeit"],
          ["S136 (1.2083)", "48-52 HRC", "$$$$", "Optik, Medizintechnik, Korrosion"],
          ["NAK80", "38-42 HRC", "$$$", "Hochglanz, vorvergütet"],
        ],
      },
      {
        title: "Kavitätenzahl und Fertigungseffizienz",
        description: "Mit steigender Kavitätenzahl sinken die Stückkosten und die Werkzeuginvestition steigt; die passende Anzahl wird im Angebot für Teil und Stückzahl festgelegt.",
        headers: ["Kavitäten", "Stückkosten", "Werkzeugkosten"],
        rows: [
          ["Einfachwerkzeug", "$$$", "$"],
          ["2 Kavitäten", "$$", "$$"],
          ["4 Kavitäten", "$$", "$$$"],
          ["8 Kavitäten", "$", "$$$$"],
          ["16+ Kavitäten", "$", "$$$$$"],
        ],
      },
    ],
  },
  "basincli-dokum": {
    categoryLabel: "Vorserie",
    title: "Druckguss",
    metaTitle: "Druckgusswerkzeugbau | Aluminium & Zamak | Mas Technic",
    metaDescription: "Konstruktion und Bau von Druckgusswerkzeugen für Aluminium und Zink. Wandstärke und Rohteil-Toleranzklasse werden im Angebot je nach Legierung und Geometrie angegeben.",
    description: "Komplexe Geometrien als ein Gussteil in Aluminium- und Zinklegierungen – mit hoher Ausbringung und niedrigen Stückkosten.",
    content: [
      "Wir konstruieren und fertigen Druckgusswerkzeuge passend zu Teilegeometrie, Legierung und erwarteter Stückzahl. Mindestwandstärke, Toleranzklasse des Rohgussteils (die CT-Klasse nach ISO 8062 hängt vom Nennmaß ab) und Gussoberfläche hängen von Legierung, Teilegröße und Werkzeugkonstruktion ab; die Werte werden im Angebot angegeben. Funktionsflächen werden anschließend auf die Toleranz der Zeichnung bearbeitet.",
      "ADC12 und A380 (Al-Si) sind Gusslegierungen für Universal- und Strukturteile, ZA-8 und ZA-27 (Zn-Al) für dünnwandige und hochbelastete Anwendungen; die Legierung wird passend zur Funktion des Teils gewählt.",
      "Bei Druckgusswerkzeugen für Aluminium, Zamak und Magnesium werden Füll- und Erstarrungsverhalten in der Werkzeugkonstruktion bewertet; der Umfang der Füllsimulation wird im Angebot angegeben.",
    ],
    features: [
      "Werkzeugkonstruktion — Passend zu Teilegröße und Legierung",
      "Dünnwandige Teile — Wandstärke je nach Legierung und Geometrie",
      "Rohteiltoleranz — CT-Klasse nach ISO 8062, je nach Nennmaß",
      "Gussoberfläche — Abhängig von Werkzeugoberfläche und Legierung",
    ],
    technicalSpecs: [
      { label: "Arbeitsbereich", value: "Im Angebot angegeben" },
      { label: "Werkstoffe", value: "ADC12, A380, ZA-8, ZA-27" },
      { label: "Werkzeugstandzeit", value: "Im Angebot angegeben" },
      { label: "Toleranz", value: "CT-Klasse je nach Nennmaß" },
    ],
    processSteps: ["Teileanalyse", "Werkzeugkonstruktion", "Füll- & Fließbewertung", "Werkzeugbau", "Probeguss", "Serienfertigung"],
    advantages: [
      "Große Legierungsauswahl (Al, Zn, Mg)",
      "Werkzeugkonstruktion unter Berücksichtigung des Füllverhaltens",
      "Kompetenz für dünnwandige Teile",
      "Hohe Ausbringung und niedrige Stückkosten",
    ],
    comparisonTables: [
      {
        title: "Vergleich der Druckgusslegierungen",
        description: "Typische Literaturwerte; maßgeblich für die Auslegung ist das Werkstoffzeugnis. Keine Kapazitätsangabe des Unternehmens.",
        headers: ["Legierung", "Zugfestigkeit", "Dichte", "Gießtemperatur", "Anwendung"],
        rows: [
          ["ADC12 (Al-Si)", "280 MPa", "2,74 g/cm³", "640-680°C", "Universell, Motorgehäuse"],
          ["A380 (Al-Si-Cu)", "320 MPa", "2,71 g/cm³", "650-700°C", "Hohe Festigkeit, Strukturteile"],
          ["ZA-8 (Zn-Al)", "350 MPa", "6,3 g/cm³", "420-440°C", "Dünnwandig, Muttern"],
          ["ZA-27 (Zn-Al)", "420 MPa", "5,0 g/cm³", "440-480°C", "Hohe Belastung, Lager"],
          ["AZ91D (Mg)", "230 MPa", "1,81 g/cm³", "620-650°C", "Leicht, Elektronikgehäuse"],
        ],
      },
    ],
  },
};
