import type { ServiceText } from "@/content/en/types";

export const part6: Record<string, ServiceText> = {
  "operasyonel-verimlilik": {
    categoryLabel: "Prozess & Betrieb",
    title: "Operative Effizienz",
    metaTitle: "Operative Effizienz | Lean Production, Kaizen, SMED | Mas Technic",
    metaDescription: "Lean Production, 5S, Kaizen, Kanban, TPM und SMED in der Praxis. Definierte Methoden für kürzere Rüstzeiten, weniger Stillstand und bessere Wiederholgenauigkeit.",
    description: "Effizienz ist kein Zielblatt, sondern eine Arbeitsweise: kürzere Rüstvorgänge, weniger Stillstand und ein Teil, das jedes Mal gleich gefertigt wird, sind Ergebnisse derselben Disziplin.",
    content: [
      "Die Dauer eines Auftrags besteht nicht nur aus Zerspanungszeit. Bei den meisten Aufträgen sind Rüsten, Warten, Handling und erneutes Messen ausschlaggebend; deshalb betrachten wir bei unserer Verbesserungsarbeit Rüstvorgang und Fluss vor den Schnittparametern.",
      "Der SMED-Ansatz teilt die Rüstarbeit in zwei Gruppen: Tätigkeiten, die bei stehender Maschine erfolgen müssen, und Tätigkeiten, die während des Laufs vorbereitet werden können. Wird die zweite Gruppe aus dem Rüstvorgang herausgelöst, verkürzt sich unmittelbar die Zeit, in der die Maschine keine Teile fertigt.",
      "5S und Kanban verringern Suchzeiten und den Umlaufbestand. Standardisierte Rüstanweisungen sorgen dafür, dass ein Bediener, der denselben Auftrag ein zweites Mal ausführt, die Entscheidungen des ersten Mals nicht neu treffen muss — hier beginnt Wiederholgenauigkeit.",
      "Im Rahmen von TPM ist Wartung ein geplanter Arbeitsschritt und kein Eingriff nach einem Ausfall. Da die Maschinengenauigkeit eine Eingangsgröße der Fertigung ist, schlägt sich eine verzögerte Wartung direkt als Toleranzverlust nieder.",
      "In Kaizen-Workshops lautet die Frage nicht „Wer hat den Fehler gemacht?“, sondern „Warum ist dieser Schritt fehleranfällig?“. Eine Korrektur, die nicht bis zur Grundursache reicht, erzeugt im nächsten Los denselben Fehler erneut.",
    ],
    features: [
      "SMED — Rüstarbeit von der Maschine verlagern",
      "5S — Such- und Vorbereitungszeiten verkürzen",
      "Kanban — Materialfluss und Steuerung des Umlaufbestands",
      "TPM — Wartung als geplanter Arbeitsschritt",
      "Standard-Rüstanweisung — Entscheidungen werden nicht neu getroffen",
      "Kaizen — Korrekturmaßnahmen bis zur Grundursache",
    ],
    technicalSpecs: [
      { label: "Ansatz", value: "Lean Production" },
      { label: "Rüsten", value: "Mit SMED getrennt" },
      { label: "Materialfluss", value: "Kanban" },
      { label: "Wartung", value: "Geplant (TPM)" },
      { label: "Verbesserung", value: "Kaizen-Workshops" },
      { label: "Nachweis", value: "Protokoll der Korrekturmaßnahmen" },
    ],
    advantages: [
      "Rüstzeit wird vor der Zerspanungszeit angegangen",
      "Arbeiten, die während des Maschinenlaufs vorbereitet werden können, werden aus dem Rüstvorgang herausgelöst",
      "Eine Standard-Rüstanweisung verbessert die Wiederholgenauigkeit",
      "Wartung ist geplant; Verzögerung führt zu Toleranzverlust",
      "Eine Korrektur wird erst abgeschlossen, wenn die Grundursache gefunden ist",
      "Verbesserungen werden dokumentiert und nachverfolgt",
    ],
    faq: [
      {
        question: "Wie wirkt sich die Effizienzarbeit auf mein Teil aus?",
        answer: "Direkt an zwei Stellen: Mit kürzeren Rüstvorgängen werden kleine Lose wirtschaftlich, und eine Standard-Rüstanweisung erleichtert es, dass dasselbe Teil von Los zu Los gleich gefertigt wird.",
      },
      {
        question: "Was ist SMED und warum ist es wichtig?",
        answer: "SMED teilt die Rüstarbeit in Tätigkeiten, die bei stehender Maschine erfolgen müssen, und solche, die während des Laufs vorbereitet werden können. Werden Letztere aus dem Rüstvorgang herausgelöst, verkürzt sich die Zeit, in der die Maschine keine Teile fertigt.",
      },
      {
        question: "Wie organisieren Sie die Wartung?",
        answer: "Wartung ist ein geplanter Arbeitsschritt (TPM). Da die Maschinengenauigkeit eine Eingangsgröße der Fertigung ist, erzeugt eine verzögerte Wartung unmittelbar das Risiko eines Toleranzverlusts.",
      },
      {
        question: "Was geschieht, wenn eine Abweichung auftritt?",
        answer: "Der Kaizen- und Korrekturmaßnahmenprozess wird durchlaufen: Auf derselben Aufspannung wird nicht weitergefertigt, bis die Grundursache gefunden ist, und die durchgeführte Korrektur wird dokumentiert.",
      },
    ],
    comparisonTables: [
      {
        title: "Verlustart und passende Methode",
        description: "In der Lean Production hat jede Verlustart ihr eigenes Werkzeug",
        headers: ["Verlustart", "Wo sie sichtbar wird", "Angewandte Methode", "Nachweis"],
        rows: [
          ["Rüstzeit", "Vorbereitung bei stehender Maschine", "SMED + Standard-Rüstanweisung", "Rüstfreigabe"],
          ["Suchen und Vorbereiten", "Suche nach Werkzeugen, Vorrichtungen, Lehren", "5S", "Ordnungsstandard"],
          ["Umlaufbestand", "Teile, die zwischen Arbeitsgängen warten", "Kanban", "Flussprotokoll"],
          ["Ungeplanter Stillstand", "Wartezeit nach einem Ausfall", "TPM — geplante Wartung", "Wartungsprotokoll"],
          ["Wiederkehrender Fehler", "Dieselbe Abweichung tritt erneut auf", "Kaizen — Ursachenanalyse", "Protokoll der Korrekturmaßnahmen"],
        ],
      },
      {
        title: "Trennung der Rüstarbeit (SMED)",
        description: "Auf welcher Seite eine Tätigkeit erfolgt, bestimmt, wie lange die Maschine stillsteht",
        headers: ["Tätigkeit", "Muss die Maschine stehen?", "Wie sie verkürzt wird"],
        rows: [
          ["Werkzeugvorbereitung und Voreinstellung", "Nein", "Vorbereitung während des vorherigen Auftrags"],
          ["Vorrichtungsmontage", "Ja", "Schnellspannung und fester Bezug"],
          ["Programm laden und prüfen", "Nein", "Simulation wird vorab abgeschlossen"],
          ["Nullpunkt setzen und Bezüge antasten", "Ja", "Eine Standard-Bezugsfläche wird verwendet"],
          ["Erstmusterprüfung", "Ja", "Der Prüfplan liegt vorab bereit"],
        ],
      },
    ],
  },
  "havacilik-uzay": {
    categoryLabel: "Hochtechnologie",
    title: "Luft- und Raumfahrt",
    metaTitle: "Teilefertigung für Luft- und Raumfahrt | Ti- & Inconel-Zerspanung | Mas Technic",
    metaDescription: "Zerspanung von Titan Ti6Al4V, Inconel 718 und Luftfahrt-Aluminium für die Luft- und Raumfahrt. Prüfplan, Erstmusterprüfung und Rückverfolgbarkeit je Los.",
    description: "Wir fertigen Triebwerkskomponenten, Strukturteile und Avionikgehäuse für die Luft- und Raumfahrt. Rückverfolgbare, an einen Prüfplan gebundene Fertigung in schwer zerspanbaren Legierungen.",
    content: [
      "Wir fertigen Triebwerkskomponenten, Strukturteile (Halter, Beschläge, Rippen) und Avionikgehäuse für die Luft- und Raumfahrt. Titan Ti6Al4V, Inconel 718 und Luftfahrt-Aluminiumlegierungen (7075-T6, 2024-T3) sind Werkstoffe, die Wärme in die Schneide leiten, die Standzeit verkürzen und empfindlich auf Spannkräfte reagieren.",
      "Anforderungen an Sonderprozesse — chemische Behandlungen (Eloxieren, Passivieren, Chromatieren), zerstörungsfreie Prüfung, Wärmebehandlung (Ausscheidungshärten, Spannungsarmglühen) und Oberflächenbeschichtung — werden nach Projektspezifikation geplant und gemeinsam mit der Lieferkette umgesetzt. Die Parameter werden eingefroren; eine Änderung erfordert eine erneute Validierung.",
      "Unser Qualitätsansatz: Erstmusterprüfung, Maß- und Sichtprüfung der im Prüfplan festgelegten Merkmale, Messung der Form- und Lagetoleranzen (GD&T), Abgleich der Werkstoffspezifikation (AMS, ASTM) mit dem Losprotokoll sowie Rückverfolgbarkeit je Los. Das Dokumentationsformat richtet sich nach der Kundenspezifikation.",
      "Auf unseren 5-Achs-Bearbeitungszentren bearbeiten wir komplexe Luftfahrtgeometrien in einer Aufspannung; unser Standard-Arbeitsbereich liegt bei ±0,01 mm. Werkzeugwege werden per Simulation verifiziert, und die Serienfertigung beginnt erst nach Freigabe der Erstmusterprüfung.",
    ],
    features: [
      "Erfahrung mit schwer zerspanbaren Legierungen — Ti6Al4V, Inconel 718",
      "Planung von Sonderprozessen — chemische Behandlung, ZfP, Wärmebehandlung",
      "Titan- & Inconel-Zerspanung — 5-Achs, HSC, Sonderwerkzeuge",
      "Erstmusterprüfung — keine Serie ohne Freigabe",
      "Rückverfolgbarkeit — Los- und Schmelzennachweis",
      "Eingefrorener Prozess — freigegebene Prozessparameter sind festgelegt",
    ],
    technicalSpecs: [
      { label: "Managementsystem", value: "ISO 9001:2015" },
      { label: "ZfP", value: "Nach Spezifikation geplant" },
      { label: "Rückverfolgbarkeit", value: "Los- und Schmelzennachweis" },
      { label: "Werkstoffe", value: "Ti6Al4V, Inconel 718, Al 7075" },
      { label: "Standardtoleranz", value: "±0,01mm" },
      { label: "Erstteil", value: "Nach Prüfplan" },
    ],
    processSteps: ["Vertragsprüfung & Bestellung", "Werkstoffbeschaffung (nach Spezifikation)", "CAM-Programmierung & Simulation", "5-Achs-CNC-Bearbeitung", "ZfP-Prüfung", "KMG & EMPB", "Oberflächenbehandlung", "Endprüfung & Verpackung"],
    advantages: [
      "Werkzeug- und Parameterdisziplin bei schwer zerspanbaren Legierungen",
      "Rückverfolgbarkeit auf Basis von Los- und Schmelzennachweisen",
      "Expertise in der Zerspanung von Ti6Al4V und Inconel 718",
      "Komplexe Luftfahrtgeometrien in einer 5-Achs-Aufspannung",
      "Erstmusterprüfprotokoll und Übergabe der Messdokumentation",
      "Freigegebene Parameter durch eingefrorenen Prozess festgelegt",
    ],
    materials: [
      { name: "Titan", grade: "Ti6Al4V (Grade 5)", properties: "Leicht, biokompatibel, 950 MPa Zugfestigkeit" },
      { name: "Inconel", grade: "718", properties: "Hochtemperaturfest, 1034 MPa, Turbinenteile" },
      { name: "Aluminium", grade: "7075-T6", properties: "Hochfest, Luftfahrt-Strukturbauteile" },
      { name: "Aluminium", grade: "2024-T3", properties: "Plattiertes Luftfahrtblech, ermüdungsbeständig" },
    ],
    faq: [
      {
        question: "Über welche Qualitätszertifikate verfügen Sie?",
        answer: "Wir verfügen über Managementsystem-Zertifikate nach ISO 9001:2015 und ISO 14001:2015. Erfordert Ihr Projekt einen anderen Standard, bewerten wir dies gemeinsam in der technischen Prüfung.",
      },
      {
        question: "Können Sie Titan zerspanen?",
        answer: "Ja, wir sind auf die Zerspanung von Titan Ti6Al4V (Grade 5) und Grade 2 spezialisiert. Mit Sonderwerkzeugen, einer Strategie mit niedriger Schnittgeschwindigkeit und hohem Vorschub sowie gezieltem Kühlmittelmanagement erzielen wir optimale Ergebnisse.",
      },
      {
        question: "Führen Sie eine Erstmusterprüfung durch?",
        answer: "Ja. Für jedes neue Teil und jede Revision wird eine Erstmusterprüfung durchgeführt und dokumentiert; das Dokumentationsformat stimmen wir gemäß Ihrer Spezifikation mit Ihnen ab.",
      },
      {
        question: "Wie werden Sonderprozesse abgewickelt?",
        answer: "Sonderprozesse wie chemische Behandlung, zerstörungsfreie Prüfung und Wärmebehandlung werden nach Projektspezifikation geplant und gemeinsam mit der Lieferkette umgesetzt. Die Parameter werden eingefroren; eine Änderung erfordert eine erneute Validierung.",
      },
    ],
    comparisonTables: [
      {
        title: "Leistungsvergleich von Luftfahrtwerkstoffen",
        description: "Typische Literaturwerte; maßgeblich für die Auslegung ist das Werkstoffzeugnis. Keine Angabe zur Firmenkapazität.",
        headers: ["Werkstoff", "Zugfestigkeit", "Dichte", "Max. Temperatur", "Korrosionsbeständigkeit", "Kosten", "Typische Anwendung"],
        rows: [
          ["Al 7075-T6", "572 MPa", "2,81 g/cm³", "150°C", "Gut (mit Eloxierung)", "$$", "Strukturhalter, Rippe, Beschlag"],
          ["Ti6Al4V (Gr5)", "950 MPa", "4,43 g/cm³", "400°C", "Ausgezeichnet", "$$$$", "Triebwerk, Fahrwerk, Verbindungselemente"],
          ["Inconel 718", "1034 MPa", "8,19 g/cm³", "700°C", "Ausgezeichnet", "$$$$$", "Turbine, Brennkammer, Abgassystem"],
          ["SS 15-5PH", "1000 MPa", "7,78 g/cm³", "316°C", "Sehr gut", "$$$", "Aktuator, Ventil, Struktur"],
        ],
      },
    ],
  },
  "savunma-sanayi": {
    categoryLabel: "Hochtechnologie",
    title: "Verteidigung",
    metaTitle: "Teilefertigung für die Verteidigung | Panzerstahl und Sonderlegierungen | Mas Technic",
    metaDescription: "Zerspanung von Panzerstahl, Titan und Sonderlegierungen für die Verteidigungsindustrie. Los- und Schmelzenrückverfolgbarkeit, an den Prüfplan gebundene Prüfung.",
    description: "Präzisionsteilefertigung für die Verteidigungsindustrie. An einen Prüfplan gebundene Fertigung in schwer zerspanbaren Werkstoffen mit Rückverfolgbarkeit je Los.",
    content: [
      "Wir fertigen kritische Komponenten für Land-, See- und Luftplattformen: Waffensystemkomponenten, optronische Gehäuse, Panzerungsteile und Komponenten für Kommunikationssysteme. Die Spezifikations- und Normanforderungen Ihres Projekts lesen wir gemeinsam in der technischen Prüfung.",
      "Bei Verteidigungsprojekten wird zu Projektbeginn schriftlich vereinbart, wie technische Daten ausgetauscht und unter welchen Bedingungen sie behandelt werden. Die von Ihrer Spezifikation geforderten Bedingungen bewerten wir gemeinsam in der Angebotsphase.",
      "Mit unserer Fähigkeit zur Bearbeitung von Panzerstahl (Armox 500T, Hardox 600), Luftfahrt-Titan (Ti6Al4V), hochfesten Stählen (4340, 300M) und Sonderlegierungen (Inconel, Stellite) erfüllen wir die anspruchsvollsten Werkstoffanforderungen der Verteidigungsindustrie.",
      "Der Umfang der zerstörungsfreien Prüfung (RT, UT, PT, MT) wird im Prüfplan nach Spezifikation festgelegt, und die Ergebnisse werden dokumentiert. Die Rückverfolgbarkeit je Los läuft zusammen mit der Konfigurations- und Revisionsverfolgung.",
    ],
    features: [
      "Spezifikationsprüfung — der Projektstandard wird gemeinsam in der technischen Prüfung bewertet",
      "Konfigurationsverfolgung — Versions- und Revisionsnachweis",
      "Datenaustausch — Bedingungen werden zu Projektbeginn schriftlich festgelegt",
      "Zerstörungsfreie Prüfung — RT, UT, PT, MT; Umfang im Plan festgelegt",
      "Zerspanung ballistischer Werkstoffe — Armox 500T, Hardox 600",
      "Konfigurationsmanagement — Versions- und Änderungsverfolgung",
    ],
    technicalSpecs: [
      { label: "Managementsystem", value: "ISO 9001:2015" },
      { label: "Spezifikation", value: "Projektbezogen geprüft" },
      { label: "ZfP", value: "RT, UT, PT, MT (nach Spezifikation)" },
      { label: "Werkstoffe", value: "Armox, Ti, 4340, 300M" },
      { label: "Bedingungen", value: "Schriftlich zu Projektbeginn" },
      { label: "Rückverfolgbarkeit", value: "Los- und Schmelzennachweis" },
    ],
    processSteps: ["Festlegung der Projektbedingungen", "Technische Prüfung & Angebot", "Werkstoffbeschaffung (nach Spezifikation)", "Fertigung", "Zerstörungsfreie Prüfung", "Konfigurationsverifizierung", "Sichere Verpackung & Lieferung"],
    advantages: [
      "Die Projektspezifikation wird in der technischen Prüfung Zeile für Zeile gelesen",
      "Bedingungen für technische Daten werden zu Projektbeginn schriftlich festgelegt",
      "Expertise in der Zerspanung von Panzerstahl und Sonderlegierungen",
      "Der Umfang der zerstörungsfreien Prüfung ist im Prüfplan festgelegt",
      "Rückverfolgbarkeit auf Basis von Los- und Schmelzennachweisen",
      "Konfigurationsmanagement und Änderungssteuerung",
    ],
    faq: [
      {
        question: "Wie werden meine technischen Daten behandelt?",
        answer: "Wie technische Daten ausgetauscht und unter welchen Bedingungen sie behandelt werden, wird zu Projektbeginn schriftlich vereinbart. Die von Ihrer Spezifikation geforderten Bedingungen bewerten wir gemeinsam in der Angebotsphase.",
      },
      {
        question: "Können Sie meine Projektspezifikation erfüllen?",
        answer: "Wir lesen Ihre Spezifikation in der technischen Prüfung Zeile für Zeile und benennen klar, welche Anforderungen wir mit unseren aktuellen Kompetenzen erfüllen und welche die Lieferkette erfordern.",
      },
      {
        question: "Können Sie ballistische Werkstoffe zerspanen?",
        answer: "Ja, wir können hochharte Panzerstähle wie Armox 500T, Hardox 600 und 300M CNC-bearbeiten.",
      },
    ],
  },
  robotik: {
    categoryLabel: "Hochtechnologie",
    title: "Robotik & Automatisierung",
    metaTitle: "Teilefertigung für Robotik & Automatisierung | ±0,01 mm | Mas Technic",
    metaDescription: "Präzise mechanische Komponenten für Industrieroboter, Cobots und Automatisierungssysteme. Aktuatorgehäuse, Gelenkteile, Greifer. Al 7075, SS 316L, ±0,01 mm.",
    description: "Präzise mechanische Komponenten für Industrieroboter, Cobots und Automatisierungssysteme. Aktuatorgehäuse, Gelenkteile und Greiferkomponenten.",
    content: [
      "Wir fertigen präzise mechanische Komponenten für Industrieroboter, kollaborative Roboter (Cobots) und kundenspezifische Automatisierungssysteme: Aktuatorgehäuse, Gelenkteile, Getriebegehäuse, Greiferkomponenten und Sensorhalter.",
      "Bei Roboterkomponenten zählt nicht ein einzelnes Maß, sondern die Lage der Achsen zueinander: Konzentrizität und Rechtwinkligkeit beeinflussen direkt die Wiederholgenauigkeit des Arms. Deshalb werden Bezugsflächen in einer Aufspannung bearbeitet und vom selben Bezug aus gemessen.",
      "Wir planen flexibel vom Prototyp zur Serie. Jedes Robotikprojekt beginnt mit einer DFM-Analyse, wird mit einem Funktionsprototyp validiert und geht nach der Musterfreigabe in die Serienfertigung.",
    ],
    features: [
      "Aktuatorgehäuse — Al 7075, SS 316L, ±0,01 mm",
      "Gelenkteile — hohe Präzision, geringes Gewicht",
      "Greiferkomponenten — kundenspezifische Geometrie, Funktionsfläche",
      "Getriebegehäuse — konzentrische Präzision, thermische Stabilität",
      "Sensorhalter — Mikropräzision, Vibrationsbeständigkeit",
      "Vom Prototyp zur Serie — DFM → Prototyp → Musterfreigabe → Serie",
    ],
    technicalSpecs: [
      { label: "Standardtoleranz", value: "±0,01mm" },
      { label: "Werkstoff", value: "Al 7075, SS 316L, POM" },
      { label: "Konzentrizität", value: "Vom Bezug aus gemessen" },
      { label: "Gewichtsopt.", value: "Topologieoptimierung" },
      { label: "GD&T", value: "Im Prüfplan" },
    ],
    advantages: [
      "Komplexe Robotergeometrien in einer 5-Achs-Aufspannung",
      "Leichte, hochfeste Komponenten aus Al 7075",
      "Bezugsflächen in einer Aufspannung bearbeitet und vom selben Bezug aus gemessen",
      "Gewichts- und Kostenoptimierung durch DFM-Analyse",
      "Reibungsloser Übergang vom Prototyp zur Serienfertigung",
      "Konzentrizität und Rechtwinkligkeit sind im Prüfplan festgelegt",
    ],
    faq: [
      {
        question: "Welche Toleranzen halten Sie bei Roboterkomponenten ein?",
        answer: "Unser Standard-Arbeitsbereich liegt bei ±0,01mm. Form- und Lagetoleranzen wie Konzentrizität und Rechtwinkligkeit werden zusammen mit dem Bezugssystem bewertet und im Prüfplan festgelegt.",
      },
      {
        question: "Bieten Sie Leichtbau-Werkstofflösungen an?",
        answer: "Ja, wir bieten ein hohes Festigkeits-Gewichts-Verhältnis mit Al 7075-T6, Gewichtsreduzierung durch Topologieoptimierung sowie Hochleistungskunststoffe wie PEEK.",
      },
      {
        question: "Sind Sie für die Serienfertigung aufgestellt?",
        answer: "Ja. In der automatisierten CNC-Serienfertigung wird mit Stangenlader und Palettensystem eine unterbrechungsfreie Bearbeitung erreicht; Losgröße und Lieferplan werden gemeinsam in der Angebotsphase festgelegt.",
      },
    ],
  },
  otomotiv: {
    categoryLabel: "Serienfertigung",
    title: "Automobil",
    metaTitle: "Teilefertigung für die Automobilindustrie | Wiederholgenaue Serie | Mas Technic",
    metaDescription: "Motor-, Getriebe-, Brems- und Fahrwerkskomponenten für die Automobilindustrie. Wiederholgenaue, an den Prüfplan gebundene Serienfertigung mit Los-Rückverfolgbarkeit.",
    description: "Wiederholgenaue Serienteilefertigung für die automobile Lieferkette: Standard-Rüstung, an den Prüfplan gebundene Messung und Rückverfolgbarkeit je Los.",
    content: [
      "Für die Automobilbranche fertigen wir Motorkomponenten (Zylinderköpfe, Kurbelwellen, Nockenwellen), Getriebeteile (Zahnräder, Wellen, Gehäuse), Bremssystemkomponenten (Bremssättel, Scheiben, Kolben) und Fahrwerkskomponenten (Querlenker, Kugelgelenke, Radbolzen).",
      "Der Weg vom Konzept zur Serienfertigung führt über Freigabepunkte: Risikoanalyse, Prüfplan, Pilotfertigung und Musterfreigabe. Den von Ihrer Spezifikation geforderten Dokumentationsumfang legen wir gemeinsam in der Angebotsphase fest.",
      "Im Automobilbereich zählt nicht die Toleranz eines einzelnen Teils, sondern die Konstanz zwischen den Losen. Verschleißempfindliche Maße werden durch prozessbegleitende Prüfungen überwacht, die Messergebnisse dokumentiert, und zeigt sich ein Drifttrend, wird der Prozess korrigiert, nicht das Teil.",
      "Die Qualitätskultur der Automobilindustrie leben wir mit der 8D-Problemlösungsmethode, Poka-Yoke-Fehlervermeidungssystemen und dem Kaizen-Ansatz der kontinuierlichen Verbesserung.",
    ],
    features: [
      "Standard-Rüstung — Konstanz zwischen den Losen",
      "Musterfreigabe — keine Serie vor Freigabe des Erstteils",
      "APQP — Produktqualitätsvorausplanung",
      "Prozessbegleitende Prüfung — verschleißempfindliche Maße werden überwacht",
      "Automatischer Werkzeugwechsel — unterbrechungsfreie Bearbeitung bei langen Losen",
      "Los-Rückverfolgbarkeit — Schmelzen- und Losnachweis",
    ],
    technicalSpecs: [
      { label: "Managementsystem", value: "ISO 9001:2015" },
      { label: "Freigabe", value: "Musterfreigabe" },
      { label: "Prozessbegl. Prüfung", value: "Driftanfällige Maße" },
      { label: "Rüsten", value: "Standardverfahren" },
      { label: "Prüfung", value: "Nach Prüfplan" },
      { label: "Rückverfolgbarkeit", value: "Los- und Schmelzennachweis" },
    ],
    processSteps: ["APQP-Planung", "FMEA-Analyse", "Prüfplan", "Pilotfertigung & MSA", "Musterfreigabe", "Serienfertigung", "SPC-Überwachung", "Kontinuierliche Verbesserung"],
    advantages: [
      "Die Serienfertigung beginnt erst nach Musterfreigabe",
      "Der Dokumentationsumfang richtet sich nach der Spezifikation",
      "Verschleißempfindliche Maße werden prozessbegleitend überwacht",
      "Konstanz zwischen den Losen durch eine Standard-Rüstanweisung",
      "8D-Problemlösung und Poka-Yoke-Fehlervermeidung",
      "Prüfplan, Mess- und Losnachweise in der Lieferdokumentation",
    ],
    faq: [
      {
        question: "Über welche Qualitätszertifikate verfügen Sie?",
        answer: "Wir verfügen über Managementsystem-Zertifikate nach ISO 9001:2015 und ISO 14001:2015. Fordert die Spezifikation Ihres Kunden einen branchenspezifischen Standard, bewerten wir dies offen in der Angebotsphase.",
      },
      {
        question: "Welche Dokumentation liefern Sie?",
        answer: "Prüfplan, Messprotokolle, der Los-/Schmelzennachweis des Werkstoffs und Musterteile werden standardmäßig bereitgestellt. Zusätzliche, von Ihrer Spezifikation geforderte Dokumente stimmen wir in der Angebotsphase ab.",
      },
      {
        question: "Wie sichern Sie die Konstanz zwischen den Losen?",
        answer: "Durch eine Standard-Rüstanweisung, Erstmusterfreigabe und an den Prüfplan gebundene prozessbegleitende Prüfungen. Verschleißempfindliche Maße werden in einem eigenen Schritt überwacht und die Ergebnisse dokumentiert.",
      },
      {
        question: "Welche Stückzahlen fertigen Sie?",
        answer: "Wir arbeiten vom Prototyp bis zur Serienfertigung. Losgröße und Lieferplan werden nach erfolgter Kapazitätsplanung mit dem Angebot festgelegt.",
      },
    ],
  },
  medikal: {
    categoryLabel: "Serienfertigung",
    title: "Medizin- & Biomedizintechnik",
    metaTitle: "Teilefertigung für die Medizintechnik | Ti Gr5, SS 316L, PEEK | Mas Technic",
    metaDescription: "Präzisionszerspanung von Medizinproduktkomponenten, chirurgischen Instrumenten und Implantatteilen. Ti Grade 5, SS 316L, CoCrMo, PEEK; Los-Rückverfolgbarkeit und Messprotokolle.",
    description: "Präzisionszerspanung von Medizinproduktkomponenten, chirurgischen Instrumenten und Implantatteilen. Teile mit anspruchsvollen Werkstoffen, engen Toleranzen und verpflichtender Rückverfolgbarkeit.",
    content: [
      "Wir fertigen Komponenten für Medizinprodukte, chirurgische Handinstrumente und Implantatteile: Implantatgeometrien wie Knochenschrauben, Platten und Stäbe, Handinstrumente wie Pinzetten und Scheren, orthopädische Komponenten sowie Teile für Laborgeräte.",
      "Die Werkstoffe dieser Branche sind nicht leicht zu zerspanen. Ti Grade 5 (Ti6Al4V) leitet Wärme in die Schneide und verkürzt die Standzeit; SS 316L bildet klebende Späne; CoCrMo wirkt abrasiv; und PEEK sowie UHMWPE weisen eine hohe Wärmeausdehnung auf, sodass die temperaturbedingte Maßänderung im Moment der Messung berücksichtigt werden muss.",
      "Bei den meisten medizinischen Teilen ist der Oberflächenzustand die Funktion selbst. Elektropolieren und Passivieren senken nicht nur die Oberflächenrauheit, sondern entfernen auch freies Eisen und verändern so das Korrosionsverhalten; welche Behandlung angewendet wird, richtet sich nach Werkstoff und Spezifikation.",
      "Die Rückverfolgbarkeit erfolgt über den Los- und Schmelzennachweis. Werkstoffzeugnis und Messprotokoll werden auf Wunsch der Lieferdokumentation beigefügt; zusätzliche, von Ihrer Spezifikation geforderte Dokumentation stimmen wir in der Angebotsphase ab.",
      "Medizinische Schrauben, Stifte und Verbinder mit kleinem Durchmesser können durch Mikrozerspanung gefertigt werden; für lange, schlanke Geometrien wird das Langdrehen bevorzugt, da es die Durchbiegung begrenzt. Der Arbeitsbereich wird nach Prüfung der Teilegeometrie und des Prozessplans im Angebot angegeben.",
    ],
    features: [
      "Zerspanung biokompatibler Werkstoffe — Ti Gr5, SS 316L, CoCrMo, PEEK, UHMWPE",
      "Mikrozerspanung — Schrauben und Stifte mit kleinem Durchmesser",
      "Langdrehen — Kontrolle der Durchbiegung bei langen, schlanken Teilen",
      "Elektropolieren und Passivieren — Oberfläche und Korrosionsverhalten",
      "Los-Rückverfolgbarkeit — Schmelzen- und Losnachweis",
      "Messprotokoll — nach Prüfplan, in der Lieferdokumentation",
    ],
    technicalSpecs: [
      { label: "Managementsystem", value: "ISO 9001:2015" },
      { label: "Werkstoff", value: "Ti Gr5, SS 316L, CoCrMo, PEEK" },
      { label: "Standardtoleranz", value: "±0,01mm" },
      { label: "Oberfläche", value: "Elektropolieren / Passivieren" },
      { label: "Rückverfolgbarkeit", value: "Los- und Schmelzennachweis" },
      { label: "Dokumentation", value: "Nach Spezifikation" },
    ],
    processSteps: ["Konstruktionsprüfung", "Werkstoffbeschaffung und Losnachweis", "CNC- / Mikrozerspanung", "Oberflächenbehandlung (Elektropolieren / Passivieren)", "Messung nach Prüfplan", "Reinigung und Verpackung", "Übergabe des Messprotokolls"],
    advantages: [
      "Werkzeug- und Parameterdisziplin bei schwer zerspanbaren biokompatiblen Werkstoffen",
      "Fertigung medizinischer Teile mit kleinem Durchmesser",
      "Kontrolle der Durchbiegung bei langen, schlanken Teilen durch Langdrehen",
      "Oberflächenbehandlung nach Werkstoff und Spezifikation gewählt",
      "Rückverfolgbarkeit über Los- und Schmelzennachweise",
      "Zusätzlicher Dokumentationsbedarf wird in der Angebotsphase geklärt",
    ],
    faq: [
      {
        question: "Über welche Qualitätszertifikate verfügen Sie?",
        answer: "Wir verfügen über Managementsystem-Zertifikate nach ISO 9001:2015 und ISO 14001:2015. Erfordert Ihr Projekt einen branchenspezifischen Standard, bewerten wir dies offen in der Angebotsphase.",
      },
      {
        question: "Mit welchen biokompatiblen Werkstoffen arbeiten Sie?",
        answer: "Wir zerspanen Ti Grade 5 (Ti6Al4V), SS 316L, CoCrMo, PEEK und UHMWPE. Das Werkstoffzeugnis stammt vom Lieferanten und wird auf Wunsch der Lieferdokumentation beigefügt.",
      },
      {
        question: "Führen Sie Oberflächenbehandlungen durch?",
        answer: "Elektropolieren und Passivieren sind möglich. Welche Behandlung geeignet ist, richtet sich nach dem Werkstoff und Ihrer Spezifikation.",
      },
      {
        question: "Wie stellen Sie die Rückverfolgbarkeit sicher?",
        answer: "Der Werkstoff wird über seinen Los- und Schmelzennachweis verfolgt; die im Prüfplan festgelegten Merkmale werden gemessen und das Messprotokoll der Lieferdokumentation beigefügt.",
      },
      {
        question: "Können Sie sehr kleine Teile fertigen?",
        answer: "Ja. Schrauben, Stifte und Verbinder mit kleinem Durchmesser sind möglich; für lange, schlanke Geometrien wird das Langdrehen bevorzugt. Der Arbeitsbereich wird nach Prüfung der Zeichnung im Angebot angegeben.",
      },
    ],
  },
};
