import type { ServiceText } from "@/content/en/types";

export const part4: Record<string, ServiceText> = {
  "kitting-paketleme": {
    categoryLabel: "Montage & Fügen",
    title: "Kitting & Verpackung",
    description: "Kundenspezifisches Kitting, Etikettierung und Schutzverpackung. Steigern Sie die Effizienz Ihrer Lieferkette.",
    content: [
      "Wir liefern Ihre Produkte sicher – mit Vakuumverpackung (Schutz vor Feuchtigkeit und Staub), ESD-/Antistatikverpackung (elektronische Bauteile), Schaumstoffpolsterung (empfindliche Teile) und Holzkisten (schwere und wertvolle Teile).",
      "Wir bieten eine umfassende Etikettierung mit Barcode-Etiketten, RFID-Tags, kundenspezifischem Etikettendesign und Mehrsprachigkeit. Unser Verpackungsservice umfasst ESD-Schutzverpackungen der Klasse MIL-PRF-81705, VCI- und Trockenmittelschutz sowie Lieferung wahlweise DDP oder FCA.",
    ],
    features: [
      "Vakuumverpackung — Schutz vor Feuchtigkeit und Staub",
      "ESD (antistatisch) — Für elektronische Bauteile",
      "Schaumstoffschutz — Für empfindliche Teile",
      "Holzkiste — Für schwere und wertvolle Teile",
    ],
    technicalSpecs: [
      { label: "ESD-Schutz", value: "MIL-PRF-81705" },
      { label: "Etikettierung", value: "Barcode + QR + RFID" },
      { label: "Schutz", value: "VCI, Trockenmittel" },
      { label: "Lieferung", value: "DDP / FCA" },
    ],
    processSteps: ["Erstellung der Kitliste", "Kommissionieren & Zählen", "Schutzverpackung", "Etikettierung", "Versand"],
    advantages: [
      "ESD-Schutz nach MIL-PRF-81705",
      "Vielfältige Etikettierungsoptionen einschließlich RFID",
      "VCI- und Trockenmittelschutz",
      "Flexible Lieferoptionen DDP/FCA",
    ],
    comparisonTables: [
      {
        title: "Verpackungsarten und Schutzstufen",
        headers: ["Verpackungsart", "Schutzstufe", "Feuchtigkeitsschutz", "Stoßschutz", "Kosten", "Geeignete Teile"],
        rows: [
          ["PE-Beutel", "Basis", "Gering", "Keiner", "$", "Allgemein, Kleinteile"],
          ["Vakuumbeutel", "Hoch", "Ausgezeichnet", "Gering", "$$", "Korrosionsempfindliches Metall"],
          ["ESD-Beutel", "Hoch", "Gut", "Gering", "$$", "Elektronik, Leiterplatten"],
          ["Schaumstoffeinlage", "Sehr hoch", "Mittel", "Ausgezeichnet", "$$$", "Empfindliche, zerbrechliche Teile"],
          ["VCI-Papier/-Folie", "Hoch", "Ausgezeichnet", "Gering", "$$", "Langzeitlagerung von Metall"],
          ["Holzkiste", "Maximal", "Gut", "Sehr hoch", "$$$$", "Schwer, groß, wertvoll"],
        ],
      },
    ],
  },
  "kaynakli-imalat": {
    categoryLabel: "Montage & Fügen",
    title: "Schweißkonstruktion",
    description: "Fügen von Metallteilen durch WIG-, MIG/MAG- und Widerstandsschweißen. Qualitätskontrolle über eine schriftliche Schweißanweisung und zerstörungsfreie Prüfung.",
    content: [
      "Wir fügen Metallteile durch WIG-Schweißen (Al, Stahl, Ti; Präzisionsanwendungen), MIG/MAG-Schweißen (Stahl, Al; schnelle Fertigung) und Widerstandsschweißen (Stahl; Punktschweißen). Die schweißbare Dicke hängt vom Werkstoff und von der Nahtgestaltung ab.",
      "Geschweißt wird nach einer schriftlichen Schweißanweisung (WPS); die verwendeten Parameter und Zusatzwerkstoffe werden je Auftrag dokumentiert. Sofern die Spezifikation es fordert, werden die Nähte mittels zerstörungsfreier Prüfung (RT, UT, PT oder MT) geprüft und die Ergebnisse den Lieferunterlagen beigefügt.",
    ],
    features: [
      "WIG-Schweißen — Al, Stahl, Ti; Präzisionsanwendungen",
      "MIG/MAG-Schweißen — Stahl, Al; schnelle Fertigung",
      "Widerstandsschweißen — Stahl; Punktschweißen",
      "Schriftliche Schweißanweisung — Schweißen nach WPS",
    ],
    technicalSpecs: [
      { label: "Verfahren", value: "Schweißen nach WPS" },
      { label: "Dicke", value: "Gemäß Nahtgestaltung" },
      { label: "ZfP", value: "RT, UT, PT, MT (gemäß Spezifikation)" },
      { label: "Werkstoffe", value: "Al, Edelstahl, Ti, Ni" },
    ],
    processSteps: ["Schweißanweisung (WPS)", "Werkstoff- & Gerätevorbereitung", "Schweißen", "ZfP-Prüfung", "Qualitätsbericht"],
    advantages: [
      "Fertigung nach schriftlicher Schweißanweisung (WPS)",
      "ZfP-Prüfung gemäß Spezifikation",
      "Prüf- und Messaufzeichnungen für Schweißnähte",
      "Kompetenz in WIG-, MIG/MAG- und Widerstandsschweißen",
    ],
    comparisonTables: [
      {
        title: "Schweißverfahren im Vergleich",
        description: "Allgemeiner Vergleich der Schweißverfahren; keine Auflistung unserer Ausrüstung oder Kapazität.",
        headers: ["Verfahren", "Werkstoffdicke", "Geschwindigkeit", "Wärmeeintrag", "Verzug", "Anwendung"],
        rows: [
          ["WIG (GTAW)", "0,5-10mm", "Gering", "Gering bis mittel", "Gering", "Präzision, dünne Bleche, Al/Ti"],
          ["MIG/MAG (GMAW)", "1-20mm", "Hoch", "Mittel bis hoch", "Mittel", "Serienfertigung, Stahl/Al"],
          ["Widerstand (Punkt)", "0,2-3mm", "Sehr hoch", "Gering (lokal)", "Sehr gering", "Blech, Automobil"],
          ["Laserschweißen", "0,1-8mm", "Sehr hoch", "Sehr gering", "Minimal", "Präzision, Medizintechnik, Elektronik"],
          ["Elektronenstrahl", "0,5-100mm", "Mittel", "Sehr gering", "Minimal", "Luft- und Raumfahrt, Kerntechnik"],
          ["Rührreibschweißen", "1-50mm", "Mittel", "Gering", "Gering", "Al-Legierungen, Raumfahrt"],
        ],
      },
      {
        title: "ZfP-Verfahren (zerstörungsfreie Prüfung)",
        headers: ["Verfahren", "Kürzel", "Erkennt", "Empfindlichkeit", "Geschwindigkeit", "Norm"],
        rows: [
          ["Durchstrahlungsprüfung", "RT", "Innere Fehler, Porosität", "Hoch", "Langsam", "EN ISO 17636"],
          ["Ultraschallprüfung", "UT", "Innere Risse, Delamination", "Sehr hoch", "Mittel", "EN ISO 17640"],
          ["Eindringprüfung", "PT", "Oberflächenrisse", "Hoch", "Mittel", "EN ISO 3452"],
          ["Magnetpulverprüfung", "MT", "Risse an/nahe der Oberfläche", "Hoch", "Schnell", "EN ISO 17638"],
          ["Sichtprüfung", "VT", "Oberflächenfehler", "Mittel", "Sehr schnell", "EN ISO 17637"],
        ],
      },
    ],
  },
  "makine-parkuru": {
    categoryLabel: "Fertigungsinfrastruktur",
    title: "Maschinenpark",
    metaTitle: "Fertigungskompetenzen | CNC-Fräsen, CNC-Drehen, EDM | Mas Technic",
    metaDescription: "5-Achs-CNC-Fräsen, Drehen mit C-/Y-Achse, Langdrehen, Tieflochbohren und Drahterodieren. Verfahrenswahl passend zur Teilegeometrie.",
    description: "Auf welcher Maschine ein Teil gefertigt wird, entscheiden seine Geometrie und seine Maßkette. Unsere Verfahrensfamilien werden gemeinsam geplant, damit sich diese Entscheidung an den Anforderungen des Teils orientieren kann.",
    content: [
      "Die Fertigungsplanung beginnt beim Teil, nicht bei einer Maschinenliste. Die Anzahl der Aufspannungen, die zu erreichenden Flächen, die Maßkette und das Werkstoffverhalten bestimmen, welche Verfahrensfamilie in welcher Reihenfolge eingesetzt wird.",
      "Simultane 5-Achs-Bearbeitung wird für Geometrien eingesetzt, bei denen mehrere Flächen in einer Aufspannung erreicht werden müssen. Weniger Aufspannungen sparen nicht nur Zeit: Jede neue Aufspannung bringt eine neue Fehlerquelle in die Maßkette, ihre Reduzierung kommt also unmittelbar der Toleranz zugute.",
      "Beim Drehen mit C- und Y-Achse werden Dreh- und Fräsoperationen an rotationssymmetrischen Teilen in einer Aufspannung kombiniert. Das Langdrehen (Swiss-Type) begrenzt bei langen Teilen mit kleinem Durchmesser die Durchbiegung, indem die freie Einspannlänge kurz gehalten wird.",
      "Tieflochbohren, Drahterodieren und Senkerodieren kommen bei Geometrien zum Einsatz, die beim Fräsen nicht erreichbar sind: Kanäle mit großem Länge-Durchmesser-Verhältnis, scharfe Innenecken in harten Werkstoffen, dünnwandige Bereiche.",
      "Die Maschinengenauigkeit ist eine Eingangsgröße der Fertigung, nicht ihr Ergebnis. Sie wird daher durch regelmäßige Prüfungen überwacht, vor kritischen Aufträgen mit einem Testteil bestätigt, und bei einer Abweichung wird der Prozess korrigiert, nicht das Teil.",
    ],
    features: [
      "Simultane 5-Achs-Bearbeitung — mehrseitige Geometrien in einer Aufspannung",
      "3- und 4-Achs-Fräsen — Planflächen, Taschen und Umfangsbearbeitung",
      "CNC-Drehen mit C-/Y-Achse — Drehen und Fräsen rotationssymmetrischer Teile in einer Aufspannung",
      "Langdrehen (Swiss-Type) — lange Teile mit kleinem Durchmesser",
      "Tieflochbohren — Bohrungen mit großem Länge-Durchmesser-Verhältnis",
      "Draht- und Senkerodieren — scharfe Innenecken in harten Werkstoffen",
    ],
    technicalSpecs: [
      { label: "Fräskonfiguration", value: "3-, 4- und 5-Achs" },
      { label: "Drehkonfiguration", value: "C- und Y-Achse, Langdrehen" },
      { label: "Standardtoleranz", value: "±0,01 mm" },
      { label: "Verfahrenswahl", value: "Nach Geometrie und Maßkette" },
      { label: "Genauigkeitsüberwachung", value: "Regelmäßige Prüfung + Testteil" },
      { label: "Prüfung", value: "Messung nach Prüfplan" },
    ],
    processSteps: ["Technische Prüfung", "Verfahrenswahl", "Kapazitätsplanung", "CAM-Programmierung", "Rüsten & Spannen", "CNC-Bearbeitung", "Fertigungsbegleitende Prüfung", "Endprüfung"],
    advantages: [
      "Das Verfahren wird nach der Teilegeometrie gewählt; das Teil wird nicht dem Verfahren angepasst",
      "Die Anzahl der Aufspannungen wird mit Blick auf die Maßkette minimiert",
      "Die Maschinengenauigkeit wird durch regelmäßige Prüfungen und Testteile überwacht",
      "Der Prüfplan für kritische Maße wird vor der Fertigung erstellt",
      "Fräsen, Drehen und Erodieren lassen sich für denselben Auftrag gemeinsam planen",
      "Bei einer Abweichung wird der Prozess korrigiert, nicht das Teil",
    ],
    faq: [
      { question: "Mit welchem Verfahren wird mein Teil gefertigt?", answer: "Das entscheidet die Geometrie: die zu erreichenden Flächen, die Maßkette, das Länge-Durchmesser-Verhältnis und der Werkstoff. Nach der technischen Prüfung teilen wir Ihnen mit dem Angebot mit, welches Verfahren in wie vielen Aufspannungen eingesetzt wird." },
      { question: "Ist eine 3-Achs- oder eine 5-Achs-Bearbeitung nötig?", answer: "Planflächen und einfache Taschen sind auf 3 Achsen wirtschaftlicher. Werden Hinterschnitte, schräge Flächen oder mehrere Flächen in einer Aufspannung benötigt, wird die 5-Achs-Bearbeitung bevorzugt; weniger Aufspannungen kommen der Toleranz zugute." },
      { question: "Lassen sich scharfe Innenecken in harten Werkstoffen herstellen?", answer: "Beim Fräsen ist der Innenradius durch den Werkzeugdurchmesser begrenzt. Für kleinere Ecken wird Draht- oder Senkerodieren eingesetzt." },
      { question: "Wie bestätigen Sie die Maschinengenauigkeit?", answer: "Die Genauigkeit wird durch regelmäßige Prüfungen überwacht und vor kritischen Aufträgen durch die Messung eines Testteils bestätigt. Die Messergebnisse werden dokumentiert." },
      { question: "Wie gehen Sie mit langen, schlanken Teilen um?", answer: "Das Langdrehen begrenzt die Durchbiegung, indem die freie Einspannlänge kurz gehalten wird. Bei Bedarf werden Arbeitsfolge und Abstützung für das Teil neu geplant." },
    ],
    comparisonTables: [
      {
        title: "Anwendungen nach Verfahrensfamilie",
        description: "Welche Verfahrensfamilie für welche Teilegeometrie bevorzugt wird",
        headers: ["Verfahrensfamilie", "Typische Geometrie", "Warum gewählt", "Einschränkung"],
        rows: [
          ["5-Achs-Fräsen", "Mehrseitige Teile mit schrägen Ebenen", "Reduziert Aufspannungen und verkürzt die Maßkette", "Lange Rüst- und Programmierzeit"],
          ["3/4-Achs-Fräsen", "Planflächen, Taschen, Umfangsnuten", "Wirtschaftlich und schnell eingerichtet", "Ungeeignet für Hinterschnitte und schräge Flächen"],
          ["Drehen mit C-/Y-Achse", "Rotationskörper, Wellen mit Querbohrungen", "Kombiniert Drehen und Fräsen in einer Aufspannung", "Nicht für nicht-rotationssymmetrische Geometrien"],
          ["Langdrehen", "Lange Teile mit kleinem Durchmesser", "Verkürzt die freie Länge, begrenzt die Durchbiegung", "Enger Durchmesserbereich"],
          ["Tieflochbohren", "Bohrungen mit großem Länge-Durchmesser-Verhältnis", "Sichert Geradheit und Spanabfuhr", "Bohrungsachse ist eingeschränkt"],
          ["Draht-/Senkerodieren", "Scharfe Innenecken in harten Werkstoffen", "Keine Schnittkraft, bildet die Form ab", "Geringe Abtragsrate"],
        ],
      },
      {
        title: "Genauigkeitsüberwachung",
        description: "Wie die Maschinengenauigkeit überwacht wird",
        headers: ["Wann", "Was geschieht", "Was dokumentiert wird"],
        rows: [
          ["Schichtbeginn", "Bedienerprüfung", "Arbeitsprotokoll"],
          ["Vor einem kritischen Auftrag", "Messung eines Testteils", "Messprotokoll"],
          ["Regelmäßig", "Geometrie- und Genauigkeitsprüfung", "Wartungsprotokoll"],
          ["Bei einer Abweichung", "Prozesskorrektur und erneute Validierung", "Protokoll der Korrekturmaßnahme"],
        ],
      },
    ],
  },
  "malzeme-kutuphanesi": {
    categoryLabel: "Fertigungsinfrastruktur",
    title: "Werkstoffbibliothek",
    metaTitle: "Werkstoffbibliothek | Rückverfolgbare Beschaffung | Mas Technic",
    metaDescription: "Breites Werkstoffspektrum von Aluminium bis Titan und von PEEK bis Inconel. Rückverfolgbare Beschaffung über Chargen- und Schmelzennachweise; Werkstoffzeugnisse auf Anfrage.",
    description: "Ein breites Werkstoffspektrum – von Aluminium bis Titan, von Kunststoffen bis zu Verbundwerkstoffen – passend zu Ihrem Projekt. Werkstoffzeugnisse und Chargennachweise erhalten Sie auf Anfrage.",
    content: [
      "Die Werkstoffbibliothek von Mas Technic umfasst Metalle, Kunststoffe, Verbundwerkstoffe und Sonderlegierungen – von Aluminium in Luftfahrtqualität über Titan in Medizinqualität bis hin zu Hochleistungskunststoffen und Superlegierungen.",
      "Zu unseren Metallen gehören Aluminium (6061, 7075, 5083 — 95-150 HB), Edelstahl (304, 316, 17-4PH — 150-350 HB), Kohlenstoffstahl (1045, 4140, 4340 — 200-350 HB), Titan (Gr2, Gr5 Ti6Al4V — 250-350 HB) sowie Messing/Bronze (C360, C932 — 60-150 HB).",
      "Zu unseren Kunststoffen und Verbundwerkstoffen gehören Acetal (POM — geringe Reibung), Polyamid (PA6, PA66 — Verschleißfestigkeit), PTFE (Chemikalienbeständigkeit), PEEK (hohe Temperatur — Luft- und Raumfahrt/Medizintechnik) und Polycarbonat (PC — Transparenz). An Sonderlegierungen liefern wir Inconel 718 (hohe Temperatur — Turbinen), Hastelloy (Korrosion — chemische Industrie), Kovar (Wärmeausdehnung — Elektronik) und Wolfram (hohe Dichte — Strahlenabschirmung).",
      "Im Wareneingang werden Zeugnis und Werkstoffidentität geprüft, eine Maßkontrolle durchgeführt und der Werkstoff mit Chargen- und Schmelzennummer erfasst. Beschaffungsweg und Lieferzeit richten sich nach der Werkstoffklasse und werden im Angebot angegeben.",
    ],
    features: [
      "Breites Werkstoffspektrum — Metalle, Kunststoffe, Verbundwerkstoffe und Sonderlegierungen",
      "Werkstoffzeugnis — Auf Anfrage",
      "Wareneingangsprüfung — Zeugnis-, Identitäts- und Maßkontrolle",
      "Chargenrückverfolgbarkeit — Lückenlos vom Rohmaterial bis zum Fertigteil",
      "Bestandsverfolgung — Werkstoff- und Chargennachweise",
      "Luftfahrt- & Medizinqualität — Werkstoffauswahl gemäß Spezifikation",
    ],
    technicalSpecs: [
      { label: "Werkstoffgruppen", value: "Metall, Kunststoff, Verbundwerkstoff, Sonderlegierung" },
      { label: "Zeugnis", value: "Auf Anfrage" },
      { label: "Beschaffung", value: "Nach Werkstoffklasse" },
      { label: "Beschaffungszeit", value: "Im Angebot angegeben" },
    ],
    processSteps: ["Bestandsprüfung", "Zeugnisprüfung", "Identitätsprüfung", "Maßkontrolle", "Lagerung", "Chargenverfolgung"],
    advantages: [
      "Technische Unterstützung bei der Wahl des richtigen Werkstoffs für jedes Projekt",
      "Beschaffungszeit nach Werkstoffklasse geplant",
      "Wareneingangsprüfung mit Zeugnis- und Identitätskontrolle",
      "Bestands- und Beschaffungsverfolgung über Werkstoff- und Chargennachweise",
      "Versorgungssicherheit durch mehrere Lieferanten",
      "Werkstoffauswahl gemäß Spezifikation für Luft- und Raumfahrt sowie Medizintechnik",
    ],
    materials: [
      { name: "Aluminium", grade: "6061, 7075, 5083", properties: "Typisch 95-150 HB, Luftfahrt/Elektronik" },
      { name: "Edelstahl", grade: "304, 316, 17-4PH", properties: "Typisch 150-350 HB, Medizintechnik/Lebensmittel" },
      { name: "Kohlenstoffstahl", grade: "1045, 4140, 4340", properties: "Typisch 200-350 HB, Maschinenteile" },
      { name: "Titan", grade: "Gr2, Gr5 (Ti6Al4V)", properties: "Typisch 250-350 HB, Medizintechnik/Luftfahrt" },
      { name: "Messing / Bronze", grade: "C360, C932", properties: "Typisch 60-150 HB, Zahnrad- und Lageranwendungen" },
      { name: "Inconel 718", grade: "Superalloy", properties: "Hohe Temperatur, Turbinenteile, auf Bestellung" },
      { name: "PEEK", grade: "450G", properties: "Hohe Temperatur, Chemikalienbeständigkeit, Luftfahrt/Medizintechnik" },
      { name: "POM (Delrin)", grade: "Delrin 150/500", properties: "Geringe Reibung, Zahnräder und Lager" },
    ],
    faq: [
      { question: "Welche Werkstoffzeugnisse stellen Sie bereit?", answer: "Ein Werkstoffzeugnis und ein Bericht zur chemischen Analyse werden auf Anfrage bereitgestellt. Jede Lieferung wird mit Chargen- und Schmelzennummer erfasst." },
      { question: "Wie lange dauert die Werkstoffbeschaffung?", answer: "Die Beschaffungszeit hängt von der Werkstoffklasse ab; Sonderwerkstoffe wie Titan und Inconel werden auftragsbezogen beschafft. Die Dauer wird im Angebot angegeben." },
      { question: "Können Sie Sonderlegierungen liefern?", answer: "Ja. Sonderlegierungen wie Inconel 718, Hastelloy, Kovar und Wolfram werden auftragsbezogen beschafft. Die Lieferzeit nennen wir mit dem Angebot, nachdem Werkstoffbeschaffung, Anzahl der Arbeitsgänge und Kapazitätsplanung geprüft wurden." },
      { question: "Wie wird die Werkstoffqualität geprüft?", answer: "Im Wareneingang werden Zeugnis und Werkstoffidentität verifiziert und eine Maßkontrolle durchgeführt; der Werkstoff wird über Chargen- und Schmelzennummer verfolgt." },
    ],
    comparisonTables: [
      {
        title: "Werkstoff-Vergleichsmatrix",
        description: "Typische mechanische Kennwerte der wichtigsten Werkstoffgruppen; maßgeblich für die Auslegung ist das Werkstoffzeugnis.",
        headers: ["Werkstoff", "Härte (HB)", "Zugfestigkeit", "Kosten"],
        rows: [
          ["Al 6061-T6", "95", "310 MPa", "$"],
          ["Al 7075-T6", "150", "572 MPa", "$$"],
          ["SS 304", "187", "515 MPa", "$$"],
          ["SS 316L", "217", "485 MPa", "$$$"],
          ["Ti6Al4V (Gr5)", "334", "950 MPa", "$$$$"],
          ["Inconel 718", "363", "1034 MPa", "$$$$$"],
          ["PEEK 450G", "100 (Shore D)", "100 MPa", "$$$$"],
          ["POM (Delrin)", "85 (Shore D)", "70 MPa", "$"],
        ],
      },
      {
        title: "Beschaffungsweg und Zeugnismatrix",
        headers: ["Werkstoffgruppe", "Beschaffung", "Zeugnis"],
        rows: [
          ["Aluminium (6061, 7075)", "Nach Werkstoffklasse", "Auf Anfrage"],
          ["Edelstahl (304, 316)", "Nach Werkstoffklasse", "Auf Anfrage"],
          ["Kohlenstoffstahl (1045, 4140)", "Auf Bestellung", "Auf Anfrage"],
          ["Titan (Gr2, Gr5)", "Auf Bestellung", "Auf Anfrage"],
          ["Inconel / Hastelloy", "Auf Bestellung", "Auf Anfrage"],
          ["PEEK / Hochleistungskunststoffe", "Auf Bestellung", "Auf Anfrage"],
        ],
      },
    ],
  },
  "kalite-kontrol": {
    categoryLabel: "Qualität & Normen",
    title: "Qualitätskontrolle",
    metaTitle: "Qualitätskontrolle | Prüfplan und Messprotokoll | Mas Technic",
    metaDescription: "Ein Prüfplan für jeden Auftrag, fertigungsbegleitende Prüfung und Endprüfung nach Plan. Akkreditierte externe KMG-Messung auf Anfrage. ISO 9001:2015.",
    description: "Qualitätskontrolle ist keine Prüfung nach der Fertigung, sondern ein Plan, der vorher erstellt wird. Welches Maß wie und in welcher Phase geprüft wird, steht fest, bevor das Teil gespannt wird.",
    content: [
      "Für jeden Auftrag wird ein Prüfplan erstellt. Er legt fest, welche Maße der Zeichnung kritisch sind, mit welcher Methode und in welcher Phase jedes Maß geprüft wird und welcher Nachweis aus jeder Prüfung hervorgeht. Er ist das Ergebnis der technischen Prüfung in der Angebotsphase.",
      "Fertigungsbegleitende Prüfungen finden während der Produktion statt. Ziel ist nicht, Fehler erst bei der Endprüfung zu finden, sondern nie ein fehlerhaftes Teil an den nächsten Arbeitsgang weiterzugeben. Die Erstteilfreigabe, die Schritte nach maßverändernden Arbeitsgängen wie der Wärmebehandlung sowie Rüstwechsel sind die natürlichen Haltepunkte für die fertigungsbegleitende Prüfung.",
      "Die Endprüfung erfolgt anhand der im Prüfplan definierten Maße, die Ergebnisse werden dokumentiert. Ist eine Koordinatenmessung (KMG) erforderlich, wird sie auf Anfrage von einer akkreditierten externen Stelle durchgeführt; so bleibt die Messung unabhängig von der Fertigung.",
      "Die Rückverfolgbarkeit des Werkstoffs erfolgt über Chargen- und Schmelzennachweise; ein Werkstoffzeugnis wird auf Anfrage den Lieferunterlagen beigefügt. Die Liste unserer Mess- und Prüfmittel ist als separates Dokument veröffentlicht und kann im Bereich Downloads heruntergeladen werden.",
      "Tritt eine Abweichung auf, lautet die Frage nicht, ob das Teil noch zu retten ist, sondern warum der Prozess dieses Ergebnis erzeugt hat. Bis die Ursache gefunden ist, wird die Fertigung mit unveränderter Einrichtung nicht fortgesetzt.",
    ],
    features: [
      "Prüfplan — kritische Maße vor der Fertigung festgelegt",
      "Erstteilprüfung — keine Serie vor der Rüstfreigabe",
      "Fertigungsbegleitende Prüfung — Fehler gelangen nicht in den nächsten Arbeitsgang",
      "Endprüfung — nach Prüfplan, dokumentiert",
      "Akkreditierte KMG-Messung durch Dritte — auf Anfrage, unabhängig von der Fertigung",
      "Rückverfolgbarkeit des Werkstoffs — Chargen- und Schmelzennachweise",
    ],
    technicalSpecs: [
      { label: "Managementsystem", value: "ISO 9001:2015" },
      { label: "Standardtoleranz", value: "±0,01 mm" },
      { label: "Prüfplan", value: "Für jeden Auftrag" },
      { label: "KMG-Messung", value: "Akkreditiert durch Dritte, auf Anfrage" },
      { label: "Messprotokoll", value: "In den Lieferunterlagen" },
      { label: "Rückverfolgbarkeit", value: "Chargen- und Schmelzennachweise" },
    ],
    processSteps: ["Technische Prüfung", "Prüfplan", "Wareneingangserfassung", "Erstteilprüfung", "Fertigungsbegleitende Prüfungen", "Endprüfung", "Messprotokoll"],
    advantages: [
      "Der Prüfplan wird vor der Fertigung erstellt, nicht nachträglich",
      "Fertigungsbegleitende Prüfungen verhindern, dass Fehler in den nächsten Arbeitsgang gelangen",
      "Die Koordinatenmessung erfolgt durch eine akkreditierte externe Stelle, unabhängig von der Fertigung",
      "Messprotokolle werden mit den Lieferunterlagen übergeben",
      "Der Werkstoff wird über Chargen- und Schmelzennachweise verfolgt",
      "Bei einer Abweichung wird der Prozess korrigiert, nicht das Teil",
    ],
    faq: [
      { question: "Welche Qualitätszertifikate besitzen Sie?", answer: "Wir sind nach ISO 9001:2015 und ISO 14001:2015 zertifiziert. Wird eine Norm außerhalb dieses Geltungsbereichs gefordert, bewerten wir dies gemeinsam in der technischen Prüfung." },
      { question: "Erhalte ich ein Messprotokoll?", answer: "Ja. Die im Prüfplan definierten Maße werden gemessen und die Ergebnisse dokumentiert; das Messprotokoll wird den Lieferunterlagen beigefügt." },
      { question: "Wird eine KMG-Messung durchgeführt?", answer: "Die Koordinatenmessung wird auf Anfrage von einer akkreditierten externen Stelle durchgeführt. So bleibt die Messung unabhängig von der Fertigung; geben Sie Ihren Bedarf einfach in der Angebotsphase an." },
      { question: "Wie läuft die Qualitätskontrolle ab?", answer: "Aus der technischen Prüfung entsteht der Prüfplan; der Wareneingang wird erfasst, das Erstteil freigegeben, während der Fertigung finden fertigungsbegleitende Prüfungen statt, und die Endprüfung wird nach Plan abgeschlossen und dokumentiert." },
      { question: "Kann ich ein Werkstoffzeugnis erhalten?", answer: "Der Werkstoff wird über Chargen- und Schmelzennachweise verfolgt. Wenn Sie ein Werkstoffzeugnis anfordern, wird es den Lieferunterlagen beigefügt." },
    ],
    comparisonTables: [
      {
        title: "Prüfphasen und ihre Nachweise",
        description: "Jeder Prüfschritt ist ein Entscheidungspunkt und hinterlässt einen Nachweis",
        headers: ["Phase", "Prüfpunkt", "Methode", "Nachweis", "Häufigkeit"],
        rows: [
          ["1. Wareneingang", "Werkstoffidentität", "Chargen-/Schmelzenverfolgung", "Rückverfolgbarkeitsnachweis", "Jede Charge"],
          ["2. Rüsten", "Prüfung von Werkzeug und Spannung", "Sichtprüfung + Messung", "Rüstfreigabe", "Jedes Rüsten"],
          ["3. Erstteil", "Kritische Maße", "Messung nach Prüfplan", "Erstteilprotokoll", "Jedes Rüsten"],
          ["4. Fertigungsbegleitend", "Driftanfällige Maße", "Fertigungsbegleitende Prüfung", "Arbeitsprotokoll", "Nach Plan"],
          ["5. Endprüfung", "Alle Maße des Prüfplans", "Messung; bei Bedarf akkreditiertes KMG", "Messprotokoll", "Nach Plan"],
        ],
      },
      {
        title: "Wahl der Prüfmethode",
        description: "Die Methode richtet sich nach dem zu messenden Merkmal und der Enge der Toleranz",
        headers: ["Merkmal", "Typische Methode", "Wann akkreditiertes KMG nötig ist"],
        rows: [
          ["Durchmesser und Länge", "Messung nach Prüfplan", "Bei enger Maßkette"],
          ["Form (Ebenheit, Zylinderform)", "Messung nach Prüfplan", "Wenn eine Form- und Lagetoleranz angegeben ist"],
          ["Position und Koaxialität", "Prüfung vom Bezug aus", "Bei komplexem Bezugssystem"],
          ["Oberflächenzustand", "Vergleichsprüfung", "Wenn ein Ra-Zahlenwert angegeben ist"],
          ["Werkstoffidentität", "Chargen-/Schmelzenverfolgung", "Nicht zutreffend — über Dokumente nachgewiesen"],
        ],
      },
    ],
  },
  "tolerans-hassasiyet": {
    categoryLabel: "Qualität & Normen",
    title: "Toleranz & Präzision",
    metaTitle: "Toleranz & Präzision | ±0,01 mm | ISO 2768 | GD&T | Mas Technic",
    metaDescription: "Standardtoleranzbereich ±0,01 mm, Auslegung nach ISO 2768 und ASME Y14.5 (GD&T). Die Toleranz wird in der technischen Prüfung nach Geometrie, Werkstoff und Maßkette festgelegt.",
    description: "Eine Toleranz ist keine Werbezahl, sondern eine Entscheidung: Wie eng jedes Maß gehalten wird, hängt davon ab, was in der Baugruppe funktionieren muss. Unser Standardarbeitsbereich liegt bei ±0,01 mm.",
    content: [
      "Unser Standardarbeitsbereich liegt bei ±0,01 mm. Ob ein Teil enger gefertigt werden kann, ist nicht allein eine Frage der Maschine, sondern der Geometrie, des Werkstoffs, der Teilegröße und der Maßkette; dies wird daher für jedes Teil gesondert in der technischen Prüfung entschieden.",
      "Am häufigsten entscheidet die Anzahl der Aufspannungen über die Toleranz. Jede neue Aufspannung bringt eine neue Fehlerquelle in die Maßkette; ein in einer Aufspannung fertiggestelltes Teil hält eine engere Toleranz als dasselbe Teil, das auf derselben Maschine in zwei Aufspannungen bearbeitet wird.",
      "Form- und Lagetoleranzen (GD&T) werden nach ASME Y14.5 gelesen. Positions-, Rechtwinkligkeits-, Koaxialitäts-, Ebenheits- und Rundheitstoleranzen sind nur zusammen mit dem Bezugssystem sinnvoll: Welche Fläche als Bezug dient, ist ebenso wichtig wie die Toleranz selbst.",
      "Für Maße ohne Toleranzangabe auf der Zeichnung gelten die Allgemeintoleranzklassen nach ISO 2768. Welche Klasse gilt, wird in der Angebotsphase bestätigt; eine nicht definierte Allgemeintoleranz ist die häufigste Ursache für Streitfälle nach der Fertigung.",
      "Eine engere Toleranz als nötig erhöht die Kosten und verlängert die Lieferzeit. In der technischen Prüfung schlagen wir vor, funktionsunkritische Maße zu lockern; gemeinsam festzulegen, welches Maß wirklich kritisch ist, macht das Teil sowohl günstiger als auch zuverlässiger.",
    ],
    features: [
      "±0,01 mm Standardtoleranz — je Teil in der technischen Prüfung bestätigt",
      "GD&T-Auslegung — Positions-, Form- und Richtungstoleranzen nach ASME Y14.5",
      "Bezugssystem — welche Fläche als Bezug dient, wird gemeinsam festgelegt",
      "Allgemeintoleranzen nach ISO 2768 — vereinbarte Klasse für nicht tolerierte Maße",
      "Maßkettenanalyse — Bewertung der Aufspannungen und Toleranzaddition",
      "Vorschlag zur Toleranzlockerung — für funktionsunkritische Maße",
    ],
    technicalSpecs: [
      { label: "Standardtoleranz", value: "±0,01 mm" },
      { label: "Allgemeintoleranz", value: "ISO 2768 (vereinbarte Klasse)" },
      { label: "Form- und Lagetoleranz", value: "ASME Y14.5 (GD&T)" },
      { label: "Bestimmt durch", value: "Geometrie, Werkstoff, Maßkette" },
      { label: "Bestätigung", value: "Technische Prüfung" },
      { label: "Prüfung", value: "Messung nach Prüfplan" },
    ],
    advantages: [
      "Toleranzen werden Maß für Maß nach der Funktion des Teils vereinbart",
      "Die Anzahl der Aufspannungen wird mit Blick auf die Maßkette minimiert",
      "GD&T und Bezugssystem werden in der technischen Prüfung gemeinsam ausgewertet",
      "Die Allgemeintoleranzklasse für nicht tolerierte Maße wird im Angebot bestätigt",
      "Das Lockern unnötig enger Toleranzen wird zur Kostensenkung vorgeschlagen",
      "Kritische Maße werden in den Prüfplan aufgenommen und mit Messprotokoll nachgewiesen",
    ],
    faq: [
      { question: "Wie groß ist Ihr Standardtoleranzbereich?", answer: "±0,01 mm. Ob ein Teil enger gefertigt werden kann, hängt von Geometrie, Werkstoff, Teilegröße und Maßkette ab und wird in der technischen Prüfung entschieden." },
      { question: "Unterstützen Sie Form- und Lagetoleranzen (GD&T)?", answer: "Ja. Positions-, Rechtwinkligkeits-, Koaxialitäts-, Ebenheits- und Rundheitstoleranzen lesen wir nach ASME Y14.5 zusammen mit dem Bezugssystem und nehmen sie in den Prüfplan auf." },
      { question: "Meine Zeichnung enthält keine Toleranzen — was nun?", answer: "Für nicht tolerierte Maße gelten die Allgemeintoleranzklassen nach ISO 2768. Welche Klasse gilt, bestätigen wir in der Angebotsphase." },
      { question: "Was ändert sich, wenn ich eine engere Toleranz verlange?", answer: "Arbeitsfolge, Spannkonzept und Prüfmethode ändern sich; Zeit und Kosten steigen. Gegebenenfalls schlagen wir vor, funktionsunkritische Maße zu lockern." },
      { question: "Wie weisen Sie nach, dass die Toleranz eingehalten wird?", answer: "Kritische Maße werden in den Prüfplan aufgenommen, gemessen und die Ergebnisse dokumentiert. Ist eine Koordinatenmessung erforderlich, wird auf Anfrage eine akkreditierte externe Messung bereitgestellt." },
    ],
    comparisonTables: [
      {
        title: "Toleranzklassen nach ISO 2768",
        description: "Allgemeintoleranzen nach Nennmaßbereich für nicht tolerierte Maße der Zeichnung (mm)",
        headers: ["Toleranzklasse (ISO 2768)", "0,5 – 3 mm", "3 – 6 mm", "6 – 30 mm", "30 – 120 mm", "120 – 400 mm"],
        rows: [
          ["f (fein)", "±0,05", "±0,05", "±0,1", "±0,15", "±0,2"],
          ["m (mittel)", "±0,1", "±0,1", "±0,2", "±0,3", "±0,5"],
          ["c (grob)", "±0,2", "±0,3", "±0,5", "±0,8", "±1,2"],
          ["v (sehr grob)", "—", "±0,5", "±1,0", "±1,5", "±2,5"],
        ],
      },
      {
        title: "GD&T — Was jede Toleranz begrenzt",
        description: "Symbole nach ASME Y14.5 und die Montagefrage, die jedes beantwortet",
        headers: ["Toleranzart", "Symbol", "Was begrenzt wird", "Typische Anwendung", "Bezug erforderlich"],
        rows: [
          ["Position", "⌖", "Lage eines Elements zum Bezug", "Positionierung von Bohrungen und Stiften", "Ja"],
          ["Rechtwinkligkeit", "⊥", "Ausrichtung einer Fläche zum Bezug", "Rechtwinkliger Bezug Fläche–Welle", "Ja"],
          ["Koaxialität", "◎", "Übereinstimmung zweier Achsen", "Lagersitz, Welle", "Ja"],
          ["Ebenheit", "▱", "Abweichung einer Fläche in sich", "Dichtfläche", "Nein"],
          ["Rundheit", "○", "Abweichung eines Querschnitts vom Kreis", "Kolben, Zylinder", "Nein"],
          ["Lauf", "↻", "Rundlauf der Fläche bei Rotation", "Welle, Spindel", "Ja"],
        ],
      },
      {
        title: "Bevor Sie eine Toleranz einengen",
        description: "Eine enge Toleranz ist nicht immer die richtige Antwort; zuerst kommen diese drei Fragen",
        headers: ["Frage", "Warum sie gestellt wird", "Typisches Ergebnis"],
        rows: [
          ["Was bestimmt dieses Maß in der Baugruppe?", "Ein Maß ohne Funktion verursacht unnötige Kosten", "Das Maß wird gelockert"],
          ["Von welchem Bezug wird das Maß genommen?", "Ein anderer Bezug verteilt die Toleranz neu", "Die Maßkette wird kürzer"],
          ["In wie vielen Aufspannungen wird gefertigt?", "Jede Aufspannung ist eine neue Fehlerquelle", "Die Arbeitsfolge ändert sich"],
        ],
      },
    ],
  },
};
