/**
 * C1 — SELF-HOSTED WEB FONTS.
 *
 *   node scripts/fonts/self-host.mjs
 *
 * Downloads the exact faces the site used to request from Google Fonts and
 * writes them as local WOFF2 files plus one generated stylesheet:
 *
 *   src/assets/fonts/*.woff2      hashed by Vite → immutable cache
 *   src/styles/fonts.css          @font-face rules (generated — do not edit)
 *   src/assets/fonts/OFL-*.txt    the licence each family ships under
 *
 * Kept: the three families and every weight/style the old request named
 * (IBM Plex Mono 400–700, Space Grotesk 400–700, Newsreader 400 roman +
 * italic, opsz axis), the `display=swap` behaviour, and the symbol subset
 * (arrows, ≤ ≥ ≈, GD&T marks) that Phase 10-4 split into its own request.
 * Dropped: cyrillic, cyrillic-ext and vietnamese — the site is Turkish and
 * English; Turkish letters (ğ ş ı İ ç ö ü) live in latin-ext, which is kept.
 *
 * All three families are SIL Open Font License 1.1, which permits bundling
 * and redistribution with the licence text alongside.
 *
 * No package is added; Node's fetch does the work.
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..", "..");
const FONT_DIR = join(root, "src", "assets", "fonts");
const CSS_OUT = join(root, "src", "styles", "fonts.css");

const FAMILIES =
  "family=IBM+Plex+Mono:wght@400;500;600;700&family=Newsreader:ital,opsz,wght@0,6..72,400;1,6..72,400&family=Space+Grotesk:wght@400;500;600;700";
const SYMBOLS = "→←↑↓↻≤≥≈⊥∥⌒⌓⟂∅⌀◎○▱⌖★☆∪";
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);
const LICENCES = {
  "IBM Plex Mono": "https://raw.githubusercontent.com/google/fonts/main/ofl/ibmplexmono/OFL.txt",
  "Space Grotesk": "https://raw.githubusercontent.com/google/fonts/main/ofl/spacegrotesk/OFL.txt",
  Newsreader: "https://raw.githubusercontent.com/google/fonts/main/ofl/newsreader/OFL.txt",
};
// A desktop Chrome user agent makes Google serve WOFF2 with unicode-range.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36";

const slug = (value) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

async function get(url, as = "text") {
  const response = await fetch(url, { headers: { "user-agent": UA } });
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  return as === "text" ? response.text() : Buffer.from(await response.arrayBuffer());
}

function parse(css, defaultSubset) {
  const faces = [];
  const re = /(?:\/\* ([a-z-]+) \*\/\s*)?@font-face \{([^}]*)\}/g;
  for (const [, subset = defaultSubset, body] of css.matchAll(re)) {
    const field = (name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim();
    faces.push({
      subset,
      family: field("font-family").replace(/'/g, ""),
      style: field("font-style"),
      weight: field("font-weight"),
      url: body.match(/url\(([^)]+)\)/)[1],
      range: field("unicode-range"),
    });
  }
  return faces;
}

const main = parse(await get(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`), "latin")
  .filter((face) => KEEP_SUBSETS.has(face.subset));
const symbols = parse(
  await get(`https://fonts.googleapis.com/css2?${FAMILIES}&text=${encodeURIComponent(SYMBOLS)}&display=swap`),
  "symbols",
);

rmSync(FONT_DIR, { recursive: true, force: true });
mkdirSync(FONT_DIR, { recursive: true });

/* A variable family is served as ONE file for several weights; group by URL
   so each file is written once and declared once with a weight range. */
const byUrl = new Map();
for (const face of [...main, ...symbols]) {
  const key = face.url;
  const entry = byUrl.get(key) ?? { ...face, weights: new Set() };
  entry.weights.add(Number(face.weight));
  byUrl.set(key, entry);
}

const rules = [];
let bytes = 0;
for (const face of byUrl.values()) {
  const weights = [...face.weights].sort((a, b) => a - b);
  const weight = weights.length > 1 ? `${weights[0]} ${weights.at(-1)}` : String(weights[0]);
  const file = `${slug(face.family)}-${face.style}-${weights.join("-")}-${face.subset}.woff2`;
  const data = await get(face.url, "buffer");
  bytes += data.length;
  writeFileSync(join(FONT_DIR, file), data);
  rules.push({ face, weight, file });
}

for (const [family, url] of Object.entries(LICENCES)) {
  writeFileSync(join(FONT_DIR, `OFL-${slug(family)}.txt`), await get(url));
}

const order = { latin: 0, "latin-ext": 1, symbols: 2 };
rules.sort((a, b) => a.face.family.localeCompare(b.face.family) || a.face.style.localeCompare(b.face.style)
  || a.weight.localeCompare(b.weight) || order[a.face.subset] - order[b.face.subset]);

const css = [
  "/* GENERATED by scripts/fonts/self-host.mjs — do not edit by hand.",
  " * Self-hosted IBM Plex Mono, Space Grotesk and Newsreader (SIL OFL 1.1,",
  " * licences in src/assets/fonts/). latin + latin-ext + the symbol subset;",
  " * `unicode-range` keeps each file unrequested until a glyph needs it. */",
  "",
  ...rules.map(({ face, weight, file }) => [
    `/* ${face.family} ${face.style} ${weight} — ${face.subset} */`,
    "@font-face {",
    `  font-family: "${face.family}";`,
    `  font-style: ${face.style};`,
    `  font-weight: ${weight};`,
    "  font-display: swap;",
    `  src: url("../assets/fonts/${file}") format("woff2");`,
    `  unicode-range: ${face.range};`,
    "}",
    "",
  ].join("\n")),
].join("\n");
writeFileSync(CSS_OUT, css);
console.log(`${rules.length} faces, ${byUrl.size} files, ${(bytes / 1024).toFixed(1)} KiB → ${FONT_DIR}`);
