import type { FamilyText } from "./types";

/* Material family pages, keyed by slug (`src/data/materialsData.ts`). */
export const families: Record<string, FamilyText> = {
  aluminyum: {
    name: "Aluminium",
    shortDescription: "Light, machinable, corrosion-resistant",
    heroTitle: "Aluminium Alloys for CNC Machining",
    heroDescription: "Precision CNC parts in aluminium alloys, from aerospace to automotive, from 6061-T6 to 7075-T6.",
    seoTitle: "Aluminium CNC Machining | 6061, 7075, 2024 Alloys",
    seoDescription: "Aluminium alloys for CNC milling and turning. 6061-T6, 7075-T6, 2024-T3 and more. Light, corrosion-resistant, excellent machinability.",
    content: {
      intro: "Aluminium is one of the most widely chosen material families in CNC machining. Thanks to their low density, aluminium alloys are markedly lighter than steel, and their good machinability makes chip-removal operations highly productive. The 2xxx, 5xxx, 6xxx and 7xxx series alloys offer a wide range of options for different strength and corrosion resistance requirements.",
      properties: "Aluminium alloys stand out for their low density and high thermal conductivity, an advantage in applications that need heat dissipation. Strength varies over a wide range with series and temper: the 7xxx series is high-strength, the 5xxx and 6xxx series medium-strength. Anodising can increase surface hardness and corrosion resistance.",
      applications: "Widely used in aerospace for fuselage panels, wing structures and interior parts. In the automotive industry it is used for engine blocks, wheels and structural components. In electronics it is preferred for heat sinks, enclosures and chassis parts. It is also common in medical device housings, marine hardware and architectural profiles.",
      machining: "Aluminium machines easily by every CNC method. It allows high cutting speeds in 3 and 5-axis milling, turning, drilling and threading. 6061-T6 and 6082 are known for their good machinability. High-strength alloys such as 7075 need more careful parameter selection.",
      selection: "For general-purpose applications 6061-T6 is a versatile choice. For structural parts that need high strength, 7075-T6 is preferred. 5052 or 5083 suit marine and corrosive environments. 2024-T3 or 7050 is used in aerospace applications. MIC-6 is recommended for precision fixture and tooling plates.",
    },
    advantages: ["Light weight", "Excellent machinability", "Good corrosion resistance", "Can be anodised", "High thermal conductivity", "Recyclable"],
    commonApplications: ["Aerospace parts", "Automotive components", "Electronic enclosures", "Heat spreaders", "Structural profiles", "Medical device housings"],
  },
  celik: {
    name: "Steel",
    shortDescription: "High strength, heat treatment, wide choice of alloys",
    heroTitle: "Steel Alloys for CNC Machining",
    heroDescription: "1045, 4140, 4340 and more. High-strength steel CNC machining for heavy industry applications.",
    seoTitle: "Steel CNC Machining | 1045, 4140, 4340 Alloys",
    seoDescription: "Steel alloys for CNC milling and turning. 1045, 4140, 4340, A36 carbon and alloy steels. High strength, heat treatment.",
    content: {
      intro: "Steel alloys are the backbone of industrial CNC machining. Carbon steels (1018, 1045) are used in general-purpose applications, while alloy steels (4140, 4340) are designed for critical parts that need high strength and toughness. Heat treatment can set mechanical properties over a wide range.",
      properties: "The strength and hardness of steel alloys vary over a wide range with carbon and alloy content and heat treatment condition. Surface hardness can be increased by surface hardening methods such as case hardening, nitriding and induction hardening; the heat treatment to apply is set by the specification.",
      applications: "In machine building it is used for shafts, gears, crankshafts and fasteners. In the automotive industry it is used for powertrain, suspension parts and chassis components. In the energy sector it is preferred for turbine shafts and pressure vessels. In the defence industry it appears in weapon systems and armour plates.",
      machining: "Carbon steels (1018, 1045) machine easily at moderate cutting speeds. Alloy steels (4140) need lower cutting speeds and rigid tooling. High-strength steels such as 4340 can be machined with CBN or ceramic inserts. Coolant is recommended for all steel types.",
      selection: "1045 suits general-purpose shafts and axles. 4140 is preferred for parts that need high toughness and fatigue resistance. 4340 is used for aerospace and defence applications. A36 is a common choice for structural frame and platform applications.",
    },
    advantages: ["High strength", "Properties adjustable by heat treatment", "Easy weldability", "Wide choice of alloys"],
    commonApplications: ["Shafts and axles", "Gear mechanisms", "Crankshafts", "Structural parts", "Tool holders"],
  },
  "paslanmaz-celik": {
    name: "Stainless Steel",
    shortDescription: "Corrosion-resistant, hygienic, durable",
    heroTitle: "Stainless Steel for CNC Machining",
    heroDescription: "304, 316L, 17-4 PH and more. Stainless steel CNC machining for the food, medical and chemical industries.",
    seoTitle: "Stainless Steel CNC Machining | 304, 316L, 17-4 PH",
    seoDescription: "Stainless steel alloys for CNC machining. 304, 316L, 17-4 PH, 303, 321, 347. Corrosion resistance, hygiene, medical and food sectors.",
    content: {
      intro: "Stainless steel is the family of steels containing at least 10.5% chromium (EN 10088), which forms a protective chromium oxide layer on the surface. Austenitic (304, 316L), martensitic (440C), precipitation-hardening (17-4 PH), duplex (2205) and ferritic types offer different combinations of corrosion resistance and mechanical properties.",
      properties: "The strength of stainless steels varies by type: austenitic types are medium-strength and tough, precipitation-hardening and martensitic types high-strength. Annealed austenitic types are non-magnetic and keep their toughness at low temperatures. The service temperature is set by type and environment.",
      applications: "Common in hygienic tanks, piping and process equipment in the food and beverage industry. Used in surgical instruments and sterilisation equipment in the medical sector. Preferred for reactors and pipelines in corrosive environments in the chemical industry. Found in decorative panels and railings in architectural applications.",
      machining: "Stainless steel offers lower machinability than aluminium and carbon steel. Its tendency to work-harden calls for continuous, stable cutting parameters. The 303 series is designed as a free-machining type. Low cutting speeds, high feed and positive-rake tools are recommended.",
      selection: "304 is the most common choice for general corrosion resistance. 316L is preferred for chloride environments and seawater. 17-4 PH is used for high strength with moderate corrosion resistance. 303 is chosen when machinability comes first. 321 or 347 is recommended for high-temperature applications.",
    },
    advantages: ["Excellent corrosion resistance", "Hygienic surface", "High-temperature strength", "Attractive appearance", "Long life"],
    commonApplications: ["Food equipment", "Medical devices", "Chemical processes", "Architectural panels", "Marine hardware"],
  },
  titanyum: {
    name: "Titanium",
    shortDescription: "Aerospace grade, biocompatible, light",
    heroTitle: "Titanium Alloys for CNC Machining",
    heroDescription: "Grade 2, Grade 5 (Ti-6Al-4V) and Grade 9. The premium material of the aerospace and medical sectors.",
    seoTitle: "Titanium CNC Machining | Ti-6Al-4V, Grade 2, Grade 5",
    seoDescription: "Titanium alloys for CNC machining. Ti-6Al-4V (Grade 5), Grade 2, Grade 9. Aerospace and medical components, high strength-to-weight ratio.",
    content: {
      intro: "With its high strength-to-weight ratio, excellent corrosion resistance and biocompatibility, titanium is one of the core materials of the aerospace and medical sectors. Commercially pure types (Grade 1-4) and alloyed types (Grade 5, 9, 23) offer different options. Although markedly lighter than steel, the alloyed types provide similar strength.",
      properties: "Titanium alloys combine low density with high strength; commercially pure types are medium-strength, Grade 5 high-strength. Corrosion resistance is very high in seawater and many acid environments. Low thermal conductivity causes heat to build up in the cutting zone during machining and needs care.",
      applications: "Used in aerospace for compressor blades, airframe fasteners and landing gear parts. Preferred in the medical sector for surgical instruments and medical device components. Found in corrosive-environment equipment in the chemical industry, and in marine and racing technologies.",
      machining: "Machining titanium takes experience. Low thermal conductivity causes intense heat build-up in the cutting zone. Low cutting speeds, high-pressure coolant and sharp carbide tools should be used. Coated tools are recommended because of the tendency for chips to stick.",
      selection: "Grade 2 suits applications where corrosion resistance and formability come first. Grade 5 (Ti-6Al-4V) is the standard choice for structural parts that need high strength. Grade 9 can be considered for medium strength and good formability. ELI (Extra Low Interstitial) Grade 23 is preferred where higher toughness is needed.",
    },
    advantages: ["High strength-to-weight ratio", "Excellent corrosion resistance", "Biocompatibility", "High-temperature strength", "Non-magnetic"],
    commonApplications: ["Aircraft parts", "Medical components", "Chemical process equipment", "Marine", "Racing technologies"],
  },
  "pirinc-bronz": {
    name: "Brass & Bronze",
    shortDescription: "Machinability champion, low friction",
    heroTitle: "Brass and Bronze Alloys for CNC Machining",
    heroDescription: "C360, C932, C954 and more. Excellent machinability for valves, bearings and fasteners.",
    seoTitle: "Brass & Bronze CNC Machining | C360, C932, C954",
    seoDescription: "Brass and bronze alloys for CNC machining. C360, C932 SAE 660, C954 aluminium bronze. Valves, bearings, marine parts.",
    content: {
      intro: "Brass (copper-zinc) and bronze (copper-tin) alloys are among the easiest materials to CNC machine. C360 free-machining brass is regarded as the reference material for chip removal. Bronze alloys, with their low coefficient of friction and excellent oil retention, are ideal for plain bearings.",
      properties: "The strength of brass and bronze alloys varies by alloy: leaded bearing bronzes are low-strength, aluminium bronzes high-strength. Their electrical and thermal conductivity is much higher than steel's.",
      applications: "In hydraulic and pneumatic systems they are used for valve bodies, fittings and adaptors. In machine building they are preferred for plain bearings, bushings and gears. In the marine sector they are used for propellers, valves and pipe fittings. In the electrical sector connectors, terminals and busbars are made from them.",
      machining: "Brass is one of the best-performing materials for machinability. It allows high cutting speeds and gives an excellent surface finish. Its short, broken chips make automatic lathe and CNC operations easier. Bronze alloys need somewhat more careful parameter selection but still give good results.",
      selection: "C360 brass is ideal for general-purpose fittings and valves. C932 (SAE 660) bronze is preferred for plain bearings and bushings. C954 aluminium bronze is used for heavy-duty bearings and marine applications. C464 naval brass is recommended for saltwater environments.",
    },
    advantages: ["Highest machinability", "Low coefficient of friction", "Decorative appearance", "Non-sparking"],
    commonApplications: ["Valve bodies", "Plain bearings", "Fasteners", "Marine parts", "Electrical connectors"],
  },
  bakir: {
    name: "Copper",
    shortDescription: "Highest conductivity, heat transfer",
    heroTitle: "Copper for CNC Machining",
    heroDescription: "C101, C110 and C122. Pure copper machining for electronics, heat exchangers and electrical systems.",
    seoTitle: "Copper CNC Machining | C101, C110, C122 Pure Copper",
    seoDescription: "Copper materials for CNC machining. C101 oxygen-free copper, C110 ETP copper, C122 DHP copper. Electrical conductivity, heat transfer.",
    content: {
      intro: "Copper has the highest electrical and thermal conductivity of all metals after silver. In CNC machining it is preferred especially for electrical conduction parts, heat spreaders and cooling systems. There are three main types: C101 (oxygen-free), C110 (electrolytic) and C122 (phosphorus-deoxidised).",
      properties: "Copper has very high electrical and thermal conductivity; annealed copper is the reference for the IACS conductivity scale. Its strength is low, so copper alloys are preferred in structural applications. A part's conductivity value is confirmed by the material certificate.",
      applications: "In the electronics industry busbar systems, earthing plates and connectors are produced. In thermal management applications cooling blocks, heat pipes and heat sinks are made. In the energy sector it is used in generator components and transformer windings. In vacuum technology it is preferred for RF cavities and waveguides.",
      machining: "Pure copper can be challenging to CNC machine because it is soft and sticky. Long, continuous chips make chip control difficult. Sharp positive-rake tools, high feed rates and effective cooling should be used. Diamond-coated or PCD tools give the best results.",
      selection: "C101 is used for vacuum applications that need maximum conductivity and purity. C110 is the most common choice for general electrical applications. C122 is preferred for heat exchanger applications that need soldering or brazing.",
    },
    advantages: ["Highest electrical conductivity after silver", "Very high thermal conductivity", "Recyclable"],
    commonApplications: ["Electrical busbars", "Heat spreaders", "Cooling blocks", "Transformer parts"],
  },
  nikel: {
    name: "Nickel Superalloys",
    shortDescription: "Extreme temperature, corrosion resistance",
    heroTitle: "Nickel Superalloys for CNC Machining",
    heroDescription: "Inconel 625, 718 and Monel. For jet engines, nuclear and chemical process equipment.",
    seoTitle: "Nickel Superalloy CNC Machining | Inconel 625, 718",
    seoDescription: "Nickel superalloys for CNC machining. Inconel 625, 718, Monel 400. Jet engines, nuclear energy, chemical processing, high temperature.",
    content: {
      intro: "Nickel superalloys are advanced engineering materials that keep their mechanical properties even at very high temperatures. The Inconel (nickel-chromium), Monel (nickel-copper) and Hastelloy (nickel-molybdenum) families are used for parts that work in harsh conditions.",
      properties: "Nickel alloys keep their strength at high temperature; precipitation-hardening types such as Inconel 718 are high-strength. Corrosion resistance is high against many acids, bases and salt solutions. The service temperature is set by alloy and environment.",
      applications: "Used in aerospace for turbine components, combustion chambers and exhaust systems. Preferred in energy and nuclear plants for reactor internals and heat exchangers. Found in corrosive-environment reactors and pipelines in the chemical process industry, and in marine equipment.",
      machining: "Nickel alloys are among the hardest materials to CNC machine. Their tendency to work-harden is very high and excessive heat builds up in the cutting zone. They need very low cutting speeds, high-pressure coolant and ceramic or CBN inserts; tool wear is high.",
      selection: "Inconel 625 is used for general high-temperature and corrosion resistance. Inconel 718 is preferred for turbine parts that need high strength. Monel 400 is ideal for seawater and acid environments.",
    },
    advantages: ["High-temperature operation", "Superior corrosion resistance", "High strength", "Oxidation resistance"],
    commonApplications: ["Turbine components", "Reactor internals", "Chemical reactors", "Exhaust manifolds"],
  },
  magnezyum: {
    name: "Magnesium",
    shortDescription: "The lightest structural metal, EMI shielding",
    heroTitle: "Magnesium Alloys for CNC Machining",
    heroDescription: "AZ31B, AZ61A, AZ80A. Weight-critical applications with the lightest of the structural metals.",
    seoTitle: "Magnesium CNC Machining | AZ31B, AZ61A Alloys",
    seoDescription: "Magnesium alloys for CNC machining. AZ31B, AZ61A, AZ80A. The lightest structural metal, EMI shielding, aerospace and automotive applications.",
    content: {
      intro: "Magnesium is the lightest of the structural metals. Markedly lighter than aluminium and steel, magnesium alloys offer an advantage in weight-critical applications. The AZ series (aluminium-zinc alloyed) are the most widely used magnesium alloys.",
      properties: "Magnesium alloys have the lowest density of the structural metals. In specific strength (strength/density) they compete with many steel and aluminium alloys. They offer good EMI (electromagnetic interference) shielding.",
      applications: "Used in aerospace for helicopter gearbox housings, instrument panels and seat frames. In the automotive industry steering column parts, wheels and engine covers are produced. In electronics it is preferred for laptop cases, camera bodies and mobile phone frames.",
      machining: "Magnesium is the easiest of all metals to machine. It allows very high cutting speeds, gives an excellent surface finish and extends tool life. There is, however, a critical safety point: magnesium chips are flammable. A class D fire extinguisher must be kept ready, and dry machining or mineral-oil-based coolant should be used.",
      selection: "AZ31B is preferred for general-purpose sheet and profile applications. AZ61A or AZ80A is used for forged parts that need higher strength.",
    },
    advantages: ["The lightest structural metal", "Excellent machinability", "Good EMI shielding", "High specific strength"],
    commonApplications: ["Electronic enclosures", "Automotive parts", "Aerospace components", "Camera bodies"],
  },
  termoplastikler: {
    name: "Thermoplastics",
    shortDescription: "Light, corrosion-resistant, insulating",
    heroTitle: "Engineering Plastics for CNC Machining",
    heroDescription: "ABS, Delrin, nylon, PTFE, PVC and more. Light, corrosion-resistant parts as an alternative to metal.",
    seoTitle: "Plastic CNC Machining | ABS, Delrin, Nylon, PTFE",
    seoDescription: "Engineering plastics for CNC machining. ABS, Delrin (POM), nylon (PA), PTFE, PVC, polycarbonate. Light, corrosion resistance, electrical insulation.",
    content: {
      intro: "Engineering thermoplastics offer light alternatives to metals in many applications. Materials such as ABS, Delrin (POM), nylon (PA), polycarbonate (PC) and PTFE have a wide range of uses thanks to their corrosion resistance, electrical insulation and low weight.",
      properties: "Thermoplastics are markedly lighter than metals. Strength varies widely by material; glass-fibre-reinforced types give the highest strength. Electrical insulation, chemical resistance and low friction together are hard to find in metals. Values change with temperature and humidity.",
      applications: "In the automotive industry dashboards, covers and housings are produced. In the food industry food-contact grade cutting boards and conveyor parts are used. In electronics insulators, connector bodies and PCB supports are preferred. In the medical sector disposable device components and laboratory equipment are made.",
      machining: "Thermoplastics are generally easier to machine than metals, but there are some points to watch. Because of their low melting points, low speed/high feed is preferred over high speed/low feed. Sharp tools should be used, and cooling should keep the material from melting. Delrin and ABS offer the best machinability.",
      selection: "ABS suits general-purpose prototypes and housings. Delrin (POM) is preferred for high precision and low friction. Nylon is used for load-bearing parts and gears. PTFE is chosen for chemical resistance and low friction. Polycarbonate is used for applications that need transparency.",
    },
    advantages: ["Markedly lighter than metals", "Corrosion-resistant", "Electrical insulation", "Low friction", "Food-contact grades available"],
    commonApplications: ["Housings and covers", "Gears and bearings", "Insulators", "Food-contact parts", "Prototype parts"],
  },
  "yuksek-performans-plastikler": {
    name: "High-Performance Plastics",
    shortDescription: "Metal alternative, high temperature, aerospace",
    heroTitle: "High-Performance Polymers for CNC Machining",
    heroDescription: "PEEK, Ultem (PEI), Torlon (PAI), Vespel. Polymers that replace metal in the aerospace and medical sectors.",
    seoTitle: "PEEK & Ultem CNC Machining | High-Performance Plastics",
    seoDescription: "High-performance plastics for CNC machining. PEEK, Ultem (PEI), Torlon (PAI). Aerospace, medical, semiconductor. Polymers as a metal alternative.",
    content: {
      intro: "High-performance polymers are advanced materials that offer mechanical, thermal and chemical properties beyond those of conventional engineering plastics. PEEK (polyether ether ketone), Ultem/PEI (polyetherimide) and Torlon/PAI (polyamide-imide) can replace aluminium and stainless steel in many applications.",
      properties: "High-performance plastics offer higher strength and continuous service temperature than engineering plastics; carbon-fibre-reinforced types give the highest strength. They offer flame retardancy, low smoke emission and chemical resistance. Values change with temperature and humidity.",
      applications: "In aerospace they replace metal in cabin interior parts, brackets and insulators. In the medical sector sterilisable surgical instrument handles and medical device components are produced. In the semiconductor industry they are preferred for wafer handling equipment and process parts. In the energy sector high-temperature seals and bushings are made.",
      machining: "CNC machining of high-performance plastics needs techniques different from metals. PEEK offers good machinability but tool wear is high. Torlon can be very hard and brittle. Diamond-coated or PCD tools give the best results. Preheating can reduce the risk of cracking.",
      selection: "PEEK is the standard choice for general high-performance applications. Ultem is preferred for aerospace applications with flame-retardancy and smoke requirements. Torlon is used for the highest temperature and wear resistance. Carbon-fibre-reinforced versions provide a metal alternative in structural applications.",
    },
    advantages: ["High continuous service temperature", "Strength as a metal alternative", "Chemical resistance", "Flame retardant", "Sterilisable"],
    commonApplications: ["Aerospace interior parts", "Medical devices", "Semiconductor equipment", "High-temperature seals"],
  },
  kompozitler: {
    name: "Composites",
    shortDescription: "Ultra-light, ultra-strong, multi-component",
    heroTitle: "Composite Materials for CNC Machining",
    heroDescription: "G-10/FR-4, carbon-fibre-reinforced polymers and phenolic laminates. Advanced engineering applications.",
    seoTitle: "Composite CNC Machining | G-10, Carbon Fibre, FR-4",
    seoDescription: "Composite materials for CNC machining. G-10/FR-4, carbon fibre laminate, nylon+CF, phenolic laminate. Aerospace, PCB, drones, structural parts.",
    content: {
      intro: "Composite materials are advanced engineering products made by combining two or more different materials, bringing the best properties of each component together in one material. Glass-fibre-reinforced epoxy (G-10/FR-4), carbon fibre laminates and phenolic resin laminates are the composites most widely used in CNC machining.",
      properties: "Composite materials combine low density with high stiffness. They have anisotropic (direction-dependent) mechanical properties; strength is very high along the fibre and markedly lower across it. They offer tailored electrical behaviour such as electrical insulation (G-10) or static dissipation (carbon fibre).",
      applications: "In the electronics industry PCB substrates, insulating sheets and test fixtures are produced. In aerospace they are used for structural panels, interior parts and drone bodies. In motor racing they are preferred for aerodynamic parts and structural components. In robotics light, stiff frames and arms are made.",
      machining: "Composite machining needs techniques and equipment different from metals. Fibre-reinforced materials are highly abrasive and shorten tool life; PCD (polycrystalline diamond) or diamond-coated tools are recommended. Because dust and fibre particles pose a health risk, suitable ventilation and dust extraction should be used.",
      selection: "G-10/FR-4 is the standard for PCBs and electrical insulation. Carbon fibre laminate is preferred for light, stiff structural parts. Phenolic laminate (Bakelite) is used for heat resistance and electrical insulation. Nylon+carbon fibre composites can be considered for light mechanical parts.",
    },
    advantages: ["Ultra-high strength-to-weight ratio", "Tailorable properties", "Corrosion-resistant", "Control of electrical properties"],
    commonApplications: ["PCB substrates", "Drone bodies", "Racing vehicles", "Robot arms", "Aerospace panels"],
  },
};
