import type { MaterialText } from "./types";

/* Material register records, keyed by id (`src/data/materialsData.ts`). */
export const materials: Record<string, MaterialText> = {
  "al-6061-t6": {
    name: "Aluminium 6061-T6",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "The most widely used aluminium alloy. Excellent machinability, good strength and corrosion resistance.",
    applications: ["Aerospace", "Automotive", "Enclosures"],
    advantages: ["Excellent machinability", "Good corrosion resistance", "Widely available"],
    limitations: ["Strength drops at high temperatures", "Loss of strength after welding"],
  },
  "al-7075-t6": {
    name: "Aluminium 7075-T6",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Aerospace grade. Offers strength close to steel but is harder to machine than 6061.",
    applications: ["Aerospace", "Defence", "High-strength structures"],
    advantages: ["Strength close to steel", "Low density", "Good fatigue resistance"],
    limitations: ["Low corrosion resistance", "Not recommended for fusion welding"],
  },
  "al-2024-t3": {
    name: "Aluminium 2024-T3",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "'Aircraft aluminium' for aerospace applications that need high fatigue resistance.",
    applications: ["Aircraft fuselage", "Wing structures", "Gears"],
    advantages: ["High fatigue resistance", "Good strength-to-weight ratio"],
    limitations: ["Low corrosion resistance", "Needs surface coating"],
  },
  "al-5052-h32": {
    name: "Aluminium 5052-H32",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Excellent saltwater corrosion resistance. Ideal for bending and forming.",
    applications: ["Marine", "Fuel tanks", "Sheet work"],
    advantages: ["Excellent corrosion resistance", "Good formability"],
    limitations: ["Low strength", "Cannot be hardened by heat treatment"],
  },
  "al-5083": {
    name: "Aluminium 5083",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Corrosion-resistant, high-strength, non-heat-treatable alloy.",
    applications: ["Marine", "Ship hulls", "Pressure vessels"],
    advantages: ["Resistant to marine environments", "Weldable"],
    limitations: ["Cannot be hardened by heat treatment"],
  },
  "al-6060": {
    name: "Aluminium 6060",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Suited to extrusion; offers a good surface and corrosion resistance for decorative anodising.",
    applications: ["Architecture", "Decorative parts", "Frames"],
    advantages: ["Excellent surface quality", "Anodises very well"],
    limitations: ["Low strength"],
  },
  "al-6063": {
    name: "Aluminium 6063",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Architectural aluminium. High surface quality and anodising results.",
    applications: ["Architectural profiles", "Furniture", "Heat sinks"],
    advantages: ["Excellent surface quality", "Suitable for anodising"],
    limitations: ["Low strength"],
  },
  "al-6082": {
    name: "Aluminium 6082",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Popular for applications under stress; corrosion-resistant and strong.",
    applications: ["Bridges", "Cranes", "Heavy structural parts"],
    advantages: ["Strength equivalent to 6061", "Good corrosion resistance"],
    limitations: ["Slightly lower formability than 6061"],
  },
  "al-2014": {
    name: "Aluminium 2014",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "A strong alloy widely used in aerospace.",
    applications: ["Aerospace", "Defence", "Structural Parts"],
    advantages: ["High strength", "Good machinability"],
    limitations: ["Low corrosion resistance"],
  },
  "al-2017a": {
    name: "Aluminium 2017A",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "A high-strength aluminium alloy known for its excellent machinability.",
    applications: ["Aerospace", "Rivets", "General machine parts"],
    advantages: ["Excellent machinability", "Good strength"],
    limitations: ["Moderate corrosion resistance"],
  },
  "al-7050": {
    name: "Aluminium 7050",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "A heat-treatable aerospace alloy with high toughness and resistance to stress corrosion cracking.",
    applications: ["Aerospace", "Fuselage frames", "Thick plates"],
    advantages: ["High toughness", "Resistant to stress corrosion"],
    limitations: ["Limited availability"],
  },
  "al-mic6": {
    name: "Aluminium MIC-6",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Stress-relieved cast aluminium plate. Low tendency to distort during machining.",
    applications: ["Fixture plates", "Printer beds", "Gauges"],
    advantages: ["Low tendency to distort", "Stress-relieved cast plate"],
    limitations: ["Low strength"],
  },
  "al-6013": {
    name: "Aluminium 6013",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "High-strength 6xxx series. Used in aerospace fuselage panels.",
    applications: ["Aircraft panels", "Automotive", "Structural profiles"],
    advantages: ["Higher strength than 6061", "Good formability"],
    limitations: ["Limited availability"],
  },
  "al-a356": {
    name: "Aluminium A356",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Cast aluminium alloy. Common in automotive wheels and engine parts.",
    applications: ["Automotive wheels", "Engine blocks", "Pump bodies"],
    advantages: ["Good castability", "Heat-treatable"],
    limitations: ["Lower strength than wrought alloys"],
  },
  "st-1045": {
    name: "Steel 1045",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Medium-carbon steel. Good machinability and medium strength. Ideal for general machine parts.",
    applications: ["Shafts", "Gears", "Axles"],
    advantages: ["Good machinability", "Can be hardened by heat treatment"],
    limitations: ["Not corrosion-resistant", "Needs surface coating"],
  },
  "st-4140": {
    name: "Steel 4140",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Versatile chromium-molybdenum alloy. High toughness and fatigue resistance.",
    applications: ["Crankshafts", "Tool holders", "Shafts"],
    advantages: ["High toughness", "Good fatigue resistance", "Can be hardened by heat treatment"],
    limitations: ["Not corrosion-resistant"],
  },
  "st-4340": {
    name: "Steel 4340",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Nickel-chromium-molybdenum. Through-hardenable, for the most demanding conditions.",
    applications: ["Landing gear", "Powertrain"],
    advantages: ["Through-hardens", "Very high strength"],
    limitations: ["Hard to machine", "Not corrosion-resistant"],
  },
  "st-a36": {
    name: "Steel A36",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "The structural steel standard. Weldable and widely available.",
    applications: ["Structural members", "Frames", "Platforms"],
    advantages: ["Widely available", "Easy to weld"],
    limitations: ["Low strength", "Not corrosion-resistant"],
  },
  "st-1018": {
    name: "Steel 1018",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Low-carbon steel. Suitable for case hardening (carburising) and welding.",
    applications: ["Pins", "Bushings", "Welded structures"],
    advantages: ["Excellent weldability", "Surface hardened by carburising"],
    limitations: ["Low strength"],
  },
  "st-8620": {
    name: "Steel 8620",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Nickel-chromium-molybdenum steel. Widely used for case hardening (carburising).",
    applications: ["Gear mechanisms", "Camshafts", "Pins"],
    advantages: ["Excellent carburising response", "Good core toughness"],
    limitations: ["Not corrosion-resistant"],
  },
  "st-d2": {
    name: "Steel D2 (Tool Steel)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "High-carbon, high-chromium cold-work tool steel. Excellent wear resistance.",
    applications: ["Cutting dies", "Punches and dies", "Blades"],
    advantages: ["Excellent wear resistance", "Dimensional stability"],
    limitations: ["Hard to machine", "Brittle"],
  },
  "st-o1": {
    name: "Steel O1 (Tool Steel)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Oil-hardening tool steel. Good machinability and dimensional stability.",
    applications: ["Dies", "Gauges", "Cutting tools"],
    advantages: ["Good machinability", "Easy heat treatment"],
    limitations: ["Low corrosion resistance"],
  },
  "st-s7": {
    name: "Steel S7 (Tool Steel)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Shock-resistant tool steel. Excellent toughness for impact applications.",
    applications: ["Forging dies", "Punches", "Formers"],
    advantages: ["Excellent impact resistance", "Air-hardening"],
    limitations: ["Hard to machine after heat treatment"],
  },
  "st-4150": {
    name: "Steel 4150",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Higher-carbon version of 4140. Higher hardness and wear resistance.",
    applications: ["Gun barrels", "Crankshafts", "Heavy-duty shafts"],
    advantages: ["Harder than 4140", "Good fatigue resistance"],
    limitations: ["Harder to machine than 4140"],
  },
  "st-h13": {
    name: "Steel H13 (Tool Steel)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Hot-work tool steel. The standard for die casting dies.",
    applications: ["Die casting dies", "Extrusion dies", "Hot forging"],
    advantages: ["High-temperature strength", "Good toughness"],
    limitations: ["Hard to machine"],
  },
  "st-p20": {
    name: "Steel P20 (Mould Steel)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Pre-hardened plastic injection mould steel. Needs no heat treatment.",
    applications: ["Plastic injection moulds", "Compression moulds", "Mould bases"],
    advantages: ["Pre-hardened", "Good polishability"],
    limitations: ["Not corrosion-resistant"],
  },
  "ss-304": {
    name: "Stainless Steel 304",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "The most common austenitic stainless steel. Good corrosion resistance and weldability; tends to work-harden when machined.",
    applications: ["Food equipment", "Chemical tanks", "Architecture"],
    advantages: ["Excellent corrosion resistance", "Hygienic", "Weldable"],
    limitations: ["Hard to machine because of work hardening", "Susceptible to pitting in chloride environments"],
  },
  "ss-316l": {
    name: "Stainless Steel 316L",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Molybdenum-alloyed. Superior corrosion resistance in chloride environments and seawater.",
    applications: ["Medical devices", "Marine", "Chemical industry"],
    advantages: ["Superior corrosion resistance", "Biocompatible"],
    limitations: ["Hard to machine because of work hardening"],
  },
  "ss-17-4ph": {
    name: "Stainless Steel 17-4 PH",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Precipitation-hardening martensitic stainless steel. High strength and good corrosion resistance.",
    applications: ["Aerospace", "Valve components", "Turbine blades"],
    advantages: ["High strength", "Can be hardened by heat treatment"],
    limitations: ["Limited weldability"],
  },
  "ss-303": {
    name: "Stainless Steel 303",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Free-machining stainless steel. Optimised for CNC automatic lathes.",
    applications: ["Nuts", "Bolts", "Fittings"],
    advantages: ["The most machinable stainless", "Corrosion resistance close to 304"],
    limitations: ["Not recommended for welding", "Slightly lower corrosion resistance than 304"],
  },
  "ss-321": {
    name: "Stainless Steel 321",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Titanium-stabilised austenitic stainless. Resistant to intergranular corrosion at high temperature.",
    applications: ["Exhaust manifolds", "Heat exchangers", "Chemical process"],
    advantages: ["High-temperature corrosion resistance", "Better welding than 304"],
    limitations: ["Hard to machine because of work hardening"],
  },
  "ss-440c": {
    name: "Stainless Steel 440C",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "High-carbon martensitic stainless. The highest hardness and wear resistance.",
    applications: ["Bearing balls", "Valve parts", "Blades"],
    advantages: ["The hardest stainless", "Excellent wear resistance"],
    limitations: ["Low corrosion resistance", "Brittle"],
  },
  "ss-2205": {
    name: "Stainless Steel 2205 (Duplex)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Duplex (austenitic-ferritic) stainless. Markedly higher yield strength than 304.",
    applications: ["Chemical tanks", "Petrochemical", "Offshore structures"],
    advantages: ["Markedly higher yield strength than 304", "Excellent corrosion resistance"],
    limitations: ["Hard to machine"],
  },
  "ss-316ti": {
    name: "Stainless Steel 316Ti",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Titanium-stabilised 316 stainless. Resistant to intergranular corrosion at high temperatures.",
    applications: ["Heat exchangers", "Chemical reactors", "Exhaust manifolds"],
    advantages: ["High-temperature corrosion resistance"],
    limitations: ["Hard to machine because of work hardening"],
  },
  "ss-347": {
    name: "Stainless Steel 347",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Niobium-stabilised austenitic stainless. An alternative to 321 in high-temperature applications.",
    applications: ["Jet engine parts", "Heat exchangers", "Nuclear reactors"],
    advantages: ["High-temperature corrosion resistance", "Better welding than 321"],
    limitations: ["Hard to machine because of work hardening"],
  },
  "br-c360": {
    name: "Brass C360",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Free-machining brass. The best performance in chip removal.",
    applications: ["Valves", "Fasteners", "Electronic connectors"],
    advantages: ["The best machinability", "Decorative appearance"],
    limitations: ["Low strength", "Sensitive to ammonia"],
  },
  "br-c932": {
    name: "Bronze C932 (SAE 660)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Leaded tin bronze. Excellent friction and oil retention properties.",
    applications: ["Plain bearings", "Bushings"],
    advantages: ["Excellent oil retention", "Low friction"],
    limitations: ["Contains lead"],
  },
  "br-c954": {
    name: "Aluminium Bronze C954",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "A high-strength bronze alloy. Strength close to steel.",
    applications: ["Heavy-duty bearings", "Marine hardware", "Gears"],
    advantages: ["High strength", "Excellent seawater resistance"],
    limitations: ["Hard to machine"],
  },
  "br-c260": {
    name: "Brass C260 (Cartridge Brass)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "70% copper, 30% zinc. Excellent cold forming capability.",
    applications: ["Cartridge cases", "Radiator cores", "Decorative hardware"],
    advantages: ["Excellent formability", "Good corrosion resistance"],
    limitations: ["Lower machinability than C360"],
  },
  "br-c464": {
    name: "Brass C464 (Naval Brass)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Tin-alloyed naval brass. Excellent resistance to saltwater corrosion.",
    applications: ["Ship parts", "Sea valves", "Pump bodies"],
    advantages: ["Excellent seawater resistance", "Resistant to dezincification"],
    limitations: ["Moderate machinability"],
  },
  "br-c510": {
    name: "Phosphor Bronze C510",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "High elastic limit for spring and contact applications.",
    applications: ["Springs", "Contacts", "Diaphragms"],
    advantages: ["High elastic limit", "Good corrosion resistance"],
    limitations: ["Hard to machine"],
  },
  "cu-c101": {
    name: "Copper C101",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Oxygen-free copper. Purity 99.99%.",
    applications: ["Electronic vacuum tubes", "Superconductors"],
    advantages: ["The highest conductivity", "Oxygen-free"],
    limitations: ["Sticky chips; hard to machine"],
  },
  "cu-c110": {
    name: "Copper C110",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Electrolytic copper (ETP — Electrolytic Tough Pitch). The standard electrical conductor copper.",
    applications: ["Electrical busbars", "Earthing", "Gaskets"],
    advantages: ["Excellent electrical conductivity"],
    limitations: ["Low machinability"],
  },
  "cu-c122": {
    name: "Copper C122 (DHP)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Phosphorus-deoxidised high-residual-phosphorus copper. The standard for heat exchangers and plumbing pipes.",
    applications: ["Plumbing pipes", "Heat exchangers", "Hot water systems"],
    advantages: ["Good weldability/solderability", "High conductivity"],
    limitations: ["Low machinability"],
  },
  "cu-c145": {
    name: "Copper C145 (Tellurium Copper)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Tellurium-alloyed free-machining copper. A combination of machinability and conductivity.",
    applications: ["Electrical fittings", "Motor commutators", "Contactors"],
    advantages: ["The best machinability among coppers", "High conductivity"],
    limitations: ["Slightly lower conductivity than C110"],
  },
  "ti-grade2": {
    name: "Titanium Grade 2",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Commercially pure titanium. Excellent corrosion resistance and biocompatibility.",
    applications: ["Medical devices", "Chemical industry", "Marine"],
    advantages: ["Excellent corrosion resistance", "Biocompatible", "Light"],
    limitations: ["Low machinability"],
  },
  "ti-grade5": {
    name: "Titanium Grade 5 (Ti-6Al-4V)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "The most common titanium alloy. High strength-to-weight ratio. The aerospace standard.",
    applications: ["Jet engine parts", "Medical components", "Racing equipment"],
    advantages: ["Strength close to steel", "Markedly lighter than steel"],
    limitations: ["Very hard to machine"],
  },
  "ti-grade9": {
    name: "Titanium Grade 9 (Ti-3Al-2.5V)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Medium-strength titanium alloy. Good formability and corrosion resistance.",
    applications: ["Bicycle frames", "Hydraulic tubing", "Marine"],
    advantages: ["Good formability", "Good corrosion resistance"],
    limitations: ["Lower strength than Grade 5"],
  },
  "ti-grade23": {
    name: "Titanium Grade 23 (Ti-6Al-4V ELI)",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Extra Low Interstitial (ELI) version. For applications that need higher toughness and biocompatibility.",
    applications: ["Medical components", "Surgical instruments", "Aerospace"],
    advantages: ["Biocompatible", "Better toughness than Grade 5"],
    limitations: ["Hard to machine"],
  },
  "ni-625": {
    name: "Inconel 625",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Nickel-chromium alloy. Extremely resistant to oxidation and corrosion.",
    applications: ["Subsea", "Exhaust systems", "Nuclear"],
    advantages: ["Oxidation resistance at high temperature", "Excellent corrosion resistance"],
    limitations: ["Very hard to machine"],
  },
  "ni-718": {
    name: "Inconel 718",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "A superalloy that keeps its high strength at temperature.",
    applications: ["Jet engines", "Rocket parts"],
    advantages: ["Keeps its strength at high temperature", "Precipitation-hardening"],
    limitations: ["Very hard to machine"],
  },
  "ni-monel400": {
    name: "Monel 400",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Nickel-copper alloy. Excellent resistance to seawater and acids.",
    applications: ["Marine valves", "Chemical process", "Oil refineries"],
    advantages: ["Excellent resistance to seawater", "Resistant to acids"],
    limitations: ["Prone to work hardening; hard to machine"],
  },
  "ni-hastelloyc276": {
    name: "Hastelloy C-276",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Molybdenum-tungsten-alloyed nickel alloy. For the harshest conditions in chemical processing.",
    applications: ["Chemical reactors", "Acid production plants", "Flue gas desulphurisation"],
    advantages: ["The widest range of corrosion resistance", "Resistant to oxidising and reducing environments"],
    limitations: ["Very hard to machine"],
  },
  "mg-az31b": {
    name: "Magnesium AZ31B",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "The most widely used magnesium alloy. Light, good formability.",
    applications: ["Electronic enclosures", "Automotive panels", "Camera bodies"],
    advantages: ["Very light", "Good formability"],
    limitations: ["Susceptible to corrosion", "Flammable chips"],
  },
  "mg-az61a": {
    name: "Magnesium AZ61A",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "Higher strength than AZ31B. Suitable for extruded profiles.",
    applications: ["Aerospace brackets", "Structural profiles", "Sports equipment"],
    advantages: ["Higher strength than AZ31B", "Good machinability"],
    limitations: ["Susceptible to corrosion", "Flammable chips"],
  },
  "mg-az80a": {
    name: "Magnesium AZ80A",
    propertyConditions: "Room temperature; values vary with temper and heat treatment condition",
    description: "High-strength wrought magnesium alloy. Aerospace structural parts.",
    applications: ["Aerospace gears", "Aircraft housings", "Motorsport"],
    advantages: ["High strength", "Light"],
    limitations: ["Susceptible to corrosion", "Flammable chips"],
  },
  "pl-abs": {
    name: "ABS",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A durable, general-purpose plastic.",
    applications: ["Prototypes", "Covers", "Toys"],
    advantages: ["Good impact strength", "Easy to machine"],
    limitations: ["Low temperature resistance", "Sensitive to UV"],
  },
  "pl-pmma": {
    name: "Acrylic (PMMA/Plexiglass)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A transparent alternative to glass. Gives optical clarity when polished.",
    applications: ["Screen protectors", "Signs", "Light pipes"],
    advantages: ["Optical clarity", "UV resistance"],
    limitations: ["Brittle", "Prone to scratching"],
  },
  "pl-delrin": {
    name: "Delrin (POM/Acetal)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "An engineering plastic for mechanical parts that need high precision.",
    applications: ["Gears", "Bearings", "Guide rails"],
    advantages: ["Excellent machinability", "Low friction", "Dimensional stability"],
    limitations: ["Hard to bond (needs special surface preparation)", "Not suitable for painting"],
  },
  "pl-nylon": {
    name: "Nylon (PA6/PA66)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "An engineering plastic with high wear resistance and mechanical strength.",
    applications: ["Gears", "Rolling bearings", "Belt pulleys"],
    advantages: ["High wear resistance", "Good strength"],
    limitations: ["Absorbs moisture", "Dimensional change"],
  },
  "pl-pc": {
    name: "Polycarbonate (PC)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A transparent engineering plastic with high impact strength.",
    applications: ["Protective shields", "Optical lenses", "Medical devices"],
    advantages: ["Exceptional impact strength", "Optical clarity"],
    limitations: ["Prone to scratching", "Moderate chemical resistance"],
  },
  "pl-ptfe": {
    name: "PTFE (Teflon)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "The plastic with the lowest coefficient of friction. Almost chemically inert.",
    applications: ["Gaskets", "Bearings", "Chemical lining"],
    advantages: ["The lowest friction", "Resistant to most chemicals", "High-temperature strength"],
    limitations: ["Low strength", "Tendency to creep"],
  },
  "pl-pvc": {
    name: "PVC",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A chemical-resistant, flame-retardant structural plastic.",
    applications: ["Pipes", "Tank linings", "Electrical conduits"],
    advantages: ["Good chemical resistance", "Flame retardant"],
    limitations: ["Low temperature resistance", "Low impact strength"],
  },
  "pl-hdpe": {
    name: "HDPE",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "High-density polyethylene. Slippery and chemical-resistant.",
    applications: ["Cutting boards", "Chemical tanks"],
    advantages: ["Very light", "Chemical-resistant", "Food-contact grades available"],
    limitations: ["Low strength", "Hard to bond"],
  },
  "pl-pp": {
    name: "Polypropylene (PP)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A light, chemical-resistant plastic suitable for hinges.",
    applications: ["Living hinges", "Chemical tanks", "Laboratory equipment"],
    advantages: ["One of the lightest plastics", "Excellent chemical resistance", "Fatigue resistance"],
    limitations: ["Sensitive to UV", "Hard to bond"],
  },
  "pl-uhmwpe": {
    name: "UHMW-PE",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Ultra-high-molecular-weight polyethylene. Excellent wear resistance and low friction.",
    applications: ["Conveyor guides", "Wear plates", "Food processing"],
    advantages: ["Excellent wear resistance", "One of the lowest coefficients of friction"],
    limitations: ["Low strength", "Sensitive to heat"],
  },
  "pl-pei": {
    name: "PEI (Ultem)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Amber-coloured high-temperature engineering plastic. Flame retardant.",
    applications: ["Aerospace interior parts", "Electrical insulators", "Medical instruments"],
    advantages: ["Flame retardant", "Sterilisable", "Good electrical insulation"],
    limitations: ["Sensitive to UV"],
  },
  "pl-cpvc": {
    name: "CPVC",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Chlorinated PVC. Superior to standard PVC for hot water and corrosive chemicals.",
    applications: ["Hot water pipes", "Chemical pipes", "Fire sprinkler lines"],
    advantages: ["Higher temperature than PVC", "Flame retardant", "Chemical-resistant"],
    limitations: ["Low impact strength"],
  },
  "pl-noryl": {
    name: "Noryl (PPO/PPE)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Modified polyphenylene oxide. Dimensional stability and low moisture absorption.",
    applications: ["Automotive dashboards", "Water treatment equipment", "Power tool housings"],
    advantages: ["Low moisture absorption", "Dimensional stability", "Light"],
    limitations: ["Sensitive to UV"],
  },
  "pl-pa66-gf30": {
    name: "PA66 + 30% Glass Fibre",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Glass-fibre-reinforced nylon. Increased strength and temperature resistance.",
    applications: ["Engine covers", "Fan blades", "Structural brackets"],
    advantages: ["High strength", "Good temperature resistance"],
    limitations: ["Abrasive chips", "Brittle"],
  },
  "pl-pps": {
    name: "PPS (Polyphenylene Sulphide)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A semi-crystalline thermoplastic with high temperature and chemical resistance.",
    applications: ["Automotive engine parts", "Pump bodies", "Chemical process"],
    advantages: ["Excellent chemical resistance", "High temperature", "Dimensional stability"],
    limitations: ["Brittle"],
  },
  "pl-pbt": {
    name: "PBT (Polybutylene Terephthalate)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Semi-crystalline thermoplastic. Ideal for electrical connectors and automotive parts.",
    applications: ["Electrical connectors", "Automotive sensors", "Switch housings"],
    advantages: ["Good electrical properties", "Fast crystallisation"],
    limitations: ["Sensitive to moisture"],
  },
  "pl-pet": {
    name: "PET (Polyethylene Terephthalate)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A transparent or white semi-crystalline plastic. Food-contact grades are available.",
    applications: ["Food packaging", "Medical devices", "Electrical insulators"],
    advantages: ["Food-contact grades available", "Good dimensional stability"],
    limitations: ["Absorbs moisture"],
  },
  "pl-peek": {
    name: "PEEK",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "High-performance semi-crystalline thermoplastic. Strength and temperature resistance as a metal alternative.",
    applications: ["Aerospace", "Medical components", "Semiconductor"],
    advantages: ["Metal alternative", "Sterilisable", "High-temperature strength"],
    limitations: ["Needs special tooling"],
  },
  "pl-torlon": {
    name: "Torlon (PAI)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "The highest-performance melt-processable plastic. Strength that replaces metal.",
    applications: ["Jet engine parts", "Semiconductor equipment", "High-temperature bearings"],
    advantages: ["High strength at high temperature", "Strength as a metal alternative"],
    limitations: ["Hard to machine"],
  },
  "pl-vespel": {
    name: "Vespel (PI)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "DuPont Vespel polyimide. Extreme temperature and wear resistance.",
    applications: ["Spacecraft", "Semiconductor", "Jet engines"],
    advantages: ["Very high continuous service temperature", "Excellent wear resistance"],
    limitations: ["Limited availability"],
  },
  "pl-peek-gf30": {
    name: "PEEK + 30% Glass Fibre",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Glass-fibre-reinforced PEEK. Increased stiffness and dimensional stability.",
    applications: ["Structural brackets", "Pump parts", "Compressor parts"],
    advantages: ["Stiffer than PEEK", "Low thermal expansion"],
    limitations: ["Abrasive chips"],
  },
  "pl-peek-cf30": {
    name: "PEEK + 30% Carbon Fibre",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Carbon-fibre-reinforced PEEK. The highest-performance polymer composite.",
    applications: ["Aerospace", "Semiconductor", "Medical"],
    advantages: ["Ultra-high strength-to-weight", "Static dissipative"],
    limitations: ["Abrasive chips; diamond or PCD tooling may be needed"],
  },
  "pl-psu": {
    name: "Polysulfone (PSU)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "A transparent, high-temperature engineering plastic. Autoclavable.",
    applications: ["Medical devices", "Dairy industry", "Water filtration"],
    advantages: ["Transparent", "Sterilisable", "Food-contact grades available"],
    limitations: ["Sensitive to UV"],
  },
  "pl-ppsu": {
    name: "PPSU (Radel)",
    propertyConditions: "23 °C, dry (unconditioned); varies with humidity and temperature",
    description: "Polyphenylsulfone. The high-temperature plastic with the highest impact strength.",
    applications: ["Surgical instrument trays", "Aircraft interior parts", "Hot water fittings"],
    advantages: ["High impact strength", "Withstands repeated autoclaving"],
    limitations: ["Stress relieving may be needed after machining"],
  },
  "co-g10": {
    name: "G-10 / FR-4",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "Glass-fibre-reinforced epoxy laminate. The standard for electrical insulation.",
    applications: ["PCB", "Electrical insulators", "Drone bodies"],
    advantages: ["Excellent electrical insulation", "High strength"],
    limitations: ["Abrasive chips", "Dust health risk"],
  },
  "co-cf-laminat": {
    name: "Carbon Fibre Laminate",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "Carbon-fibre-reinforced epoxy sheet. Ultra-light and ultra-strong.",
    applications: ["Racing vehicles", "Drone frames", "Prosthetic components"],
    advantages: ["The highest strength-to-weight ratio", "Excellent stiffness"],
    limitations: ["Abrasive chips", "Anisotropic"],
  },
  "co-nylon-cf": {
    name: "Nylon + Carbon Fibre",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "Carbon-fibre-reinforced nylon. For light, stiff structural parts.",
    applications: ["Drone frames", "Robot arms", "3D printing"],
    advantages: ["Light", "Stiff", "Wear resistance"],
    limitations: ["Absorbs moisture", "Anisotropic"],
  },
  "co-phenolic": {
    name: "Phenolic Laminate (Bakelite)",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "The first synthetic plastic. Still used for heat resistance and electrical insulation.",
    applications: ["Electrical insulators", "Brake linings", "Pan handles"],
    advantages: ["Heat resistance", "Electrical insulation"],
    limitations: ["Brittle", "Limited colour options"],
  },
  "co-ultem-cf": {
    name: "Ultem + Carbon Fibre",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "Carbon-fibre-reinforced PEI. For aerospace structural components.",
    applications: ["Aerospace interior structures", "Satellite components", "Racing cars"],
    advantages: ["Flame retardant + structural", "Light"],
    limitations: ["Needs special machining"],
  },
  "co-garolite": {
    name: "Garolite G-11",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "The high-temperature version of G-10.",
    applications: ["High-temperature insulators", "Transformer parts", "Motor insulation"],
    advantages: ["Higher temperature than G-10", "Excellent insulation"],
    limitations: ["Abrasive", "Health-risk chips"],
  },
  "co-kevlar": {
    name: "Kevlar Laminate",
    propertyConditions: "Along the fibre, room temperature; markedly lower across the fibre",
    description: "Aramid-fibre-reinforced epoxy. Impact-absorbing, light, high toughness.",
    applications: ["Ballistic protection", "Ski equipment", "Marine hulls"],
    advantages: ["Excellent impact absorption", "Very light", "High toughness"],
    limitations: ["Very hard to machine", "Absorbs moisture"],
  },
};
