-- ════════════════════════════════════════════════════════════════════════
-- BASE OPERATIONAL TABLES (polish run 2026-09-30) — NOT APPLIED TO PRODUCTION
--
-- Five tables every later migration ALTERs or adds policies to were never
-- CREATEd by any migration: customers, rfqs, orders, wbs, issues (and
-- documents, which only ever received policies). They exist in the live
-- Lovable-managed project, so `supabase db reset` on a fresh database failed
-- at 20260217215210 ("relation public.rfqs does not exist").
--
-- This file is timestamped BEFORE the first migration so a reset creates the
-- tables first. Every statement is idempotent (IF NOT EXISTS), so applying it
-- to the live project is a no-op. Shapes follow docs/supabase-full-setup.sql
-- and src/integrations/supabase/types.ts; later migrations still add their own
-- columns with ADD COLUMN IF NOT EXISTS.
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.customers (
  id          integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name        text,
  short_name  text,
  company     text,
  email       text,
  phone       text,
  city        text,
  address     text,
  tax_info    text,
  iban        text,
  balance     numeric,
  last_order  date,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.rfqs (
  id          text PRIMARY KEY,
  customer    text,
  company     text,
  email       text,
  phone       text,
  service     text,
  material    text,
  quantity    integer,
  notes       text,
  files       text[],
  status      text,
  date        date,
  quoted_price numeric,
  rejection_reason text,
  created_at  timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.orders (
  id            text PRIMARY KEY,
  customer      text,
  part_name     text,
  quantity      integer,
  completed_qty integer NOT NULL DEFAULT 0,
  qc_passed_qty integer NOT NULL DEFAULT 0,
  packed_qty    integer NOT NULL DEFAULT 0,
  machine       text,
  notes         text,
  status        text,
  progress      integer,
  order_date    date,
  deadline      date,
  rfq_ref       text,
  created_at    timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.wbs (
  id           text PRIMARY KEY,
  order_id     text,
  customer     text,
  part_name    text,
  machine      text,
  current_step integer,
  total_qty    integer,
  status       text,
  deadline     date,
  created_at   timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.issues (
  id         text PRIMARY KEY,
  job        text,
  machine    text,
  category   text,
  severity   text,
  status     text,
  detail     text,
  resolution text,
  date       date,
  cost       numeric,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.documents (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title      text NOT NULL,
  file_urls  text[],
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rfqs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wbs       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.issues    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
