// Originally generated by Lovable. The credentials it inlined here now come
// from the environment (see ./env); regenerating this file must not put them
// back into source.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from './env';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/* `localStorage` read here, at module load, threw a SecurityError when the
   browser blocks site storage and took every route that imports the client
   (sign-in, quote) down with it. `undefined` lets supabase-js pick its own
   default: localStorage when it is usable, memory otherwise (L01 scenario). */
function usableLocalStorage(): Storage | undefined {
  try {
    const storage = window.localStorage;
    storage.getItem("__mas_probe__");
    return storage;
  } catch {
    return undefined;
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: usableLocalStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});