import type { FamilyText } from "@/content/en/types";

/* Werkstofffamilien-Seiten, nach Slug geordnet (`src/data/materialsData.ts`). */
export const families: Record<string, FamilyText> = {
  aluminyum: {
    name: "Aluminium",
    shortDescription: "Leicht, gut zerspanbar, korrosionsbeständig",
    heroTitle: "Aluminiumlegierungen für die CNC-Zerspanung",
    heroDescription: "CNC-Präzisionsteile aus Aluminiumlegierungen, von der Luft- und Raumfahrt bis zum Automobil, von 6061-T6 bis 7075-T6.",
    seoTitle: "Aluminium CNC-Zerspanung | Legierungen 6061, 7075, 2024",
    seoDescription: "Aluminiumlegierungen für CNC-Fräsen und CNC-Drehen. 6061-T6, 7075-T6, 2024-T3 und weitere. Leicht, korrosionsbeständig, hervorragend zerspanbar.",
    content: {
      intro: "Aluminium gehört zu den am häufigsten gewählten Werkstofffamilien in der CNC-Zerspanung. Dank ihrer geringen Dichte sind Aluminiumlegierungen deutlich leichter als Stahl, und ihre gute Zerspanbarkeit macht die spanende Bearbeitung sehr produktiv. Die Legierungen der Serien 2xxx, 5xxx, 6xxx und 7xxx bieten eine große Auswahl für unterschiedliche Anforderungen an Festigkeit und Korrosionsbeständigkeit.",
      properties: "Aluminiumlegierungen zeichnen sich durch geringe Dichte und hohe Wärmeleitfähigkeit aus, ein Vorteil bei Anwendungen mit Wärmeabfuhr. Die Festigkeit variiert je nach Serie und Werkstoffzustand stark: Die Serie 7xxx ist hochfest, die Serien 5xxx und 6xxx sind mittelfest. Durch Eloxieren lassen sich Oberflächenhärte und Korrosionsbeständigkeit erhöhen.",
      applications: "In der Luft- und Raumfahrt wird es für Rumpfpaneele, Flügelstrukturen und Innenraumteile eingesetzt. In der Automobilindustrie dient es für Motorblöcke, Räder und Strukturbauteile. In der Elektronik wird es für Kühlkörper, Gehäuse und Chassisteile bevorzugt. Verbreitet ist es zudem bei Gehäusen für Medizingeräte, Schiffsbeschlägen und Architekturprofilen.",
      machining: "Aluminium lässt sich mit allen CNC-Verfahren leicht bearbeiten. Es erlaubt hohe Schnittgeschwindigkeiten beim 3- und 5-Achs-Fräsen, Drehen, Bohren und Gewindeschneiden. 6061-T6 und 6082 sind für ihre gute Zerspanbarkeit bekannt. Hochfeste Legierungen wie 7075 erfordern eine sorgfältigere Parameterwahl.",
      selection: "Für allgemeine Anwendungen ist 6061-T6 eine vielseitige Wahl. Für Strukturteile mit hohen Festigkeitsanforderungen wird 7075-T6 bevorzugt. 5052 oder 5083 eignen sich für maritime und korrosive Umgebungen. In der Luft- und Raumfahrt kommen 2024-T3 oder 7050 zum Einsatz. Für Präzisionsvorrichtungs- und Werkzeugplatten wird MIC-6 empfohlen.",
    },
    advantages: ["Geringes Gewicht", "Hervorragende Zerspanbarkeit", "Gute Korrosionsbeständigkeit", "Eloxierbar", "Hohe Wärmeleitfähigkeit", "Recycelbar"],
    commonApplications: ["Teile für die Luft- und Raumfahrt", "Automobilkomponenten", "Elektronikgehäuse", "Wärmeverteiler", "Strukturprofile", "Gehäuse für Medizingeräte"],
  },
  celik: {
    name: "Stahl",
    shortDescription: "Hohe Festigkeit, Wärmebehandlung, große Legierungsauswahl",
    heroTitle: "Stahllegierungen für die CNC-Zerspanung",
    heroDescription: "1045, 4140, 4340 und weitere. CNC-Zerspanung hochfester Stähle für Anwendungen der Schwerindustrie.",
    seoTitle: "Stahl CNC-Zerspanung | Legierungen 1045, 4140, 4340",
    seoDescription: "Stahllegierungen für CNC-Fräsen und CNC-Drehen. 1045, 4140, 4340, A36 – Kohlenstoffstähle und legierte Stähle. Hohe Festigkeit, Wärmebehandlung.",
    content: {
      intro: "Stahllegierungen sind das Rückgrat der industriellen CNC-Zerspanung. Kohlenstoffstähle (1018, 1045) werden für allgemeine Anwendungen eingesetzt, legierte Stähle (4140, 4340) sind für kritische Teile mit hohen Anforderungen an Festigkeit und Zähigkeit ausgelegt. Durch Wärmebehandlung lassen sich die mechanischen Eigenschaften in einem weiten Bereich einstellen.",
      properties: "Festigkeit und Härte von Stahllegierungen variieren stark mit Kohlenstoff- und Legierungsgehalt sowie dem Wärmebehandlungszustand. Die Oberflächenhärte lässt sich durch Randschichthärteverfahren wie Einsatzhärten, Nitrieren und Induktionshärten erhöhen; die anzuwendende Wärmebehandlung legt die Spezifikation fest.",
      applications: "Im Maschinenbau wird er für Wellen, Zahnräder, Kurbelwellen und Verbindungselemente eingesetzt. In der Automobilindustrie dient er für Antriebsstrang, Fahrwerksteile und Chassiskomponenten. Im Energiesektor wird er für Turbinenwellen und Druckbehälter bevorzugt. In der Verteidigungsindustrie findet er sich in Waffensystemen und Panzerplatten.",
      machining: "Kohlenstoffstähle (1018, 1045) lassen sich bei moderaten Schnittgeschwindigkeiten leicht bearbeiten. Legierte Stähle (4140) erfordern niedrigere Schnittgeschwindigkeiten und steife Werkzeugaufnahmen. Hochfeste Stähle wie 4340 können mit CBN- oder Keramik-Wendeschneidplatten bearbeitet werden. Für alle Stahlsorten wird Kühlschmierstoff empfohlen.",
      selection: "1045 eignet sich für allgemeine Wellen und Achsen. 4140 wird für Teile mit hohen Anforderungen an Zähigkeit und Dauerfestigkeit bevorzugt. 4340 kommt in der Luft- und Raumfahrt und Verteidigung zum Einsatz. A36 ist eine gängige Wahl für Tragrahmen und Plattformen.",
    },
    advantages: ["Hohe Festigkeit", "Eigenschaften durch Wärmebehandlung einstellbar", "Gut schweißbar", "Große Legierungsauswahl"],
    commonApplications: ["Wellen und Achsen", "Getriebe", "Kurbelwellen", "Strukturteile", "Werkzeughalter"],
  },
  "paslanmaz-celik": {
    name: "Edelstahl",
    shortDescription: "Korrosionsbeständig, hygienisch, langlebig",
    heroTitle: "Edelstahl für die CNC-Zerspanung",
    heroDescription: "304, 316L, 17-4 PH und weitere. CNC-Zerspanung von Edelstahl für Lebensmittel-, Medizin- und Chemieindustrie.",
    seoTitle: "Edelstahl CNC-Zerspanung | 304, 316L, 17-4 PH",
    seoDescription: "Edelstahllegierungen für die CNC-Zerspanung. 304, 316L, 17-4 PH, 303, 321, 347. Korrosionsbeständigkeit, Hygiene, Medizintechnik und Lebensmittelbranche.",
    content: {
      intro: "Edelstahl ist die Familie der Stähle mit mindestens 10,5 % Chrom (EN 10088), das an der Oberfläche eine schützende Chromoxidschicht bildet. Austenitische (304, 316L), martensitische (440C), ausscheidungshärtende (17-4 PH), Duplex- (2205) und ferritische Sorten bieten unterschiedliche Kombinationen aus Korrosionsbeständigkeit und mechanischen Eigenschaften.",
      properties: "Die Festigkeit von Edelstählen hängt von der Sorte ab: Austenitische Sorten sind mittelfest und zäh, ausscheidungshärtende und martensitische Sorten hochfest. Lösungsgeglühte austenitische Sorten sind nicht magnetisch und bleiben auch bei tiefen Temperaturen zäh. Die Einsatztemperatur richtet sich nach Sorte und Umgebung.",
      applications: "Verbreitet in hygienischen Tanks, Rohrleitungen und Prozessanlagen der Lebensmittel- und Getränkeindustrie. In der Medizintechnik für chirurgische Instrumente und Sterilisationsgeräte eingesetzt. In der Chemieindustrie für Reaktoren und Rohrleitungen in korrosiven Umgebungen bevorzugt. In der Architektur in dekorativen Paneelen und Geländern zu finden.",
      machining: "Edelstahl ist schlechter zerspanbar als Aluminium und Kohlenstoffstahl. Seine Neigung zur Kaltverfestigung erfordert kontinuierliche, stabile Schnittparameter. Die Sorte 303 ist als zerspanungsoptimierte Automatensorte ausgelegt. Empfohlen werden niedrige Schnittgeschwindigkeiten, hoher Vorschub und Werkzeuge mit positivem Spanwinkel.",
      selection: "304 ist die gängigste Wahl für allgemeine Korrosionsbeständigkeit. 316L wird für chloridhaltige Umgebungen und Meerwasser bevorzugt. 17-4 PH kommt bei hoher Festigkeit mit mäßiger Korrosionsbeständigkeit zum Einsatz. 303 wird gewählt, wenn die Zerspanbarkeit im Vordergrund steht. Für Hochtemperaturanwendungen werden 321 oder 347 empfohlen.",
    },
    advantages: ["Hervorragende Korrosionsbeständigkeit", "Hygienische Oberfläche", "Warmfestigkeit", "Ansprechende Optik", "Lange Lebensdauer"],
    commonApplications: ["Lebensmittelanlagen", "Medizingeräte", "Chemische Prozesse", "Architekturpaneele", "Schiffsbeschläge"],
  },
  titanyum: {
    name: "Titan",
    shortDescription: "Luftfahrtqualität, biokompatibel, leicht",
    heroTitle: "Titanlegierungen für die CNC-Zerspanung",
    heroDescription: "Grade 2, Grade 5 (Ti-6Al-4V) und Grade 9. Der Premiumwerkstoff der Luft- und Raumfahrt und der Medizintechnik.",
    seoTitle: "Titan CNC-Zerspanung | Ti-6Al-4V, Grade 2, Grade 5",
    seoDescription: "Titanlegierungen für die CNC-Zerspanung. Ti-6Al-4V (Grade 5), Grade 2, Grade 9. Komponenten für Luft- und Raumfahrt und Medizintechnik, hohes Festigkeits-Gewichts-Verhältnis.",
    content: {
      intro: "Mit seinem hohen Festigkeits-Gewichts-Verhältnis, seiner hervorragenden Korrosionsbeständigkeit und Biokompatibilität ist Titan einer der Kernwerkstoffe der Luft- und Raumfahrt und der Medizintechnik. Reintitansorten (Grade 1-4) und legierte Sorten (Grade 5, 9, 23) bieten unterschiedliche Optionen. Obwohl deutlich leichter als Stahl, erreichen die legierten Sorten eine vergleichbare Festigkeit.",
      properties: "Titanlegierungen verbinden geringe Dichte mit hoher Festigkeit; Reintitansorten sind mittelfest, Grade 5 ist hochfest. Die Korrosionsbeständigkeit in Meerwasser und vielen sauren Medien ist sehr hoch. Die geringe Wärmeleitfähigkeit führt bei der Zerspanung zu Wärmestau in der Schnittzone und erfordert Sorgfalt.",
      applications: "In der Luft- und Raumfahrt für Verdichterschaufeln, Verbindungselemente der Flugzeugzelle und Fahrwerksteile eingesetzt. In der Medizintechnik für chirurgische Instrumente und Komponenten von Medizingeräten bevorzugt. Zu finden in Anlagen für korrosive Umgebungen in der Chemieindustrie sowie in Schiffs- und Rennsporttechnik.",
      machining: "Die Zerspanung von Titan erfordert Erfahrung. Die geringe Wärmeleitfähigkeit verursacht einen starken Wärmestau in der Schnittzone. Einzusetzen sind niedrige Schnittgeschwindigkeiten, Hochdruck-Kühlschmierstoff und scharfe Hartmetallwerkzeuge. Wegen der Neigung zum Anhaften der Späne werden beschichtete Werkzeuge empfohlen.",
      selection: "Grade 2 eignet sich für Anwendungen, bei denen Korrosionsbeständigkeit und Umformbarkeit im Vordergrund stehen. Grade 5 (Ti-6Al-4V) ist die Standardwahl für Strukturteile mit hohen Festigkeitsanforderungen. Grade 9 kommt für mittlere Festigkeit bei guter Umformbarkeit in Frage. ELI (Extra Low Interstitial) Grade 23 wird bevorzugt, wenn höhere Zähigkeit gefordert ist.",
    },
    advantages: ["Hohes Festigkeits-Gewichts-Verhältnis", "Hervorragende Korrosionsbeständigkeit", "Biokompatibilität", "Warmfestigkeit", "Nicht magnetisch"],
    commonApplications: ["Flugzeugteile", "Medizinische Komponenten", "Chemische Prozessanlagen", "Schiffstechnik", "Rennsporttechnik"],
  },
  "pirinc-bronz": {
    name: "Messing & Bronze",
    shortDescription: "Spitzenreiter der Zerspanbarkeit, geringe Reibung",
    heroTitle: "Messing- und Bronzelegierungen für die CNC-Zerspanung",
    heroDescription: "C360, C932, C954 und weitere. Hervorragende Zerspanbarkeit für Ventile, Lager und Verbindungselemente.",
    seoTitle: "Messing & Bronze CNC-Zerspanung | C360, C932, C954",
    seoDescription: "Messing- und Bronzelegierungen für die CNC-Zerspanung. C360, C932 SAE 660, C954 Aluminiumbronze. Ventile, Lager, Schiffsteile.",
    content: {
      intro: "Messing- (Kupfer-Zink) und Bronzelegierungen (Kupfer-Zinn) gehören zu den am leichtesten CNC-zerspanbaren Werkstoffen. Automatenmessing C360 gilt als Referenzwerkstoff für die spanende Bearbeitung. Bronzelegierungen sind mit ihrem niedrigen Reibungskoeffizienten und ihrem hervorragenden Ölhaltevermögen ideal für Gleitlager.",
      properties: "Die Festigkeit von Messing- und Bronzelegierungen hängt von der Legierung ab: Bleihaltige Lagerbronzen sind niedrigfest, Aluminiumbronzen hochfest. Ihre elektrische und thermische Leitfähigkeit ist deutlich höher als die von Stahl.",
      applications: "In Hydraulik- und Pneumatiksystemen werden sie für Ventilkörper, Fittings und Adapter eingesetzt. Im Maschinenbau werden sie für Gleitlager, Buchsen und Zahnräder bevorzugt. Im maritimen Bereich dienen sie für Propeller, Ventile und Rohrverbindungsteile. In der Elektrotechnik werden daraus Steckverbinder, Klemmen und Stromschienen gefertigt.",
      machining: "Messing gehört zu den Werkstoffen mit der besten Zerspanbarkeit. Es erlaubt hohe Schnittgeschwindigkeiten und ergibt eine hervorragende Oberflächengüte. Die kurzen, gebrochenen Späne erleichtern die Bearbeitung auf Drehautomaten und CNC-Maschinen. Bronzelegierungen erfordern eine etwas sorgfältigere Parameterwahl, liefern aber dennoch gute Ergebnisse.",
      selection: "Messing C360 ist ideal für allgemeine Fittings und Ventile. Bronze C932 (SAE 660) wird für Gleitlager und Buchsen bevorzugt. Aluminiumbronze C954 kommt für hochbelastete Lager und maritime Anwendungen zum Einsatz. Marinemessing C464 wird für Salzwasserumgebungen empfohlen.",
    },
    advantages: ["Höchste Zerspanbarkeit", "Niedriger Reibungskoeffizient", "Dekorative Optik", "Funkenfrei"],
    commonApplications: ["Ventilkörper", "Gleitlager", "Verbindungselemente", "Schiffsteile", "Elektrische Steckverbinder"],
  },
  bakir: {
    name: "Kupfer",
    shortDescription: "Höchste Leitfähigkeit, Wärmeübertragung",
    heroTitle: "Kupfer für die CNC-Zerspanung",
    heroDescription: "C101, C110 und C122. Zerspanung von Reinkupfer für Elektronik, Wärmetauscher und elektrische Systeme.",
    seoTitle: "Kupfer CNC-Zerspanung | C101, C110, C122 Reinkupfer",
    seoDescription: "Kupferwerkstoffe für die CNC-Zerspanung. C101 sauerstofffreies Kupfer, C110 ETP-Kupfer, C122 DHP-Kupfer. Elektrische Leitfähigkeit, Wärmeübertragung.",
    content: {
      intro: "Kupfer hat nach Silber die höchste elektrische und thermische Leitfähigkeit aller Metalle. In der CNC-Zerspanung wird es vor allem für stromführende Teile, Wärmeverteiler und Kühlsysteme bevorzugt. Es gibt drei Hauptsorten: C101 (sauerstofffrei), C110 (elektrolytisch) und C122 (phosphordesoxidiert).",
      properties: "Kupfer besitzt eine sehr hohe elektrische und thermische Leitfähigkeit; geglühtes Kupfer ist die Referenz der IACS-Leitfähigkeitsskala. Seine Festigkeit ist gering, daher werden für Strukturanwendungen Kupferlegierungen bevorzugt. Den Leitfähigkeitswert eines Teils bestätigt das Werkstoffzeugnis.",
      applications: "In der Elektronikindustrie werden Stromschienensysteme, Erdungsplatten und Steckverbinder gefertigt. Im Wärmemanagement entstehen Kühlblöcke, Heatpipes und Kühlkörper. Im Energiesektor wird es in Generatorkomponenten und Transformatorwicklungen eingesetzt. In der Vakuumtechnik wird es für HF-Kavitäten und Hohlleiter bevorzugt.",
      machining: "Reinkupfer kann bei der CNC-Zerspanung anspruchsvoll sein, da es weich und schmierend ist. Lange, zusammenhängende Späne erschweren die Spankontrolle. Einzusetzen sind scharfe Werkzeuge mit positivem Spanwinkel, hohe Vorschübe und eine wirksame Kühlung. Diamantbeschichtete oder PKD-Werkzeuge liefern die besten Ergebnisse.",
      selection: "C101 wird für Vakuumanwendungen mit höchsten Anforderungen an Leitfähigkeit und Reinheit eingesetzt. C110 ist die gängigste Wahl für allgemeine elektrische Anwendungen. C122 wird für Wärmetauscheranwendungen bevorzugt, die Weich- oder Hartlöten erfordern.",
    },
    advantages: ["Höchste elektrische Leitfähigkeit nach Silber", "Sehr hohe Wärmeleitfähigkeit", "Recycelbar"],
    commonApplications: ["Stromschienen", "Wärmeverteiler", "Kühlblöcke", "Transformatorteile"],
  },
  nikel: {
    name: "Nickel-Superlegierungen",
    shortDescription: "Extreme Temperaturen, Korrosionsbeständigkeit",
    heroTitle: "Nickel-Superlegierungen für die CNC-Zerspanung",
    heroDescription: "Inconel 625, 718 und Monel. Für Strahltriebwerke, Kerntechnik und chemische Prozessanlagen.",
    seoTitle: "Nickel-Superlegierungen CNC-Zerspanung | Inconel 625, 718",
    seoDescription: "Nickel-Superlegierungen für die CNC-Zerspanung. Inconel 625, 718, Monel 400. Strahltriebwerke, Kernenergie, chemische Verfahrenstechnik, hohe Temperaturen.",
    content: {
      intro: "Nickel-Superlegierungen sind hochentwickelte Konstruktionswerkstoffe, die ihre mechanischen Eigenschaften auch bei sehr hohen Temperaturen behalten. Die Familien Inconel (Nickel-Chrom), Monel (Nickel-Kupfer) und Hastelloy (Nickel-Molybdän) werden für Teile eingesetzt, die unter rauen Bedingungen arbeiten.",
      properties: "Nickellegierungen behalten ihre Festigkeit bei hohen Temperaturen; ausscheidungshärtende Sorten wie Inconel 718 sind hochfest. Die Korrosionsbeständigkeit gegenüber vielen Säuren, Laugen und Salzlösungen ist hoch. Die Einsatztemperatur richtet sich nach Legierung und Umgebung.",
      applications: "In der Luft- und Raumfahrt für Turbinenkomponenten, Brennkammern und Abgassysteme eingesetzt. In Energie- und Kernkraftanlagen für Reaktoreinbauten und Wärmetauscher bevorzugt. Zu finden in Reaktoren und Rohrleitungen für korrosive Umgebungen in der chemischen Verfahrenstechnik sowie in maritimer Ausrüstung.",
      machining: "Nickellegierungen gehören zu den am schwierigsten CNC-zerspanbaren Werkstoffen. Ihre Neigung zur Kaltverfestigung ist sehr hoch, und in der Schnittzone entsteht übermäßige Wärme. Sie erfordern sehr niedrige Schnittgeschwindigkeiten, Hochdruck-Kühlschmierstoff und Keramik- oder CBN-Wendeschneidplatten; der Werkzeugverschleiß ist hoch.",
      selection: "Inconel 625 wird für allgemeine Hochtemperatur- und Korrosionsbeständigkeit eingesetzt. Inconel 718 wird für Turbinenteile mit hohen Festigkeitsanforderungen bevorzugt. Monel 400 ist ideal für Meerwasser und saure Umgebungen.",
    },
    advantages: ["Einsatz bei hohen Temperaturen", "Überragende Korrosionsbeständigkeit", "Hohe Festigkeit", "Oxidationsbeständigkeit"],
    commonApplications: ["Turbinenkomponenten", "Reaktoreinbauten", "Chemische Reaktoren", "Abgaskrümmer"],
  },
  magnezyum: {
    name: "Magnesium",
    shortDescription: "Das leichteste Strukturmetall, EMV-Abschirmung",
    heroTitle: "Magnesiumlegierungen für die CNC-Zerspanung",
    heroDescription: "AZ31B, AZ61A, AZ80A. Gewichtskritische Anwendungen mit dem leichtesten der Strukturmetalle.",
    seoTitle: "Magnesium CNC-Zerspanung | Legierungen AZ31B, AZ61A",
    seoDescription: "Magnesiumlegierungen für die CNC-Zerspanung. AZ31B, AZ61A, AZ80A. Das leichteste Strukturmetall, EMV-Abschirmung, Anwendungen in Luft- und Raumfahrt und Automobil.",
    content: {
      intro: "Magnesium ist das leichteste der Strukturmetalle. Magnesiumlegierungen sind deutlich leichter als Aluminium und Stahl und bieten Vorteile bei gewichtskritischen Anwendungen. Die AZ-Serie (mit Aluminium und Zink legiert) umfasst die am häufigsten verwendeten Magnesiumlegierungen.",
      properties: "Magnesiumlegierungen haben die geringste Dichte der Strukturmetalle. In der spezifischen Festigkeit (Festigkeit/Dichte) konkurrieren sie mit vielen Stahl- und Aluminiumlegierungen. Sie bieten eine gute EMV-Abschirmung (elektromagnetische Störungen).",
      applications: "In der Luft- und Raumfahrt für Getriebegehäuse von Hubschraubern, Instrumententafeln und Sitzgestelle eingesetzt. In der Automobilindustrie werden Lenksäulenteile, Räder und Motorabdeckungen gefertigt. In der Elektronik wird es für Laptopgehäuse, Kameragehäuse und Rahmen von Mobiltelefonen bevorzugt.",
      machining: "Magnesium ist das am leichtesten zerspanbare aller Metalle. Es erlaubt sehr hohe Schnittgeschwindigkeiten, ergibt eine hervorragende Oberflächengüte und verlängert die Werkzeugstandzeit. Es gibt jedoch einen kritischen Sicherheitsaspekt: Magnesiumspäne sind brennbar. Ein Feuerlöscher der Brandklasse D muss bereitstehen, und es sollte trocken oder mit Kühlschmierstoff auf Mineralölbasis bearbeitet werden.",
      selection: "AZ31B wird für allgemeine Blech- und Profilanwendungen bevorzugt. AZ61A oder AZ80A kommen für Schmiedeteile mit höheren Festigkeitsanforderungen zum Einsatz.",
    },
    advantages: ["Das leichteste Strukturmetall", "Hervorragende Zerspanbarkeit", "Gute EMV-Abschirmung", "Hohe spezifische Festigkeit"],
    commonApplications: ["Elektronikgehäuse", "Automobilteile", "Komponenten für die Luft- und Raumfahrt", "Kameragehäuse"],
  },
  termoplastikler: {
    name: "Thermoplaste",
    shortDescription: "Leicht, korrosionsbeständig, isolierend",
    heroTitle: "Technische Kunststoffe für die CNC-Zerspanung",
    heroDescription: "ABS, Delrin, Nylon, PTFE, PVC und weitere. Leichte, korrosionsbeständige Teile als Alternative zu Metall.",
    seoTitle: "Kunststoff CNC-Zerspanung | ABS, Delrin, Nylon, PTFE",
    seoDescription: "Technische Kunststoffe für die CNC-Zerspanung. ABS, Delrin (POM), Nylon (PA), PTFE, PVC, Polycarbonat. Leicht, korrosionsbeständig, elektrisch isolierend.",
    content: {
      intro: "Technische Thermoplaste bieten in vielen Anwendungen leichte Alternativen zu Metallen. Werkstoffe wie ABS, Delrin (POM), Nylon (PA), Polycarbonat (PC) und PTFE sind dank ihrer Korrosionsbeständigkeit, elektrischen Isolierung und ihres geringen Gewichts vielseitig einsetzbar.",
      properties: "Thermoplaste sind deutlich leichter als Metalle. Die Festigkeit variiert je nach Werkstoff stark; glasfaserverstärkte Sorten erreichen die höchste Festigkeit. Die Kombination aus elektrischer Isolierung, chemischer Beständigkeit und geringer Reibung ist bei Metallen kaum zu finden. Die Werte ändern sich mit Temperatur und Feuchtigkeit.",
      applications: "In der Automobilindustrie werden Armaturenbretter, Abdeckungen und Gehäuse gefertigt. In der Lebensmittelindustrie kommen lebensmitteltaugliche Schneidbretter und Förderteile zum Einsatz. In der Elektronik werden Isolatoren, Steckverbindergehäuse und Leiterplattenhalter bevorzugt. In der Medizintechnik entstehen Komponenten für Einweggeräte und Laborausrüstung.",
      machining: "Thermoplaste lassen sich im Allgemeinen leichter bearbeiten als Metalle, einige Punkte sind jedoch zu beachten. Wegen ihrer niedrigen Schmelzpunkte wird niedrige Drehzahl bei hohem Vorschub gegenüber hoher Drehzahl bei niedrigem Vorschub bevorzugt. Es sind scharfe Werkzeuge einzusetzen, und die Kühlung muss ein Aufschmelzen des Werkstoffs verhindern. Delrin und ABS bieten die beste Zerspanbarkeit.",
      selection: "ABS eignet sich für allgemeine Prototypen und Gehäuse. Delrin (POM) wird für hohe Präzision und geringe Reibung bevorzugt. Nylon wird für tragende Teile und Zahnräder eingesetzt. PTFE wird für chemische Beständigkeit und geringe Reibung gewählt. Polycarbonat kommt bei Anwendungen zum Einsatz, die Transparenz erfordern.",
    },
    advantages: ["Deutlich leichter als Metalle", "Korrosionsbeständig", "Elektrische Isolierung", "Geringe Reibung", "Lebensmitteltaugliche Sorten verfügbar"],
    commonApplications: ["Gehäuse und Abdeckungen", "Zahnräder und Lager", "Isolatoren", "Teile mit Lebensmittelkontakt", "Prototypenteile"],
  },
  "yuksek-performans-plastikler": {
    name: "Hochleistungskunststoffe",
    shortDescription: "Metallalternative, hohe Temperaturen, Luft- und Raumfahrt",
    heroTitle: "Hochleistungspolymere für die CNC-Zerspanung",
    heroDescription: "PEEK, Ultem (PEI), Torlon (PAI), Vespel. Polymere, die in der Luft- und Raumfahrt und der Medizintechnik Metall ersetzen.",
    seoTitle: "PEEK & Ultem CNC-Zerspanung | Hochleistungskunststoffe",
    seoDescription: "Hochleistungskunststoffe für die CNC-Zerspanung. PEEK, Ultem (PEI), Torlon (PAI). Luft- und Raumfahrt, Medizintechnik, Halbleiter. Polymere als Metallalternative.",
    content: {
      intro: "Hochleistungspolymere sind hochentwickelte Werkstoffe, deren mechanische, thermische und chemische Eigenschaften über die herkömmlicher technischer Kunststoffe hinausgehen. PEEK (Polyetheretherketon), Ultem/PEI (Polyetherimid) und Torlon/PAI (Polyamidimid) können in vielen Anwendungen Aluminium und Edelstahl ersetzen.",
      properties: "Hochleistungskunststoffe bieten eine höhere Festigkeit und Dauergebrauchstemperatur als technische Kunststoffe; kohlenstofffaserverstärkte Sorten erreichen die höchste Festigkeit. Sie sind flammhemmend, raucharm und chemisch beständig. Die Werte ändern sich mit Temperatur und Feuchtigkeit.",
      applications: "In der Luft- und Raumfahrt ersetzen sie Metall in Kabineninnenteilen, Halterungen und Isolatoren. In der Medizintechnik werden sterilisierbare Griffe chirurgischer Instrumente und Komponenten von Medizingeräten gefertigt. In der Halbleiterindustrie werden sie für Wafer-Handling-Ausrüstung und Prozessteile bevorzugt. Im Energiesektor entstehen Hochtemperaturdichtungen und -buchsen.",
      machining: "Die CNC-Zerspanung von Hochleistungskunststoffen erfordert andere Techniken als bei Metallen. PEEK ist gut zerspanbar, verursacht jedoch hohen Werkzeugverschleiß. Torlon kann sehr hart und spröde sein. Diamantbeschichtete oder PKD-Werkzeuge liefern die besten Ergebnisse. Vorwärmen kann das Rissrisiko verringern.",
      selection: "PEEK ist die Standardwahl für allgemeine Hochleistungsanwendungen. Ultem wird für Anwendungen der Luft- und Raumfahrt mit Anforderungen an Flammhemmung und Rauchentwicklung bevorzugt. Torlon kommt bei höchsten Anforderungen an Temperatur- und Verschleißbeständigkeit zum Einsatz. Kohlenstofffaserverstärkte Varianten bieten bei Strukturanwendungen eine Alternative zu Metall.",
    },
    advantages: ["Hohe Dauergebrauchstemperatur", "Festigkeit als Metallalternative", "Chemische Beständigkeit", "Flammhemmend", "Sterilisierbar"],
    commonApplications: ["Innenraumteile für die Luft- und Raumfahrt", "Medizingeräte", "Halbleiterausrüstung", "Hochtemperaturdichtungen"],
  },
  kompozitler: {
    name: "Verbundwerkstoffe",
    shortDescription: "Ultraleicht, ultrafest, mehrkomponentig",
    heroTitle: "Verbundwerkstoffe für die CNC-Zerspanung",
    heroDescription: "G-10/FR-4, kohlenstofffaserverstärkte Kunststoffe und Phenolharz-Schichtstoffe. Anspruchsvolle technische Anwendungen.",
    seoTitle: "Verbundwerkstoffe CNC-Zerspanung | G-10, Kohlefaser, FR-4",
    seoDescription: "Verbundwerkstoffe für die CNC-Zerspanung. G-10/FR-4, Kohlefaserlaminat, Nylon+CF, Phenolharz-Schichtstoff. Luft- und Raumfahrt, Leiterplatten, Drohnen, Strukturteile.",
    content: {
      intro: "Verbundwerkstoffe sind hochentwickelte technische Produkte aus zwei oder mehr unterschiedlichen Werkstoffen, die die besten Eigenschaften jeder Komponente in einem Werkstoff vereinen. Glasfaserverstärktes Epoxid (G-10/FR-4), Kohlefaserlaminate und Phenolharz-Schichtstoffe sind die in der CNC-Zerspanung am häufigsten verwendeten Verbundwerkstoffe.",
      properties: "Verbundwerkstoffe verbinden geringe Dichte mit hoher Steifigkeit. Ihre mechanischen Eigenschaften sind anisotrop (richtungsabhängig); die Festigkeit ist in Faserrichtung sehr hoch und quer dazu deutlich geringer. Sie bieten gezielt einstellbares elektrisches Verhalten wie elektrische Isolierung (G-10) oder statische Ableitung (Kohlefaser).",
      applications: "In der Elektronikindustrie werden Leiterplattensubstrate, Isolierplatten und Prüfvorrichtungen gefertigt. In der Luft- und Raumfahrt werden sie für Strukturpaneele, Innenraumteile und Drohnengehäuse eingesetzt. Im Motorsport werden sie für Aerodynamikteile und Strukturbauteile bevorzugt. In der Robotik entstehen leichte, steife Rahmen und Arme.",
      machining: "Die Zerspanung von Verbundwerkstoffen erfordert andere Techniken und Ausrüstung als bei Metallen. Faserverstärkte Werkstoffe sind stark abrasiv und verkürzen die Werkzeugstandzeit; empfohlen werden PKD- (polykristalliner Diamant) oder diamantbeschichtete Werkzeuge. Da Staub und Faserpartikel ein Gesundheitsrisiko darstellen, sind eine geeignete Belüftung und Staubabsaugung einzusetzen.",
      selection: "G-10/FR-4 ist der Standard für Leiterplatten und elektrische Isolierung. Kohlefaserlaminat wird für leichte, steife Strukturteile bevorzugt. Phenolharz-Schichtstoff (Bakelit) wird für Wärmebeständigkeit und elektrische Isolierung eingesetzt. Verbunde aus Nylon und Kohlefaser kommen für leichte mechanische Teile in Frage.",
    },
    advantages: ["Extrem hohes Festigkeits-Gewichts-Verhältnis", "Gezielt einstellbare Eigenschaften", "Korrosionsbeständig", "Steuerbare elektrische Eigenschaften"],
    commonApplications: ["Leiterplattensubstrate", "Drohnengehäuse", "Rennfahrzeuge", "Roboterarme", "Paneele für die Luft- und Raumfahrt"],
  },
};
