import type { MaterialText } from "@/content/en/types";

/* Material register records, keyed by id (`src/data/materialsData.ts`). */
export const materials: Record<string, MaterialText> = {
  "al-6061-t6": {
    name: "Aluminium 6061-T6",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Die meistverwendete Aluminiumlegierung. Hervorragend zerspanbar, gute Festigkeit und Korrosionsbeständigkeit.",
    applications: ["Luft- und Raumfahrt", "Automobil", "Gehäuse"],
    advantages: ["Hervorragend zerspanbar", "Gute Korrosionsbeständigkeit", "Gut verfügbar"],
    limitations: ["Festigkeitsabfall bei hohen Temperaturen", "Festigkeitsverlust nach dem Schweißen"],
  },
  "al-7075-t6": {
    name: "Aluminium 7075-T6",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Luftfahrtqualität. Festigkeit nahe an Stahl, jedoch schwerer zerspanbar als 6061.",
    applications: ["Luft- und Raumfahrt", "Verteidigung", "Hochfeste Strukturen"],
    advantages: ["Festigkeit nahe an Stahl", "Geringe Dichte", "Gute Dauerfestigkeit"],
    limitations: ["Geringe Korrosionsbeständigkeit", "Schmelzschweißen nicht empfohlen"],
  },
  "al-2024-t3": {
    name: "Aluminium 2024-T3",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "„Flugzeugaluminium“ für Luftfahrtanwendungen mit hohen Anforderungen an die Dauerfestigkeit.",
    applications: ["Flugzeugrumpf", "Flügelstrukturen", "Zahnräder"],
    advantages: ["Hohe Dauerfestigkeit", "Gutes Festigkeits-Gewichts-Verhältnis"],
    limitations: ["Geringe Korrosionsbeständigkeit", "Oberflächenbeschichtung erforderlich"],
  },
  "al-5052-h32": {
    name: "Aluminium 5052-H32",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hervorragende Beständigkeit gegen Salzwasserkorrosion. Ideal zum Biegen und Umformen.",
    applications: ["Marine", "Kraftstofftanks", "Blechbearbeitung"],
    advantages: ["Hervorragende Korrosionsbeständigkeit", "Gute Umformbarkeit"],
    limitations: ["Geringe Festigkeit", "Nicht aushärtbar durch Wärmebehandlung"],
  },
  "al-5083": {
    name: "Aluminium 5083",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Korrosionsbeständige, hochfeste, nicht aushärtbare Legierung.",
    applications: ["Marine", "Schiffsrümpfe", "Druckbehälter"],
    advantages: ["Beständig in maritimer Umgebung", "Schweißbar"],
    limitations: ["Nicht aushärtbar durch Wärmebehandlung"],
  },
  "al-6060": {
    name: "Aluminium 6060",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Für das Strangpressen geeignet; gute Oberfläche und Korrosionsbeständigkeit für dekoratives Eloxieren.",
    applications: ["Architektur", "Dekorteile", "Rahmen"],
    advantages: ["Hervorragende Oberflächenqualität", "Sehr gut eloxierbar"],
    limitations: ["Geringe Festigkeit"],
  },
  "al-6063": {
    name: "Aluminium 6063",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Architekturaluminium. Hohe Oberflächenqualität und gute Eloxierergebnisse.",
    applications: ["Architekturprofile", "Möbel", "Kühlkörper"],
    advantages: ["Hervorragende Oberflächenqualität", "Eloxierbar"],
    limitations: ["Geringe Festigkeit"],
  },
  "al-6082": {
    name: "Aluminium 6082",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Beliebt für beanspruchte Anwendungen; korrosionsbeständig und fest.",
    applications: ["Brücken", "Krane", "Schwere Strukturbauteile"],
    advantages: ["Festigkeit wie 6061", "Gute Korrosionsbeständigkeit"],
    limitations: ["Etwas geringere Umformbarkeit als 6061"],
  },
  "al-2014": {
    name: "Aluminium 2014",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Eine feste Legierung, die in der Luft- und Raumfahrt weit verbreitet ist.",
    applications: ["Luft- und Raumfahrt", "Verteidigung", "Strukturbauteile"],
    advantages: ["Hohe Festigkeit", "Gut zerspanbar"],
    limitations: ["Geringe Korrosionsbeständigkeit"],
  },
  "al-2017a": {
    name: "Aluminium 2017A",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hochfeste Aluminiumlegierung, bekannt für ihre hervorragende Zerspanbarkeit.",
    applications: ["Luft- und Raumfahrt", "Niete", "Allgemeine Maschinenteile"],
    advantages: ["Hervorragend zerspanbar", "Gute Festigkeit"],
    limitations: ["Mäßige Korrosionsbeständigkeit"],
  },
  "al-7050": {
    name: "Aluminium 7050",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Aushärtbare Luftfahrtlegierung mit hoher Zähigkeit und Beständigkeit gegen Spannungsrisskorrosion.",
    applications: ["Luft- und Raumfahrt", "Rumpfspanten", "Dicke Platten"],
    advantages: ["Hohe Zähigkeit", "Beständig gegen Spannungsrisskorrosion"],
    limitations: ["Eingeschränkt verfügbar"],
  },
  "al-mic6": {
    name: "Aluminium MIC-6",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Spannungsarm geglühte Aluminiumgussplatte. Geringe Verzugsneigung bei der Zerspanung.",
    applications: ["Vorrichtungsplatten", "Druckbetten", "Lehren"],
    advantages: ["Geringe Verzugsneigung", "Spannungsarm geglühte Gussplatte"],
    limitations: ["Geringe Festigkeit"],
  },
  "al-6013": {
    name: "Aluminium 6013",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hochfeste 6xxx-Serie. Eingesetzt für Rumpfpaneele in der Luftfahrt.",
    applications: ["Flugzeugpaneele", "Automobil", "Strukturprofile"],
    advantages: ["Höhere Festigkeit als 6061", "Gute Umformbarkeit"],
    limitations: ["Eingeschränkt verfügbar"],
  },
  "al-a356": {
    name: "Aluminium A356",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Aluminium-Gusslegierung. Verbreitet für Fahrzeugfelgen und Motorteile.",
    applications: ["Fahrzeugfelgen", "Motorblöcke", "Pumpengehäuse"],
    advantages: ["Gute Gießbarkeit", "Aushärtbar"],
    limitations: ["Geringere Festigkeit als Knetlegierungen"],
  },
  "st-1045": {
    name: "Stahl 1045",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Mittelkohlenstoffstahl. Gut zerspanbar, mittlere Festigkeit. Ideal für allgemeine Maschinenteile.",
    applications: ["Wellen", "Zahnräder", "Achsen"],
    advantages: ["Gut zerspanbar", "Durch Wärmebehandlung härtbar"],
    limitations: ["Nicht korrosionsbeständig", "Oberflächenbeschichtung erforderlich"],
  },
  "st-4140": {
    name: "Stahl 4140",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Vielseitige Chrom-Molybdän-Legierung. Hohe Zähigkeit und Dauerfestigkeit.",
    applications: ["Kurbelwellen", "Werkzeughalter", "Wellen"],
    advantages: ["Hohe Zähigkeit", "Gute Dauerfestigkeit", "Durch Wärmebehandlung härtbar"],
    limitations: ["Nicht korrosionsbeständig"],
  },
  "st-4340": {
    name: "Stahl 4340",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Nickel-Chrom-Molybdän. Durchhärtbar, für höchste Beanspruchungen.",
    applications: ["Fahrwerke", "Antriebsstrang"],
    advantages: ["Durchhärtbar", "Sehr hohe Festigkeit"],
    limitations: ["Schwer zerspanbar", "Nicht korrosionsbeständig"],
  },
  "st-a36": {
    name: "Stahl A36",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Der Standard-Baustahl. Schweißbar und gut verfügbar.",
    applications: ["Tragwerksteile", "Rahmen", "Plattformen"],
    advantages: ["Gut verfügbar", "Leicht schweißbar"],
    limitations: ["Geringe Festigkeit", "Nicht korrosionsbeständig"],
  },
  "st-1018": {
    name: "Stahl 1018",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Kohlenstoffarmer Stahl. Geeignet zum Einsatzhärten (Aufkohlen) und Schweißen.",
    applications: ["Stifte", "Buchsen", "Schweißkonstruktionen"],
    advantages: ["Hervorragend schweißbar", "Oberflächenhärtung durch Aufkohlen"],
    limitations: ["Geringe Festigkeit"],
  },
  "st-8620": {
    name: "Stahl 8620",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Nickel-Chrom-Molybdän-Stahl. Weit verbreitet zum Einsatzhärten (Aufkohlen).",
    applications: ["Getriebe", "Nockenwellen", "Stifte"],
    advantages: ["Hervorragend aufkohlbar", "Gute Kernzähigkeit"],
    limitations: ["Nicht korrosionsbeständig"],
  },
  "st-d2": {
    name: "Stahl D2 (Werkzeugstahl)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Kaltarbeitsstahl mit hohem Kohlenstoff- und Chromgehalt. Hervorragende Verschleißfestigkeit.",
    applications: ["Schneidwerkzeuge", "Stempel und Matrizen", "Klingen"],
    advantages: ["Hervorragende Verschleißfestigkeit", "Maßbeständigkeit"],
    limitations: ["Schwer zerspanbar", "Spröde"],
  },
  "st-o1": {
    name: "Stahl O1 (Werkzeugstahl)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Ölhärtender Werkzeugstahl. Gute Zerspanbarkeit und Maßbeständigkeit.",
    applications: ["Matrizen", "Lehren", "Zerspanwerkzeuge"],
    advantages: ["Gut zerspanbar", "Einfache Wärmebehandlung"],
    limitations: ["Geringe Korrosionsbeständigkeit"],
  },
  "st-s7": {
    name: "Stahl S7 (Werkzeugstahl)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Schlagfester Werkzeugstahl. Hervorragende Zähigkeit für schlagbeanspruchte Anwendungen.",
    applications: ["Schmiedegesenke", "Stempel", "Umformwerkzeuge"],
    advantages: ["Hervorragende Schlagfestigkeit", "Lufthärtend"],
    limitations: ["Nach Wärmebehandlung schwer zerspanbar"],
  },
  "st-4150": {
    name: "Stahl 4150",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Variante von 4140 mit höherem Kohlenstoffgehalt. Höhere Härte und Verschleißfestigkeit.",
    applications: ["Waffenläufe", "Kurbelwellen", "Hochbelastete Wellen"],
    advantages: ["Härter als 4140", "Gute Dauerfestigkeit"],
    limitations: ["Schwerer zerspanbar als 4140"],
  },
  "st-h13": {
    name: "Stahl H13 (Werkzeugstahl)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Warmarbeitsstahl. Der Standard für Druckgusswerkzeuge.",
    applications: ["Druckgusswerkzeuge", "Strangpresswerkzeuge", "Warmschmieden"],
    advantages: ["Warmfestigkeit", "Gute Zähigkeit"],
    limitations: ["Schwer zerspanbar"],
  },
  "st-p20": {
    name: "Stahl P20 (Formenstahl)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Vorvergüteter Formenstahl für Spritzgießwerkzeuge. Keine Wärmebehandlung erforderlich.",
    applications: ["Spritzgießwerkzeuge", "Presswerkzeuge", "Formaufbauten"],
    advantages: ["Vorvergütet", "Gut polierbar"],
    limitations: ["Nicht korrosionsbeständig"],
  },
  "ss-304": {
    name: "Edelstahl 304",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Der gängigste austenitische Edelstahl. Gute Korrosionsbeständigkeit und Schweißbarkeit; neigt bei der Zerspanung zur Kaltverfestigung.",
    applications: ["Lebensmittelanlagen", "Chemietanks", "Architektur"],
    advantages: ["Hervorragende Korrosionsbeständigkeit", "Hygienisch", "Schweißbar"],
    limitations: ["Schwer zerspanbar durch Kaltverfestigung", "Lochfraßanfällig in chloridhaltiger Umgebung"],
  },
  "ss-316l": {
    name: "Edelstahl 316L",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Molybdänlegiert. Überlegene Korrosionsbeständigkeit in chloridhaltiger Umgebung und Meerwasser.",
    applications: ["Medizinprodukte", "Marine", "Chemische Industrie"],
    advantages: ["Überlegene Korrosionsbeständigkeit", "Biokompatibel"],
    limitations: ["Schwer zerspanbar durch Kaltverfestigung"],
  },
  "ss-17-4ph": {
    name: "Edelstahl 17-4 PH",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Ausscheidungshärtender martensitischer Edelstahl. Hohe Festigkeit und gute Korrosionsbeständigkeit.",
    applications: ["Luft- und Raumfahrt", "Ventilkomponenten", "Turbinenschaufeln"],
    advantages: ["Hohe Festigkeit", "Durch Wärmebehandlung härtbar"],
    limitations: ["Eingeschränkt schweißbar"],
  },
  "ss-303": {
    name: "Edelstahl 303",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Automaten-Edelstahl. Optimiert für CNC-Drehautomaten.",
    applications: ["Muttern", "Schrauben", "Fittings"],
    advantages: ["Am besten zerspanbarer Edelstahl", "Korrosionsbeständigkeit nahe 304"],
    limitations: ["Schweißen nicht empfohlen", "Etwas geringere Korrosionsbeständigkeit als 304"],
  },
  "ss-321": {
    name: "Edelstahl 321",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Titanstabilisierter austenitischer Edelstahl. Beständig gegen interkristalline Korrosion bei hohen Temperaturen.",
    applications: ["Abgaskrümmer", "Wärmetauscher", "Chemische Verfahrenstechnik"],
    advantages: ["Korrosionsbeständig bei hohen Temperaturen", "Besser schweißbar als 304"],
    limitations: ["Schwer zerspanbar durch Kaltverfestigung"],
  },
  "ss-440c": {
    name: "Edelstahl 440C",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Martensitischer Edelstahl mit hohem Kohlenstoffgehalt. Höchste Härte und Verschleißfestigkeit.",
    applications: ["Lagerkugeln", "Ventilteile", "Klingen"],
    advantages: ["Härtester Edelstahl", "Hervorragende Verschleißfestigkeit"],
    limitations: ["Geringe Korrosionsbeständigkeit", "Spröde"],
  },
  "ss-2205": {
    name: "Edelstahl 2205 (Duplex)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Duplex-Edelstahl (austenitisch-ferritisch). Deutlich höhere Streckgrenze als 304.",
    applications: ["Chemietanks", "Petrochemie", "Offshore-Strukturen"],
    advantages: ["Deutlich höhere Streckgrenze als 304", "Hervorragende Korrosionsbeständigkeit"],
    limitations: ["Schwer zerspanbar"],
  },
  "ss-316ti": {
    name: "Edelstahl 316Ti",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Titanstabilisierter Edelstahl 316. Beständig gegen interkristalline Korrosion bei hohen Temperaturen.",
    applications: ["Wärmetauscher", "Chemiereaktoren", "Abgaskrümmer"],
    advantages: ["Korrosionsbeständig bei hohen Temperaturen"],
    limitations: ["Schwer zerspanbar durch Kaltverfestigung"],
  },
  "ss-347": {
    name: "Edelstahl 347",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Niobstabilisierter austenitischer Edelstahl. Eine Alternative zu 321 bei Hochtemperaturanwendungen.",
    applications: ["Triebwerksteile", "Wärmetauscher", "Kernreaktoren"],
    advantages: ["Korrosionsbeständig bei hohen Temperaturen", "Besser schweißbar als 321"],
    limitations: ["Schwer zerspanbar durch Kaltverfestigung"],
  },
  "br-c360": {
    name: "Messing C360",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Automatenmessing. Beste Leistung bei der Spanabnahme.",
    applications: ["Ventile", "Verbindungselemente", "Elektronische Steckverbinder"],
    advantages: ["Beste Zerspanbarkeit", "Dekoratives Aussehen"],
    limitations: ["Geringe Festigkeit", "Ammoniakempfindlich"],
  },
  "br-c932": {
    name: "Bronze C932 (SAE 660)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Bleihaltige Zinnbronze. Hervorragende Gleit- und Ölhalteeigenschaften.",
    applications: ["Gleitlager", "Buchsen"],
    advantages: ["Hervorragende Ölhaltung", "Geringe Reibung"],
    limitations: ["Bleihaltig"],
  },
  "br-c954": {
    name: "Aluminiumbronze C954",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hochfeste Bronzelegierung. Festigkeit nahe an Stahl.",
    applications: ["Hochbelastete Lager", "Schiffsbeschläge", "Zahnräder"],
    advantages: ["Hohe Festigkeit", "Hervorragend meerwasserbeständig"],
    limitations: ["Schwer zerspanbar"],
  },
  "br-c260": {
    name: "Messing C260 (Patronenmessing)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "70 % Kupfer, 30 % Zink. Hervorragend kaltumformbar.",
    applications: ["Patronenhülsen", "Kühlerblöcke", "Dekorbeschläge"],
    advantages: ["Hervorragende Umformbarkeit", "Gute Korrosionsbeständigkeit"],
    limitations: ["Schlechter zerspanbar als C360"],
  },
  "br-c464": {
    name: "Messing C464 (Marinemessing)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Zinnlegiertes Marinemessing. Hervorragende Beständigkeit gegen Salzwasserkorrosion.",
    applications: ["Schiffsteile", "Seeventile", "Pumpengehäuse"],
    advantages: ["Hervorragend meerwasserbeständig", "Entzinkungsbeständig"],
    limitations: ["Mäßig zerspanbar"],
  },
  "br-c510": {
    name: "Phosphorbronze C510",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hohe Elastizitätsgrenze für Feder- und Kontaktanwendungen.",
    applications: ["Federn", "Kontakte", "Membranen"],
    advantages: ["Hohe Elastizitätsgrenze", "Gute Korrosionsbeständigkeit"],
    limitations: ["Schwer zerspanbar"],
  },
  "cu-c101": {
    name: "Kupfer C101",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Sauerstofffreies Kupfer. Reinheit 99,99 %.",
    applications: ["Elektronenröhren", "Supraleiter"],
    advantages: ["Höchste Leitfähigkeit", "Sauerstofffrei"],
    limitations: ["Klebrige Späne; schwer zerspanbar"],
  },
  "cu-c110": {
    name: "Kupfer C110",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Elektrolytkupfer (ETP — Electrolytic Tough Pitch). Das Standardkupfer für elektrische Leiter.",
    applications: ["Stromschienen", "Erdung", "Dichtungen"],
    advantages: ["Hervorragende elektrische Leitfähigkeit"],
    limitations: ["Schlecht zerspanbar"],
  },
  "cu-c122": {
    name: "Kupfer C122 (DHP)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Phosphordesoxidiertes Kupfer mit hohem Restphosphorgehalt. Der Standard für Wärmetauscher und Installationsrohre.",
    applications: ["Installationsrohre", "Wärmetauscher", "Warmwassersysteme"],
    advantages: ["Gut schweiß- und lötbar", "Hohe Leitfähigkeit"],
    limitations: ["Schlecht zerspanbar"],
  },
  "cu-c145": {
    name: "Kupfer C145 (Tellurkupfer)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Tellurlegiertes Automatenkupfer. Verbindet Zerspanbarkeit und Leitfähigkeit.",
    applications: ["Elektrische Armaturen", "Motorkommutatoren", "Schütze"],
    advantages: ["Bestzerspanbares Kupfer", "Hohe Leitfähigkeit"],
    limitations: ["Etwas geringere Leitfähigkeit als C110"],
  },
  "ti-grade2": {
    name: "Titan Grade 2",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Reintitan. Hervorragende Korrosionsbeständigkeit und Biokompatibilität.",
    applications: ["Medizinprodukte", "Chemische Industrie", "Marine"],
    advantages: ["Hervorragende Korrosionsbeständigkeit", "Biokompatibel", "Leicht"],
    limitations: ["Schlecht zerspanbar"],
  },
  "ti-grade5": {
    name: "Titan Grade 5 (Ti-6Al-4V)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Die gängigste Titanlegierung. Hohes Festigkeits-Gewichts-Verhältnis. Der Standard in der Luft- und Raumfahrt.",
    applications: ["Triebwerksteile", "Medizinische Komponenten", "Rennsportausrüstung"],
    advantages: ["Festigkeit nahe an Stahl", "Deutlich leichter als Stahl"],
    limitations: ["Sehr schwer zerspanbar"],
  },
  "ti-grade9": {
    name: "Titan Grade 9 (Ti-3Al-2.5V)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Titanlegierung mittlerer Festigkeit. Gute Umformbarkeit und Korrosionsbeständigkeit.",
    applications: ["Fahrradrahmen", "Hydraulikrohre", "Marine"],
    advantages: ["Gute Umformbarkeit", "Gute Korrosionsbeständigkeit"],
    limitations: ["Geringere Festigkeit als Grade 5"],
  },
  "ti-grade23": {
    name: "Titan Grade 23 (Ti-6Al-4V ELI)",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "ELI-Variante (Extra Low Interstitial). Für Anwendungen mit höheren Anforderungen an Zähigkeit und Biokompatibilität.",
    applications: ["Medizinische Komponenten", "Chirurgische Instrumente", "Luft- und Raumfahrt"],
    advantages: ["Biokompatibel", "Zäher als Grade 5"],
    limitations: ["Schwer zerspanbar"],
  },
  "ni-625": {
    name: "Inconel 625",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Nickel-Chrom-Legierung. Äußerst oxidations- und korrosionsbeständig.",
    applications: ["Unterwassertechnik", "Abgassysteme", "Kerntechnik"],
    advantages: ["Oxidationsbeständig bei hohen Temperaturen", "Hervorragende Korrosionsbeständigkeit"],
    limitations: ["Sehr schwer zerspanbar"],
  },
  "ni-718": {
    name: "Inconel 718",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Eine Superlegierung, die ihre hohe Festigkeit auch bei hohen Temperaturen behält.",
    applications: ["Triebwerke", "Raketenteile"],
    advantages: ["Warmfest", "Ausscheidungshärtend"],
    limitations: ["Sehr schwer zerspanbar"],
  },
  "ni-monel400": {
    name: "Monel 400",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Nickel-Kupfer-Legierung. Hervorragend beständig gegen Meerwasser und Säuren.",
    applications: ["Schiffsventile", "Chemische Verfahrenstechnik", "Ölraffinerien"],
    advantages: ["Hervorragend meerwasserbeständig", "Säurebeständig"],
    limitations: ["Neigt zur Kaltverfestigung; schwer zerspanbar"],
  },
  "ni-hastelloyc276": {
    name: "Hastelloy C-276",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Molybdän-Wolfram-legierte Nickellegierung. Für extremste Bedingungen in der chemischen Verfahrenstechnik.",
    applications: ["Chemiereaktoren", "Säureproduktionsanlagen", "Rauchgasentschwefelung"],
    advantages: ["Breiteste Korrosionsbeständigkeit", "Beständig in oxidierenden und reduzierenden Medien"],
    limitations: ["Sehr schwer zerspanbar"],
  },
  "mg-az31b": {
    name: "Magnesium AZ31B",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Die meistverwendete Magnesiumlegierung. Leicht, gut umformbar.",
    applications: ["Elektronikgehäuse", "Karosseriepaneele", "Kameragehäuse"],
    advantages: ["Sehr leicht", "Gute Umformbarkeit"],
    limitations: ["Korrosionsanfällig", "Brennbare Späne"],
  },
  "mg-az61a": {
    name: "Magnesium AZ61A",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Höhere Festigkeit als AZ31B. Geeignet für Strangpressprofile.",
    applications: ["Luftfahrthalterungen", "Strukturprofile", "Sportgeräte"],
    advantages: ["Höhere Festigkeit als AZ31B", "Gut zerspanbar"],
    limitations: ["Korrosionsanfällig", "Brennbare Späne"],
  },
  "mg-az80a": {
    name: "Magnesium AZ80A",
    propertyConditions: "Raumtemperatur; Werte abhängig von Zustand und Wärmebehandlung",
    description: "Hochfeste Magnesium-Knetlegierung. Strukturbauteile für die Luft- und Raumfahrt.",
    applications: ["Luftfahrtgetriebe", "Flugzeuggehäuse", "Motorsport"],
    advantages: ["Hohe Festigkeit", "Leicht"],
    limitations: ["Korrosionsanfällig", "Brennbare Späne"],
  },
  "pl-abs": {
    name: "ABS",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein robuster Universalkunststoff.",
    applications: ["Prototypen", "Abdeckungen", "Spielzeug"],
    advantages: ["Gute Schlagzähigkeit", "Leicht zerspanbar"],
    limitations: ["Geringe Temperaturbeständigkeit", "UV-empfindlich"],
  },
  "pl-pmma": {
    name: "Acrylglas (PMMA/Plexiglas)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Eine transparente Alternative zu Glas. Poliert optisch klar.",
    applications: ["Displayschutz", "Schilder", "Lichtleiter"],
    advantages: ["Optische Klarheit", "UV-Beständigkeit"],
    limitations: ["Spröde", "Kratzempfindlich"],
  },
  "pl-delrin": {
    name: "Delrin (POM/Polyacetal)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein technischer Kunststoff für mechanische Teile mit hohen Präzisionsanforderungen.",
    applications: ["Zahnräder", "Lager", "Führungsschienen"],
    advantages: ["Hervorragend zerspanbar", "Geringe Reibung", "Maßbeständigkeit"],
    limitations: ["Schwer klebbar (spezielle Oberflächenvorbehandlung nötig)", "Nicht lackierbar"],
  },
  "pl-nylon": {
    name: "Polyamid (PA6/PA66)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein technischer Kunststoff mit hoher Verschleißfestigkeit und mechanischer Festigkeit.",
    applications: ["Zahnräder", "Wälzlager", "Riemenscheiben"],
    advantages: ["Hohe Verschleißfestigkeit", "Gute Festigkeit"],
    limitations: ["Nimmt Feuchtigkeit auf", "Maßänderung"],
  },
  "pl-pc": {
    name: "Polycarbonat (PC)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein transparenter technischer Kunststoff mit hoher Schlagzähigkeit.",
    applications: ["Schutzscheiben", "Optische Linsen", "Medizinprodukte"],
    advantages: ["Außergewöhnliche Schlagzähigkeit", "Optische Klarheit"],
    limitations: ["Kratzempfindlich", "Mäßige Chemikalienbeständigkeit"],
  },
  "pl-ptfe": {
    name: "PTFE (Teflon)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Der Kunststoff mit dem niedrigsten Reibungskoeffizienten. Chemisch nahezu inert.",
    applications: ["Dichtungen", "Lager", "Chemische Auskleidungen"],
    advantages: ["Niedrigste Reibung", "Beständig gegen die meisten Chemikalien", "Hohe Temperaturbeständigkeit"],
    limitations: ["Geringe Festigkeit", "Neigung zum Kriechen"],
  },
  "pl-pvc": {
    name: "PVC",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein chemikalienbeständiger, flammhemmender Konstruktionskunststoff.",
    applications: ["Rohre", "Tankauskleidungen", "Elektro-Installationsrohre"],
    advantages: ["Gute Chemikalienbeständigkeit", "Flammhemmend"],
    limitations: ["Geringe Temperaturbeständigkeit", "Geringe Schlagzähigkeit"],
  },
  "pl-hdpe": {
    name: "HDPE",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Polyethylen hoher Dichte. Gleitfähig und chemikalienbeständig.",
    applications: ["Schneidbretter", "Chemietanks"],
    advantages: ["Sehr leicht", "Chemikalienbeständig", "Lebensmitteltaugliche Typen verfügbar"],
    limitations: ["Geringe Festigkeit", "Schwer klebbar"],
  },
  "pl-pp": {
    name: "Polypropylen (PP)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein leichter, chemikalienbeständiger Kunststoff, geeignet für Scharniere.",
    applications: ["Filmscharniere", "Chemietanks", "Laborausrüstung"],
    advantages: ["Einer der leichtesten Kunststoffe", "Hervorragende Chemikalienbeständigkeit", "Dauerfestigkeit"],
    limitations: ["UV-empfindlich", "Schwer klebbar"],
  },
  "pl-uhmwpe": {
    name: "UHMW-PE",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ultrahochmolekulares Polyethylen. Hervorragende Verschleißfestigkeit und geringe Reibung.",
    applications: ["Förderbandführungen", "Verschleißplatten", "Lebensmittelverarbeitung"],
    advantages: ["Hervorragende Verschleißfestigkeit", "Einer der niedrigsten Reibungskoeffizienten"],
    limitations: ["Geringe Festigkeit", "Wärmeempfindlich"],
  },
  "pl-pei": {
    name: "PEI (Ultem)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Bernsteinfarbener Hochtemperatur-Konstruktionskunststoff. Flammhemmend.",
    applications: ["Luftfahrt-Innenausstattung", "Elektrische Isolatoren", "Medizinische Instrumente"],
    advantages: ["Flammhemmend", "Sterilisierbar", "Gute elektrische Isolation"],
    limitations: ["UV-empfindlich"],
  },
  "pl-cpvc": {
    name: "CPVC",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Chloriertes PVC. Standard-PVC überlegen bei Heißwasser und aggressiven Chemikalien.",
    applications: ["Warmwasserrohre", "Chemierohre", "Sprinklerleitungen"],
    advantages: ["Temperaturbeständiger als PVC", "Flammhemmend", "Chemikalienbeständig"],
    limitations: ["Geringe Schlagzähigkeit"],
  },
  "pl-noryl": {
    name: "Noryl (PPO/PPE)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Modifiziertes Polyphenylenoxid. Maßbeständig mit geringer Feuchtigkeitsaufnahme.",
    applications: ["Armaturenbretter", "Wasseraufbereitungsanlagen", "Elektrowerkzeuggehäuse"],
    advantages: ["Geringe Feuchtigkeitsaufnahme", "Maßbeständigkeit", "Leicht"],
    limitations: ["UV-empfindlich"],
  },
  "pl-pa66-gf30": {
    name: "PA66 + 30 % Glasfaser",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Glasfaserverstärktes Polyamid. Erhöhte Festigkeit und Temperaturbeständigkeit.",
    applications: ["Motorabdeckungen", "Lüfterflügel", "Strukturhalterungen"],
    advantages: ["Hohe Festigkeit", "Gute Temperaturbeständigkeit"],
    limitations: ["Abrasive Späne", "Spröde"],
  },
  "pl-pps": {
    name: "PPS (Polyphenylensulfid)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Teilkristalliner Thermoplast mit hoher Temperatur- und Chemikalienbeständigkeit.",
    applications: ["Motorteile (Automobil)", "Pumpengehäuse", "Chemische Verfahrenstechnik"],
    advantages: ["Hervorragende Chemikalienbeständigkeit", "Hochtemperaturbeständig", "Maßbeständigkeit"],
    limitations: ["Spröde"],
  },
  "pl-pbt": {
    name: "PBT (Polybutylenterephthalat)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Teilkristalliner Thermoplast. Ideal für elektrische Steckverbinder und Automobilteile.",
    applications: ["Elektrische Steckverbinder", "Fahrzeugsensoren", "Schaltergehäuse"],
    advantages: ["Gute elektrische Eigenschaften", "Schnelle Kristallisation"],
    limitations: ["Feuchtigkeitsempfindlich"],
  },
  "pl-pet": {
    name: "PET (Polyethylenterephthalat)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Transparenter oder weißer teilkristalliner Kunststoff. Lebensmitteltaugliche Typen sind verfügbar.",
    applications: ["Lebensmittelverpackungen", "Medizinprodukte", "Elektrische Isolatoren"],
    advantages: ["Lebensmitteltaugliche Typen verfügbar", "Gute Maßbeständigkeit"],
    limitations: ["Nimmt Feuchtigkeit auf"],
  },
  "pl-peek": {
    name: "PEEK",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Teilkristalliner Hochleistungsthermoplast. Festigkeit und Temperaturbeständigkeit als Metallersatz.",
    applications: ["Luft- und Raumfahrt", "Medizinische Komponenten", "Halbleiter"],
    advantages: ["Metallersatz", "Sterilisierbar", "Hohe Temperaturbeständigkeit"],
    limitations: ["Spezielle Werkzeuge erforderlich"],
  },
  "pl-torlon": {
    name: "Torlon (PAI)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Der leistungsstärkste schmelzverarbeitbare Kunststoff. Festigkeit, die Metall ersetzt.",
    applications: ["Triebwerksteile", "Halbleiteranlagen", "Hochtemperaturlager"],
    advantages: ["Hohe Festigkeit bei hohen Temperaturen", "Festigkeit als Metallersatz"],
    limitations: ["Schwer zerspanbar"],
  },
  "pl-vespel": {
    name: "Vespel (PI)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "DuPont-Vespel-Polyimid. Extreme Temperatur- und Verschleißbeständigkeit.",
    applications: ["Raumfahrzeuge", "Halbleiter", "Triebwerke"],
    advantages: ["Sehr hohe Dauergebrauchstemperatur", "Hervorragende Verschleißfestigkeit"],
    limitations: ["Eingeschränkt verfügbar"],
  },
  "pl-peek-gf30": {
    name: "PEEK + 30 % Glasfaser",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Glasfaserverstärktes PEEK. Erhöhte Steifigkeit und Maßbeständigkeit.",
    applications: ["Strukturhalterungen", "Pumpenteile", "Verdichterteile"],
    advantages: ["Steifer als PEEK", "Geringe Wärmeausdehnung"],
    limitations: ["Abrasive Späne"],
  },
  "pl-peek-cf30": {
    name: "PEEK + 30 % Kohlefaser",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Kohlefaserverstärktes PEEK. Der leistungsstärkste Polymer-Verbundwerkstoff.",
    applications: ["Luft- und Raumfahrt", "Halbleiter", "Medizintechnik"],
    advantages: ["Extrem hohes Festigkeits-Gewichts-Verhältnis", "Statisch ableitfähig"],
    limitations: ["Abrasive Späne; ggf. Diamant- oder PKD-Werkzeuge nötig"],
  },
  "pl-psu": {
    name: "Polysulfon (PSU)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Ein transparenter Hochtemperatur-Konstruktionskunststoff. Autoklavierbar.",
    applications: ["Medizinprodukte", "Molkereiindustrie", "Wasserfiltration"],
    advantages: ["Transparent", "Sterilisierbar", "Lebensmitteltaugliche Typen verfügbar"],
    limitations: ["UV-empfindlich"],
  },
  "pl-ppsu": {
    name: "PPSU (Radel)",
    propertyConditions: "23 °C, trocken (nicht konditioniert); abhängig von Feuchte und Temperatur",
    description: "Polyphenylsulfon. Der Hochtemperaturkunststoff mit der höchsten Schlagzähigkeit.",
    applications: ["Sterilisationstrays für Chirurgie", "Flugzeug-Innenausstattung", "Warmwasserfittings"],
    advantages: ["Hohe Schlagzähigkeit", "Wiederholt autoklavierbar"],
    limitations: ["Nach der Zerspanung ggf. Spannungsarmglühen nötig"],
  },
  "co-g10": {
    name: "G-10 / FR-4",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Glasfaserverstärktes Epoxidlaminat. Der Standard für die elektrische Isolation.",
    applications: ["Leiterplatten", "Elektrische Isolatoren", "Drohnengehäuse"],
    advantages: ["Hervorragende elektrische Isolation", "Hohe Festigkeit"],
    limitations: ["Abrasive Späne", "Gesundheitsrisiko durch Staub"],
  },
  "co-cf-laminat": {
    name: "Kohlefaserlaminat",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Kohlefaserverstärkte Epoxidplatte. Extrem leicht und extrem fest.",
    applications: ["Rennfahrzeuge", "Drohnenrahmen", "Prothesenkomponenten"],
    advantages: ["Höchstes Festigkeits-Gewichts-Verhältnis", "Hervorragende Steifigkeit"],
    limitations: ["Abrasive Späne", "Anisotrop"],
  },
  "co-nylon-cf": {
    name: "Polyamid + Kohlefaser",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Kohlefaserverstärktes Polyamid. Für leichte, steife Strukturbauteile.",
    applications: ["Drohnenrahmen", "Roboterarme", "3D-Druck"],
    advantages: ["Leicht", "Steif", "Verschleißfest"],
    limitations: ["Nimmt Feuchtigkeit auf", "Anisotrop"],
  },
  "co-phenolic": {
    name: "Phenolharzlaminat (Bakelit)",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Der erste synthetische Kunststoff. Weiterhin eingesetzt für Wärmebeständigkeit und elektrische Isolation.",
    applications: ["Elektrische Isolatoren", "Bremsbeläge", "Pfannengriffe"],
    advantages: ["Wärmebeständigkeit", "Elektrische Isolation"],
    limitations: ["Spröde", "Begrenzte Farbauswahl"],
  },
  "co-ultem-cf": {
    name: "Ultem + Kohlefaser",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Kohlefaserverstärktes PEI. Für Strukturbauteile in der Luft- und Raumfahrt.",
    applications: ["Luftfahrt-Innenstrukturen", "Satellitenkomponenten", "Rennwagen"],
    advantages: ["Flammhemmend + strukturell", "Leicht"],
    limitations: ["Spezielle Zerspanung erforderlich"],
  },
  "co-garolite": {
    name: "Garolite G-11",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Die Hochtemperaturvariante von G-10.",
    applications: ["Hochtemperaturisolatoren", "Transformatorteile", "Motorisolation"],
    advantages: ["Temperaturbeständiger als G-10", "Hervorragende Isolation"],
    limitations: ["Abrasiv", "Gesundheitsschädliche Späne"],
  },
  "co-kevlar": {
    name: "Kevlar-Laminat",
    propertyConditions: "In Faserrichtung, Raumtemperatur; quer zur Faser deutlich niedriger",
    description: "Aramidfaserverstärktes Epoxid. Schlagabsorbierend, leicht, hohe Zähigkeit.",
    applications: ["Ballistischer Schutz", "Skiausrüstung", "Bootsrümpfe"],
    advantages: ["Hervorragende Schlagabsorption", "Sehr leicht", "Hohe Zähigkeit"],
    limitations: ["Sehr schwer zerspanbar", "Nimmt Feuchtigkeit auf"],
  },
};
