import type { MaterialText } from "@/content/en/types";

/* Material register records, keyed by id (`src/data/materialsData.ts`). */
export const materials: Record<string, MaterialText> = {
  "al-6061-t6": {
    name: "6061-T6 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "应用最广泛的铝合金。可加工性优异，强度和耐腐蚀性良好。",
    applications: ["航空航天", "汽车", "外壳"],
    advantages: ["可加工性优异", "耐腐蚀性良好", "货源充足"],
    limitations: ["高温下强度下降", "焊接后强度降低"],
  },
  "al-7075-t6": {
    name: "7075-T6 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "航空级材料。强度接近钢，但加工难度高于 6061。",
    applications: ["航空航天", "国防工业", "高强度结构"],
    advantages: ["强度接近钢", "密度低", "抗疲劳性能良好"],
    limitations: ["耐腐蚀性低", "不推荐熔焊"],
  },
  "al-2024-t3": {
    name: "2024-T3 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "“航空铝”，用于要求高抗疲劳性能的航空航天应用。",
    applications: ["飞机机身", "机翼结构", "齿轮"],
    advantages: ["抗疲劳性能高", "强重比良好"],
    limitations: ["耐腐蚀性低", "需要表面涂层"],
  },
  "al-5052-h32": {
    name: "5052-H32 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "耐海水腐蚀性能优异。适合折弯和成形。",
    applications: ["船舶", "燃油箱", "钣金加工"],
    advantages: ["耐腐蚀性优异", "成形性良好"],
    limitations: ["强度低", "不能通过热处理强化"],
  },
  "al-5083": {
    name: "5083 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "耐腐蚀、高强度、不可热处理强化的合金。",
    applications: ["船舶", "船体", "压力容器"],
    advantages: ["耐海洋环境", "可焊接"],
    limitations: ["不能通过热处理强化"],
  },
  "al-6060": {
    name: "6060 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "适合挤压成型；表面质量和耐腐蚀性良好，适用于装饰性阳极氧化。",
    applications: ["建筑", "装饰件", "框架"],
    advantages: ["表面质量优异", "阳极氧化效果很好"],
    limitations: ["强度低"],
  },
  "al-6063": {
    name: "6063 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "建筑铝材。表面质量高，阳极氧化效果好。",
    applications: ["建筑型材", "家具", "散热器"],
    advantages: ["表面质量优异", "适合阳极氧化"],
    limitations: ["强度低"],
  },
  "al-6082": {
    name: "6082 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "常用于承受应力的应用；耐腐蚀且强度高。",
    applications: ["桥梁", "起重机", "重型结构件"],
    advantages: ["强度与 6061 相当", "耐腐蚀性良好"],
    limitations: ["成形性略低于 6061"],
  },
  "al-2014": {
    name: "2014 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "广泛用于航空航天的高强度合金。",
    applications: ["航空航天", "国防工业", "结构件"],
    advantages: ["强度高", "可加工性良好"],
    limitations: ["耐腐蚀性低"],
  },
  "al-2017a": {
    name: "2017A 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "以可加工性优异著称的高强度铝合金。",
    applications: ["航空航天", "铆钉", "通用机械零件"],
    advantages: ["可加工性优异", "强度良好"],
    limitations: ["耐腐蚀性一般"],
  },
  "al-7050": {
    name: "7050 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "可热处理强化的航空合金，韧性高，耐应力腐蚀开裂。",
    applications: ["航空航天", "机身框架", "厚板"],
    advantages: ["韧性高", "耐应力腐蚀"],
    limitations: ["货源有限"],
  },
  "al-mic6": {
    name: "MIC-6 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "经去应力处理的铸造铝板。加工时变形倾向小。",
    applications: ["夹具底板", "打印机平台", "量规"],
    advantages: ["变形倾向小", "去应力铸造板"],
    limitations: ["强度低"],
  },
  "al-6013": {
    name: "6013 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "高强度 6xxx 系列。用于航空航天机身壁板。",
    applications: ["飞机壁板", "汽车", "结构型材"],
    advantages: ["强度高于 6061", "成形性良好"],
    limitations: ["货源有限"],
  },
  "al-a356": {
    name: "A356 铝合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "铸造铝合金。常用于汽车轮毂和发动机零件。",
    applications: ["汽车轮毂", "发动机缸体", "泵体"],
    advantages: ["铸造性能良好", "可热处理强化"],
    limitations: ["强度低于变形合金"],
  },
  "st-1045": {
    name: "1045 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "中碳钢。可加工性良好，强度中等。适用于通用机械零件。",
    applications: ["轴", "齿轮", "车轴"],
    advantages: ["可加工性良好", "可通过热处理淬硬"],
    limitations: ["不耐腐蚀", "需要表面涂层"],
  },
  "st-4140": {
    name: "4140 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "用途广泛的铬钼合金钢。韧性和抗疲劳性能高。",
    applications: ["曲轴", "刀柄", "轴"],
    advantages: ["韧性高", "抗疲劳性能良好", "可通过热处理淬硬"],
    limitations: ["不耐腐蚀"],
  },
  "st-4340": {
    name: "4340 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "镍铬钼钢。可整体淬透，适用于最严苛的工况。",
    applications: ["起落架", "动力传动系统"],
    advantages: ["可整体淬透", "强度很高"],
    limitations: ["加工困难", "不耐腐蚀"],
  },
  "st-a36": {
    name: "A36 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "标准结构钢。可焊接，货源充足。",
    applications: ["结构构件", "框架", "平台"],
    advantages: ["货源充足", "易于焊接"],
    limitations: ["强度低", "不耐腐蚀"],
  },
  "st-1018": {
    name: "1018 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "低碳钢。适合表面硬化（渗碳）和焊接。",
    applications: ["销", "衬套", "焊接结构"],
    advantages: ["焊接性优异", "可通过渗碳进行表面硬化"],
    limitations: ["强度低"],
  },
  "st-8620": {
    name: "8620 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "镍铬钼钢。广泛用于表面硬化（渗碳）。",
    applications: ["齿轮机构", "凸轮轴", "销"],
    advantages: ["渗碳效果优异", "心部韧性良好"],
    limitations: ["不耐腐蚀"],
  },
  "st-d2": {
    name: "D2 钢（工具钢）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "高碳高铬冷作工具钢。耐磨性优异。",
    applications: ["冲裁模", "冲头和模具", "刀片"],
    advantages: ["耐磨性优异", "尺寸稳定性好"],
    limitations: ["加工困难", "脆性大"],
  },
  "st-o1": {
    name: "O1 钢（工具钢）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "油淬工具钢。可加工性和尺寸稳定性良好。",
    applications: ["模具", "量规", "切削刀具"],
    advantages: ["可加工性良好", "易于热处理"],
    limitations: ["耐腐蚀性低"],
  },
  "st-s7": {
    name: "S7 钢（工具钢）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "耐冲击工具钢。韧性优异，适用于冲击工况。",
    applications: ["锻模", "冲头", "成形模"],
    advantages: ["抗冲击性能优异", "空淬硬化"],
    limitations: ["热处理后加工困难"],
  },
  "st-4150": {
    name: "4150 钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "4140 的高碳版本。硬度和耐磨性更高。",
    applications: ["枪管", "曲轴", "重载轴"],
    advantages: ["硬度高于 4140", "抗疲劳性能良好"],
    limitations: ["加工难度高于 4140"],
  },
  "st-h13": {
    name: "H13 钢（工具钢）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "热作工具钢。压铸模具的标准材料。",
    applications: ["压铸模具", "挤压模具", "热锻"],
    advantages: ["高温强度高", "韧性良好"],
    limitations: ["加工困难"],
  },
  "st-p20": {
    name: "P20 钢（模具钢）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "预硬化塑料注塑模具钢。无需热处理。",
    applications: ["塑料注塑模具", "压缩模具", "模架"],
    advantages: ["预硬化", "抛光性良好"],
    limitations: ["不耐腐蚀"],
  },
  "ss-304": {
    name: "304 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "最常用的奥氏体不锈钢。耐腐蚀性和焊接性良好；加工时易产生加工硬化。",
    applications: ["食品设备", "化工储罐", "建筑"],
    advantages: ["耐腐蚀性优异", "卫生", "可焊接"],
    limitations: ["因加工硬化而难以加工", "在氯化物环境中易发生点蚀"],
  },
  "ss-316l": {
    name: "316L 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "含钼合金。在氯化物环境和海水中具有更优的耐腐蚀性。",
    applications: ["医疗器械", "船舶", "化学工业"],
    advantages: ["耐腐蚀性更优", "生物相容性好"],
    limitations: ["因加工硬化而难以加工"],
  },
  "ss-17-4ph": {
    name: "17-4 PH 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "沉淀硬化马氏体不锈钢。强度高，耐腐蚀性良好。",
    applications: ["航空航天", "阀门部件", "涡轮叶片"],
    advantages: ["强度高", "可通过热处理淬硬"],
    limitations: ["焊接性有限"],
  },
  "ss-303": {
    name: "303 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "易切削不锈钢。针对 CNC 自动车床优化。",
    applications: ["螺母", "螺栓", "管件"],
    advantages: ["可加工性最好的不锈钢", "耐腐蚀性接近 304"],
    limitations: ["不推荐焊接", "耐腐蚀性略低于 304"],
  },
  "ss-321": {
    name: "321 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "钛稳定化奥氏体不锈钢。高温下耐晶间腐蚀。",
    applications: ["排气歧管", "换热器", "化工工艺"],
    advantages: ["耐高温腐蚀", "焊接性优于 304"],
    limitations: ["因加工硬化而难以加工"],
  },
  "ss-440c": {
    name: "440C 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "高碳马氏体不锈钢。硬度和耐磨性最高。",
    applications: ["轴承钢球", "阀门零件", "刀片"],
    advantages: ["硬度最高的不锈钢", "耐磨性优异"],
    limitations: ["耐腐蚀性低", "脆性大"],
  },
  "ss-2205": {
    name: "2205 不锈钢（双相）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "双相（奥氏体-铁素体）不锈钢。屈服强度明显高于 304。",
    applications: ["化工储罐", "石油化工", "海上结构"],
    advantages: ["屈服强度明显高于 304", "耐腐蚀性优异"],
    limitations: ["加工困难"],
  },
  "ss-316ti": {
    name: "316Ti 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "钛稳定化 316 不锈钢。高温下耐晶间腐蚀。",
    applications: ["换热器", "化学反应器", "排气歧管"],
    advantages: ["耐高温腐蚀"],
    limitations: ["因加工硬化而难以加工"],
  },
  "ss-347": {
    name: "347 不锈钢",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "铌稳定化奥氏体不锈钢。在高温应用中可替代 321。",
    applications: ["喷气发动机零件", "换热器", "核反应堆"],
    advantages: ["耐高温腐蚀", "焊接性优于 321"],
    limitations: ["因加工硬化而难以加工"],
  },
  "br-c360": {
    name: "C360 黄铜",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "易切削黄铜。切削排屑性能最佳。",
    applications: ["阀门", "紧固件", "电子连接器"],
    advantages: ["可加工性最佳", "外观美观"],
    limitations: ["强度低", "对氨敏感"],
  },
  "br-c932": {
    name: "C932 青铜（SAE 660）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "含铅锡青铜。减摩性能和储油性能优异。",
    applications: ["滑动轴承", "衬套"],
    advantages: ["储油性能优异", "摩擦低"],
    limitations: ["含铅"],
  },
  "br-c954": {
    name: "C954 铝青铜",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "高强度青铜合金。强度接近钢。",
    applications: ["重载轴承", "船用五金件", "齿轮"],
    advantages: ["强度高", "耐海水性能优异"],
    limitations: ["加工困难"],
  },
  "br-c260": {
    name: "C260 黄铜（弹壳黄铜）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "70% 铜、30% 锌。冷成形性能优异。",
    applications: ["弹壳", "散热器芯", "装饰五金件"],
    advantages: ["成形性优异", "耐腐蚀性良好"],
    limitations: ["可加工性低于 C360"],
  },
  "br-c464": {
    name: "C464 黄铜（海军黄铜）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "含锡海军黄铜。耐海水腐蚀性能优异。",
    applications: ["船舶零件", "海水阀门", "泵体"],
    advantages: ["耐海水性能优异", "耐脱锌腐蚀"],
    limitations: ["可加工性一般"],
  },
  "br-c510": {
    name: "C510 磷青铜",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "弹性极限高，适用于弹簧和触点。",
    applications: ["弹簧", "触点", "膜片"],
    advantages: ["弹性极限高", "耐腐蚀性良好"],
    limitations: ["加工困难"],
  },
  "cu-c101": {
    name: "C101 铜",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "无氧铜。纯度 99.99%。",
    applications: ["电子真空管", "超导体"],
    advantages: ["导电性最高", "无氧"],
    limitations: ["切屑粘刀，加工困难"],
  },
  "cu-c110": {
    name: "C110 铜",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "电解铜（ETP，电解韧铜）。标准电工导体用铜。",
    applications: ["电气母排", "接地", "垫片"],
    advantages: ["导电性优异"],
    limitations: ["可加工性低"],
  },
  "cu-c122": {
    name: "C122 铜（DHP）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "磷脱氧高残磷铜。换热器和给排水管道的标准材料。",
    applications: ["给排水管道", "换热器", "热水系统"],
    advantages: ["焊接性/钎焊性良好", "导电性高"],
    limitations: ["可加工性低"],
  },
  "cu-c145": {
    name: "C145 铜（碲铜）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "含碲易切削铜。兼具可加工性和导电性。",
    applications: ["电气配件", "电机换向器", "接触器"],
    advantages: ["铜材中可加工性最佳", "导电性高"],
    limitations: ["导电性略低于 C110"],
  },
  "ti-grade2": {
    name: "Grade 2 钛",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "工业纯钛。耐腐蚀性和生物相容性优异。",
    applications: ["医疗器械", "化学工业", "船舶"],
    advantages: ["耐腐蚀性优异", "生物相容性好", "质轻"],
    limitations: ["可加工性低"],
  },
  "ti-grade5": {
    name: "Grade 5 钛合金（Ti-6Al-4V）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "最常用的钛合金。强重比高。航空航天标准材料。",
    applications: ["喷气发动机零件", "医疗部件", "赛车装备"],
    advantages: ["强度接近钢", "明显轻于钢"],
    limitations: ["加工非常困难"],
  },
  "ti-grade9": {
    name: "Grade 9 钛合金（Ti-3Al-2.5V）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "中等强度钛合金。成形性和耐腐蚀性良好。",
    applications: ["自行车车架", "液压管路", "船舶"],
    advantages: ["成形性良好", "耐腐蚀性良好"],
    limitations: ["强度低于 Grade 5"],
  },
  "ti-grade23": {
    name: "Grade 23 钛合金（Ti-6Al-4V ELI）",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "超低间隙（ELI）版本。适用于要求更高韧性和生物相容性的应用。",
    applications: ["医疗部件", "手术器械", "航空航天"],
    advantages: ["生物相容性好", "韧性优于 Grade 5"],
    limitations: ["加工困难"],
  },
  "ni-625": {
    name: "Inconel 625",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "镍铬合金。抗氧化和耐腐蚀性能极强。",
    applications: ["海底设备", "排气系统", "核工业"],
    advantages: ["高温抗氧化", "耐腐蚀性优异"],
    limitations: ["加工非常困难"],
  },
  "ni-718": {
    name: "Inconel 718",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "在高温下保持高强度的高温合金。",
    applications: ["喷气发动机", "火箭零件"],
    advantages: ["高温下保持强度", "沉淀硬化"],
    limitations: ["加工非常困难"],
  },
  "ni-monel400": {
    name: "Monel 400",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "镍铜合金。耐海水和耐酸性能优异。",
    applications: ["船用阀门", "化工工艺", "炼油厂"],
    advantages: ["耐海水性能优异", "耐酸"],
    limitations: ["易加工硬化，加工困难"],
  },
  "ni-hastelloyc276": {
    name: "Hastelloy C-276",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "含钼钨的镍基合金。适用于化工过程中最恶劣的工况。",
    applications: ["化学反应器", "制酸装置", "烟气脱硫"],
    advantages: ["耐腐蚀范围最广", "耐氧化性和还原性环境"],
    limitations: ["加工非常困难"],
  },
  "mg-az31b": {
    name: "AZ31B 镁合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "应用最广泛的镁合金。质轻，成形性良好。",
    applications: ["电子设备外壳", "汽车面板", "相机机身"],
    advantages: ["非常轻", "成形性良好"],
    limitations: ["易腐蚀", "切屑易燃"],
  },
  "mg-az61a": {
    name: "AZ61A 镁合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "强度高于 AZ31B。适用于挤压型材。",
    applications: ["航空支架", "结构型材", "运动器材"],
    advantages: ["强度高于 AZ31B", "可加工性良好"],
    limitations: ["易腐蚀", "切屑易燃"],
  },
  "mg-az80a": {
    name: "AZ80A 镁合金",
    propertyConditions: "室温；数值随材料状态及热处理条件而变化",
    description: "高强度变形镁合金。用于航空航天结构件。",
    applications: ["航空齿轮", "飞机壳体", "赛车运动"],
    advantages: ["强度高", "质轻"],
    limitations: ["易腐蚀", "切屑易燃"],
  },
  "pl-abs": {
    name: "ABS",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "耐用的通用塑料。",
    applications: ["样件", "盖板", "玩具"],
    advantages: ["抗冲击强度良好", "易于加工"],
    limitations: ["耐温性低", "对紫外线敏感"],
  },
  "pl-pmma": {
    name: "亚克力（PMMA/有机玻璃）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "玻璃的透明替代材料。抛光后具有光学透明度。",
    applications: ["屏幕保护罩", "标牌", "导光管"],
    advantages: ["光学透明", "耐紫外线"],
    limitations: ["脆性大", "易划伤"],
  },
  "pl-delrin": {
    name: "Delrin（POM/聚甲醛）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "适用于高精度机械零件的工程塑料。",
    applications: ["齿轮", "轴承", "导轨"],
    advantages: ["可加工性优异", "摩擦低", "尺寸稳定性好"],
    limitations: ["难以粘接（需特殊表面处理）", "不适合涂漆"],
  },
  "pl-nylon": {
    name: "尼龙（PA6/PA66）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "耐磨性和机械强度高的工程塑料。",
    applications: ["齿轮", "滚动轴承", "皮带轮"],
    advantages: ["耐磨性高", "强度良好"],
    limitations: ["吸湿", "尺寸变化"],
  },
  "pl-pc": {
    name: "聚碳酸酯（PC）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "抗冲击强度高的透明工程塑料。",
    applications: ["防护罩", "光学透镜", "医疗器械"],
    advantages: ["抗冲击强度极高", "光学透明"],
    limitations: ["易划伤", "耐化学性一般"],
  },
  "pl-ptfe": {
    name: "PTFE（Teflon）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "摩擦系数最低的塑料。化学性质几乎完全惰性。",
    applications: ["垫片", "轴承", "化工衬里"],
    advantages: ["摩擦最低", "耐大多数化学品", "高温强度好"],
    limitations: ["强度低", "易蠕变"],
  },
  "pl-pvc": {
    name: "PVC",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "耐化学、阻燃的结构塑料。",
    applications: ["管道", "储罐衬里", "电线导管"],
    advantages: ["耐化学性良好", "阻燃"],
    limitations: ["耐温性低", "抗冲击强度低"],
  },
  "pl-hdpe": {
    name: "HDPE",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "高密度聚乙烯。表面光滑，耐化学性好。",
    applications: ["砧板", "化工储罐"],
    advantages: ["非常轻", "耐化学性好", "有食品接触级可选"],
    limitations: ["强度低", "难以粘接"],
  },
  "pl-pp": {
    name: "聚丙烯（PP）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "质轻、耐化学的塑料，适用于铰链。",
    applications: ["一体式铰链", "化工储罐", "实验室设备"],
    advantages: ["最轻的塑料之一", "耐化学性优异", "抗疲劳"],
    limitations: ["对紫外线敏感", "难以粘接"],
  },
  "pl-uhmwpe": {
    name: "UHMW-PE",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "超高分子量聚乙烯。耐磨性优异，摩擦低。",
    applications: ["输送导轨", "耐磨板", "食品加工"],
    advantages: ["耐磨性优异", "摩擦系数最低之一"],
    limitations: ["强度低", "对热敏感"],
  },
  "pl-pei": {
    name: "PEI（Ultem）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "琥珀色耐高温工程塑料。阻燃。",
    applications: ["航空内饰件", "电绝缘件", "医疗器械"],
    advantages: ["阻燃", "可消毒灭菌", "电绝缘性良好"],
    limitations: ["对紫外线敏感"],
  },
  "pl-cpvc": {
    name: "CPVC",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "氯化 PVC。用于热水和腐蚀性化学品时优于普通 PVC。",
    applications: ["热水管道", "化工管道", "消防喷淋管路"],
    advantages: ["耐温性高于 PVC", "阻燃", "耐化学性好"],
    limitations: ["抗冲击强度低"],
  },
  "pl-noryl": {
    name: "Noryl（PPO/PPE）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "改性聚苯醚。尺寸稳定，吸湿率低。",
    applications: ["汽车仪表板", "水处理设备", "电动工具外壳"],
    advantages: ["吸湿率低", "尺寸稳定性好", "质轻"],
    limitations: ["对紫外线敏感"],
  },
  "pl-pa66-gf30": {
    name: "PA66 + 30% 玻纤",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "玻纤增强尼龙。强度和耐温性提高。",
    applications: ["发动机罩盖", "风扇叶片", "结构支架"],
    advantages: ["强度高", "耐温性良好"],
    limitations: ["切屑磨蚀性强", "脆性大"],
  },
  "pl-pps": {
    name: "PPS（聚苯硫醚）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "耐高温、耐化学的半结晶热塑性塑料。",
    applications: ["汽车发动机零件", "泵体", "化工工艺"],
    advantages: ["耐化学性优异", "耐高温", "尺寸稳定性好"],
    limitations: ["脆性大"],
  },
  "pl-pbt": {
    name: "PBT（聚对苯二甲酸丁二醇酯）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "半结晶热塑性塑料。适用于电气连接器和汽车零件。",
    applications: ["电气连接器", "汽车传感器", "开关外壳"],
    advantages: ["电气性能良好", "结晶速度快"],
    limitations: ["对湿气敏感"],
  },
  "pl-pet": {
    name: "PET（聚对苯二甲酸乙二醇酯）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "透明或白色的半结晶塑料。有食品接触级可选。",
    applications: ["食品包装", "医疗器械", "电绝缘件"],
    advantages: ["有食品接触级可选", "尺寸稳定性良好"],
    limitations: ["吸湿"],
  },
  "pl-peek": {
    name: "PEEK",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "高性能半结晶热塑性塑料。强度和耐温性可替代金属。",
    applications: ["航空航天", "医疗部件", "半导体"],
    advantages: ["可替代金属", "可消毒灭菌", "高温强度好"],
    limitations: ["需要专用刀具"],
  },
  "pl-torlon": {
    name: "Torlon（PAI）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "性能最高的可熔融加工塑料。强度足以替代金属。",
    applications: ["喷气发动机零件", "半导体设备", "高温轴承"],
    advantages: ["高温下强度高", "强度可替代金属"],
    limitations: ["加工困难"],
  },
  "pl-vespel": {
    name: "Vespel（PI）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "DuPont Vespel 聚酰亚胺。耐极端温度，耐磨性极佳。",
    applications: ["航天器", "半导体", "喷气发动机"],
    advantages: ["长期使用温度非常高", "耐磨性优异"],
    limitations: ["货源有限"],
  },
  "pl-peek-gf30": {
    name: "PEEK + 30% 玻纤",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "玻纤增强 PEEK。刚度和尺寸稳定性提高。",
    applications: ["结构支架", "泵零件", "压缩机零件"],
    advantages: ["刚度高于 PEEK", "热膨胀低"],
    limitations: ["切屑磨蚀性强"],
  },
  "pl-peek-cf30": {
    name: "PEEK + 30% 碳纤维",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "碳纤维增强 PEEK。性能最高的聚合物复合材料。",
    applications: ["航空航天", "半导体", "医疗"],
    advantages: ["强重比极高", "静电耗散"],
    limitations: ["切屑磨蚀性强，可能需要金刚石或 PCD 刀具"],
  },
  "pl-psu": {
    name: "聚砜（PSU）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "透明的耐高温工程塑料。可高压灭菌。",
    applications: ["医疗器械", "乳品工业", "水过滤"],
    advantages: ["透明", "可消毒灭菌", "有食品接触级可选"],
    limitations: ["对紫外线敏感"],
  },
  "pl-ppsu": {
    name: "PPSU（Radel）",
    propertyConditions: "23 °C，干态（未调湿）；随湿度和温度而变化",
    description: "聚苯砜。抗冲击强度最高的耐高温塑料。",
    applications: ["手术器械托盘", "飞机内饰件", "热水管件"],
    advantages: ["抗冲击强度高", "耐反复高压灭菌"],
    limitations: ["加工后可能需要去应力处理"],
  },
  "co-g10": {
    name: "G-10 / FR-4",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "玻纤增强环氧层压板。电绝缘的标准材料。",
    applications: ["PCB", "电绝缘件", "无人机机身"],
    advantages: ["电绝缘性优异", "强度高"],
    limitations: ["切屑磨蚀性强", "粉尘危害健康"],
  },
  "co-cf-laminat": {
    name: "碳纤维层压板",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "碳纤维增强环氧板材。超轻、超强。",
    applications: ["赛车", "无人机机架", "假肢部件"],
    advantages: ["强重比最高", "刚度优异"],
    limitations: ["切屑磨蚀性强", "各向异性"],
  },
  "co-nylon-cf": {
    name: "尼龙 + 碳纤维",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "碳纤维增强尼龙。适用于轻质、高刚度结构件。",
    applications: ["无人机机架", "机器人手臂", "3D 打印"],
    advantages: ["质轻", "刚度高", "耐磨"],
    limitations: ["吸湿", "各向异性"],
  },
  "co-phenolic": {
    name: "酚醛层压板（电木）",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "最早的合成塑料。至今仍用于耐热和电绝缘场合。",
    applications: ["电绝缘件", "刹车片", "锅柄"],
    advantages: ["耐热", "电绝缘"],
    limitations: ["脆性大", "颜色选择有限"],
  },
  "co-ultem-cf": {
    name: "Ultem + 碳纤维",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "碳纤维增强 PEI。适用于航空航天结构部件。",
    applications: ["航空内饰结构", "卫星部件", "赛车"],
    advantages: ["阻燃且可作结构件", "质轻"],
    limitations: ["需要专门的加工工艺"],
  },
  "co-garolite": {
    name: "Garolite G-11",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "G-10 的耐高温版本。",
    applications: ["高温绝缘件", "变压器零件", "电机绝缘"],
    advantages: ["耐温性高于 G-10", "绝缘性优异"],
    limitations: ["磨蚀性强", "切屑危害健康"],
  },
  "co-kevlar": {
    name: "Kevlar 层压板",
    propertyConditions: "沿纤维方向，室温；垂直于纤维方向时明显较低",
    description: "芳纶纤维增强环氧。吸收冲击，质轻，韧性高。",
    applications: ["防弹防护", "滑雪装备", "船体"],
    advantages: ["冲击吸收性能优异", "非常轻", "韧性高"],
    limitations: ["加工非常困难", "吸湿"],
  },
};
